### ISSUE TITLE
Bug `AIRFLOW_LOCAL_SETTINGS_CONFIGMAP` incorrectly states example with `pod_mutation_hook`

### ISSUE THREAD

**Issue by kristof-mattei** [apache/airflow#10027]
**Apache Airflow version**:
1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Irrelevant

**Environment**:

- **Cloud provider or hardware configuration**: Self-hosted K8s cluster
- **OS** (e.g. from /etc/os-release): Official Airflow Docker version
- **Kernel** (e.g. `uname -a`): Official Airflow Docker version
- **Install tools**: Helm Chart
- **Others**: 

**What happened**:

The documentation sets the expectation that I can modify the pod before it gets launched by using the `AIRFLOW__KUBERNETES__AIRFLOW_LOCAL_SETTINGS_CONFIGMAP`. 
https://airflow.apache.org/docs/stable/configurations-ref.html#airflow-local-settings-configmap

This doesn't happen, and reading through the source code I don't see how it can possibly function like that.
1. Get config value: https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L218
2. Mount file https://github.com/apache/airflow/blob/master/airflow/kubernetes/worker_configuration.py#L291
3. ??

The file itself is not opened on the Airflow Scheduler, where it should've been used, instead, it is passed on to the worker. 
While that may work for other things in `local_settings`, it doesn't for the `pod_mutating_hook`!

**What you expected to happen**:

`pod_mutating_hook` to work.
**How to reproduce it**:

1. Use K8s Executor
2. Use `pod_mutating_hook`

**Anything else we need to know**:

I think this is a documentation issue, where the example should be removed (https://airflow.apache.org/docs/stable/configurations-ref.html#airflow-local-settings-configmap)

Somebody else with the same issue on StackOverflow: https://stackoverflow.com/questions/61067025/

**Comment by kaxil** [comment]
https://github.com/apache/airflow/blob/8bd15ef634cca40f3cf6ca3442262f3e05144512/airflow/kubernetes/pod_launcher.py#L68-L84 --> Before a pod is run it goes through pod_mutation_hook -> We use it to add more labels and I know many other users use it. If it is failing for you in 1.10.11 is because of a bug that would be solved in 1.10.12 (PR: https://github.com/apache/airflow/pull/9903)

**Comment by Kristof-Mattei** [comment]
@kaxil 
I managed to get the hook working by putting it in `local_settings.py` in the scheduler.


`AIRFLOW__KUBERNETES__AIRFLOW_LOCAL_SETTINGS_CONFIGMAP` defines  the configmap that contains the `local_settings.py`, but it is only being used once the pod is launched, as part of the mounted volume, so that's too late, and also in a different context (i.e. the new pod). At that moment the resources have already been set (which is what I'm trying to modify as `AIRFLOW_KUBERNETES_WORKER_RESOURCES` hasn't landed yet.

**Comment by kaxil** [comment]
pod_mutation_hook just applies to PODs launched by KubernetesExecutor and KubernetesPodOperator and not any other pods. Am I mis-understanding the use-case here?

**Comment by Kristof-Mattei** [comment]
No, that's correct!

But I'm advocating for the example here: https://airflow.apache.org/docs/stable/configurations-ref.html#airflow-local-settings-configmap

Where it states:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-configmap
data:
  airflow_local_settings.py: |
      def pod_mutation_hook(pod):
          ...
  airflow.cfg: |
      ...
```

to be removed, as using `AIRFLOW__KUBERNETES__AIRFLOW_LOCAL_SETTINGS_CONFIGMAP` to inject `airflow_local_settings.py` into the created pod to then mutate it is  not possible!

**Comment by Kristof-Mattei** [comment]
`pod_mutation_hook` works perfectly, I am stating that defining `pod_mutation_hook` inside of `airflow_local_settings.py` mounted INSIDE of a K8s container via `AIRFLOW__KUBERNETES__AIRFLOW_LOCAL_SETTINGS_CONFIGMAP ` has 0 effect.

Let's look at the documentation: 
https://airflow.apache.org/docs/stable/configurations-ref.html#airflow-local-settings-configmap

The example config file looks as follows:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-configmap
data:
  airflow_local_settings.py: |
      def pod_mutation_hook(pod):
          ...
  airflow.cfg: |
      ...
```

Let's try that out:

We set `AIRFLOW__KUBERNETES__AIRFLOW_LOCAL_SETTINGS_CONFIGMAP` to `airflow-k8s-configmap` and create the following configmap:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: airflow-k8s-configmap
data:
    airflow_local_settings.py: |
        import pprint
        import logging
    
        logging.warning("Imported airflow-k8s-configmap")
        def pod_mutation_hook(pod):
            pod.annotations["foo"] = "bar"

            logging.warning(pprint.pprint(pod))
```

One would expect this logging to show up in the scheduler, and one would expect newly created pods to have the `"foo": "bar"` annotation.

I have tried this, and I can assure you, it does not work.

I have debugged the code line by line, and found out that this config-map is mounted INSIDE of the newly created pod, and thus AFTER the `KubernetesExecutor` has LAUNCHED the pod, ergo AFTER `KubernetesExecutor` has done any modificatons through `pod_mutation_hook(pod)`. 

In order of execution:

1. Read contents of `AIRFLOW_LOCAL_SETTINGS_CONFIGMAP` into variable: https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L218
1. Define the volume mount that mounts `airflow_local_settings.py` in this config map to `config_path = '{}/config/airflow_local_settings.py'.format(self.worker_airflow_home)`: https://github.com/apache/airflow/blob/master/airflow/kubernetes/worker_configuration.py#L298
1. Create the pod framework to be launched: https://github.com/apache/airflow/blob/master/airflow/kubernetes/worker_configuration.py#L426
1. Pass on this pod: https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L424 -> https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L462 -> https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L480
1. Mutate the pod, with `pod_mutation_hook` and launch it: https://github.com/apache/airflow/blob/master/airflow/kubernetes/pod_launcher.py#L69

All of this happened in a context where we do not have that particular `airflow_local_settings.py` mounted, ergo our `pod_mutation_hook` is never used!

The newly launched pod, in 5. will have said file mounted, but the new pod is not responsible for launching new pods, it's responsible for executing a task!

**Comment by kaxil** [comment]
You are using it wrongly. Let me try to explain.

"airflow.cfg" and "airflow_local_settings.py" file needs to exist on the Scheduler (Whether your Scheduler is on a VM or a POD isn't relevant here). We have also added documentation on where to out this file: https://airflow.apache.org/docs/stable/concepts.html#where-to-put-airflow-local-settings-py

The `pod_mutation_hook` now is used whenever you use `KubernetesExecutor` or `KubernetePodOperator`. The PODs launched by KubernetesExecutor or KubernetePodOperator will use this mutation hook.

Now, back to the configmap. The case when you are using `KubernetesExecutor` and have a task that use KuberneretPodOperator, you need both `airflow.cfg` and `airflow_local_settings.py` file to exist on the worker pods launched by the KubernetesExecutor.

The KubernetesExecutor launches a Worker Pod for this task. 

Scheduler Pod ---> Worker Pod (Pod_1 -- launched by KubernetesExecuetor) --> (Pod_2 -- launched by 
 Pod_1 the task using KubernetePodOperator)

Now the entire **[kubernetes]** section in airflow.cfg (https://github.com/apache/airflow/blob/master/airflow/config_templates/default_airflow.cfg#L870-L1028) is used only for KubernetesExecutor and affects what is mounted on the **Worker Pods** launched by KubernetesExecutor.

If you don't specify `airflow_local_settings` configmap,  the airflow_local_settings file would not be mounted to the worker pod (Pod_1 in the above example) and only airflow.cfg file is mounted. So now for Pod_2 (launched by Pod_1) -- (special case when you use KubernetesPodOperator with KubernetesExecutor), since Pod_1 (the worker POD) doesn't have airflow_local_settings.py file even though the Scheduler has it, Pod_2 would not be mutated since the file doesn't exist over there.

Consider it same as airflow.cfg -- why do you mount airflow.cfg file both to the Scheduler POD and the worker POD. Similarly for this edge case you need airflow_local_settings.py file at both the places.

https://github.com/apache/airflow/blob/ba2d6408e64f219e8f53a20a5a149e3d8109db31/airflow/kubernetes/worker_configuration.py#L279-L305 --> This code is used to decide what is mounted on the Worker Pod (**REF_1**)

https://github.com/apache/airflow/blob/ba2d6408e64f219e8f53a20a5a149e3d8109db31/airflow/executors/kubernetes_executor.py#L462-L481 --> Pod created for each task run by KubernetesExecutor (**REF_2**) -- The mutation is applied to this POD as this is launched by the Scheduler and it has airflow_local_settings.py file

https://github.com/apache/airflow/blob/ba2d6408e64f219e8f53a20a5a149e3d8109db31/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L383 --> This code is used to create a new POD when using KubernetesPod Operator (REF_3) -- Since airflow_local_settings.py wasn't mounted on POD generated in **REF_2** the mutations weren't applied to this POD.
