### ISSUE TITLE
Using >= or =~ in dependency management is a very bad practice

### ISSUE THREAD

**Issue by NBardelot** [apache/airflow#10038]
From an ops point of view, packaging Airflow with about 150 dependencies not strictly tied to a version is a bad practice. In `setup.py` there are about 20 dependencies using `=~` versions and about 130 dependencies using `>= ` versions. This means there is no guarantee that two instances of Airflow run the same versions of python libraries.

One version of such a library being bugged, or worse, compromised, means deploying a faulty Airflow.

Being forced to manually compute dozens of dependency versions and force them in requirements.txt is not a viable solution. 

A workaround if to freeze a whole Python PI tree in an artefacts management tool like Nexus or Artifactory, in order to guarantee one state of the dependency tree... But that should not be forced upon the users.

Airflow should freeze its dependency tree when a new stable version comes out.

**Comment by kaxil** [comment]
Airflow has a constraints file you could use to produce repeatable installations.

Check the section in https://github.com/apache/airflow#installing-from-pypi

**Comment by kaxil** [comment]
All the constraint files contain a specific version, example: 

```
Babel==2.8.0
Flask-Admin==1.5.4
Flask-AppBuilder==2.3.4
Flask-Babel==1.0.0
Flask-Bcrypt==0.7.1
Flask-Caching==1.3.3
Flask-JWT-Extended==3.24.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
Flask==1.1.2
JPype1==0.7.1
JayDeBeApi==1.2.3
Jinja2==2.10.3
Mako==1.1.3
Markdown==2.6.11
MarkupSafe==1.1.1
PyHive==0.6.2
PyJWT==1.7.1
PyNaCl==1.4.0
PySmbClient==0.1.5
PyYAML==5.3.1
Pygments==2.6.1
SQLAlchemy-JSONField==0.9.0
SQLAlchemy-Utils==0.36.8
SQLAlchemy==1.3.18
Sphinx==3.1.2
Unidecode==1.1.1
WTForms==2.3.1
Werkzeug==0.16.1
```

**Comment by kaxil** [comment]
The main reason of doing that is also explained in https://github.com/apache/airflow#installing-from-pypi

>Airflow is a bit of both a library and application. Libraries usually keep their dependencies open and applications usually pin them, but we should do neither and both at the same time. We decided to keep our dependencies as open as possible (in setup.py) so users can install different versions of libraries if needed.

**Comment by potiuk** [comment]
Hello Noel,

Indeed the problem you describe is very true for Applications but it is
quite the opposite for libraries. Unfortunately Airflow is a bit of both,
that's why we had  to find a bit different solution - keeping the setup.py
dependencies as open as possible but allowing Airflow as application to be
installed with frozen set of dependencies. Those are frozen both - for
master (we automatically test and re-freeze them continuously after testing
during our CI process) but also we freeze the fixed set of dependencies
whenever we release a stable version of Airflow (and you can very easily
use either the latest or the 1.10.x frozen version at any time by providing
the right `--constraint` URL.

You can take a look at our 'Installimg from PyPI' chapter of README.md -
https://github.com/apache/airflow#installing-from-pypi where it is
explained how to install Airflow in repeatable way (using constraint files
we maintain automatically with all the dependencies frozen). Also
INSTALL.txt contains the right instructions (note that they changed a bit
in the upcoming version but you can find the corresponding instructions in
1.10.10 and 1.10.11 tags of the same files - for 1.10.10 and 1.10.12. the
current set of instructions will be valid as of 1.10.12)

For detailed instructions and explanation why we had gone that route, you
can see
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#airflow-dependencies
(also the following chapter 'Pinned constraint files' where we explained
how we addressed it). As mentioned - it's the second iteration of approach
to fix it. The first one in 1.10.10 and 1.10.11 has proven to be too
'heavy' for maintenance by contributors, so we improved it, simplified it,
and we fully automated the process of dependency freezing last week (and it
will be released in 1.10.12).

I hope this addresses your concerns.

Please read those links I sent and let us know if it does or does not
address your concerns (and let
Is know please why - if not). Also if you have any concrete proposals how
we can improve the current setup without breaking our 'both library and
app' requirement - we are happy to hear it. Whether it is the documentation
or the process improvement proposals.

I am particularly interested in how we can surface information about it
better. It seems that despite all our efforts to explain it in INSTALL.txt,
README.md and CONTRIBUTING.rst - it's not enough as people sometimes do not
find it easily, so I would love to hear some suggestions and proposals how
we could improve it - especially from person not familiar with the process
and whole reasoning.

The most welcome is a PR improving it that we can review and merge :).

J

wt., 28 lip 2020, 16:57 użytkownik Noël Bardelot <notifications@github.com>
napisał:

**Comment by NBardelot** [comment]
Thank you @kaxil and @potiuk for such insightful and speedy answers.

The issue I think is that in my case we do not install Airflow from the command line using pypi, but we use a Docker image.

I see that you changed the constraints behaviour in the Dockerfile 9 days ago @potiuk, I did not see this commit in the version I currently use.

https://github.com/apache/airflow/commit/de9eaeb434747897a192ef31815fbdd519e29c4d

With this commit I no longer have an issue from a Docker perspective. 

Again, thank you both for your help and for the nice work :)

**Comment by potiuk** [comment]
Just two more things if you are using the image.

You can take a look at the IMAGES.rst where the case about constraints and how to use them is very well explained with examples.

Also you can watch my talk from the Airflow Summit where I am explaining how the image works, how it is layered and how to build your own image. The part about constraints is not very detailed but you can watch all the other aspects such as adding your own dependencies  - including build and runtime dependencies : https://youtu.be/wDr3Y7q2XoI

**Comment by mik-laj** [comment]
Is there anything left to do in this ticket? We have docs about it: https://airflow.readthedocs.io/en/latest/installation.html
