### ISSUE TITLE
Add download function at gdrive hook

### ISSUE THREAD

**Issue by SaladBreaker** [apache/airflow#10126]
**Description**

Right now the GoogleDriveHook class from: airflow/airflow/providers/google/suite/hooks/drive.py has only a upload function, it would be nice if a download function was also provided.

**Use case / motivation**

This is useful for example if a lot of data is keep in drive in some xlsx file and you want to obtain that data, automatically as a source for a ETL process.

**Comment by turbaszek** [comment]
@SaladBreaker would you like to implement it? I'm happy to help with it, let me know if you need any guidance 🚀

**Comment by SaladBreaker** [comment]
Thanks, I'll try it.

**Comment by p-madduri** [comment]
any update on this?

**Comment by Scuall1992** [comment]
Hello, can I implement this feature?

**Comment by eladkal** [comment]
@Scuall1992 assigned to you.
Just mentioning that we have also https://github.com/apache/airflow/issues/13966 but download isn't part of it.

**Comment by Scuall1992** [comment]
Hello, can you help me? As I understood I need to develop download function in hooks/drive.py, with these signature

def download_file(self, remote_location: str, local_location: str) -> str:

I'm receiving file id and download it in local_location.

If file isn't exists then what type of exception I should raise?

**Comment by Scuall1992** [comment]
Also I found the difference between downloading Google Doc files and others https://developers.google.com/drive/api/v3/manage-downloads

What we need in this issue?

**Comment by RNHTTR** [comment]
Note that the GoogleDriveHook inherits from the [GoogleBaseHook](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_modules/airflow/providers/google/common/hooks/base_google.html#GoogleBaseHook), which has the method `download_content_from_request`. You can use this method to write data to a file handle, e.g. a `BytesIO` object. You can then write the contents of that object to disk.

Instead of adding functionality to the hook, you might want to consider creating a transfer operator, e.g. `gdrive_to_local.py`. You can use the `_upload_data` method in the [GoogleDriveToGCSOperator](https://github.com/RNHTTR/airflow/blob/f9d442f9a85b4b705bbe574f718034cf6bab5486/airflow/providers/google/cloud/transfers/gdrive_to_gcs.py) as an example, but instead of passing the value of the file handle to GCS, you can [write it to a file](https://stackoverflow.com/a/60450462/7004653).
