### ISSUE TITLE
Web UI should present 'scheduler status' somewhere

### ISSUE THREAD

**Issue by kretes** [apache/airflow#1028]
Hello,

given airflow architecture with DB as an integration layer it is easy to get into a situation where web is online but scheduler is down. Looking at the UI one is thinking 'why the hell my dags are not running'

We need 'scheduler last seen' in the web UI with some red color if scheduler process didn't fire up in last X minutes.

**Comment by mistercrunch** [comment]
+1! 

It's not done yet since we have PagerDuty raise hell as soon as the scheduler stops spinning.

On our side we also have a nice Panoramix dashboard (https://github.com/mistercrunch/panoramix) that shows the health of the cluster.

I agree that this should be part of Airflow as a product. Maybe a full blown "Cluster Monitoring" page under the Admin menu.

**Comment by r39132** [comment]
Thoughts on implementation:
1) New table for cluster_status
a.) Possible columns include: 
  i) `service_id` (should be a unique id for the service : e.g. `<service_type>_<hostname>_<port>`)
  ii) `service_type` (should be a unique id for the service
  iii) `hostname`
  iv) `listen_port`
  v) `last_heartbeat_at_epoch_second`
  vi) `last_restarted_at_epoch_second`
  vii) `created_at_epoch_second`
2) Add some code to the scheduler to heartbeat to this table
3) Add a new page for cluster monitoring that shows the scheduler is running!
We support multiple schedulers, so we will need a unique way to identify them.

**Comment by jgao54** [comment]
Will look into this.

**Comment by jgao54** [comment]
It seems that the scheduler doesn’t currently expose any ports (only webserver does). So with our current model, we can only identify down to the unique hosts that are running. We could either use the unique baseJob’s id to identify each scheduler (but user won’t be able to know which id maps to which port/instance); or we could add port # or a user-defined name to pass in as CLI argument.

**Comment by jgao54** [comment]
Also, I noticed that while I have the scheduler running,  the scheduler data is not being committed to the Job table when I queried it. Not sure why this is the case. 
@mistercrunch please advice.

**Comment by jlowin** [comment]
I originally opened #1381 but I think this is a more appropriate place to mention it -- 

In order to mitigate confusion about the difference between `dagrun.execution_date` (the start of the "execution period") and `dagrun.start_date` (the end of the execution period, or the date the "execution period" is actually evaluated), suggest adding a "next scheduled run date" to the DAG UI.

See for example #1373

**Comment by jgao54** [comment]
@jlowin Thanks for the note. "Next scheduled run date" would definitely be useful. Before I implement it, just want to confirm that by DAG UI, do you mean adding an additional field in the table in **Browser -> DagRun**?  Or do you have another place for it in mind?

As for Cluster Monitoring, a separate page will probably be created, i.e. **Admin -> Cluster Monitoring**.
I discussed with @criccomini  about this and would like to get your input on it:

Currently, the pid that the scheduler job is running on is not tracked anywhere in the db, which implies that if the process gets killed for whatever reason while running, the job state in the db will stuck as 'running' forever and can be misleading in the UI. Would it make sense to do a kill_zomebies() for the Jobs similar to how the TIs works (i.e. if it's been a long time since the last heartbeat)?  Or are there any caveats to this?

Another question related to this but is on a higher level is that in general, there are some information we are not currently tracking in the db: if we have 2+ schedulers on the same instance, we cannot differentiate them from one another other than the Job Id, since the ids are assigned arbitrarily. Would it make sense to introduce pid or port or some kind of unique identifier so we know exactly which scheduler is down?

**Comment by bolkedebruin** [comment]
@jgao54 can you create a Jira for this please?
