### ISSUE TITLE
Add Kerberos Support for Presto Hook

### ISSUE THREAD

**Issue by jaketf** [apache/airflow#10306]
**Description**
Airflow should be able to use [kerberos security features](https://airflow.apache.org/docs/stable/security.html#kerberos) to run queries against a kerberized presto cluster from an airflow task.

**Use case / motivation**

Schedule queries on a kerberized presto infrastructure using airflow.

**Related Issues**
abandoned / stale PR w/ lack of test coverage requesting same feature
https://github.com/apache/airflow/pull/8491

**Comment by mik-laj** [comment]
@jaketf I'd love to do it.

**Comment by mik-laj** [comment]
Small update:
I tried to complete this ticket but couldn't test Airflow with Kerberos because the Kerberos setup in Breeze is not complete.
I have a new setup: https://github.com/mik-laj/presto-kerberos-docker

I also opened PR to presto-python-client to add support for self-signed SSL certificate: https://github.com/prestosql/presto-python-client/pull/36 
I will have to prepare some documents so that this change can be merged, but that doesn't block us as I have a workaround.

**Comment by mik-laj** [comment]
Small update:
I have a working PR, but it still needs some care to make everything easily accessible with the breeze command.

One problem has already been found thanks to system tests.  Snowflake-connector-python library monkey patch  Python core. It enforce SSL certificates verification ,so it cannot be turned off certificate verification for developing purposes. We will probably have to report the bug to the maintainers of this library, and for now I will have to skip tests for Salesforce. 
https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/network.py#L89-L92
