### ISSUE TITLE
Incompatibility with boto3 >= 2.8

### ISSUE THREAD

**Issue by Shivi127** [apache/airflow#10319]
**Do not use issues for support requests or general help queries**

Please ask on one of our mailing lists, or in our Slack channel. See the "Ask a question" section of http://airflow.apache.org/community/

Issues which are not bug reports or feature requests (i.e. "how do I get X working", or "How do I best do X?") will likely be closed without a response.

**Comment by potiuk** [comment]
Hey @Shivi127 - we need more information, I think you copied the original content in the issue. Ideally if you know more details and know we need to limit boto3 versions, you might - rather than creating an issue - open directly a PR addressing the problem with some description and explanation. It should be as easy as updating one line in setup.py
