### ISSUE TITLE
Run multiple containers in `KubernetesPodOperator`

### ISSUE THREAD

**Issue by frederichaase** [apache/airflow#10313]
**Description**

The `airflow.contrib.operators.kubernetes_pod_operator.KubernetesPodOperator` does not have the possibility to start mutliple containers in the same pod.

**Use case / motivation**

Useful if one need to start sidecars or external services in the same pod. I am not sure about the API here, should it be possible to provide a list of images and cmds?

**Related Issues**

**Comment by mik-laj** [comment]
https://lists.apache.org/x/thread.html/rb1bcafea1b8f86e6d155aea7169c05805f7021e90f1636afc8019074@%3Cdev.airflow.apache.org%3E
can you have a look here? does this allow you to meet your use case?

**Comment by kaxil** [comment]
Closing this since we have not yet received response to last suggestion -- we can re-open if this is still an issue from Airflow 2.0+

**Comment by everglory99** [comment]
Is this feature available in Airflow 2.0? I add a sidecar container (`fluent-bit`) in `pod_template_file` used in `KubernetesPodOperator`. However, the POD is always in running mode even the `base` container is finished successfully. I think this is because the sidecar container is still running. Is there a way to fix this issue? Thanks!

**Comment by WongyuChoi** [comment]
@everglory99 Maybe [Pod Mutation Hook](https://airflow.apache.org/docs/apache-airflow/stable/kubernetes.html#pod-mutation-hook) can help?
