### ISSUE TITLE
GCSToGoogleSheetsOperator backwards compatibility bug

### ISSUE THREAD

**Issue by kaydani** [apache/airflow#10322]
**Apache Airflow version**: airflow-1.10.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: GCP Composer

- **Cloud provider or hardware configuration**: GCP Composer
- **OS** (e.g. from /etc/os-release): GCP Composer
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Imported GCSToGoogleSheetsOperator using `from airflow.providers.google.suite.transfers.gcs_to_sheets import GCSToGoogleSheetsOperator`

In airflow UI, I see the following error `Broken DAG: [/home/airflow/gcs/dags/dag.py] getboolean() got an unexpected keyword argument 'fallback'`

**What you expected to happen**: the dag to start running

I think there's a backwards compatibility issue since this is a v2 operator, but I am running v1 of airflow

**How to reproduce it**:
import GCSToGoogleSheetsOperator in any dag file

How often does this problem occur? Once? Every time etc? Every time

**Comment by potiuk** [comment]
Backport providers were tested and should work for 1.10.6+ version.  There is no guarantee they work with earlier versions and we do not plan to make any fixes to  make them work this way. That is far too much effort to make sure that it works for all past versions.

The behaviour of getboolean was fixed in https://github.com/apache/airflow/pull/4674/files  which was way after 1.10.2 release.

My recommendation is that if you want to use backport providers, you should migrate to latest version of Apache Airflow.
