### ISSUE TITLE
Add support for server-side encryption to S3 hook 

### ISSUE THREAD

**Issue by d-lee** [apache/airflow#1036]
It would be nice to have server-side encryption support added to S3 hook. Currently AWS has three different options for SSE - SSE-S3, SSE-KMS, and SSE-C  (http://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html). While we are mostly interested in SSE-C, others might benefit from having SSE-KMS, and SSE-S3 as well.

Most likely it would require switching from boto to boto3 as server-side encryption support in boto 2.x is limited to SSE-S3 only.

**Comment by jlowin** [comment]
@d-lee I think I may have added partial support for this in #1137, see here: https://github.com/airbnb/airflow/blob/master/airflow/hooks/S3_hook.py#L347. However this is the `boto`(2) version of encryption -- I don't think it's quite what you want but it might be a step in the right direction. Moving from `boto`(2) to `boto3` is non-trivial due to the total API switch. By any chance are you doing work with `boto3` that could form the basis of a PR?

**Comment by bolkedebruin** [comment]
@d-lee please create a Jira for this if you don't mind. Thanks!
