### ISSUE TITLE
PostgressHook connection - pass additional extra paramters

### ISSUE THREAD

**Issue by agivola** [apache/airflow#10505]
Hi, when working with PostgressHook connection and use it in multi-threads we need to pass extra parameters like pool_size, max_overflow and max_timeout as connection  parameters . Now only this parameters are accepted:
'sslmode', 'sslcert', 'sslkey','sslrootcert', 'sslcrl', 'application_name','keepalives_idle'

https://airflow.apache.org/docs/stable/_modules/airflow/hooks/postgres_hook.html

**Comment by mik-laj** [comment]
This is a great ticket for a first contribution. Would you like to help us with this?
Here is the development environment guide: https://github.com/apache/airflow/blob/master/BREEZE.rst
Here is the contributor guide:  https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst

**Comment by daemon-demon** [comment]
Hi, I would like to work on this as my first contribution.

**Comment by mik-laj** [comment]
@daemon-demon I assigned you to this ticket.

**Comment by kbobrien** [comment]
I was about to open a ticket to support the `target_session_attrs` psycopg2 parameter but this ticket could cover that use case too.  Is there really a need to limit the parameters supplied to `psycopg2.connect()` on the Airflow side, psycopg2 itself doesn't limit the parameters it passes through to the underlying library?  

Could I suggest that we remove the List of parameters supported by the Hook altogether and just pass through what users supply in the extra_json as kv's?  Since this check doesn't fail hard it provides limited benefit to users who probably expect their extra parameters were passed down since they got no warnings or errors.

**Comment by RosterIn** [comment]
@daemon-demon There was a PR that tried to achieve that https://github.com/apache/airflow/pull/7632
maybe it will help you as a starting point

**Comment by agivola** [comment]
@kbobrien Hi, I think that the best way is to allow pass all parameters via extra_json without restrictions.

**Comment by daemon-demon** [comment]
@RosterIn @agivola 
I will be creating a PR today for the fix I put in to allow all parameters to pass without restrictions.
