### ISSUE TITLE
option to disable "lots of circles" in error page

### ISSUE THREAD

**Issue by jameswynn** [apache/airflow#10549]
**Description**

The "lots of circles" error page is very rough via Remote Desktop connections. In the current global pandemic many people are working remotely via already constrained connections. Needless redraws caused by the highly animated circles can cause frustrating slowdowns and sometimes lost connections.

**Use case / motivation**

It should be trivially simple to disable the animated portion of the error page and instead use a standard error page. Ideally this would be something easily achievable via configuration options and exposed in the Helm chart.

**Related Issues**

N/A

**Comment by potiuk** [comment]
That's a vaild point I must say.

**Comment by potiuk** [comment]
If any would like to pick it up, I am all for making this page static.

**Comment by jpmarques66** [comment]
@potiuk Would love to try to solve this one.

**Comment by mik-laj** [comment]
@jpmarques66 I can see that you are not active on this ticket, so I unassigned you from this ticket.  Now another contributor can start working on it. If you want to continue working, let me know and I will assign you again.

**Comment by lewis-anderson53** [comment]
I'm looking to make my first contribution to the project, I've just been looking at how this is rendered and I've got a pretty good idea how we could implement this.

If the `airflow.cfg` file contains something like `circles_dynamic`, we could fetch the value when rendering the circles HTML template [here](https://github.com/apache/airflow/blob/4cde47b339d5ab5e4ebccfb22962ccbfc4c5457e/airflow/www/views.py#L368) where the default fallback value is `True`, meaning this SVG will by default behave as it currently does.

In the [circles.html](https://github.com/apache/airflow/blob/4cde47b339d5ab5e4ebccfb22962ccbfc4c5457e/airflow/www/templates/airflow/circles.html#L37) template, we could use Jinja to determine whether or not to load the default `circles.js` or some new file, called `circles_static.js`, which simply draws the circles once, without redrawing them constantly, which I understand to be the root cause of this issue right @jameswynn ?

Open to suggestions, this is just the first method that came to my mind!

**Comment by bbovenzi** [comment]
Alternatively, instead of adding _another_ config item. We could just get rid of the lots of circles. It doesn't really provide anything useful, as far as I'm aware.

**Comment by baryluk** [comment]
I also have similar issue as OP. I use VNC a lot, and it causes sever frame rate drop, as well causes serious CPU usage increase on both VNC server and client (to the point that the small client PC spins CPU fan to the max). I wish it was just gone.

**Comment by baryluk** [comment]
Thank you again @bbovenzi . Awesome.
