### ISSUE TITLE
Licensing risks

### ISSUE THREAD

**Issue by ryw** [apache/airflow#10667]
I've pulled together a list of questionable licenses that license scanners will pick up for Airflow. Ideally we should look to remove the dependencies from the project.

Project | License  | PR |
|---------|----------|----|
| [astroid](https://pypi.org/project/astroid/) | LGPL-3.0 |
| [certifi](https://pypi.org/project/certifi/) | MPL-2.0 |
| [chardet](https://pypi.org/project/chardet/) | LGPL-2.1 |
| [JayDeBeApi](https://pypi.org/project/JayDeBeApi/) | LGPL-3.0 |
| [ldap3](https://pypi.org/project/ldap3/) | LGPL-3.0 |
| [mysql-connector-python](https://pypi.org/project/mysql-connector-python/) | GPL-3.0 |
| [paramiko](https://pypi.org/project/paramiko/) | LGPL-3.0 |
| [pathspec](https://pypi.org/project/pathspec/) | MPL-2.0 |
| [psycopg2-binary](https://pypi.org/project/psycopg2binary/) | LGPL-3.0 |
| [pycountry](https://pypi.org/project/pycountry/) | LGPL-2.1 |
| [PyGithub](https://pypi.org/project/PyGithub/) | LGPL-3.0 |
| [pymssql](https://pypi.org/project/pymssql/) | LGPL-3.0 |
| [PySmbClient](https://pypi.org/project/PySmbClient/) | GPL-3.0 |
| [pytest-rerunfailures](https://pypi.org/project/pytest-rerunfailures/) | MPL-2.0 |
| [text-unidecode](https://pypi.org/project/text-unidecode/) | Artistic-2.0 |
| [Unidecode](https://pypi.org/project/Unidecode/) | GPL-3.0 | https://github.com/apache/airflow/pull/10665 |
| [yamllint](https://pypi.org/project/yamllint/) | GPL-3.0 |

**Comment by potiuk** [comment]
Duplicate of #9898 

Just to give a bit of context here: As an ASF project we are bound by the https://www.apache.org/legal/resolved.html

We've discussed most (if not all) of those licences in #9898. I looked through it and do not find any new "watchouts".

IMHO the result of this discussion is that we are "ok". Unless there is other reason (not ASF policies) that we want to get rid of those as risk @ryw? 

Maybe we simply want to get rid of those because we want to avoid any risk whatsoever ?

**Comment by ryw** [comment]
We should seek to eliminate category-x dependencies/references, if possible, as the cleanest resolution.

For those that we cannot get rid of, or don't think we must get rid of (if we think we are OK in how we're using them), we'll document that somewhere for reference (which I volunteer to do).

**Comment by potiuk** [comment]
Sure - I am perfectly ok with that - and documenting is a good thing. 

I just think we are spinning in circles a bit - I thought we reached conclusions and explained all reasons in #9898. So I am surprised a bit that we have the second one, but I might be wrong about "conclusions", so I prefer to ask.

**Comment by ryw** [comment]
Hi @potiuk i better understand now the technique we're using to provide constraint files that aren't in the source code - which definitely helps with automated scanners, since those files are in orphaned branches. 

Is the intention to keep this structure going forward through future releases, or is it a 1.10 -> 2.0 thing?

**Comment by potiuk** [comment]
It's going to stay like that as far as I am concerned. But his is something we are going to discuss on Monday. 

I am writing a short proposal for 2.0 release/packaging process today, so that everyone can read it before we have our Monday meetingu on 2.0. I promised I send it before at the last meeting.

**Comment by ryw** [comment]
Thanks @potiuk closing this issue, as the latest master doesn't trigger all these licenses any longer.

**Comment by potiuk** [comment]
Ah, so Snyke is not that smart eventually :). We still have text-unicode as transitive (tho optional) dependency still.
