### ISSUE TITLE
When multiple filters selected in arg_tags_filter, each filter works as 'or' instead of 'and'.

### ISSUE THREAD

**Issue by oboki** [apache/airflow#10724]
**Description**

When I selected multiple filters, it seemed that the tag filter didn't work as I thought. so I checked the query and found that the query uses `in clause`.

```sql
SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval 
FROM dag 
WHERE dag.is_subdag = 0 AND dag.is_active = 1 AND (EXISTS (SELECT 1 
FROM dag_tag 
WHERE dag.dag_id = dag_tag.dag_id AND dag_tag.name IN (%s, %s)))
```

**Use case / motivation**

I want this filter to work with the 'and' condition. and I think 'and' condition is more familiar with the filter function.

**Comment by kaxil** [comment]
cc @ryanahamilton Our author of the filter :) Was this intentional ?

**Comment by ryanahamilton** [comment]
@kaxil I think you might be mixing this up with the _status_ filter I added. The tags filter was added shortly before by @zacharya19 in #6489. What say you @zacharya19?

**Comment by kaxil** [comment]
aah sorry for the mixup :)

**Comment by zacharya19** [comment]
@kaxil Yep, it was intentional.
What I had in mind is tags per "team", so it make sense it will be "OR".
I think we should add a config option to control the default behavior and maybe an option to choose it in the UI.

**Comment by tschroeder-zendesk** [comment]
Fairly old issue, but it would be really helpful if we could use AND or have an option in our case we have about 400 dags and we are generally only working with a handful of them. We have them tagged as 3 different things pod/cluster/state and would be great if we could easily say I want all  cluster=green AND pod=13 for example instead of the current workaround which means we will need to add a bunch of superfluous tags that have the combo options so we can see a nice slice of dags.

**Comment by sm-kacper** [comment]
Totally agree, we are in a very similar situation. We have plenty of dags and we use tags to group them by client, environment, service they are using etc. It would be perfect option for our use case to use AND operator in tags, so that we can choose a small subset of dags f.e. all dags that use certain api for given client.

**Comment by potiuk** [comment]
Just repeating myself - but Airflow is created by >2100 contributors - mostly users who want to solve their problems. 

Contributions are most welcome and if any of the people here would like to go an extra mile (or rather foot) to add this as a feature - you are most welcome!

This is the fastest and most certain way to get it implemented.

**Comment by sm-kacper** [comment]
I can see that a decision has been made to implement this feature as a part of UI part (see PR #25437). Is there anything i can do, as a Python dev that has no skills in the UI area, to help in this implementation?

**Comment by jscheffl** [comment]
This bug report is quite outdated, there are more recent requests for changes which super-seed this request.

**Comment by ryuichi-zd** [comment]
Found a more recent issue raised: https://github.com/apache/airflow/issues/39363
