### ISSUE TITLE
Release Helm Chart officially

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#10752]
**Description**

When we are ready, we should release the Helm Chart officially. 

**Use case / motivation**

Discussion in Apache Software Foundation started: https://github.com/helm/charts/issues/23685 about standardising policies and tools for releasing Helm Charts in ASF and we should follow it.

**Comment by potiuk** [comment]
CC: @dimberman @kaxil @ashb

**Comment by mik-laj** [comment]
I would like to leave a note here that if we publish the documentation on ArtifactsHub, we will have user-friendly reference documentation. 
See: 
https://github.com/apache/airflow/issues/11077

**Comment by dimberman** [comment]
@mik-laj That's fantastic thank you!!

**Comment by ryw** [comment]
dropping a note here that we decided to defer this to post Airflow 2.0

**Comment by dnskr** [comment]
Hi @potiuk, @ryw and others!
Do we have any updates on this issue?
Can I use this chart or can I help somehow to move forward?

I am asking because current airflow helm chart from https://charts.helm.sh/stable is still community edition which is not relevant to the [doc](https://github.com/apache/airflow/tree/master/chart#installing-the-chart)
```
$ helm repo list
NAME                    URL
stable                  https://charts.helm.sh/stable

$ helm search repo stable/airflow
NAME            CHART VERSION   APP VERSION     DESCRIPTION
stable/airflow  7.13.3          1.10.12         DEPRECATED - please use: https://github.com/air...
```

**Comment by potiuk** [comment]
I  hope we can discuss the steps to make helm "released" at the next "dev" meeting which is going to be tomorrow ..

**Comment by dnskr** [comment]
I'll be happy to contribute into it if needed.

**Comment by kaxil** [comment]
**Next Steps**:

- [ ] Finalize Versioning Strategy
- [ ] Review Current Test Coverage
- [ ] Review Architecture
- [ ] Publish Snapshot
- [ ] Release first version on official destination (https://dist.apache.org/repos/dist/release/airflow/)
- [ ] Publish it on community hubs

I will start creating issues for each point

**Comment by kaxil** [comment]
@dnskr Can you start looking at tests and add where they are missing, that would be a great help

**Comment by thesuperzapper** [comment]
Just my 2c, but I also think there is a significant amount of documentation lacking which will make a bad first experience with the chart:
- the `values.yaml` file is missing comments for most values
- more general explanations are pretty sparse (it seems we currently only have short paragraphs in the README)
- examples for common environments are missing (GKE, EKS, On-Prem)


Related to this (and the discussion about versioning strategy), we should consider:
- publishing the doc's seperate to airflow itself, (because I assume we will release the chart at a different cadence to airflow)
- provide upgrade guides for major/minor version bumps of the chart

**Comment by kaxil** [comment]
Good points @thesuperzapper - I added a point to review and add lacking documentation (we can expand on the details after we create issues for each of those points).

**Comment by kaxil** [comment]
The following Project Board should help with tracking the progress as well as to all of you who would like to help with the process.

**Comment by lewismc** [comment]
This would be super helpful folks. I'll try my best to provide more PR's on the Chart as my experiments evolve and knowledge improves.

**Comment by kaxil** [comment]
The first version of the official Helm Chart was finally released yesterday.

Mailing List Announcement: https://lists.apache.org/thread.html/r131d839158b8a7a92a7813183cae30d248be9e330ea2faaf9e654970%40%3Cdev.airflow.apache.org%3E :tada:
:package: ArtifactHub: https://artifacthub.io/packages/helm/apache-airflow/airflow
:books: Docs: ⁨https://airflow.apache.org/docs/helm-chart/1.0.0/
:rocket: Quick Start Installation Guide: https://airflow.apache.org/docs/helm-chart/1.0.0/quick-start.html

Thanks to all the contributors who made this possible.

**Comment by potiuk** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by lewismc** [comment]
Real nice work 🎉
