### ISSUE TITLE
Model User has table name 'user' which is a special table in postgres

### ISSUE THREAD

**Issue by laura-moore** [apache/airflow#1083]
PostgresQL creates its own 'user' table. An improvement for Airflow would be to avoid using this as a table name for the User model and go with 'users' instead.

**Comment by mistercrunch** [comment]
I'm confused as to how everyone else is using Postgres then?

**Comment by mistercrunch** [comment]
@r39132 aren't you guys using Postgres as a backend

**Comment by laura-moore** [comment]
I've suggested this only as an improvement. 

Calling the table 'user' doesn't stop Airflow from working with a postgres backend, but 'user' is considered a reserved word in postgres that should not be used for table names. If I log on to the postgres shell:

`select * from user;`

returns the postgres current_user (not the airflow users).  To see the airflow users, I need to:

`select * from "user";`

So the users are there and airflow is still working, but from perspective of development/debug/best practice, I am suggesting that renaming this table would be an improvement (not a necessity).

**Comment by mtoma** [comment]
I can confirm that this issue is slightly confusing on a postgres setup.

`airflow=# select * from user;`
`current_user`
`--------------`
`postgres`
`(1 row)`

`airflow=# select * from public.user;`
`id | username | email | password`
`----+----------+-------+----------`
`(0 rows)`

[PostgreSQL System Information Functions](http://www.postgresql.org/docs/current/static/functions-info.html)
