### ISSUE TITLE
Airflow Logo hides half of the page

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11025]
Looks like a side-effect of https://github.com/apache/airflow/pull/11018

Airflow Logo almost takes up half of the page on current master: 

![image](https://user-images.githubusercontent.com/8811558/93656441-65aead80-fa22-11ea-9cf5-a3ec5eed1c11.png)

cc @ryanahamilton

**Comment by ryanahamilton** [comment]
This would surely be a side-effect of #11018, but I'm unable to reproduce in Chrome, Safari, or Firefox on Mac. I can certainly provide a simple solution for this if it is indeed a problem.

**Comment by yuqian90** [comment]
I could reproduce this in Chrome on Mac.

@ryanahamilton I think there are two issues at least.
1. For the problem @kaxil  reported, I think it's caused by the javascript code in graph.html, tree.html, etc that does this. These code picks up the `svg` tag in the header as well and transform it. That's why it became distorted. If you could identify all these code and change them to select something more specific that should fix it, e.g. `d3.select("#svg_container svg")` or something along that line. It's not clear to me why you had issues reproducing this though.

```javascript
  d3.select("svg")
  .insert("g")
...
```
2. Unrelated to 1, even in the home page, the alignment of the logo seems off. Looks like this for me. I believe this is a simpler problem than 1.

![image](https://user-images.githubusercontent.com/6637585/93661782-1d78a500-fa8d-11ea-9e05-f59f0f32f2d3.png)

**Comment by turbaszek** [comment]
> ![image](https://user-images.githubusercontent.com/8811558/93656441-65aead80-fa22-11ea-9cf5-a3ec5eed1c11.png)

Go big or go home 😸

**Comment by ryanahamilton** [comment]
I can see it now—I didn't know it was view-specific and hadn't ventured off of the home page in my testing.

@yuqian90 yes, that is indeed the issue. Generic selectors that assumed another SVG element would never be added to the page. I'll fix this. 

As for the #2, you. probably just need to run `airflow/www/compile_assets.sh`—there is a CSS adjustment of the padding around the logo in `main.css` that you don't appear to have.

**Comment by ryanahamilton** [comment]
Graph view is also drawing teensy little charts on top of the logo 🧐  

<img width="138" alt="Image 2020-09-19 at 8 05 41 AM" src="https://user-images.githubusercontent.com/3267/93666922-11babd80-fa50-11ea-9ab8-53f1b92827b7.png">
