### ISSUE TITLE
Classifiers seem inaccurate

### ISSUE THREAD

**Issue by pganssle** [apache/airflow#11059]
I was looking at your `setup.py` to see if you would be affected by forthcoming breaking changes in `tzlocal` (you will not because you have already pinned to an old version anyway), and I noticed that while your [classifiers say that you support Python 3.6-3.8](https://github.com/apache/airflow/blob/19d781f2fdcc21bfd1be98ece5a864bf342c2adc/setup.py#L789-L791), your [`python_requires` says 3.6 only](https://github.com/apache/airflow/blob/19d781f2fdcc21bfd1be98ece5a864bf342c2adc/setup.py#L805). I'm not sure if you're aware, but `pip install .` on anything except for Python 3.6 will _refuse to install this package_, and one reason that `setup.py install` may still work is that `setup.py install` is deprecated and it is no longer being maintained.

You may want to loosen the bounds on the `python_requires`, because it is not as if `pip` can automatically satisfy the dependency anyway.

**Comment by mik-laj** [comment]
@pgagnon It makes sense. Can I assign you to this task so that you open a PR?

I always have a problem with the butt classifier, but I checked and we have too strict restrictions.
<img width="264" alt="Screenshot 2020-09-22 at 10 41 32" src="https://user-images.githubusercontent.com/12058428/93861040-3321e080-fcc0-11ea-8f07-2694c87ae15d.png">

**Comment by ashb** [comment]
`~=3.6` in Python version specifiers is the equivalent of: `= 3.6, == 3.*` https://www.python.org/dev/peps/pep-0440/#compatible-release
