### ISSUE TITLE
Unexpected super long period CI tasks.

### ISSUE THREAD

**Issue by wu-sheng** [apache/airflow#11114]
**Description**

**Use case / motivation**

Hi, Airflow team
This issue is not related to the Airflow feature, but to the GitHub action control. 
I am talking with the GitHub Action team, as I noticed, sometimes, the ASF GitHub action has very limited slots for Apache SkyWalking.
GitHub did some research, and at least found one task from the Airflow project, 
https://github.com/apache/airflow/actions/runs/259069303

This task lasts over 6 hours until GitHub action platform terminated it. Could you help with rechecking why it last so long?

**Related Issues**

**Comment by potiuk** [comment]
We also recently noticed some slow-downs and limited number of slots for Airflow. So far it's been rather generous :). 

I am not exactly what the root cause was, but. It could be because of a weird race condition with cancelling jobs. This is a special step in our build that waits until images are build by another ("workflow_run") workflow. This is because the PR workflow does not have the permissions to push such image, so workflow run builds the image, but this particular job waits for it. 

Usually it takes < 4 minutes, sometimes ~ 10 minutes and in rare circumstances ~20 minutes. We do have canceling implemented in the "workflow_run"  - if it fails or gets canceled, it should cancel this "PR" job. But there is one case wich might happen - if the "cancel" step in the "workflow_run" gets cancelled as well, the PR might not get cancelled.

This can be easy to fix - ao far we did not have any timeout for that step, so default 6hrs one applies. I will decrease the timeout to 40 mins or so (to get some spare time), so that in this rare cases we will timeout faster.

**Comment by wu-sheng** [comment]
The GitHub team can't be sure either at this moment, they gave me this task link, which is the only reason I reached the AirFlow team just for checking.

Close this at any moment you want, I just wanted to ping the Airflow team to inform what I got.

**Comment by potiuk** [comment]
PR in progress: https://github.com/apache/airflow/pull/11117

BTW. I am also working (but had some interruptions) on a change that will decrease the number of jobs and time used by those jobs in general for like 90% of our PRs. I estimate that in most cases (80%-90% of builds) those PRs will use < 25 % of the current build time and it will decrease the waiting time from 40 minutes to 10 minutes on average.

Looks like it's a good time to prioritise it.

**Comment by potiuk** [comment]
And thanks a lot for Pinging us @wu-sheng ! Really appreciate it!

**Comment by potiuk** [comment]
@wu-sheng The timeout PR is merged so there should be no more 6hrs long jobs (I set 50 minutes). I will also observe if the 50 minutes jobs are happening often. 

On the other hand - Is it possible to add me somehow to the discussion with GitHub? 
I would love to be able to understand potential problems and maybe I can help in the discussion. I think we are in the same boat here :) and got quite some experience in the Github Actions CI and maybe I can help somehow.

One more thing.

One of the big speedups (still not the final one) we got in Airflow was thanks to switching to 'workflow_run' types of workflows and sharing images via GitHub registry, as well as the custom "Cancel Workflow Runs" actions I developed. 

Canceling duplicate workflows (for example when people submit fixup to their PRs) is not an easy and obvious thing in GitHub Actions - for repositories that use "Pull Request from Forks" approach (all Apache projects are), but I developed this custom action - https://github.com/marketplace/actions/cancel-workflow-runs to help with that - and it helps a lot in optimizing our builds. Maybe you would like to use it :).

**Comment by wu-sheng** [comment]
> https://github.com/marketplace/actions/cancel-workflow-runs 

This is super COOL!!, I will ask the community to try that. SkyWalking is using a lot of resources too.

> On the other hand - Is it possible to add me somehow to the discussion with GitHub?

I submitted a GitHub ticket, it seems private only. Currently, no further progress besides all the above information.
