### ISSUE TITLE
Big Query Location Not working

### ISSUE THREAD

**Issue by Iskz** [apache/airflow#11203]
We are having issue when trying to use BigQueryHook to retrieve a dataset which is NOT IN US

```
from airflow.contrib.hooks.bigquery_hook import BigQueryHook
bq_hook = BigQueryHook(bigquery_conn_id='bigquery_default', location='asia-southeast1', use_legacy_sql=True)

query = """
SELECT * FROM `non-us-dataset.table_id`;
"""

bq_hook.get_records(sql=query)
```

example error:
```

{
    'reason': 'notFound',
    'message': 'Not found: Dataset dataset-xxx:`dataset_id was not found in location US'
}.The job was:
    {
        'kind': 'bigquery#job',
        'etag': '123412341234==',
        'id': 'dataset-xxx:US.123412341234',
        'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/dataset-xxx/jobs/123412341234?location=US',
        'user_email': 'service-account',
        'configuration':
        {
            'query':
            {
                'query': "SELECT * FROM `non-us-dataset.table_id`",
                'priority': 'INTERACTIVE',
                'useLegacySql': True
            },
            'jobType': 'QUERY'
        },
        'jobReference':
        {
            'projectId': 'dataset-xxx',
            'jobId': '12341234',
            'location': 'US'
        },
        'statistics':
        {
            'creationTime': '1601460946946',
            'startTime': '1601460946960',
            'endTime': '16014609...'
        }
```

**Comment by TobKed** [comment]
You can try to use `airflow.providers.google.cloud.hooks.bigquery.BigQueryHook.run_query` method.

However `bq_hook.get_records` should work anyway. Which version of airflow do you use?

**Comment by Iskz** [comment]
currently i'm on version 1.10.12
for airflow.providers.google.cloud.hooks.bigquery.BigQueryHook package are you referring to 
https://pypi.org/project/apache-airflow-backport-providers-google/

**Comment by TobKed** [comment]
I referred to the latest state on the master. I will investigate how backport packages works, I am not familiar with them.
I found PR related to the location support https://github.com/apache/airflow/pull/4695

I will try to reproduce your error on 1.10.12 and verify is it working on the latest master and with backported package.

**Comment by turbaszek** [comment]
The `BigQueryHook` from providers package has no `get_records` method. Please see the information about backport packages:
https://airflow.readthedocs.io/en/latest/backport-providers.html

**Comment by TobKed** [comment]
@turbaszek `get_records` method is inherited from `DbApiHook` and if I am not mistaken is present in backported packages as well.

@Iskz I reproduced your case and it seems that error message is little bit misleading. It seems that the problem is not in location (I played with it extensively as well) but with backtics enclosing table reference.
According to the documentation:
https://cloud.google.com/bigquery/docs/reference/legacy-sql#from-tables
you should enclose table reference in brackets so it would be `[my-dashed-project:dataset1.tableName]` (or `[dataset1.tableName]`,  project name is optional if dataset belongs to the project defined within used gcp connection).
Let me know does it work for you.

**Comment by Iskz** [comment]
@TobKed Well, I got a different error instead after using legacy SQL
'Querying tables partitioned on a field is not supported in Legacy SQL: ...'

**Comment by TobKed** [comment]
It may be problematic to use legacySQL with such features. Are you restricted to legacySQL?
If not you can migrate them to standardSQL and setting up `use_legacy_sql=False`.

https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql

**Comment by Iskz** [comment]
Sorry for the late reply. The goal was to run a basic query to retrieve dataset from bq. Initially I have tried the bq_hook.get_pandas_df(). Hit some issues, but was resolved. I did want to look into other ways of getting the result instead of in a dataframe object.

**Comment by eladkal** [comment]
@TobKed can you clarify what is the bug? it sounds more like we need to make some clarifications in the docs

**Comment by TobKed** [comment]
Problem was using backtics instead of brackets enclosing table reference ([comment](https://github.com/apache/airflow/issues/11203#issuecomment-702364275)) and then using lecacy SQL ([comment](https://github.com/apache/airflow/issues/11203#issuecomment-702638181)). It seems not related to BigQuery hook/operators but to the usage of BQ iteself.
IMHO this issue could be closed.
WDYT @eladkal @turbaszek ?

**Comment by potiuk** [comment]
Agree.,
