### ISSUE TITLE
Missing "git_subpath" config in Helm values

### ISSUE THREAD

**Issue by flvndh** [apache/airflow#11237]
I'm not sure if it's a bug or not as it is kind of [specific](https://github.com/apache/airflow/blob/87038ae42aff3ff81cba1111e418a1f411a0c7b1/airflow/kubernetes/worker_configuration.py#L195) but in `airflow/executors/kubernetes_executor.py` the `KubeConfig` class tries to get the [value ](https://github.com/apache/airflow/blob/87038ae42aff3ff81cba1111e418a1f411a0c7b1/airflow/executors/kubernetes_executor.py#L111) of `git_subpath` but this value isn't [present ](https://github.com/apache/airflow/blob/87038ae42aff3ff81cba1111e418a1f411a0c7b1/chart/values.yaml#L504) in `chart/values.yaml` on the `v1-10-stable` branch.

**Comment by mik-laj** [comment]
Why do you want to use Chart from v1-10-test branch? The chart from [master](https://github.com/apache/airflow/tree/master/chart) is compatible with Airflow 1.10 and 2.0 and is being actively developed.

**Comment by brettstewart** [comment]
@flvndh You can add `git_subpath` under the kubernetes section in values.yaml
https://github.com/apache/airflow/blob/87038ae42aff3ff81cba1111e418a1f411a0c7b1/chart/values.yaml#L485

The configmap will pick it up since it loops through all the key/value pairs
https://github.com/apache/airflow/blob/87038ae42aff3ff81cba1111e418a1f411a0c7b1/chart/templates/configmap.yaml#L38
