### ISSUE TITLE
Missing timer metric dag.loading-duration.<dag_file> in documentation

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#11341]
**Apache Airflow version**: doc on version 1.10.6+

In [1.10.5 metrics documentation](http://airflow.apache.org/docs/1.10.5/metrics.html), there is an entry for `dag.loading-duration.<dag_id>`.

In [1.10.6 metrics documentation](http://airflow.apache.org/docs/1.10.6/metrics.html), the entry disappeared.

The format has also change from `dag.loading-duration.<dag_file>` to `dag.loading-duration.<dag_id>` starting from 1.10.4 according to this [JIRA ticket](https://issues.apache.org/jira/browse/AIRFLOW-5274) and [PR](https://github.com/apache/airflow/pull/5890).

**Comment by kaxil** [comment]
Thanks, will check

**Comment by kaxil** [comment]
So the issue was although the docs were updated in 1.10.6 the code wasn't. But the metric `dag.loading-duration.<dag_id>` was emitted (also in Airflow 1.10.12)

From Airflow 1.10.13 this metric will be changed to `dag_processing.loading-duration.<dag_file>`


dag_processing.last_duration.<dag_file> |  
-- | --

**Comment by kaxil** [comment]
(#5890 has been cherry-picked)
