### ISSUE TITLE
Should operators push their values by default?

### ISSUE THREAD

**Issue by hyperborea** [apache/airflow#1146]
I'm struggling with the best practice around using operators result values downstream in other tasks.

Example:
a) get a single value through a (templated) Hive query
b) dependent on the value, send a (templated) email or not
c) insert this value into a (templated) postgres history table

All of this could obviously be achieved through a PythonOperator and using the hooks / send_email directly, but that's not very clean and I'd rather keep the different parts neatly in their own tasks: HiveOperator for a), EmailOperator (or some ConditionalEmailOperator) for b) and PostgresOperator for c). The problem is that none of these operators returns their values and in fact it seems like only BashOperator implements a xcom_push parameter for this purpose.

What's considered the right way to solve this problem? I'm close to extending the operators we're using, but maybe I'm just missing something obvious.

**Comment by r39132** [comment]
I think this is an excellent question. I agree that they should. To link them together, you can use a PythonOperator, BranchPythonOperator or a ShortCircuitOperator. 

I'd be in favor of altering existing operators so they push their return values onto xcom where appropriate. This may be tricky for operators that can return a ton of data, since we store this data in the metadata db and I don't believe we ever clear that data. 

Submit a PR and we would happily review it.

**Comment by r39132** [comment]
For any operator that returns a value, that value is available via xcom.

It's important to consider how much data can be returned by an operator, because storing that in the xcom table can be expensive. If you extend the hive operator to return a single value (e.g. like a count query), then that return value will be automatically stored in xcom for you to use. You will then need to read that value in a PythonOperator, BranchPythonOperator, or ShortCircuitOperator, which can do custom logic around emailing and inserting into a DB. I don't think we have a mechanism to pass params to more generic operators from other operators.

**Comment by bolkedebruin** [comment]
I think it should be slightly different. I think operators should push handles to the values to xcom. Those handles could point to something at hdfs, s3, whatever. A bit like the output functions of luigi tasks. This resolves the issue of large datasets and really allow you to work from the data's perspective instead of being task centric.

**Comment by dgies** [comment]
You folks raise some interesting points.
@hyperborea is right that there is some value in being able to have a query return a value for use in other tasks.  That could probably be done now with PythonOperator/HiveCliHook.run_cli and EmailOperator.
@r39132 is right that in returning a full query result will often be impractical/impossible from a performance perspective.  The xcom system is designed for return values, not datasets
@bolkedebruin brings up the interesting idea of returning result handles much like Luigi does it.  It would probably make the Airflow batch system more flexible to orient jobs around arbitrary resource handles instead of only execution dates like it is now.  Some issues with this proposal:
- The creation of a resource handle would have to be implemented one-by-one for each operator.  For HiveOperator it might be tricky to identify the precise output if the supplied HQL consists of multiple queries.  Same for Pig scripts with multiple outputs.  For a PythonOperator we'd need a new convention for DAG authors to specify the output handles.
- This output handle approach wouldn't do much for @hyperborea 's original use case. A simple "select count(*)" Hive query would probably return a handle to a temporary directory on HDFS

It seems to me we need two approaches:
1. Create a new operator which executes a single-value Hive query and returns the value via xcom.  The operator raises an exception if the query returned multiple values.
2. Existing operators should, where practical, be modified to return some sort of handle or handles to their output.  In the case of HiveOperator this might mean parsing the log for messages about updated tables or partitions.  Because some operators may update multiple destinations the returned handle may be a nested array.

**Comment by bolkedebruin** [comment]
@dgies Not entirely: if a handler as a generic interface being it iterable or not it does not really matter if it is a "select count(*)" or a handle to a set of files.  So ideally current operators would be adjusted indeed.

**Comment by dgies** [comment]
@bolkedebruin The problem is if you're implementing this enhancement to HiveOperator, how do you know whether to return a numeric count, or a handle to the HDFS location containing the count?  If you're implementing an operator that uses this result, how do you know what to expect?  A general HiveOperator will have to return an array of result handles to be usable for all possible queries.  Making it _sometimes_ return a single scalar will lead to messy code.

**Comment by jlowin** [comment]
Maybe I'm misunderstanding the issue, but XCom values are totally arbitrary and it's up to the user to determine how they are pushed/pulled and interpreted. Therefore, I'm not sure much extra work has to be done to support the handle approach.

For example, extend `HiveOperator` to create and return the handle:

``` python
class MyHiveOperator(HiveOperator):
    def execute(self, context):
        # do the normal execution
        super().execute(context)
        # then push the handle, whatever it might be
        return make_handle()
```

Then build a `PythonOperator` (or `BranchPythonOperator`) that pulls the handle, uses it to check a (potentially) more complex result, and continue appropriate.

``` python
def fn(context):
    handle = context['task_instance'].xcom_pull(task_ids='my_hive_operator')
    result = do_something(handle)
    if result:
        send_email()
    else:
        dont_send_email()
    return handle
PythonOperator(python_callable=fn)
```

To replicate Luigi-style targets, the HiveOperator could return (for example) an s3 path to a `_success` file. The PythonOperator could use that path to check for the file.

If the consensus is that this is a useful pattern, but the xcom implementation is a bottleneck due to complexity (especially because it requires the subclass boilerplate) then maybe we can look at decorators that make it easier to push/pull values (but don't make any demands about what those values are!). For example:

``` python
my_first_op = xcom_push_decorator(HiveOperator(), fn_that_defines_push)
my_second_op = xcom_pull_decorator(PythonOperator(), my_first_op)
```

I think the proof is that I wrote the XCom interface and I still had to go look it up just now :)
