### ISSUE TITLE
apache-operator-*.tgz tarballs missing setup.py and setup_requires dependencies.

### ISSUE THREAD

**Issue by mjpieters** [apache/airflow#11546]
**Apache Airflow version**: 2.0.0a1

**Environment**:

- **OS** (e.g. from /etc/os-release): MacOS
- **Install tools**: pip

**What happened**:

Installing from the 0.0.1a1 release tarballs fails as there is no `setup.py` file:

```bash
$ pip install https://dist.apache.org/repos/dist/dev/airflow/providers/0.0.1a1/apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz
Looking in links: /.../pip/wheelhouse/
Collecting https://dist.apache.org/repos/dist/dev/airflow/providers/0.0.1a1/apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz
  Using cached https://dist.apache.org/repos/dist/dev/airflow/providers/0.0.1a1/apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz (167 kB)
    ERROR: Command errored out with exit status 1:
     command: /.../bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vh/.../T/pip-req-build-vo6wt0kh/setup.py'"'"'; __file__='"'"'/private/var/folders/vh/.../T/pip-req-build-vo6wt0kh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vh/.../T/pip-req-build-vo6wt0kh/pip-egg-info
         cwd: /private/var/folders/vh/.../T/pip-req-build-vo6wt0kh/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/.../lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/vh/.../T/pip-req-build-vo6wt0kh/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Instead of `setup.py`, there is a `setup_providers_package.py` file:

```bash
$ curl -s https://dist.apache.org/repos/dist/dev/airflow/providers/0.0.1a1/apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz | tar tzv | grep setup
-rw-r--r--  0 root   root     1456 Oct 14 07:45 apache-airflow-providers-amazon-0.0.1/setup.cfg
-rw-r--r--  0 root   root    55159 Oct 14 07:30 apache-airflow-providers-amazon-0.0.1/setup_provider_packages.py
```

If I re-package the tarbal with that file moved to `setup.py` I get a different error:

```bash
$ tbtemp=$( mktemp -d -t airflow-porviders); pushd $tbtemp
/var/folders/vh/.../T/airflow-porviders.MwwV87dG ~/oldlocation
$ curl -s https://dist.apache.org/repos/dist/dev/airflow/providers/0.0.1a1/apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz | tar xz
$ mv apache-airflow-providers-amazon-0.0.1/setup_provider_packages.py apache-airflow-providers-amazon-0.0.1/setup.py
$ tar czf apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz apache-airflow-providers-amazon-0.0.1/
$ popd
~/oldlocation
$ pip install $tbtemp/apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz
Looking in links: /.../pip/wheelhouse/
Processing /var/folders/vh/.../T/airflow-porviders.MwwV87dG/apache-airflow-providers-amazon-0.0.1a1-bin.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /.../bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vh/.../T/pip-req-build-15bh7ahl/setup.py'"'"'; __file__='"'"'/private/var/folders/vh/.../T/pip-req-build-15bh7ahl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vh/.../T/pip-req-build-15bh7ahl/pip-egg-info
         cwd: /private/var/folders/vh/.../T/pip-req-build-15bh7ahl/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vh/.../T/pip-req-build-15bh7ahl/setup.py", line 37, in <module>
        import semver
    ModuleNotFoundError: No module named 'semver'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This indicates `setup_requires` dependencies have not been specified. 

**Anything else we need to know**:

The provided wheels work fine, so `https://dist.apache.org/repos/dist/dev/airflow/providers/0.0.1a1/apache_airflow_providers_amazon-0.0.1a1-py3-none-any.whl`, etc. (note the underscores in the filename where the `tgz` used dashes), presuably because these have been built by running `setup_provider_packages.py` directly with the setup dependencies installed locally.

**Comment by potiuk** [comment]
Thanks @mjpieters ! Will fix it.

**Comment by potiuk** [comment]
Auto-closed during testing by mistake

**Comment by potiuk** [comment]
I already have a working version of this. @mjpieters (but also @kaxil and @ashb ). And I have one question on what you think Kaxil and Ash regarding releasing the providers officially.

We've agreed that we will release the sources for each provider separately, and while I implemented this issue I think I achieved exactly this by fixing the broken sdist package (as pointed out by @mjpieters - thanks again!).

According to ASF release policies, we need to make sure to release a  source package that must be sufficient for the user to rebuild the packages.

```
SOURCE PACKAGES
Every ASF release MUST contain one or more source packages, which MUST be sufficient for a user to build and test the release provided they have access to the appropriate platform and tools.
```
And when you look at the sdist packages (with fixed setup.py) for each provider does exactly this. If you see at the artifacts produced during the build here - my test CI build (artifacts will appear soon in https://github.com/potiuk/airflow/actions/runs/313648146), both providers and backport provider's sdist packages are exactly this - they allow anyone with the appropriate platform and sources to rebuild those provider packages. The PR for that change is opened now: https://github.com/apache/airflow/pull/11630 - I am still running some final reviews and fixes with the generated packages, but it should be fine. 

Now. The question I have: for Airflow, we have a separate -src.tar.gz file, which contains quite a bit more than the sdist .tar.gz package: Dockerfile, scripts, open API specification, and all the auxiliary stuff that we want to also release. I believe for providers, we do not need any of those, and we do not need anything more than the sdist tar.gz file. So IMHO we do not need to release any additional src-tar.gz file.

Let me know what you think @ashb @kaxil!

BTW: I think I did quite a nice refactor and simplification of package generation with those changes. I still generate the packages dynamically - (the setup.py files are generated from a JINJA template for each provider (separate setup.py  for backports and separately for the regular providers). Those setup.py will be updated and stored in the repo - separate setup.py for each provider in the relevant packages - this way we will keep track of those setup.py files via git history, which is pretty nice I think. 

I also test installation of all the generated packages (both .whl and sdist now - not only .whl as it used to be) on 1.10.12 for backport and on the latest "bare" airflow from the master for the regular provider packages (separate jobs in CI for those). 

This is all on top of verifying if all the operators/hooks/ etc. are importable (in 1.10.12 and master respectively). 

I think we are getting to a nice solution there. Once we move to betas and implement extras dependencies #11464 and later implement all the discovery features so that Airflow can automatically use those provider's extra links etc. (TODOs in https://github.com/apache/airflow/projects/5)  - I think it's a really nice approach we are going to have.
