### ISSUE TITLE
Operator for prometheus API interaction

### ISSUE THREAD

**Issue by cherusk** [apache/airflow#11549]
**Description**

Instead of building prometheus queries on other operators, e.g. python operator, come forth with a dedicated prometheus API interacting operator.

I'm prepared to substantially contribute to such a operator and would mostly like to learn would that be acceptable for the AIRFLOW community.

**Use case / motivation**

For a project of mine, godon[1], which is basing on airflow at its core I'm seeking to have an operator that interacts with the prometheus API to at least gather metrics. There are already prometheus-api shim libarires[2] offered which makes a dedicated operator quite tangible. 

[1] https://github.com/cherusk/godon
[2] https://github.com/AICoE/prometheus-api-client-python

**Related Issues**

Not knowingly.

**Comment by mik-laj** [comment]
We are open to all operators, but they must have unit tests. :-) 

Related: https://github.com/apache/airflow/issues/10386

**Comment by mik-laj** [comment]
Could you provide some use cases for such an operator?

**Comment by cherusk** [comment]
> Could you provide some use cases for such an operator?

I provided that of godon, where it would scrape the exporters or aggregator prometheus instance periodically in an optimization DAG. Would you need more detail?

**Comment by ashb** [comment]
It is also possible that you can create the operator "externally" to the Airflow source code -- https://github.com/great-expectations/airflow-provider-great-expectations is one such example.

Then if it proves popular we could discuss moving it "in tree" if needed.

**Comment by cherusk** [comment]
Why, it's a valid feature request which can be actioned by me or others

**Comment by ashb** [comment]
It can be yes, but it can also be done by anyone as a third party module, and then it doesn't need a small handful of busy people to review, test, do release management and follow Apache policies around releases.

I have no problem with it being in tree, but out of tree does have advantages for moving quickly.

**Comment by cherusk** [comment]
Understand your point and it's fair. Yet, I see no harm in leaving this open, as it's declared as what it is, a feature idea and should stay open to the world in that context. If mainliners don't want to support it, so be it. But closing it would signal wrong impression, at least for now.

**Comment by ashb** [comment]
Oh sorry, yes. I never intended to close this!

**Comment by potiuk** [comment]
I think we need to discuss this in the devlist. What is the future of Airflow in terms of new "providers" - whether we should incorporate more providers in Airflow after 2.0 and support them by community (and possibly grow it by accepting more committers from different areas) or whether we should slim it down and not accept wider contributions).

This has never been discussed openly - and while I feel there are some opinions there, there, they are just that - opinions, until we make it a point and discuss in the community and make decisions. 

I do not know personally what is my opinion at that because it is exactly this - it has not been discussed, neither pros/cons nor actual approach here has ever been discussed in the devlist as far as I can remember.

@ashb  -> I think it would be great if you start this discussion at the devlist, before we lightly discard such ideas whether new providers will be added in the community or as 3rd-party implementations ?

I think, whatever decision will be made, it should be made after raising the issue and public discussion at the devlist.

**Comment by ashb** [comment]
@potiuk I wasn't intending to create any consensus or precedent here -- merely pointing out that "operators are just python modules" so can easily live outside of the Airflow tree.

This is not new behaviour, nor should it controversial, as operators are just Python classes loaded when parsing the DAG file -- and we'd have to go out of our way in Airflow to stop this being the case.

I'll have a think if I _do_ want to create such a precedent/proposal.

**Comment by potiuk** [comment]
I think this is something definitely after we release 2.0 - the long planned "What's beyond 2.0" discussion.

**Comment by RNHTTR** [comment]
closing in favor of #20053
