### ISSUE TITLE
airflow2 alpha1 issues

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#11794]
1.
getting ModuleNotFoundError: No module named 'airflow.contrib.auth' when trying to create user

2.
should password package be default not an [extra]? can't use webui or trigger dag without password

3.
authenticate field (under [webserver]) in .cfg seems unused too

**Comment by mik-laj** [comment]
All these problems are because we deleted the Non-RBAC UI. We now only support the new RBAC UI based on Flask App Builder in Airflow 2.0. In Airflow 1.10, we support RBAC UI and Non-RBAC UI. but the non-RBAC UI doesn't get any new features, just security fixes starting from Airflow 1.10.8.
See: https://github.com/apache/airflow/blob/master/UPDATING.md#drop-legacy-ui-in-favor-of-fab-rbac-ui
