### ISSUE TITLE
One dag_run per DAG per second limitation

### ISSUE THREAD

**Issue by xavierp** [apache/airflow#1192]
Hello there, i have decided to open an issue to talk about the one `dag_run` per DAG per seconde limitation.

Here is the story : i was trying to figure out the best way to handle the parsing of an unknown number of files. For the background, at my company, we are migrating to a new infrastructure and we need to import old logs file. They are not timely based an can be thousands...

After a few tries i asked for help on the [Airflow Google Group](https://groups.google.com/forum/#!topic/airbnb_airflow/eI9eziXZ-W0) and discussed a bit about it with  @artwr .

To work this out i made a `TriggerMultipleDagRunOperator` based on the `TriggerDagRunOperator`. The callable function just return a list of `DagRun` objects. Sample code [here](https://gist.github.com/xavierp/e56a656aec0db9ecae8a). (This is far from perfection and was only done for test purposes)

I was first limited by the unique constraint key (`dag_id`, `execution_date`) on the `dag_run` table.

So i wrote a little patch to change that, but after a few tests i realized that a big part of airflow
is based on the fact that only one `dag_run` for a specified `dag_id` should append at the same time.
For example the webserver interfaces  /graph, /gant, /log are build using only the execution date and not the `dag_id`.

I think that we should be able to have multiple `dag_run` at the time for the same `dag_id` if they have
different input parameters (especially the `conf` field in the `dag_run` table)
For example if i have a DAG that do some tasks to import and parse a file, why could i not have multiple `dag_run` at the same time if they have different target file in the `dag_run`.`conf` field ?

My questions are :
- Is that the correct and intended behaviour ?
- Do you have a better workout around this ? (For the moment i use my `TriggerMultipleDagRunOperator` 
  with a `time.sleep(1)` in the for loop...)
- What do you think about it ?
- Do you plan / are you open to modifications of this ?

Here is a proposal :
We could, for example, create a unique key for the `dag_run` based on  (`dag_id`,  `execution_date`, `conf_hash`).
This would implies some modifications in the database model, in the main Airflow code and in the UI.

By the way thanks for the amazing work you have already done on Airflow and i would be very glad to help. :)

Best regards,

Xavier.

**Comment by mistercrunch** [comment]
Originally Airflow ran only on schedules, and the primary key for a task instance was defined as dag_id, task_id and execution_date. When we added the notion of externally triggered DAGs (not on a schedule), we kept the PK as an artifact since changing that would require a significant refactor. 

We did introduce the notion of run_id though that also has to be unique. (I believe there's a unique constraint on dag_id, run_id)

Anyhow, changing that would require much more work than working around it. (What should the tree view look like for instance?) So I'd suggest running around it. 

Running on schedule brings a lot of clarity to batch processing (though it's not always ideal or even possible). I'd consider having a job that run say every hour and batch processes all the files that have accumulated.

**Comment by stmudie** [comment]
I am running into this same issue. I wish to run a DAG against a folder full of files. I realise I could write a batch process, however, I was hoping to use the DAG to define the workflow for a single file. E.g., each task in the DAG to work on a single file. I'm using a BranchedPythonOperator to select tasks based on file contents etc.
