### ISSUE TITLE
add DateTimeBranchOperator

### ISSUE THREAD

**Issue by RosterIn** [apache/airflow#11929]
**Use case / motivation**

Airflow have `BranchSQLOperator` and `BranchPythonOperator`.
Airflow also have `DateTimeSensor`.

I find it very useful to have `DateTimeBranchOperator` that will allow to branch workflow based on specific DateTime
Sometimes in DAGs you want to do another set of tasks according to specific dates or time.

**Comment by tomasfarias** [comment]
Hello 👋 

I've been using Airflow for a while now and would love to get involved with the project and contribute some code. If nobody's working on this I'd like to open a PR. Just wanted to clarify a few questions:

* Should `DateTimeBranchOperator` support comparisons with partial dates? For example: branching based on a comparison between the current date and only a year, instead of a full date. I believe we should, although this may lead to a long argument list as we would need one for each date attribute.
* Should the operator inherit from `BaseBranchOperator`? Seems to me that would be the best option, but none of the examples mentioned inherit from it (`BranchSQLOperator` and `BranchPythonOperator`).

**Comment by mik-laj** [comment]
@tomasfarias Hi. It is best if you prepare a small POC that will not contain tests and will not even fully work but will allow us to familiarize ourselves with your concept. Then we can iterate over this code together. What do you think about it?

**Comment by tomasfarias** [comment]
Sounds perfect to me! Thanks for the guidance @mik-laj, I'll open a PR shortly.

**Comment by eladkal** [comment]
@tomasfarias Thanks for your contribution :+1:

**Comment by tomasfarias** [comment]
@eladkal thanks to you for the patience, great feedback, and all the work in Airflow!
