### ISSUE TITLE
sql_alchemy_conn - password contains special character

### ISSUE THREAD

**Issue by Nick-0723** [apache/airflow#11930]
**Apache Airflow version**: 1.10.7

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**: centos 7

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: sql_alchemy_conn 中 mysql 密码保护特殊字符如'#' '^' '@' 等时，无法与 mysql 认证通过。

[2020-10-29 15:31:51,830] {settings.py:254} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=23122
DB: mysql://airflow:***@xxxx:3306/airflow
ERROR 1045 (28000): Access denied for user 'airflow'@'xxx' (using password: YES)

**What you expected to happen**: 正确连接

**How to reproduce it**:

**Anything else we need to know**:

**Comment by auvipy** [comment]
can you the user access?

**Comment by Nick-0723** [comment]
> can you the user access?

airflow even can't start

**Comment by XD-DENG** [comment]
@Nick-0723 please report issue in English so that most folks in the community can understand the question.

Regarding your question itself, you need to encode the special characters in the URI. You can refer to this thread https://stackoverflow.com/questions/2401516/system-uri-cant-parse-when-password-or-username-field-contains-a-special-charac . It's similar.
