### ISSUE TITLE
For Airflow UI - changing background color to the hovered row (DAG)

### ISSUE THREAD

**Issue by debodirno** [apache/airflow#11996]
**Description**

For better UX, it seems this is very important, when there are multiple DAGs and you need to check the Links corresponding to the DAG.

**Use case / motivation**

A light sky blue or alice blue background color for table row on hover would help a lot when checking the extreme right side of the table, when there are lots of DAGs.

Seems like an easy issue to fix, but would really help with the user experience.

**Comment by XD-DENG** [comment]
A quite sensible feature to me. CC the UI/UX guru @ryanahamilton 

@debodirno if you have bandwidth, I would also encourage you to try to implement this feature and raise a PR later. Let me know if you are interested so I can assign this issue to you.

**Comment by debodirno** [comment]
@XD-DENG Yes, I am interested.

**Comment by XD-DENG** [comment]
Cool, I have assigned it to you. Thanks.

Look forward to your PR!

**Comment by ryanahamilton** [comment]
@debodirno AFAIK all of the tables in the UI already have a row-hover background-color change. Is the screenrecording below what you are referring to?

Since you mentioned "checking the links", you might be interested in seeing the updates made just this week in #11866.

![Screen Recording 2020-10-31 at 07 49 49 AM](https://user-images.githubusercontent.com/3267/97778484-e39bc380-1b4d-11eb-97cb-c75a84271f8c.gif)

**Comment by debodirno** [comment]
@ryanahamilton, oh I missed this. #11866 should solve this. Thanks!
