### ISSUE TITLE
S3Sensor should not parse AWS credentials files

### ISSUE THREAD

**Issue by adambom** [apache/airflow#120]
The standard way to read AWS credentials and the way boto implements it is to check first for environment variables and then fall back to `~/.aws/credentials` if the env variables don't exist. Airflow shouldn't be parsing that file on its own. Parsing credentials should be delegated to boto. The way it's implemented now, it's effectively impossible to connect to S3 without reading credentials from a credentials file.

Our use case is to dockerize airflow, using environment variables in our docker container to read in AWS credentials.

**Comment by artwr** [comment]
@adambom,

We needed and still need to support different config file formats than the ones supported by boto, hence our roundabout way of doing this, though I should probably reuse the facilities provided by boto when parsing the file formats it understands.

It is also possible to store the credentials in the extras of the airflow connection. See https://github.com/airbnb/airflow/blob/master/airflow/hooks/S3_hook.py#L82-84.

I will work on a way to fall back on environment variables, but because of our need to use several sets of credentials environment variables could not override values provided in the Airflow connections.

**Comment by adambom** [comment]
Thanks @artwr. Sounds like a decent solution. In the meantime we'll look into using the extra_params.

**Comment by robbwagoner** [comment]
+1 - our airflow instances have an IAM Role. Boto would use the Role on its own if the s3_hook wasn't requiring a credentials file.

**Comment by artwr** [comment]
@adambom and @robbwagoner, this issue should be resolved in the latest version of airflow. Specifying a s3 connection with empty extra will default back to boto's facilities for this. Sorry it took so long.

Feel free to reopen if you still have issues, but I have successfully tested this internally.
