### ISSUE TITLE
How do you use hooks?

### ISSUE THREAD

**Issue by davidaventimiglia-personal** [apache/airflow#123]
I see hooks being described in general terms under "Concepts" in the documentation, and I see particular hooks being described in detail under "API" in the documentation, but I see no example of how they would be used.  Do you have any examples of how they get "hooked" into a DAG?  Thanks.

**Comment by gtoonstra** [comment]
A hook is basically a connection to some system. So an operator and a sensor would use a "hook"  to connect to hive to execute query "X", which effects some update (operator) or checks on the results of some rows (sensor). I just finished a pull request for a new http operator, which can talk to many HTTP-based systems. An operator would usually use POST/PUT or DELETE (through the hook) and the sensor would usually use a "GET" request. 

Most hooks require a connection declaration. Rather than encoding that into every hook itself, there's a connections tab on the admin menu (of the webserver), where you can configure what ops and sensors connect to. So that way you keep username/pw and host configs out of the way of code. In the DAG you can then still refer to specific connection-id's.

**Comment by mistercrunch** [comment]
It abstracts 2 components of any external system:
- The connection information (hostname, login, password, default schema, ...)
- The API, making a more pythonesque / intuitive / homogeneous API on top of external systems API

These hooks are used by operators to interact with the external system. For example, HiveToMySqlTransfer and PostgresToMySqlTransfer would both use the MySql hook function that allows for loading data in MySql.

You can also use these hooks in PythonOperator, or interactively, say in iPython or Juniper to interact with your external systems without having to log in and use their often too complex API.

Here's an example of how easy it is to get some data out of Presto and into a Pandas dataframe:

```
from airflow.hooks import PrestoHook
h = PrestoHook()
df = h.get_pandas_df("SELECT * FROM users LIMIT 100")
...
```

**Comment by davidaventimiglia-personal** [comment]
Cool, cool.  So, how would I go about using the `S3Hook` object and its `load_file` operation to load a local file up to an S3 bucket within a DAG?  The basic flow would be, use a `BashOperator` to fetch data from a remote-endpoint (using `curl` or an API client or what-have-you), copy that file up to AWS S3, and then use another `BashOperator` to bulk-`COPY` the data into AWS Redshift.

**Comment by mistercrunch** [comment]
Well consider the fact that you may have multiple workers and that each task may take place on any worker. For that reason Airflow tasks should only use the local filesystem within the task execution scope and cleanup after themselves.

If you want to leverage the hooks, your best bet is to do it within a PythonOperator. You write a python function that say uses the `requests` library to fetch your file, push that to S3 using the S3Hook, then probably another task to run load from S3 to redshift (BashOperator? PostgresOperator?).

**Comment by davidaventimiglia-personal** [comment]
Thanks.  I'm not even sure if I want to leverage hooks.  I just know that I want to scribble a file onto a worker's local file-system, copy it to S3, and do a Redshift bulk `COPY`.  The first is already handled with a BashOperator.  The third can be handled either with a BashOperator or a PostgresOperator.  For copying the file to S3, I figured that since Airflow already has a "S3-thing" (i.e., an S3Hook) then I'd try to use it.  But, it seems I ought to be able to use a BashOperator for that as well, along with the AWS CLI.  That might be easier than using the PythonOperator in the way that you describe.

**Comment by mistercrunch** [comment]
Step 1-2 need to happen atomically if you use the local file system and you want your DAG to work on a multi-worker environment, unless you use a mountpoint that all workers have mounted.

PythonOperator leveraging hooks leads to better looking, more reusable code than BashOperator in general, but whatever works for you!

We like to leave all the connection information (hostname, login, passwords) out of our scripts and PythonOperator+hooks allow for that.

**Comment by thomastanmin93** [comment]
@mistercrunch 
![image](https://cloud.githubusercontent.com/assets/8220811/10876940/6f90a656-817c-11e5-8a6b-49bd9f66d0d8.png)

I want to use the S3KeySensor to check if some files exist in the aws S3, when I config the connection of  S3KeySensor ,I don't know how should I config the host && schema && login && password since I needn't use these params when I access aws s3 using aws cli.

Can you give me an axample ?

**Comment by artwr** [comment]
@Thomasmisfit , you could use the following and use a config file. We support boto, s3cmd and aws credential files.

![screen shot 2015-11-02 at 9 40 52 am](https://cloud.githubusercontent.com/assets/1518713/10889269/dd0c7b38-8145-11e5-8918-38f81e8ec4c3.png)

Or you could also enter the access and secret key in the extra field. The keys have to be named `aws_access_key_id` and `aws_secret_access_key`.
