### ISSUE TITLE
Standardize our YAML file extension name

### ISSUE THREAD

**Issue by jbampton** [apache/airflow#12426]
**Description**

We have both `.yaml` and `.yml` files. 

"The official recommended filename extension for YAML files has been `.yaml` since 2006"

So all YAML files should use the same file extension.

https://en.wikipedia.org/wiki/YAML
https://yaml.org/

**Comment by potiuk** [comment]
Not everything can be changed unfortunately AFAIK. I am afraid a lot of tools /external services expect .yml - for example readthedocs (https://docs.readthedocs.io/en/stable/config-file/v2.html) and codecov require specifically .yml (https://docs.codecov.io/docs/codecov-yaml) files - similarly ISSUE_TEMPLATE/confg.yml for github issues: (https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository) 

So while the official recommendation is there, I don't think we are in a position to standardize it fully, I am afraid. 

And since we cannot do that, I am not that bothered that we have both yml and .yaml in other place.

We can try to standardize to .yaml wherever we can if that bothers others however, no problem with that.
