### ISSUE TITLE
https and s3 domain  in s3 links for docs

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#12555]
I think we need to (eventually)  get rid of the s3 links and replace it with our domain (docs.airflow.apache.org)? 

I think it would be great to have https:// there as well. I know it's not something that can be done quickly but we should eventually make it works.

**Comment by potiuk** [comment]
cc: @mik-laj

**Comment by mik-laj** [comment]
We cannot use docs.airflow.apache.org domain as it is against Apache's releasing policy.

> Do not include any links on the project website that might encourage non-developers to download and use nightly builds, snapshots, release candidates, or any other similar package.

http://www.apache.org/legal/release-policy.html

We can think about the use of a domain that clearly defines the purpose, e.g. docs-dev.airflow.apache.org but that will require discussion with INFRA and a more complex AWS setup.  I have both doubts as to whether INFRA will be willing to add a DNS record that points to the AWS server. 

I prefer to do this after Airflow 2.0 is released because it does not affect end users and does not pose a security risk.

**Comment by potiuk** [comment]
Sure. Nothing to hurry. I think something like "latest-docs.airflow.apache.org" should be fine.

**Comment by mik-laj** [comment]
There is at least two projects with the subdomain `docs.*`
http://docs.cloudstack.apache.org/en/latest/#
https://docs.trafficserver.apache.org/en/8.1.x/
and interestingly, it uses RTD.

**Comment by ashb** [comment]
Great, so it was just the redirect idea they didn't like. Hopefully.

**Comment by ashb** [comment]
S3 has an https url: https://apache-airflow-docs.s3-eu-central-1.amazonaws.com/index.html  (The "problem" with it is that it doesn't redirect from https://apache-airflow-docs.s3-eu-central-1.amazonaws.com/)

**Comment by mik-laj** [comment]
Yes. website don't support SSL: https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html#WebsiteRestEndpointDiff

> Amazon S3 does not support HTTPS access to the website. If you want to use HTTPS, you can use Amazon CloudFront to serve a static website hosted on Amazon S3.

https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html

**Comment by ashb** [comment]
Yes, but it's only a problem for people who try to hit `/` -- all links actually work fine

**Comment by ashb** [comment]
I'd like to avoid CloudFront - I've always found it massively slow to update when pushing new changes.
