### ISSUE TITLE
Code Coverage is Broken

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#12748]
https://codecov.io/github/apache/airflow?branch=master CodeCov code-coverage is broken on Master. It wasn't great but still useful to check which sections needed lacks tests.

cc @potiuk

**Comment by potiuk** [comment]
Oh yeah. nobody noticed for 6 months ;) . I think It actually works but in a weird way. I will look at that after we get RC out unless someone does it first.

**Comment by vikramkoka** [comment]
@kaxil @potiuk @ashb 
I was looking at this the other day when Ash shared the code coverage report. Is there an immediate next step here? If so, should we move to a different milestone?

**Comment by eladkal** [comment]
code coverage suppose to show the code lines that are missing test coverage isn’t it?
for example https://codecov.io/gh/apache/airflow/tree/master/airflow/providers/amazon/aws/hooks
I can see that s3.py has 31.68%
but when I click on the file I can’t see what lines don’t have coverage. I get GitHub API: Forbidden

**Comment by potiuk** [comment]
I think as of April after some fixes, the coverage is back on track:

Particularly: https://github.com/apache/airflow/commit/1dfbb8d2031cb8a3e95e4bf91aa478857c5c3a85  helped with that because master merges started to succeed and "master merge" builds are the ones contributing "full coverage" information

Example:
* s3 is 94%: https://codecov.io/gh/apache/airflow/src/master/airflow/providers/amazon/aws/hooks/s3.py
* overall coverage is 89.97%

I looked at the coverage graphs (the sunburst chart is pretty usefule) and there are a few interesting things - maybe we would like to address them:

* Kubernetes executor has surprisingly low 64% https://codecov.io/gh/apache/airflow/src/master/airflow/executors/kubernetes_executor.py  - looks like some of the "flush/end" code is not tested.
* Task command has a few missing parts: https://codecov.io/gh/apache/airflow/src/master/airflow/cli/commands/task_command.py (77%)
* There are quite a number of untested views: https://codecov.io/gh/apache/airflow/src/master/airflow/www/views.py 80%
* Kuberentes refresh_config has untested method https://codecov.io/gh/apache/airflow/src/master/airflow/kubernetes/refresh_config.py 75%

**Comment by potiuk** [comment]
Created some good-first-issues for those: #15523 #15524 #15525 #15526

**Comment by kaxil** [comment]
Awesome, thanks @potiuk
