### ISSUE TITLE
Should a SKIPPED task be counted towards ALL_DONE?

### ISSUE THREAD

**Issue by lamdrew** [apache/airflow#1300]
Should a SKIPPED task be counted towards TriggerRule.ALL_DONE? Currently this seems to be the case.

I would expect that if any upstream dependencies are SKIPPED, all downstream tasks are skipped as well. Otherwise would it be possible to add a TriggerRule that is similar to ALL_DONE except if any upstream tasks are SKIPPED?

Tested with Airflow 1.6.2

**Comment by jlowin** [comment]
cc @withnale

Currently, "Done" means "Finished without error" including skipped. Not arguing for or against, that's just the status quo. I don't use this trigger rule so I think it's best if folks that do weigh in!

**Comment by r39132** [comment]
@lamdrew The intention was yes - "ALL_DONE" means the task has been evaluated. This include success, failure, skipped, etc... Skipped is a form of evaluation because it is skipped based on a condition. It sounds like you need another trigger rule. Please provide an example of your DAG and what you are trying to achieve. There is probably a work-around.

**Comment by withnale** [comment]
In #1292 I've added a number of parameterized tests that effectively document the status quo.

It may be that if this PR is merged and SKIPPED becomes more clearly defined, there may well be cause for a number of additional trigger_rules

**Comment by r39132** [comment]
@lamdrew : I think this could be a useful feature to add. We'd be happy to review a PR for it.
