### ISSUE TITLE
Lazy load Task in TaskGroup

### ISSUE THREAD

**Issue by scauglog** [apache/airflow#13066]
**Description**

Lazy load task in a task group 

**Use case / motivation**

I have a DAG with 4 * 3 000 task that can run in parallel I have grouped them under 4 subdags and it work fine but when I use TaskGroup instead of Subdag the DAG is really slow to display. I would like the UI to only load html element for the "main dag" for graph and tree view.

**Comment by ashb** [comment]
Yeah, that would be a nice improvement!

**Comment by kaxil** [comment]
cc @yuqian90 @ryanahamilton Any interest in doing it :)

**Comment by yuqian90** [comment]
I'd love to. But i'm busy with other things at the moment. Won't be able to get this at least till next month. If someone likes to take it please go for it.

For the time being, @scauglog , did you consider simply adding a few layers of TaskGroup to nest the 300 tasks in each TaskGroup into a more levels? E.g. first level has 4 TaskGroups. Inside each TaskGroup, there are 10 sub-TaskGroups. In each sub-TaskGroup, there are 300 tasks. I guess it might help because the bottleneck is usually when Graph View tries to render all the nodes. As long as it doesn't have to render all 3000 tasks at once, it's usually not too bad. Let me know if that improves the speed.

**Comment by bbovenzi** [comment]
We'll try to tackle this when updating the tree view for #18009

**Comment by jscheffl** [comment]
I believe this is outdated as all components of UI have migrated to AIP-38 / Grid view.
