### ISSUE TITLE
Add an option to pause/unpause a task in a dag through the Web UI

### ISSUE THREAD

**Issue by hsnprsd** [apache/airflow#13150]
**Description**

As of now, there is a on/off switch in the Web UI which can be used to make a dag not get scheduled untill you turn the dag on.
I think the same feature can be implemented to mark a single task as skipped/failed in a dag.
It can be an explicit mark as failed/skipped. It can also not schedule the task for running until it gets unpaused and it can reschedule the task then based on the catch_up parameter of the dag/task.

**Use case / motivation**

I think it is a common use case when there is a bug in some task and you don't want to waste resources on scheduling and running a failing task for a short period of time until you debugged it and the task runs successfully.
Using the current tools you should remove the task from the dags in the dags_folder which is not desired.

**Are you willing to submit a PR?**

I can create a PR for this feature but I just wanted to know If I am missing some features that airflow has that can make these tasks simpler and it would be a waste of time to implement this feature.

**Comment by turbaszek** [comment]
I think this use case sounds similar to what was suggested in #12199. I will close the issue due to #12199, please reopen if you think that your use case is different.   

Also, if you are interested in helping implement this feature you may express your interest in related devlist thread:
https://lists.apache.org/thread.html/r14e23de7b71f61e3e81b11eb84da2612938982c46c9824e884d8ba50%40%3Cdev.airflow.apache.org%3E

**Comment by mik-laj** [comment]
Other similar issue: https://github.com/apache/airflow/issues/9298
