### ISSUE TITLE
XCom isolation between dags running in the same time

### ISSUE THREAD

**Issue by yyyyyyuanfei** [apache/airflow#1334]
Dear Airflow maintainer 

I am trying to use airflow for ad-hoc execution, the use case is: when user clicks a button, there will be a dag run triggered with a set of conf specific to that user action context.

My question is about XCom, when multiple users trigger the dag runs simultaneously, how can I limit the XCom payload to each dag run context respectively?

For example, I have t1->t2, t1 generates a temp file, then sends the path to t2 for further processing via XCom, when two users trigger the job, u1's t1 generated temp file could be used by u2's t2.

Or maybe I am using it not the right way? Any suggestion? 

Thanks!

**Comment by yyyyyyuanfei** [comment]
@r39132 thoughts?

**Comment by jlowin** [comment]
As long as your users don't hit the button at the exact same time, then I think you'll get the behavior you want. XComs are pulled not only based on `dag_id` but also `execution_date`, so if user 1 runs the DAG with a different execution date than User 2 (even if it's just a second), you should be fine.

With that said, the situation you're describing is sort of on the border of what Airflow supports. Running ad-hoc DAGs is relatively new and was designed more to allow "one-off" executions that don't follow the normal schedule rather than many simultaneous executions. So while I think it will work, please note there could be some unexpected side effects. It's a use case we will keep in mind as we reconsider how DAGs should be run.

**Comment by yyyyyyuanfei** [comment]
Thank you for the explanation! I did see that behavior while experimenting around the simultaneous executions, as it fails to create the dag_run due to the `(dag_id, execution_date)` index. 
Without deep consideration, I wonder if purely adding a `dag_run_id` and persistent the related context around that id works or not?

**Comment by r39132** [comment]
@stranbird I need to see some code. Essentially, we do save the full context for each externally-triggered dag run, so you can have a processing DAG triggered from a sensing DAG as mentioned in my blog article or by user defined actions as you outline above. Assuming the execution date resolves to milliseconds or microseconds, the chance of downstream from conflicts should be minimal, assuming you need xcom. Xcom is not used in the triggerdag interaction  - we store the picked json dict in the dag_run record created by the triggerdag operator or CLI command.
