### ISSUE TITLE
Operator will fail if listing reports exceed quotas on Campaign Manager 360 API

### ISSUE THREAD

**Issue by tonycoco** [apache/airflow#13495]
**Apache Airflow version**: latest

**Environment**:

Google Cloud – Composer

**What happened**:

From `airflow.providers.google.marketing_platform.operators.campaign_manager` see: `GoogleCampaignManagerDeleteReportOperator`

https://github.com/apache/airflow/blob/master/airflow/providers/google/marketing_platform/operators/campaign_manager.py#L114

When using a `report_name` to delete the report (not an ID) this list command will cause quota to be exceeded if the report's name is pages down the list and if you have many copies of this operator running concurrently.

**What you expected to happen**:

Delete the report just fine.

**Comment by potiuk** [comment]
This cannot be done on operator level due to the way operators work in Airflow. 

However there is a feature in Airflow that is designed to handle this case - pools. 

You should experiment what is the maximum number of running operators that will not cause exceeding quotas and set the maximum size of the pool to that value. If you then use the pool for all your DAGs wehen This way you will have maxiumum N runing tasks for the service at a time - no matter how many of those are queued. 

You can read more about pools here: http://airflow.apache.org/docs/apache-airflow/1.10.14/concepts.html#pools

**Comment by potiuk** [comment]
And just to add to it. The root cause of the problem is that the API of campaign manager does not have any other way to get the report by name https://developers.google.com/doubleclick-advertisers/v3.3/reports/get only can use Id, and https://developers.google.com/doubleclick-advertisers/v3.3/reports/list does not allow filtering by name. 

The only way to optimize the "by name" search is to ask the campaign manager team to improve their API. So you should rather open an issue to the campaign manager API rather than to the operator, as we are simply using the API that is available.
