### ISSUE TITLE
In DockerOperator the parameter auto_remove doesn't work in 

### ISSUE THREAD

**Issue by doron8cohen** [apache/airflow#13532]
When setting DockerOperator with auto_remove=True in airflow version 2.0.0 the container remain in the container list if it was finished with 'Exited (1)'

**Comment by kaxil** [comment]
Was it working for you in previous Airflow versions?

**Comment by doron8cohen** [comment]
i haven't seen it until now... thanks for the fix!

**Comment by artful88533** [comment]
@kaxil Hello!
I have upgraded Airflow from 1.10.15 to 2.0.2 and faced with a similar problem.
In version 1.10.15 when task is marked by hands as Failed, docker container is automatically removed.
In version 2.0.2 when task is marked by hands as Failed, docker container isn’t automatically removed.
Parameter  auto_remove=True  is present.
From docker inspect:
```
            "ExitCode": 137,
```
Is it possible to automatically remove the container if task is marked by hands as Failed?

**Comment by Nemesis2791** [comment]
`"auto_remove": "force"` doesn't work for me if container is killed with:
`ERROR - Job 10594 was killed before it finished (likely due to running out of memory)`

Full error logs:
`
WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
INFO - Sending Signals.SIGTERM to group 1920538. PIDs of all processes in the group: [1920538]
INFO - Sending the signal Signals.SIGTERM to group 1920538
ERROR - Received SIGTERM. Terminating subprocesses.
INFO - Stopping docker container
WARNING - process psutil.Process(pid=1920538, name='airflow task ru', status='sleeping', started='02:20:33') did not respond to SIGTERM. Trying SIGKILL
INFO - Sending the signal Signals.SIGKILL to group 1920538
INFO - Process psutil.Process(pid=1920538, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='02:20:33') (1920538) terminated with exit code Negsignal.SIGKILL
ERROR - Job 10594 was killed before it finished (likely due to running out of memory)
`

**Comment by Taragolis** [comment]
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#index-SIGKILL
