### ISSUE TITLE
Version Incompatibility in 1.10.14 between apache-airflow-backport-providers-slack & airflow-1.10.14 

### ISSUE THREAD

**Issue by yogyang** [apache/airflow#13558]
**Apache Airflow version**: 1.10.14

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): no k8s

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

when preparing codes for Airflow 2.0 compatibility

```
SolverProblemError

  Because apache-airflow-backport-providers-slack (2020.10.29) depends on slackclient (>=2.0.0,<3.0.0)
   and apache-airflow[aws,celery,crypto,datadog,ldap,mongo,password,postgres,sentry,slack,ssh,statsd] (1.10.14) depends on slackclient (>=1.0.0,<2.0.0), apache-airflow-backport-providers-slack (2020.10.29) is incompatible with apache-airflow[aws,celery,crypto,datadog,ldap,mongo,password,postgres,sentry,slack,ssh,statsd] (1.10.14).
  So, because airflow depends on both apache-airflow[aws,celery,crypto,datadog,ldap,mongo,password,postgres,sentry,slack,ssh,statsd] (=1.10.14) and apache-airflow-backport-providers-slack (=2020.10.29), version solving failed.
```

**What you expected to happen**:

`backport-providers-slack` should have lower slack

**How to reproduce it**:

pip install apache-airflow==1.10.14 
pip install apache-airflow-backport-providers-slack 

**Anything else we need to know**:

**Comment by potiuk** [comment]
This is because you are using poetry. Airlfow should be installed with PIP rather than poetry using the constraint files (as described in http://airflow.apache.org/docs/apache-airflow/stable/installation.html 

There are far too many dependencies in airflow to manage them with multiple tools that have different resolvers. So e have PIP + constraint files. I know people were using Poetry with using the constraint files - follow the discussion here: https://github.com/apache/airflow/issues/13149#issuecomment-748062078

It would be great, if you find consistent method of installation to contribute back PR to our documentation to describe how to use constraints with poetry.
