### ISSUE TITLE
Clearing of historic Task or DagRuns leads to failed DagRun

### ISSUE THREAD

**Issue by oz-r** [apache/airflow#13853]
**Apache Airflow version**: 2.0.0

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Amazon Linux 2
- **Kernel** (e.g. `uname -a`): Linux
- **Install tools**:
- **Others**:

**What happened**:

Clearing a DagRun that has an `execution_date` in the past where the time difference between now and that `execution_date` is greater than the DagRun timeout leads to the DagRun failing on clear, and not running.

**What you expected to happen**:
The DagRun should enter the Running state

I anticipate this is a bug where the existing DagRun duration is not being reset and so the new DagRun is timing out as soon as it starts.

**How to reproduce it**:

Create an DAG with a DagRun timeout. Trigger said DAG. Wait for `DagRun timeout + 1` minutes and then clear said DagRun. New DagRun will immediately fail.

**Anything else we need to know**:
This occurs regardless of whether the DAG/Task succeeded or failed. Also, any DagRun that has timed out can never be cleared.

**Comment by oz-r** [comment]
I imagine #13407 has the same root cause.

**Comment by yogyang** [comment]
Hi, @kaxil would you help identify this, this bug is kind of preventing me from upgrading the Airflow to 2.0 as we do need the ability to rerun the previous dag-runs in case of some error data.

I compared the codes to 1.10.14(which has no this problem):

in 2.0.0 we have skipped the task_instance runs when the dag is found as dag_timout
https://github.com/apache/airflow/blob/c743b95a02ba1ec04013635a56ad042ce98823d2/airflow/jobs/scheduler_job.py#L1290-L1299

while in 1.10.14, 
when the dag is found as dag_timeout, we still run the task_instances.
https://github.com/apache/airflow/blob/c743b95a02ba1ec04013635a56ad042ce98823d2/airflow/jobs/scheduler_job.py#L1290-L1299

seems it has the different cause compared with https://github.com/apache/airflow/issues/13407

**Comment by kaxil** [comment]
Yeah I think the dagrun_timeout was broken (or didn't work as intended) in 1.10.x

**Comment by lsowen** [comment]
I think the issue was is `1.10.x`, dagrun_timeout was essentially "how long as this DAG been executing".  In `2.0.x` it is now "how long has it been since the _scheduled_ start time".  

I think the old behavior makes more sense, as it:
1. Enforces a maximum DAG duration (intended effect)
2. While still allowing a DAG to be re-executed

**Comment by lsowen** [comment]
it looks like https://github.com/apache/airflow/pull/14455 is meant to address this.

**Comment by oz-r** [comment]
> I think the old behavior makes more sense, as it:
> 
> 1. Enforces a maximum DAG duration (intended effect)
> 2. While still allowing a DAG to be re-executed

I agree with this (was about going to make the same point).

**Comment by lsowen** [comment]
Is this or #14265 a candidate for https://github.com/apache/airflow/milestone/21?

**Comment by ericdevries** [comment]
I also agree with the old behavior being more sensible, but can we at least confirm the new implementation is a bug or a feature?

**Comment by darthale** [comment]
This is still happening for me in airflow 2.0.2.

**Comment by ebdavison** [comment]
I am on airflow 2.1.0 and this is definitely an issue on that version.

Can someone comment on the status of this?  I have had to update 400+ DAGs to remove the `dagrun_timeout` config item to have older DAGs re-run.  We had an issue recently and I needed to re-run DAGs from the last 5 days but with a `dagrum_timeout` of 120 seconds, this was failing all DAGs that got cleared.

How am I supposed to limit the length of time a DAG can run _AND_ still be able to re-run older DAGs as needed in airflow 2.+?

**Comment by kaxil** [comment]
Looks like a bug, needs fixing - added to 2.1.1 milestone

**Comment by renanleme** [comment]
We have this problem on our cluster. 
I found a workaround while we don't fix it in a newer version.
The way I found is cleaning the failed tasks from the homepage/dagrun list instead of the dag tree view it self.
Example in pictures:
Let's say that after cleaning this execution it started failing, if you go to the homepage and search for the dag, you will see that a execution failed:
![image](https://user-images.githubusercontent.com/129836/122928087-70a3bf00-d361-11eb-81e1-0de21cc36dd7.png)
So if you click on it (yellow marked in the image) you will open the dag run list, and you will be able to see the failed one:
![image](https://user-images.githubusercontent.com/129836/122928350-aea0e300-d361-11eb-809a-82442d10e9c4.png)

Then, you can select it and clear the stated. It will clear the execution and it will work as expected 🙏🏻 
![image](https://user-images.githubusercontent.com/129836/122928577-ead44380-d361-11eb-87ab-f887045f0a17.png)

Probably the workflow for this action (cleaning) is different from the one that we have on the tree view UI, hope this help you guys to fix it :)

**Comment by uranusjr** [comment]
Could someone verify whether this is still an issue with 2.1.1? Context: https://github.com/apache/airflow/issues/14265#issuecomment-873756374

**Comment by JCoder01** [comment]
Yes, still seems to be an issue.

**Comment by ephraimbuddy** [comment]
I was able to reproduce this in 2.0.0 but not in 2.1.2. @oz-r can you confirm?

**Comment by oz-r** [comment]
Finally got around to updating Airflow and it seems to be working as expected now.

**Comment by potiuk** [comment]
Thanks for confirming it !
