### ISSUE TITLE
KubernetesExecutor Pod not deleted

### ISSUE THREAD

**Issue by armandleopold** [apache/airflow#13917]
**Apache Airflow version**: 2.0.0
**Kubernetes version**: 1.15.5
**Environment**: private.cloud

- **Install tools**: helm chart bitnami

**What happened**:
When running a DAG with KubernetesExecutor and KubernetesPodOperator, at the end of the DAG, the pod launched by the KubernetesExecutor doesn't disapear even with 
```
    - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
      value: "True"
```
**What you expected to happen**:

At the end of the DAG run, the worker pod launched with the kubernetesExecutor disapear.

**How to reproduce it**:
* Install Airflow 2.0 with KubernetesExecutor
* Launch a DAG with podOperator
* check if the pod launched by the KubernetesExecutor disapeared.
* The pod is in a loop :
(from the scheduler) : 
```
[2021-01-26 17:42:10,957] {kubernetes_executor.py:147} INFO - Event: javahelloworldprintarmand10-65794b003e2a40c69dc6fae97d0c95e7 had an event of type MODIFIED
[2021-01-26 17:42:10,957] {kubernetes_executor.py:210} INFO - Event: javahelloworldprintarmand10-65794b003e2a40c69dc6fae97d0c95e7 is Running
[2021-01-26 17:42:13,103] {kubernetes_executor.py:147} INFO - Event: javahelloworldprintarmand10-65794b003e2a40c69dc6fae97d0c95e7 had an event of type MODIFIED
[2021-01-26 17:42:13,103] {kubernetes_executor.py:210} INFO - Event: javahelloworldprintarmand10-65794b003e2a40c69dc6fae97d0c95e7 is Running
[2021-01-26 17:42:26,888] {kubernetes_executor.py:147} INFO - Event: javahelloworldprintarmand10-65794b003e2a40c69dc6fae97d0c95e7 had an event of type MODIFIED
[2021-01-26 17:42:26,888] {kubernetes_executor.py:210} INFO - Event: javahelloworldprintarmand10-65794b003e2a40c69dc6fae97d0c95e7 is Running
```
(from the pod Loop Restarting) : 
```
[2021-01-26 17:42:11,764] {dagbag.py:440} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/git-airflow-dags/example-dags/java-hello-world.py
/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:26 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1Volume`.
/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:27 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1VolumeMount`.
Running <TaskInstance: java-hello-world.printarmand10 2021-01-26T17:36:05.584694+00:00 [success]> on host javahelloworldprintarmand10-65794b003e2a40c69dc6fae97d0c95e7
```

**Anything else we need to know**:

Happens 100% of the time.
The Airflow frontend doesn't show the anomaly.

**Comment by dimberman** [comment]
@armandleopold are you sure the task is completed? Those logs seem to suggest that it's still running.

Can you `kubectl describe pod` on the pod?

**Comment by armandleopold** [comment]
I am sorry, i cannot reproduce the error because i have switched to LocalExecutor.

**Comment by reshmakolluru** [comment]
Is there any update on this issue? I am also currently facing the same issue.
<img width="969" alt="Screenshot 2022-07-06 at 4 43 06 PM" src="https://user-images.githubusercontent.com/16771958/177537729-455eebf6-8813-4ae4-8c3c-2a6e0a78424b.png">

logs are as follows:

<img width="1394" alt="Screenshot 2022-07-06 at 4 44 25 PM" src="https://user-images.githubusercontent.com/16771958/177537934-a4fefd20-fb10-4c76-bf60-16650b80699c.png">

**Comment by potiuk** [comment]
@reshmakolluru . There is no update. Otherwise you would see it here. Everything you see here is public and you can trace it down yourself.

But it could be unrealated, it's impossible to say without you providing more evidences. I suggest you open a new issue, describe your configuration, circumstances, detailed logs, what you observe etc. - without that commenting on a closed issue makes no sense and brings no-one any closer to being able to diagnose it. 

Please invest your time in describing your case if you would like to get some help from peopl here (be mindful this is a free forum and you get best help if you show all evidences and spent your time on reporting details of your problems, so that those who do it for free here can help to solve your problem).  

BTW. If you do not have reproducible case that you can give reproduction steps, open discussion instead of issue (as instructed in the issue template).
