### ISSUE TITLE
Moving data from RDS to S3

### ISSUE THREAD

**Issue by srinugsr2020** [apache/airflow#1405]
Hi,
We have a requirement to move data from RDS to S3. Will airflow be useful to move data from RDS to S3 using Ec2 instances. I read that Airflow is not for Data transfer. Please confirm. Thank you.

**Comment by notifytovishal** [comment]
IMO, Yes but maybe not. Essentially you have a task in hand to move MySql(RDS) data to S3. You can use airflow for such a task using MySql and S3 operators. But, since you are moving data from RDS to S3, you should take a look at AWS pipelines. You could still use airflow to schedule and define the jobs that run the data transfer.

**Comment by jlowin** [comment]
Airflow is for running tasks, but what those tasks do is up to you. One of the most common use cases for Airflow is moving data from one place to another. However, if all you want to do is move data one time, then Airflow is not the right tool. If you want to move data regularly, then Airflow will schedule your tasks and make sure they run.
