### ISSUE TITLE
where is v2.0.0 changelog?

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#14091]
where is v2.0.0 changelog?

https://github.com/apache/airflow/blob/2.0.1rc2/CHANGELOG.txt has v1.10.14 and v2.0.1 but not v2.0.0

https://airflow.apache.org/docs/apache-airflow/stable/changelog.html?highlight=changelog does not have v2.0.0 either

**Comment by potiuk** [comment]
First of all - this is not a BUG. If you want to ask such queastions, it's much better to ask them using the "Discussion" rather than "issue" link (actually when you open a "New Issue" there is even a separate section that leads you there. So my kind request next time please open discussion for that not an issue, that makes live of maintainers much easier. 

I think we will update it shortly. We have not yet figured out how to do it best and after 2.0.1 we will likely do :),

For now you can find change log from 2.0 here: https://github.com/apache/airflow/releases/tag/2.0.0

**Comment by tooptoop4** [comment]
for the benefit of admins the helpful answer is:

https://lists.apache.org/thread.html/r44d48e9e660c0f6177c95e7cb6686df3e3990621c2d372c74554d08b%40%3Cdev.airflow.apache.org%3E
https://lists.apache.org/thread.html/r7f37fbda77f317ab9a7445ea5759272437da6567dc40c1eb42a60c41%40%3Cdev.airflow.apache.org%3E
https://lists.apache.org/thread.html/r75ede252be66d4f93e52e56d4e3e76b97ac30cf7125f364be91f534e%40%3Cdev.airflow.apache.org%3E
