### ISSUE TITLE
Clarify that Docker is not required for contributing

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [apache/airflow#14230]
To setup airflow, Docker must be installed. But, Airflow is at the base a Flask app and as such does not require docker.

Requiring Docker is a legacy carried on from FlaskAppBuilder. 

Summary: To engage more contributors to contribute to a Python project, Docker might be removed

**Comment by potiuk** [comment]
I do not think there is ever a requirement to setup Docker.  I am not sure where you take the notion for it. It is a useful tool for CONTRIBUTORS to have Docker-based environment (thanks to that this environment is consistent between developers) but even there, there is local virtualenv option that does not require Docker. For users, the installation instructions are describing local installation without docker. 

I will close that as invalid for now, but maybe my perception is wrong. If you would like to re-open it, can you please describe how you reached the conclusion that docker is required ? And if there are places in the documentation that suggest it, can you please point to those?

**Comment by Abdur-rahmaanJ** [comment]
@potiuk I thought you knew the CONTRIBUTING.rst. I am from the [Python Usergroup of Mauritius](https://www.pymug.com). Since Mr Lamberti is in our country, we thought it would be an excellent opportunity to get people involved in a 'real' Open Source project. That's why i was trying out the instructions.

In [CONTRIBUTING.rst](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#step-2-configure-your-environment), [step 2](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#step-2-configure-your-environment) it says: 

> Configure the Docker-based Breeze development environment and run tests. 

Read upto 6.

```
Step 2: Configure Your Environment
Configure the Docker-based Breeze development environment and run tests.

You can use the default Breeze configuration as follows:

Install the latest versions of the Docker Community Edition and Docker Compose and add them to the PATH.

Enter Breeze: ./breeze

Breeze starts with downloading the Airflow CI image from the Docker Hub and installing all required dependencies.

Enter the Docker environment and mount your local sources to make them immediately visible in the environment.

Create a local virtualenv, for example:

mkvirtualenv myenv --python=python3.6
Initialize the created environment:
./breeze initialize-local-virtualenv --python 3.6
Open your IDE (for example, PyCharm) and select the virtualenv you created as the project's default virtualenv in your IDE.
```

**Comment by potiuk** [comment]
It's not obligatory.

If you find it confusing @Abdur-rahmaanJ  - can you please open PR to indicate that it is optional ( only if you want to run more sophisticated tests and run pre-commits with mypy/pylint/flake8).  This is best thing to help - to contribute to the documentation with the user/contributor perspective.

If you look further down the line you will see this part https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#development-environments which explain the differences between those two environments (Local and Breeze) and explains where you need to use one and when the other. 

BTW. It has nothing to do with Flask App Builder. It is there to maintain consistent and common development environment so that you can replicate CI failures locally and work on solving them locally rather by pushing stuff to CI.

**Comment by ashb** [comment]
@Abdur-rahmaanJ As Jarek says, a PR to make this clearer would be welcomed.

**Comment by Abdur-rahmaanJ** [comment]
Ok, let me address this

**Comment by Abdur-rahmaanJ** [comment]
Companion PR: [14246](https://github.com/apache/airflow/pull/14246)
