### ISSUE TITLE
UI: Start Date is incorrect in "DAG Details" view

### ISSUE THREAD

**Issue by koshy1123** [apache/airflow#14299]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

The start date in the "DAG Details" view `{AIRFLOW_URL}/dag_details?dag_id={dag_id}` is incorrect if there's a schedule for the DAG.

**What you expected to happen**:

Start date should be the same as the specified date in the DAG.

**How to reproduce it**:
For example, I created a DAG with a start date of `2019-07-09` but the DAG details view shows:
![image](https://user-images.githubusercontent.com/12819087/108415107-ee07c900-71e1-11eb-8661-79bd0288291c.png)

Minimal code block to reproduce:
```
from datetime import datetime, timedelta
START_DATE = datetime(2019, 7, 9)
DAG_ID = '*redacted*'
dag = DAG(
    dag_id=DAG_ID,
    description='*redacted*',
    catchup=False,
    start_date=START_DATE,
    schedule_interval=timedelta(weeks=1),
    )
start = DummyOperator(task_id='start', dag=dag)
```

**Comment by kurtqq** [comment]
Possibly there is a mix.
There are two kinds of start date in the UI.
1. the one that you shared which should be the start_date propery as defined in the DAG.
2. the one that showed when hovering the (i) icon int the DAG page which shows when the dag actualy ran.

Since in your image it shows full timestamp I assume that it takes the same value of start_date like the one in point (2).

**Comment by ashb** [comment]
Yeah, this is confusing terminology, rather than the wrong date being displayed.

Closing this as "wont fix" for now as we are working on a new UI

**Comment by ashb** [comment]
Just looked at the screenshot more closely and it's showing the wrong value, yes!

It's showing the start date for a dag run or task, but given the title says "DAG Details" it _should_ show the start_date of the dag.

**Comment by uranusjr** [comment]
This happens when `catchup=False`. The calculation mutates the DAG instance here:

https://github.com/apache/airflow/blob/6690758c696562e0fd4f1858d937d43efd1fbb47/airflow/models/dag.py#L580-L584

because when there’s no catchup, we don’t want to schedule the DAG for periods before the current time. So the displayed time is *logically* correct to the scheduler—the DAG won’t actually start being scheduled until the logical start date, even if the user set the value to an earlier time—but probably not what the user expects (as this issue shows).

So the current start date isn’t wrong (in a sense); confusing terminology is a good description. Simply changing the start date to show the value specified by the user is also misleading IMO because the DAG detail page won’t be able to reflect `catchup=False`, and the user will be confused why the DAG is not being scheduled after the start date.

**Comment by ashb** [comment]
Nice analysis @uranusjr -- we probably need to tweak the display in the case of catchup=False then.

**Comment by uranusjr** [comment]
So what can we do here? One way is to explicitly store the user-defined start date (e.g. `DAG.declated_start_date`) and rename the field as **Declared start date** so it’s clearer that might not be the time the DAG *actually* started. Another is to hide the field when `catchup=False` altogether, and maybe display something else to indicate whether the DAG has started or not.

**Comment by bbovenzi** [comment]
@uranusjr What would the "something else" be to indicate if a dag has started? Right now we show a count of task instances, would that be sufficient?

<img width="453" alt="Screen Shot 2021-05-28 at 12 20 53 PM" src="https://user-images.githubusercontent.com/4600967/120020318-28d28780-bfaf-11eb-9403-1905a468f97a.png">

**Comment by uranusjr** [comment]
Yeah, that (combine with showing the DAG has `catchup=False`) is probably sufficient IMO.
