### ISSUE TITLE
Missing schedule_delay metric

### ISSUE THREAD

**Issue by arbass22** [apache/airflow#14364]
**Apache Airflow version**: 2.0.0 but applicable to master

**Environment**: Running on ECS but not relevant to question

**What happened**: I am not seeing the metric dagrun.schedule_delay.<dag_id> being reported.  A search in the codebase seems to reveal that it no longer exists.   It was originally added in https://github.com/apache/airflow/pull/5050.

I suspect either:
1.  This metric was intentionally removed, in which case the docs should be updated to remove it.
2. It was unintentionally removed during a refactor, in which case we should add it back.
3. I am bad at searching through code, and someone could hopefully point me to where it is reported from now. 

**How to reproduce it**:
https://github.com/apache/airflow/search?q=schedule_delay

**Comment by jhtimmins** [comment]
@arbass22 Thanks for bringing this up! Looks like you're right, the functionality was removed when support for multiple schedulers (AIP-15) was introduced https://github.com/apache/airflow/commit/73b9163a8f55ce3d5bf6aec0a558952c27dd1b55#diff-bde85feb359b12bdd358aed4106ef4fccbd8fa9915e16b9abb7502912a1c1ab3L799.

@kaxil @ashb Do either of you know if this was intentional, or if it was removed accidentally during the merge?

**Comment by ashb** [comment]
Whops, no, not intentionally removed.

**Comment by ianlofs** [comment]
Found this because I was doing a deep five through this recently because I am currently trying to figure out the best way to monitor for DAGs that never start. This is where this is getting emitted in the 1.10.X series, https://github.com/apache/airflow/blob/v1-10-stable/airflow/jobs/scheduler_job.py#L1296. If this is getting added back It would be really useful if the metric was emitted all the time instead of only when a new DagRun is getting created. This would result in more metrics getting sent but would allow for monitoring on if a DAG was missed all together (for instance due to `catchup = False` being set on a Dag and that Dag running longer than the schedule period. Would definitely be willing to add a PR to add in this functionality.

**Comment by ashb** [comment]
When you say "emitted all the time" what are you thinking? Could you provide a bit more detail to what you mean?

**Comment by ianlofs** [comment]
@ashb Ah yeah for sure!

So ideally everyone who created a DAG would know to setup `catchup=True` for DAGs where this is necessary. However this is not always the case in practice when you have many teams utilizing Airflow that you are trying to support. It would be nice to be able to use latency metrics to know when a DAG that should be starting isn't starting (this could be because a previous DAG run is still executing). However it also could be some other, unreported failure or error. If there was a steady stream of latency metrics for DAGs the absence of those metrics could be used to alert on. So instead of only emitting a latency metric every time a a new DagRun is created emitting a latency metric for each DAG every time the scheduler parses the DAGs. I guess in the case of a new DagRun not being created this would be the most recent latency.

**Comment by ianlofs** [comment]
Hello! Any updates on this? @ashb. This is definitely preventing us from upgrading to Airflow 2 as these latency metrics are really important to how we monitor Airflow.
