### ISSUE TITLE
change the status code which healthcheck API returns

### ISSUE THREAD

**Issue by ShintaroOba** [apache/airflow#14385]
**Description**
Healthcheck endpoint returns 503 (Service Unavailable) when server is unhealthy.

**Use case / motivation**
Current healthcheck api returns status code "200 (OK)"even if server is "unhealthy".
It couldn't be working healthcheck correctly when some cloud services (like aws) which can periodically sends healthcheck requests to airflow.
Because they are judging success or failure only seeing status code of api response. They don't see response body json at all.

**Are you willing to submit a PR?**
Yup. But I'm not ready ready PR for this issue.

**Related Issues**

**Comment by jhtimmins** [comment]
Confirmed that this is the behavior, as any failure is caught and then a standard response is returned.
https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/health_endpoint.py#L37

@ephraimbuddy @mik-laj do y'all think this should be updated?

**Comment by ephraimbuddy** [comment]
> Confirmed that this is the behavior, as any failure is caught and then a standard response is returned.
> https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/health_endpoint.py#L37
> 
> @ephraimbuddy @mik-laj do y'all think this should be updated?

Yep @jhtimmins, it's a good call. Needs to be updated

**Comment by mik-laj** [comment]
this health check is part of the webserver and if the webserver returns an incorrect value, the error code will be different than 200. 

For other components it doesn't work and we probably shouldn't fix it because it won't allow chrvk component in isolatiin, i.e. if the webserver won't work then all other components will also report that they are in unhealthy state, which won't be correct, when scheduler is still live.   I think, we should use other health check.

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/11161
