### ISSUE TITLE
Refer Best Practices of using Variables in the Concepts/Variables section

### ISSUE THREAD

**Issue by ldealmei** [apache/airflow#14392]
**Description**
The `Variable` feature caused us some issue because of the performance impact it can have if badly used. See [here](https://issues.apache.org/jira/browse/AIRFLOW-29).
To a rather new user, it is not obvious that how the DAG is written can have a considerable impact in executing it.
In our case we were generating 100s of tasks each using `Variable.get` in its configuration, making loading the Dag extermely slow (and timeout).

**Use case / motivation**

Our suggestion would be that emphasis is put in the docs in the Concept/Variables section of this coupling between how Variable is used and performance/stability.

**Are you willing to submit a PR?**

I'll try to suggest something.

**Related Issues**

https://issues.apache.org/jira/browse/AIRFLOW-29

https://github.com/apache/airflow/issues/1380

**Comment by vikramkoka** [comment]
Please suggest something or even articulate the questions you would like answered in the documentation.

**Comment by ldealmei** [comment]
I am not sure what was unclear in my message. I believe I did suggest something and even articulated why it was relevant for me.
Would you like me to redact exactly what to change in the docs?

As I wrote, my suggestion is:

> Our suggestion would be that emphasis is put in the docs in the Concept/Variables section of this coupling between how Variable is used and performance/stability.

or as the title indicates, to simply:

> Refer Best Practices of using Variables in the Concepts/Variables section

**Comment by collinmcnulty** [comment]
I can take a shot at improving this. I agree with @ldealmei that if you follow the example on the [Variables page](https://airflow.apache.org/docs/apache-airflow/stable/concepts/variables.html), it walks you straight into an antipattern that will slow the dag parsing down significantly.

**Comment by eladkal** [comment]
> I can take a shot at improving this. I agree with @ldealmei that if you follow the example on the [Variables page](https://airflow.apache.org/docs/apache-airflow/stable/concepts/variables.html), it walks you straight into an antipattern that will slow the dag parsing down significantly.

The variable doc does mention:

"We also recommend that you try to keep most of your settings and configuration in your DAG files, so it can be versioned using source control; Variables are really only for values that are truly runtime-dependent."


Also we explain in:
https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code

"Specifically you should not run any database access, heavy computations and networking operations."


I think the current doc is good enough. if someone think otherwise please explain (or better yet open a PR with your suggestion)
