### ISSUE TITLE
Clear the entire TaskGroup section

### ISSUE THREAD

**Issue by zacharya19** [apache/airflow#14529]
**Description**

Allow to clear the whole tasks inside a TaskGroup, instead of doing it one by one.

**Use case / motivation**

One of the things I love about SubDags is the option to clear the entire sub flow in case I want to rerun it.
In some cases I've a single parent and it's easy, but in some flows there are multiple parents (and now thanks to TaskGroup there could be even more easily), so the easy way to clear it is to go to the task instances page and start filtering, which is sub-optimal.

**Are you willing to submit a PR?**

Sure.

**Comment by eladkal** [comment]
@zacharya19 assigned to you

**Comment by ConstantinoSchillebeeckx** [comment]
hey @zacharya19 have you made any progress on this? I'd be willing to help too.

**Comment by zacharya19** [comment]
> hey @zacharya19 have you made any progress on this? I'd be willing to help too.

Sadly, no, I've been way too busy lately.
Feel free to take it off my hands, I would love to see this feature!

**Comment by ManiBharataraju** [comment]
@eladkal - This one is interesting. However, I am trying to visualize what happens when u click on the taskgroup. Given that TaskGroups are more of a UI feature and do not have an instance of their own, will the UI look similar to other operators(will involve changes including other items i guess) or maybe something like clicking on the DagRun bubble in tree view where u have only three options to mark success/failed or clear(drawback no downstream option)?

**Comment by edjeffery** [comment]
+1 would really love to see this feature!

**Comment by oleg-savko** [comment]
+1 waiting for this feature!

**Comment by potiuk** [comment]
I think - similarly to "Task Group Retry" and canceling "composite sensors" discussions - this one will not happen until somoene writes and discusses AIP about Task Group "write" behaviour. this is going to be a complex and difficul task.

**Comment by potiuk** [comment]
See discussion https://lists.apache.org/thread/1y7y5t6xj7fj8yj8vsqj9jxpw3vbyyg3

**Comment by asitstands** [comment]
@potiuk We manually clear each task in a task group using the graph view. Such a manual manipulation is totally legitimated as far as I know. The suggested feature could be considered as simply automating this manual manipulation. I think that this automation cannot introduce any more complexity or side effect than the manual manipulation. I hope adding this feature to be considered positively.

**Comment by potiuk** [comment]
I think you can definitely make a PR for it if you fill like it. There is a certain complexity of automating it which makes it complex - if you want to run it in single transaction (i.e. fast) you will start hitting the potential deadlock scenarios i mentioned. If you want to make it to 'simulate' users doing it one by one in each transaction separately, the  you will have another problem - with even 10s of tasks such operation will tke potentially minutes - at which point you have to consider which entity is controlling the lopping and 'clicking'. Whe you are doing it manually - you are that entity and then you can manually react the situation where one of those actions fails, timeouts or is already outdated because state of the task changed. When you want to do it in 'fire and forget' mode you need to first of all handle all those cases and secondly - give a user feedback and chance to react and take different actions. All this has to be implemented. 

And there is a question where should it be controlled from - is it from the browser client (JavaScript) or some server job which is running a long running job looping over the tasks. Both have pros and cons.


You are basically speaking about replacing a human cdoing multiple actions one by one and reacting differently to it with someltllthing that runs in the background and does the same and reacts to different errors.

So i am not at all talking it's not possible. It certainly is. It's just much more complex than you think on the surface and someone has to simply ... Implement it taking into account all the complexity.

If you think it is 'simple' then it probably means you can easily submit a PR for that. I am happy to revisew it actually and discuss all the scenarios during review that i explained above 

J.

**Comment by asitstands** [comment]
@potiuk Thank you for detailed explanation. However, I still have a question. With CLI, we can clear all tasks in a task group. For example, assuming `prefix_group_id=True`, like this.
```bash
airflow tasks clear -t 'taskgroup_foo\..+' my_dag -s ...
```
What prevent adding UI to execute, say, this command?

**Comment by potiuk** [comment]
There are two major differences:

* environment where the command runs
* mechanism of feedback to the user when there are problems.

In this case again you have human running the command and terminal where the operation is run (and human overlooking and reacting it) rather than webserver UI. 

Webserver - almost by definition handles short "requests". While in terminal you can run long tasks because  - well - you have an open terminall - that serves as the environment where the job runs. Then you have also a feedback mechanism - you can print logs and errors to the user and let the user read the logs and manually decide how to react on those problems. You can see that this and that manual task failed and run manual commands that will fix the problem. It's a super-low level interface that requires constant attention and possibly follow-up manual remedy of any problems that will arise.

In Webserver UI this is a completely different story. You expect to send a request ("clear") and then something should do  it - you will not stare at the terminal and logs, you will likely close the browser or move to another screen when you request such operation to happen if it takes more than a second or two. this is how web UI works.

And in order to do that you need ot implement much more:
*process that actually runs the long term operation (most web solutions and HTTP connection will have a time limit on running a single request and runnign a request that waits for some time is not good
* this process is likely not going to run in your browser (unlike the terminal command) because of the nature of browser UI
* when it fails you really need to notify they user somehow (because the user will likely be already somewhere else or maybe evne close the browser in the meantime
* when there are errors you need to know what kind of errors there will be and give the user an opportunity to fix them or acknowledge that the problem does not need fixing - sending logs is useless because that would mean that the user will have to manually react on any log -entry - which means finding the right task and performing an action. So you need to implement the whole mechanism of communicating with the user and allowing the user to react to problems that might happen. If you have one or two tasks, this seems easy, but when you have 100s or 1000s tasks then such "request" can take many minutes to complete and produce 100s or thousants of errorrs to deal with, so you have to prepare a solution that will let the user effectively deal with those if you want to make into a "proper UI" feature.
 
From In the command line it's perfectly fine to tell the users - "those are logs of your command - deal with it" . In the UI, you need to implement proper UI for that. 

This is precisely why we have no "backfill" implemented in the UI - only as a command line.

And @asitstands - if you think that things are easy - there is nothing to prevent you from implementing it. Feel free. It's very easy to tell that something is "easy" and ask otehrs to do that, and very different thiing to implement it itself. Airflow has more than 2000 contributors and anyone can contribute anything - providing that it will pass the review.

In this case - until all the problems and paths of processing are not solved the change will not be accepted. But if you implement, test and prove that all of this is fine and that our users will get a great tool to manage multiple (sometimes 100s sometimes 1000s entities). I am super happy to accept such change.

**Comment by asitstands** [comment]
@potiuk I hope you don't feel uncomfotable on my follow-up questions. Web UI has a feature to clear a task and its all downstream tasks. What happens if there are 100s or 1000s of downstream tasks? Is clearing all downstream tasks particularly easier in some reason? To me, as a user not familiar to the implementation details, the suggested feature looks natural, similar to some existing features, and useful. So, I am asking. Unfortunately, I have no time to get familiar with the implementation of airflow and make changes. I just thank all the contributors and maintainers for this great software. However, I think I can still ask and discuss features, as a user.

**Comment by romj4k3** [comment]
Hey guys, what's going on with that task? I need this solution. Please, do it :)

**Comment by potiuk** [comment]
> Hey guys, what's going on with that task? I need this solution. Please, do it :) It's not complex I know it! Just do it!

If you know it's easy @romj4k3 - feel free to provide PR. As simple as that. You can become one of the more than 2000 contributors. It's super easy way to repay the debt you have for using free software.

**Comment by pierrejeambrun** [comment]
I would be glad to take a look at this one :)

**Comment by Gunnnn** [comment]
+1!!!!!!

**Comment by pierrejeambrun** [comment]
Completed in https://github.com/apache/airflow/pull/26658, closing :)

**Comment by pierrejeambrun** [comment]
@uranusjr you were faster than me 😂, thanks
