### ISSUE TITLE
Drop support for LocalExecutor/SequentialExecutor in Helm Chart?

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#14649]
Hello,

I wonder if we should support SeqentialExecutor and LocalExecutor in the Helm Chart. Especially using `SequentialExecutor` in Kubernetes doesn't sound like a good idea, and it makes sense to me to drop support for it and focus only on `CeleryExecutor`, `CeleryKubernetesExecutor` and KubernetesExecutor.

This will allow us to reduce the complexity, because we can delete some conditions in the code.
https://github.com/apache/airflow/blob/e1ff59ea381f505c0cd2f1fd59f505cc315746f2/chart/templates/scheduler/scheduler-networkpolicy.yaml#L43
Additionally, we will then be able to inform the user that he is going the wrong way before going too far.
https://github.com/apache/airflow/blob/master/chart/templates/check-values.yaml

Best regards,
Kamil Breguła

CC: @potiiuk @dimberman @ashb

**Comment by XD-DENG** [comment]
My 2 cents: if we can, I suggest to keep `LocalExecutor`, because it's much more simplified architecture compared with `Celery`. It's possible that people would want such a small setting-up even if on K8S cluster, for demo/testing purposes, or purely needing a small Airflow instance.

Of course I understand keeping `LocalExecutor` AND removing `SequentialExecutor` may not make sense from the complexity reducing perspective. Happy to discuss further.

**Comment by mik-laj** [comment]
@XD-DENG Deleting Sequential Executor support will still facilitate the development of the project because we will not have to test if Airflow together with SequentiialExecutor works.

**Comment by kaxil** [comment]
+1 to keep LocalExecutor
