### ISSUE TITLE
Using TaskGroup without context manager (Graph view visual bug)

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#14864]
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**What happened**:
When I do not use the context manager for the task group and instead call the add function to add the tasks, those tasks show up on the Graph view.
![Screen Shot 2021-03-17 at 2 06 17 PM](https://user-images.githubusercontent.com/5952735/111544849-5939b200-8732-11eb-80dc-89c013aeb083.png) 

However, when I click on the task group item on the Graph UI, it will fix the issue. When I close the task group item, the tasks will not be displayed as expected.
![Screen Shot 2021-03-17 at 2 06 21 PM](https://user-images.githubusercontent.com/5952735/111544848-58a11b80-8732-11eb-928b-3c76207a0107.png)

**What you expected to happen**:
I expected the tasks inside the task group to not display on the Graph view.
![Screen Shot 2021-03-17 at 3 17 34 PM](https://user-images.githubusercontent.com/5952735/111545824-eaf5ef00-8733-11eb-99c2-75b051bfefe1.png)

**How to reproduce it**:
Render this DAG in Airflow

```python
from airflow.models import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.dummy import DummyOperator
from airflow.utils.task_group import TaskGroup
from datetime import datetime
with DAG(dag_id="example_task_group", start_date=datetime(2021, 1, 1), tags=["example"], catchup=False) as dag:
    start = BashOperator(task_id="start", bash_command='echo 1; sleep 10; echo 2;')
    tg = TaskGroup("section_1", tooltip="Tasks for section_1")
    task_1 = DummyOperator(task_id="task_1")
    task_2 = BashOperator(task_id="task_2", bash_command='echo 1')
    task_3 = DummyOperator(task_id="task_3")
    tg.add(task_1)
    tg.add(task_2)
    tg.add(task_3)
```

**Comment by ryanahamilton** [comment]
I was able to reproduce this with the supplied sample DAG.

@yuqian90 any ideas on this? You probably know this graph view task group logic fairly well after your work on #14661.

**Comment by yuqian90** [comment]
Hi @ryanahamilton and @wolfier , I can explain why this is happening, but I'll need some suggestions from you and others on how to improve this.
There are two ways of putting a task into a `TaskGroup`:
1. Create the task inside the contextmanager of the `TaskGroup`;
2. Pass the `task_group` as an argument to the constructor of the task.

The reproducing example is doing neither of these. Instead it's calling `TaskGroup.add` **after** the task has already been created. At the time of creating the task, there was no `TaskGroup` contextmanager nor was the `task_group` specified. So the tasks were already added to the root `task_group` of the dag, resulting in this inconsistent behaviour.

To fix this, you just need to use a contextmanager. Or do this:
```python
from airflow.models import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.dummy import DummyOperator
from airflow.utils.task_group import TaskGroup
from datetime import datetime
with DAG(dag_id="example_task_group", start_date=datetime(2021, 1, 1), tags=["example"], catchup=False) as dag:
    start = BashOperator(task_id="start", bash_command='echo 1; sleep 10; echo 2;')
    tg = TaskGroup("section_1", tooltip="Tasks for section_1")
    task_1 = DummyOperator(task_id="task_1", task_group=tg)
    task_2 = BashOperator(task_id="task_2", bash_command='echo 1', task_group=tg)
    task_3 = DummyOperator(task_id="task_3", task_group=tg)
```

Some ideas for improvement, not sure what's best:
1. Add a check somewhere to make sure a task is not added to more than one `TaskGroup`. Where should such a check be?
2. Make `TaskGroup.add` a private method. The reason it currently looks like a public method is that it's called in places such as the constructor of `BaseOperator`. But strictly speaking, users of Airflow should not be encouraged to call `TaskGroup.add` directly because it doesn't do what the name says.

**Comment by eladkal** [comment]
> Add a check somewhere to make sure a task is not added to more than one TaskGroup. Where should such a check be?
We should definitely prevent adding task to more than 1 task group.
