### ISSUE TITLE
Can not change webserver.defaultUser.password when install by helm

### ISSUE THREAD

**Issue by patsevanton** [apache/airflow#14872]
**Apache Airflow version**:
latest helm chart from master branch

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.18

**What happened**:
```
git clone https://github.com/apache/airflow.git
helm dependency update
helm install --set webserver.defaultUser.password=new_password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.xip.io airflow ./
```
**Login as admin:admin**

**What you expected to happen**:
i think login as admin:new_password

Can not change webserver.defaultUser.password when install by helm

**Comment by kaxil** [comment]
cc @Dr-Denzy

**Comment by Dr-Denzy** [comment]
I will take a look.

**Comment by Dr-Denzy** [comment]
> **Apache Airflow version**:
> latest helm chart from master branch
> 
> **Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
> 1.18
> 
> **What happened**:
> 
> ```
> git clone https://github.com/apache/airflow.git
> helm dependency update
> helm install --set webserver.defaultUser.password=new_password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.xip.io airflow ./
> ```
> 
> **Login as admin:admin**
> 
> **What you expected to happen**:
> i think login as admin:new_password
> 
> Can not change webserver.defaultUser.password when install by helm

@patsevanton I could not exactly reproduce this issue.
After installing with helm, `helm get values airflow` produced this output:
`USER-SUPPLIED VALUES:
ingress:
  enabled: true
  hosts:
  - airflow.192.168.22.7.xip.io
webserver:
  defaultUser:
    password: new_password`
And I when port-forwarded to my localhost I was able to log into the Airflow UI with username: `admin` password: `new_password`

**Comment by patsevanton** [comment]
Thanks! I check and login into airflow with  username: admin password: new_password

**Comment by rgolab** [comment]
After first install it's true it works. But when you update helm with new value - the new value is visible in the `helm get values airflow` but you are not able to login by using new password.

Steps to reproduce:
1) `helm install --set webserver.defaultUser.password=password airflow ./`
2) `helm upgrade --install --set webserver.defaultUser.password=new_password airflow ./`
3) you are able to login by using `password` and `new_password` is not used

**Comment by Bash-** [comment]
I also still have this same issue. It ignores the new value of the `webserver.defaultUser.password` when performing an `helm upgrade`. 
`helm get values airflow` returns the new password I set, but I can still only login with the default admin/admin in the Airflow UI.

**Comment by potiuk** [comment]
> I also still have this same issue. It ignores the new value of the `webserver.defaultUser.password` when performing an `helm upgrade`. `helm get values airflow` returns the new password I set, but I can still only login with the default admin/admin in the Airflow UI.

This is simply wrong expectation that you have. 

Default is default password when you first time create Airlfow application. Once you create Airflow DB, default is not used any more (it is well, you know, default). 

That's precisely intended behaviour. Don't expect DB synchronization features from Helm. Once you install airflow for the first time, the user is already created (and you likely have changed the password already - this is a very good practice to change the password after installation, because someone - for exmple - could see it in the logs.  So overriding this admin user's password with the default password makes completely no sense.

**Comment by Bash-** [comment]
@potiuk Clear, I understand what you mean.
And you are right, we now understand that the user is created in the backend database, we did not clear it when uninstalling the Helm deployment, installing the Helm Chart again used the old database records.

We did this because we are looking for a way to programmatically create a user. Some context about how we hoped to do it:
1. We use [Secret Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/introduction.html) to load Azure Key Vault secrets as Kubernetes Secrets into our AKS cluster. We can use those k8s secrets in our `values.yml` for fields like `resultBackendSecretName` or `fernetKeySecretName`.
2. We hoped to store user credentials like this as well, and have an option in the `values.yml` to create users based on values that are stored in a Kubernetes secret. That is why we tried some different things, like misusing the defaultuser value.

Since this is not the way to go, could you advise us how we should create users within Airflow on Kubernetes?

Should we maybe just do it manually via the UI or via the CLI with `airflow users create`? Or do you think we could still do that programmatically within our Airflow image?

**Comment by potiuk** [comment]
This shoudl be done outside of Helm or Image. Neither helm nor image lifecycle is good for that. 

Usually when you deploy Airflow you somehow needs to make sure the database is populated with the right configuration etc. Usually - if you need to re-create Airlfow deployment several time you employ some kind of "infrastructure as a service" approach - typically Terraform but there are ather possibilities.

Preparing the initial database is the job of those tools. And since Airlfow is totally agnostic on how users are creating their "whole" deployments, you should simply make it in the way it is usually done in your organisation. We do not want to limit you in any way or suggest anything, because the space of possible solution is vast, and each organisation has their own standards on how this is done.

**Comment by potiuk** [comment]
And in some cases you might revert to manual or scriptable way. Airflow has CLI, API, UI, you can also import/export the DB entries if you feel it's good. As I said - all interfaces are there, you just must plug them in in the way how your organisation typically manages those (or create such standard yourself if you do not have them).

**Comment by Bash-** [comment]
We indeed use Terraform to provision the infrastructure we need for Airflow, including the database.
But alright, we will think about how we can create users easily and safely with our setup, as a step after Airflow is deployed. Thank you for your explanation!

**Comment by kaxil** [comment]
@Bash- I would recommend you use APIs for that functionality -- or just CLI with null-resource to run bash commands
