### ISSUE TITLE
A Small Exception Message Typo

### ISSUE THREAD

**Issue by berksudan** [apache/airflow#14933]
I guess, line 59 in file "[airflow/airflow/task/task_runner/__init__.py](https://github.com/apache/airflow/blob/5a864f0e456348e0a871cf4678e1ffeec541c52d/airflow/task/task_runner/__init__.py#L59)" should change like:

**OLD**: f'The task runner could not be loaded. Please check "executor" key in "core" section.'
**NEW**: f'The task runner could not be loaded. Please check "task_runner" key in "core" section.'

So, "executor" should be replaced with "task_runner".

**Comment by kaxil** [comment]
Thanks @berksudan , would you like to create your first PR with that fix ?

**Comment by qfaizan401** [comment]
Thanks, @berksudan to open this issue. This is the first issue that I am handling. Yes, I think you are right that Line 59 in file "airflow/airflow/task/task_runner/init.py" should change from:
OLD: f'The task runner could not be loaded. Please check "executor" key in "core" section.'
to:
NEW: f'The task runner could not be loaded. Please check "task_runner" key in "core" section.'

Because your function "get_task_runner" states about the task runner, not the executor.
