### ISSUE TITLE
dill version conflict fails CI

### ISSUE THREAD

**Issue by uranusjr** [apache/airflow#14994]
Currently all PRs have their CI failing during the *Check if CI image build is needed* stage because `pip check` fails with

```
apache-beam 2.28.0 has requirement dill<0.3.2,>=0.3.1.1, but you have dill 0.3.3.
```

The source of the conflict is simple; Airflow itself declares `dill>=0.2.2, <0.4`, but `apache-beam[gcp]` (pulled in by extra) declares `>=0.3.1.1,<0.3.2`. The CI is currently using pip’s legacy resolver, which naively chooses in dill 0.3.3 when it seems the initial requirement in `apache-airflow` to cause the conflict.

The thing I’ve *not* figured out, however, is why the CI worked previously. Neither `apache-airflow` and `apache-beam` have changed this particular dependency declaration for quite a long time, and a similar conflict should have occured long ago.

As for a fix, the simplest solution would be to pin `apache-airflow`’s `dill` dependency to `<0.3.2`. Or switch to pip’s new resolver, which can correctly install `apache-airflow[all]` as of pip 21.0.1 from my test run.

**Comment by potiuk** [comment]
We are using constraints to limit the version of dill that is installed, however we know apache beam has a number of problems with dependencies. The reason we are not failing in CI is simple. 

https://github.com/apache/airflow/blob/fe2a70c713f8d12199579bfca26eb916035ab206/setup.py#L750

```
# Those packages are excluded because they break tests and they are not needed to run our test suite.
# This can be removed as soon as we get non-conflicting
# requirements for the apache-beam as well.
#
# Currently Apache Beam has very narrow and old dependencies for 'dill' and 'mock' packages which
# are required by our tests (but only for tests).
#
PACKAGES_EXCLUDED_FOR_CI = [
    'apache-beam',
]
```

The `dill` failing the build was a different reason entirely. This has been fixed in https://github.com/apache/airflow/pull/14998. The problem was that a different bug caused the CI image to rebuild in an environment ( providers) where we do not care about pip check where we want to just check all providers importability. And this docker image build (which was unnecessary and harmful) was run in the way that did not exclude `apache-beam` and failed the `pip check`.

**Comment by potiuk** [comment]
The problem will be solved finaly in the next version of beam it seems - see https://github.com/apache/beam/pull/14328. 

In the meantime I will make a change that will make us ready to remove beam from this exclusion when new version is released without mock dependency.
