### ISSUE TITLE
Build out custom Table components

### ISSUE THREAD

**Issue by ryanahamilton** [apache/airflow#15018]

**Comment by mik-laj** [comment]
@ryanahamilton Could you please write a little more? Apache Airflow is a community-managed project, so we should pay special attention to make the scope and purpose of the changes known to everyone. Otherwise, people who do not follow all activities in the project cannot participate in the development of the project.

**Comment by ryanahamilton** [comment]
@mik-laj yes, details are coming! We have this issue in the "Needs Scoping" column of [the project board](https://github.com/apache/airflow/projects/9). Maybe there's a label we could/should add to make it clear that it isn't ready to be worked on for people not looking at Issues via the project board?

**Comment by mik-laj** [comment]
I am afraid that no label will help because new members of the community will not understand it. The link to the project won't help either, because it still doesn't explain what we want to do. The project does contain a hint. Its name includes "AIP-38", but that also doesn't help a new contributor.

I think that each ticket requires a description that explains what and why we want to do.  I was in a similar situation when I was working on the API and you can see my tickets: https://github.com/apache/airflow/issues/8113

**Comment by ryanahamilton** [comment]
That makes sense. Maybe the best course of action will be to just add them to the project board asa "Notes" until we're ready to convert to an Issue with full details.
