### ISSUE TITLE
Passing Custom Image Family Name to the DataprocClusterCreateOperator()

### ISSUE THREAD

**Issue by pateash** [apache/airflow#15245]
**Description**
Currently, we can only pass custom Image name to  **DataprocClusterCreateOperator(),**
as the custom image expires after 60 days, we either need to update the image or we need to pass the expiration token.

Functionality is already available in **gcloud** and **REST**.

`gcloud dataproc clusters test_cluster ......
--image projects/<custom_image_project_id>/global/images/family/<family_name>
.......
`

**Use case / motivation**
The user should be able to pass either Custom Image or Custom Image family name,
so we don't have to update the image up on expiration or use expiration token.

**Are you willing to submit a PR?**
Yes

**Related Issues**
None

**Comment by ashishpatel0720** [comment]
I will work on this.

**Comment by ashishpatel0720** [comment]
There is workaround to this, we can just pass **family/<family_name>** in custom_image parameter to DataprocClusterCreateOperator(), taking advantage of because the way **custom_image_url** is created.

![image](https://user-images.githubusercontent.com/16856802/113821798-3717da80-979a-11eb-87d4-1e9f48f711cc.png)

But I really think there should be a dedicated parameter for avoiding any confusion.

**Comment by ashishpatel0720** [comment]
testing completed
![image](https://user-images.githubusercontent.com/16856802/114296309-3ea3f000-9ac8-11eb-9742-70505aef3e24.png)

![image](https://user-images.githubusercontent.com/16856802/114296325-5ed3af00-9ac8-11eb-8b21-92a1a4a8c0e1.png)

![image](https://user-images.githubusercontent.com/16856802/114296320-5b402800-9ac8-11eb-95ee-4ced7305a6b7.png)
