### ISSUE TITLE
Airflow UI display error

### ISSUE THREAD

**Issue by shentlu** [apache/airflow#15268]
Has everyone met airflow UI display error with browser cache? Is it a bug? Thanks.

**Comment by XD-DENG** [comment]
Please provide more information, like your setting up/configuration/environment. Trackback/logs/screenshots would be helpful.

**Comment by shentlu** [comment]
> Please provide more information, like your setting up/configuration/environment. Trackback/logs/screenshots would be helpful.

For example, i uploaded an updated DAG(to change schedule interval) to airflow linux server, but airflow WEB UI page shows overdue data about this DAG. Then i need to clear cache and refresh the page so that it will show the real-time data about this DAG.

**Comment by vikramkoka** [comment]
I am sorry, it is not clear if this is a problem or not. 
Just to be precise, the Airflow UI in 1.10.x is NOT a real-time UI which automatically refreshes the status of the DAG. 
The Airflow UI (for Graph View) in 2.x does have an auto-refresh capability to see the status of the tasks currently being executed. 

Please provide additional information and screenshots as requested above, so that we can respond effectively.
