### ISSUE TITLE
Airflow Docker tutorial: Unhealthy container 

### ISSUE THREAD

**Issue by benoua** [apache/airflow#15291]
**Environment**:
MacOs
docker-compose version 1.27.4

**What happened**:
I am following Airflow in Docker [tutorial](https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html?highlight=docker).

I did: 
```
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.0.1/docker-compose.yaml'
mkdir ./dags ./logs ./plugins
echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
```

Then, when initialising the docker compose with `docker-compose up airflow-init` I received the following error:

```
Creating network "airflow-local_default" with the default driver
Creating volume "airflow-local_postgres-db-volume" with default driver
Creating airflow-local_redis_1    ... done
Creating airflow-local_postgres_1 ... done

ERROR: for airflow-init  Container "768fe436ac8e" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
Container 768fe436ac8e corresponds to postgre docker when making a `docker containers ps`

If it was working correctly, I should have:
```
airflow-init_1       | Upgrades done
airflow-init_1       | Admin user airflow created
airflow-init_1       | 2.0.1
start_airflow-init_1 exited with code 0
```

![image](https://user-images.githubusercontent.com/24606918/114090119-4ccef200-98b7-11eb-8357-3042361d6d93.png)

Thank you very much for your help !

**Comment by kaxil** [comment]
Can you clean up and try again please

```
docker-compose down --volumes --rmi all
```

**Comment by benoua** [comment]
Thank you for your help. I have tried it but still the same result. 

```
➜  airflow-local docker-compose down --volumes --rmi all

Stopping airflow-local_redis_1    ... done
Stopping airflow-local_postgres_1 ... done
Removing airflow-local_redis_1    ... done
Removing airflow-local_postgres_1 ... done
Removing network airflow-local_default
Removing volume airflow-local_postgres-db-volume
Removing image postgres:13
Removing image redis:latest
Removing image apache/airflow:2.0.1
Removing image apache/airflow:2.0.1
WARNING: Image apache/airflow:2.0.1 not found.
Removing image apache/airflow:2.0.1
WARNING: Image apache/airflow:2.0.1 not found.
Removing image apache/airflow:2.0.1
WARNING: Image apache/airflow:2.0.1 not found.
Removing image apache/airflow:2.0.1
WARNING: Image apache/airflow:2.0.1 not found.
➜  airflow-local docker-compose up airflow-init
Creating network "airflow-local_default" with the default driver
Creating volume "airflow-local_postgres-db-volume" with default driver
Pulling postgres (postgres:13)...
13: Pulling from library/postgres
75646c2fb410: Pull complete
2355d0ffeb55: Pull complete
7e98825f6d67: Pull complete
cfd3ce06be45: Pull complete
c7b7bb83e8f7: Pull complete
c67869305108: Pull complete
19614baa7ddd: Pull complete
af508737d813: Pull complete
b60c3437a436: Pull complete
424da1ff3ea9: Pull complete
076f107f1898: Pull complete
7b398ea488bf: Pull complete
e0fcc114ae29: Pull complete
67d927dd9b8a: Pull complete
Digest: sha256:b25265ac1dfa19224fd47dd9f5744aa177248fd64e89f407446559cc7dbc7a23
Status: Downloaded newer image for postgres:13
Pulling redis (redis:latest)...
latest: Pulling from library/redis
75646c2fb410: Already exists
50c782b7d4d9: Pull complete
e624b72b42cc: Pull complete
dfcb918317cc: Pull complete
d8fcc46eaa64: Pull complete
c83989cecb0f: Pull complete
Digest: sha256:a63d3f66fb2f69d955d4f2ca0b229385537a77872ffc04290acae65aed5317d2
Status: Downloaded newer image for redis:latest
Pulling airflow-init (apache/airflow:2.0.1)...
2.0.1: Pulling from apache/airflow
45b42c59be33: Pull complete
f875e16ab19c: Pull complete
a4fb13de3215: Pull complete
f3dd9aaf319e: Pull complete
451a8f7ee895: Pull complete
e2d0adf49357: Pull complete
52856765f525: Pull complete
fd428150aaa6: Pull complete
b4fa7f6b9775: Pull complete
b34f0a9234cb: Pull complete
537882d8c1ac: Pull complete
dffdc965d748: Pull complete
a97e5a67cb46: Pull complete
c401f5284516: Pull complete
af49f5db1642: Pull complete
c61449868181: Pull complete
0b574505c97e: Pull complete
a65349ef32b2: Pull complete
Digest: sha256:2bf4fe559e9e699487a50d4e587358bb0b3c90b59c8fefeccc8a4fb2e83f3d09
Status: Downloaded newer image for apache/airflow:2.0.1
Creating airflow-local_postgres_1 ... done
Creating airflow-local_redis_1    ... done

ERROR: for airflow-init  Container "5e4f1ede9aaa" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by mik-laj** [comment]
Do you have enough resources to run all containers?

**Comment by benoua** [comment]
I have a macbook pro with 16G RAM + 40G free disk. Should be enough ?

**Comment by mik-laj** [comment]
It depends on your docker configuration. See: http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/start/docker.html section. Before begin

**Comment by guard13** [comment]
Good morning,

I give you the link to my solution which works and allows me to continue Airflow either on the Datascientest VM (but it dropped me, while resetting) or on my VMWare UBUNTU 20.04
https://support.datascientest.com/t/airflow-probleme-dinstallation/14687/3

I answer the question myself since I finally managed to launch Airflow in docker both on the Datascientest VM and on my own VM (But the DataScientest VM let me down this evening)
On the other hand everything works under 20.04 on VMWare

So the method works on Ubuntu 20.04

The method was therefore very simple:
1- The version of Docker is no longer compatible with Airflow
2- The version of Docker Compose is no longer compatible with Airflow

A - So I had to uninstall Docker and reinstall it

sudo apt remove docker docker-engine docker.io containerd runc

sudo apt autoremove

sudo rm -rf /var/lib/docker

sudo apt update

sudo apt install apt-transport-https ca-certificates curl software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update

sudo apt install docker-ce docker-ce-cli containerd.io

docker-v

sudo systemctl status docker



B- We had to uninstall Docker Compose and reinstall

sudo rm /usr/local/bin/docker-compose

sudo apt install docker-compose

C- Then we follow the command lines of the official Airflow website for Airflow in Docker (https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html)

docker run --rm "debian:bullseye-slim" bash -c 'numfmt --to iec $(echo $(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE))))'

curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.6.2/docker-compose.yaml'

mkdir -p ./dags ./logs ./plugins ./config

echo -e "AIRFLOW_UID=$(id -u)" > .env

AIRFLOW_UID=50000

docker compose up airflow-init

docker compose up

AND SURPRISE EVERYTHING WORKS
We identify ourselves with the username airflow and the password airflow

Courage, it was not easy...

ATTENTION :
This resets your .env file which will need to be updated (for example for mongodb environment variables)
