### ISSUE TITLE
There is a vulnerability in jquery 3.4.1 ,upgrade recommended

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/airflow#15364]
https://github.com/apache/airflow/blob/7490c6b8109adcc5aec517fc8d39cfc31912d92f/airflow/www/yarn.lock#L4208-L4211

CVE-2020-11023  CVE-2020-11022

Recommended upgrade version：3.5.0

**Comment by kaxil** [comment]
FYI: The last time we upgraded to 3.5 -- FlaskAppbuilder (library we use for Airflow Webserver) broke..

https://github.com/apache/airflow/pull/10684#issuecomment-686629229
https://github.com/apache/airflow/pull/10684#issuecomment-686629969

**Comment by zachliu** [comment]
in case anyone is interested

Vulnerable javascript library: jQuery
version: 3.4.1

Details:
jQuery versions below 3.5.0 used a regex in its jQuery.htmlPrefilter method. This regex which is used to ensure that all tags are XHTML-compliant could introduce a vulnerability to Cross-site Scripting(XSS) attack. Please refer to vendor documentation (https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/ and https://jquery.com/upgrade-guide/3.5/) for the security fix details.

----------------------------------------------

In jQuery versions greater than or equal to 1.2 and before 3.5.0, passing HTML from untrusted sources - even after sanitizing it - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute untrusted code. This problem is patched in jQuery 3.5.0. Please refer https://github.com/jquery/jquery/security/advisories/GHSA-gxr4-xjj5-5px2 and https://nvd.nist.gov/vuln/detail/CVE-2020-11022 ...

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/10429

**Comment by HardikVijayPatel** [comment]
What Airflow release version will have the jquery fix? and will this be available for both airflow 1 and airflow 2 ?

**Comment by kaxil** [comment]
> What Airflow release version will have the jquery fix? and will this be available for both airflow 1 and airflow 2 ?

Will be in Airflow 2.1.2. Airflow 1.x has reached End of life so no new releases will be cut for it.

https://github.com/apache/airflow#version-life-cycle

**Comment by HardikVijayPatel** [comment]
> > What Airflow release version will have the jquery fix? and will this be available for both airflow 1 and airflow 2 ?
> 
> Will be in Airflow 2.1.2. Airflow 1.x has reached End of life so no new releases will be cut for it.
> 
> https://github.com/apache/airflow#version-life-cycle

thanks! aprrox ETA for the release?

**Comment by kaxil** [comment]
~1 or 2 months

**Comment by HardikVijayPatel** [comment]
@kaxil this fix has got moved from airflow 2.1.2 to 2.1.3, is that right? as i don't see the issue mentioned in change log for the 2.1.2 release:
https://airflow.apache.org/docs/apache-airflow/stable/changelog.html

**Comment by kaxil** [comment]
@HardikVijayPatel This is available in 2.1.2 -- looks like because of the bad commit message it wasn't captured in Changelog -- 

https://github.com/apache/airflow/commit/9b0b0c68f6db940b16037be8dd7c1884ce6f1a87#diff-04917bec1b0d3cdd9aeaaeb24b1309315aeff5835dc78ab60fdf57768303b725

**Comment by HardikVijayPatel** [comment]
@kaxil I just updated my version to 2.1.2 and ran the following command in the console and see the version as 3.4.1:
console.log(jQuery().jquery);
VM58:1 3.4.1
undefined
am i checking something wrong or is there something missing here?

**Comment by kaxil** [comment]
cc @bbovenzi -- Any ideas ?

**Comment by kaxil** [comment]
@HardikVijayPatel looks like that is coming from https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/static/appbuilder/js/jquery-latest.js

You might have to ping or create issue in that project -> https://github.com/dpgaspar/Flask-AppBuilder/issues
