### ISSUE TITLE
breeze should load local tmux configuration in 'breeze start-airflow'

### ISSUE THREAD

**Issue by pateash** [apache/airflow#15416]
**Description**

Currently, when we run 

`
breeze start-airflow
`

**breeze** doesn't load local tmux configuration file **.tmux.conf** and we get default tmux configuration inside the containers.

**Use case / motivation**

Breeze must load local **tmux configuration** in to the containers and developers should be able to use their local configurations.

**Are you willing to submit a PR?**
YES

**Related Issues**
None

**Comment by mik-laj** [comment]
SGTM. Can you submit a PR?

**Comment by uranusjr** [comment]
I wondered about this a while ago (mostly because I don’t want to repeatedly `set mouse on`). The problem is any slightly sophisticated local tmux setup would contain a lot of dependencies and it’s not realistic to pull them all into the container. So maybe a better approach would be have a directory *in the repository*; if the user puts a (git-ignored) `.tmux.conf` file in it, the file is mounted to the container’s `~/.tmux.conf`.

**Comment by ashishpatel0720** [comment]
> SGTM. Can you submit a PR?

Yes I will.

**Comment by potiuk** [comment]
We already have similar mechanism for reading user-supplied env variables placed in `files/airflow-breeze-config` folder.
 https://github.com/apache/airflow/blob/130f9e32f49e10511863d05c03f3532269ae27db/scripts/in_container/configure_environment.sh#L36


It could be done in a very similar way .

**Comment by ashishpatel0720** [comment]
> We already have similar mechanism for reading user-supplied env variables placed in `files/airflow-breeze-config` folder.
> https://github.com/apache/airflow/blob/130f9e32f49e10511863d05c03f3532269ae27db/scripts/in_container/configure_environment.sh#L36
> 
> It could be done in a very similar way .

thanks @potiuk, let me check.

**Comment by ashishpatel0720** [comment]
PR #15454 
I guess, I have to update docs as well.
