### ISSUE TITLE
Improve test coverage of views

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#15525]
There are quite a number of untested views: 

https://codecov.io/gh/apache/airflow/src/master/airflow/www/views.py 80%

We might want to improve test coverage for those.

**Comment by uranusjr** [comment]
I wonder if this is also a good chance to improve the www/view tests as a whole. One thing I found while working on improving test suite run time (#14857 etc.) was the whole `tests/www/test_views.py` file is much too complex and less maintainable relative to other tests (#14863), and could use some big cleanup and reorganisation (e.g. split into smaller files with more granular fixture setup).

**Comment by potiuk** [comment]
Yeah. We know it. But we also want to get rid of it and replace it with the new UI (work is on-going) so rather than refactoring and fixing the current approach (which is based on Flask Application Builder) we want to 'properly' build the new UI. See https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-38+Modern+Web+Application

**Comment by potiuk** [comment]
But feel free to do it If you feel like it :). The old UI will be with us for quite a while still (at least till 3.0)

**Comment by rsg17** [comment]
Hi - I am new to Airflow and would like to contribute to this. Do you have some pointers to help me get started? I was going to look at the previous PRs to get some ideas and context.

**Comment by uranusjr** [comment]
To test a view, you need to set up a `Flask` app instance, and use it to invoke the views. Since setting up the `Flask` instance is quite costly, it’s important to reuse the instance as much as possible; in general we use Pytest’s [fixture scope](https://docs.pytest.org/en/stable/fixture.html#scope-sharing-fixtures-across-classes-modules-packages-or-session) for this; fixtures generating `Flask` instance would be marked either `module` or even `session` scoped so they can be reused by tests inside a `.py` file or for the entire `pytest` run. So it’d be very beneficial to first read and understand how Pytest fixtures, discoverer, and runner work. The test setup would make a lot more sense after that.

**Comment by eladkal** [comment]
Updated status:
https://app.codecov.io/gh/apache/airflow/blob/main/airflow/www/views.py 80.56%

**Comment by potiuk** [comment]
We can close that one as we are moving to fast api.
