### ISSUE TITLE
Specific documentation for Configuration JSON when triggering a DAG manually

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#15590]
When you click on 'Trigger Dag', you are redirected to a section in which you can introduce a configuration JSON, and you see a message like this:

`To access configuration in your DAG use {{ dag_run.conf }}.`

It would be very cool to be able to write your own documentation as well, so that you can explain how there to use the dag_run.conf variables of that dag. 

If someone guides me how to code this, I will be happy to try

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/pull/13365
Is it related?

**Comment by JavierLopezT** [comment]
> #13365
> Is it related?

Indeed, it seems to be what I want. However, I think there isn't any documentation, is it?

**Comment by eladkal** [comment]
@JavierLopezT can you please provide example of what you expect from this feature and why #13365 isn't covering it?

**Comment by JavierLopezT** [comment]
> @JavierLopezT can you please provide example of what you expect from this feature and why #13365 isn't covering it?

It is basically what I said in https://github.com/apache/airflow/issues/15590#issuecomment-829418518 If my assumption that #13365 will render the entire documentation of the DAG in that screen is correct, then I think what I propose could be more optimal in some cases. Let's say I have the following DAG doc:

```
"""This DAG blabla blablaba
 + 100 lines of documentation

When you trigger manually the DAG, the parameters blabla"""
```

I don't want to see 103 lines on the screen of JSON configuration. Instead, I just want to see the last line, which I will assign to the attribute `dag.doc_json_configuration` or something like that, instead of the attribute `dag.doc_md`

**Comment by JavierLopezT** [comment]
comment for removing stale

**Comment by jens-scheffler-bosch** [comment]
Hi @JavierLopezT During housekeeping I was directed to this (a bit stale) feature request. Meanwhile the UI has progressed a lot and since Airflow 2.6.0 there is a total new parameter UI which allows better help text and easier use for users to define run parameters.

Most of the current features in current 2.6.2 have been discussed and implemented within AIP-50 (see https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-50+Trigger+DAG+UI+Extension+with+Flexible+User+Form+Concept) and are for the current version described in https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html#use-params-to-provide-a-trigger-ui-form

As of the current state of the UI and limited information I can see in this feature request, is there still anything missing that you see as gap in terms of "documentation"? As this item is stale for a wile (~18months) I'm going to close - but we could re-open based on your feedback.
