### ISSUE TITLE
Auto refresh feature for graph view

### ISSUE THREAD

**Issue by aranjanthakur** [apache/airflow#15879]
**Description**

Graph view can be configured for auto refresh. In airflow.cfg we can set following configs:

1) on/off switch
2) Refresh period ( There should be a lower limit. )

Extended feature - Above two configs should be overriden at DAG level as some DAGs might need quicker refresh period than others.

**Use case / motivation**

When monitoring a DAG, we need to refresh the graph view multiple times to check the status.

**Are you willing to submit a PR?**

Yes

**Related Issues**

No

**Comment by bbovenzi** [comment]
1. I have been thinking about doing an "auto-on" to detect if the that dag has any active runs. Would that solve the first config?

2. Right now the refresh interval is set to 3 seconds. Is there a more reasonable time you'd suggest?
It would be best to agree on a good interval rather than piling on more config. Especially on a per dag basis, I feel like that could be confusing for many users.

**Comment by aranjanthakur** [comment]
Auto-on feature for detecting active runs sounds good. I agree with the 3 seconds refresh interval and that we should not be piling on more configs.
