### ISSUE TITLE
Tree View is blocked by DagRuns status when showing all 356 DagRuns

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#16130]
**Apache Airflow version**: 2.1.0

**Browsers**: Chrome and Firefox

**What happened**:

When showing all 365 DagRuns, they overlap with the "tree" on the left and we can't see the tree anymore

![2021-05-27_16-49](https://user-images.githubusercontent.com/14293802/119895246-8dd4a180-bf0b-11eb-90f8-eca8909cc739.png)

in addition, when "Auto-refresh" is ON, the whole DagRun status section is gone

![2021-05-27_16-44](https://user-images.githubusercontent.com/14293802/119894601-cb84fa80-bf0a-11eb-892f-b8e3f348d45b.png)

**What you expected to happen**:

1. DagRuns status doesn't overlap with the "tree" so that I can still see the tree
2. Auto-refresh doesn't hide the task status

**How to reproduce it**:

Go to a DAG with more than 365 DagRuns and show 365 DagRuns in `Tree View`

**Comment by zachliu** [comment]
@Tofull is my description of the bug confusing? :thinking:

**Comment by Tofull** [comment]
> @Tofull is my description of the bug confusing? 🤔

I hit the same behaviour like you describe with the version 2.1.0. We upgraded to `airflow == 2.1.1rc1` and the Tree View is now working as expected.
I think the PR https://github.com/apache/airflow/pull/16522 fixes the overlapping issue (related to issue https://github.com/apache/airflow/issues/16238).
This issue is also related to PR https://github.com/apache/airflow/pull/16437.
Both PRs have been merged, [see changelog of version 2.1.1rc1](https://github.com/apache/airflow/compare/2.1.0...2.1.1rc1).
