### ISSUE TITLE
Weekly Run Dag not trigerring

### ISSUE THREAD

**Issue by psmukherjee009** [apache/airflow#16164]
#!/usr/bin/env python3
from airflow.models import DAG
from airflow.operators.bash import BashOperator
from airflow.utils.dates import days_ago
from datetime import timedelta

args = {
    'owner': 'partha',
    'depends_on_past': False,
    'start_date': days_ago(6),
    'retries': 0,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(
    dag_id='scheduler_interval_102',
    schedule_interval='15 5 * * 0',
    default_args=args,
    catchup=False,
    tags=['Test1']
)

hello_my_task = BashOperator(
    task_id='hello_task_1',
    bash_command='echo "hello_world %s %s"' % (dag.dag_id, dag.schedule_interval),
    dag=dag,
)

This is a simple setup with mysql db of Airflow 2.0 in ubuntu 21.04

Change the scheduled interval to
1. '15 5 * * *'
2. '15 5 * * 0-1',
and it works

3. '15 5 * * SUN' -- does not work

**Comment by eladkal** [comment]
I think your issue is because you set `days_ago(6)` so it's not a full week ago when I changed it to be  `days_ago(10)` it worked fine.
In any case the `start_date` needs to be static date and in both cases ` schedule_interval='15 5 * * SUN'` works fine on master branch:

```
from airflow.models import DAG
from airflow.operators.bash import BashOperator
from datetime import timedelta, datetime

args = {
    'owner': 'partha',
    'depends_on_past': False,
    'start_date': datetime(2015, 12, 1),
    'retries': 0,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(
    dag_id='scheduler_interval_102',
    schedule_interval='15 5 * * SUN',
    default_args=args,
    catchup=False,
    tags=['Test1']
)

hello_my_task = BashOperator(
    task_id='hello_task_1',
    bash_command='echo "hello_world %s %s"' % (dag.dag_id, dag.schedule_interval),
    dag=dag,
)

```

![Screen Shot 2021-05-31 at 17 32 15](https://user-images.githubusercontent.com/45845474/120208607-5715c880-c236-11eb-806c-2f943e2e5874.png)
