### ISSUE TITLE
API ListDAGs inconsistent with Web View/CLI

### ISSUE THREAD

**Issue by jpyen** [apache/airflow#16228]
`/api/v1/dags` lists a total of 39 DAGs, while only 8 DAGs are present which can be seen in the Web UI and Airflow CLI on worker pods.

Any explanation on why I get different results from the API vs all other methods?

It seems that the API is showing deleted DAGs without a present file.

**Apache Airflow version**: 2.0.1 / 2.1.0

**Comment by jpyen** [comment]
Is it possible that `/api/v1/dags` is only listing DAGs the current user has access to - present or not?
https://github.com/apache/airflow/blob/main/airflow/api_connexion/endpoints/dag_endpoint.py#L64


In contrast the UI seems to get the DAG list ground-truth from here: https://github.com/apache/airflow/blob/8505d2f0a4524313e3eff7a4f16b9a9439c7a79f/airflow/www/views.py#L551 and then uses  `get_accessible_dag_ids` to only show a selection. 

Is this assessment correct?

**Comment by uranusjr** [comment]
Correct, the index page lists all DAGs by default, while the API only lists those the user has the permission to view (since the API returns DAG details that the user may not have permission to view).

(Thinking loudly) Maybe we should make this less confusing? For example, the API can instead list all the DAGs, but only show details of those the user has permissions to view; or maybe the web UI should only show DAGs viewable by the user (at least by default).

**Comment by jpyen** [comment]
Thanks for the quick reply uranusjr, in this case I would be confused that the API shows more (invalid) DAGs, as in DAGs that have been deleted and should not be visible - even with the right permissions? (Thats as far as I understood the issue)

**Comment by uranusjr** [comment]
I think your understanding is correct. I’m not sure why the API does not filter out inactive DAGs (they probably should show sub-DAGs though I’m not 100% sure), could be an oversight or intetional design. We’ll need someone who was involved in the API implementation to answer this.
