### ISSUE TITLE
Airflow Tree View for larger dags

### ISSUE THREAD

**Issue by syedshameersarwar** [apache/airflow#16238]
Hi, Airflow Web UI shows nothing on tree view for larger dags (more than 100 tasks), although it's working fine for smaller dags. Anything that is needed to be configured in `airflow.cfg` to support larger dags in the UI?

![alt larger](https://user-images.githubusercontent.com/42420177/120632899-ed3e2e80-c482-11eb-8c96-40bf751377e7.png)

Smaller Dag:

![alt smaller](https://user-images.githubusercontent.com/42420177/120633072-28d8f880-c483-11eb-8fad-ee3f59461894.png)

**Apache Airflow version**: 2.1.0 (Celery)

**Environment**: 

- **Cloud provider or hardware configuration**: `AWS EC2`
- **OS** (e.g. from /etc/os-release): `Ubuntu 18.04`
- **Kernel** (e.g. `uname -a`): `5.4.0-1045-aws`
- **Install tools**: `pip`

**What you expected to happen**:
It is rendering correctly on `Airflow 1.10.13 (Sequential)`

![image](https://user-images.githubusercontent.com/42420177/120633643-cf24fe00-c483-11eb-9cce-09f07be38905.png)

**How to reproduce it**:
Create a sample dag with `>=` 100 tasks

**Anything else we need to know**:
The cli command for viewing dag tree is working correctly `airflow tasks list services_data_sync --tree`

**Comment by fjmacagno** [comment]
I dont know if it is the same issue, but my large dags are showing up in tree view, but unusably: 
![image](https://user-images.githubusercontent.com/42754983/121547021-9f648180-c9c0-11eb-8e24-982eeaa282e4.png)

**Comment by kaxil** [comment]
cc @bbovenzi

**Comment by jdahlbaek** [comment]
We're experiencing both of the above issues in the tree view. Additionally, on my mobile device, I'm unable to get the web ui to show the tree at all. On desktops, some trial and error with zooming in/out and then refreshing the page seems to help.

**Comment by bbovenzi** [comment]
@jdahlbaek We support mobile screen sizes. But let me look into the rest of these concerns and see what's going on.

**Comment by bbovenzi** [comment]
@fjmacagno @syedshameersarwar Does this happen when the auto-refresh is on, or whenever?

**Comment by fjmacagno** [comment]
> @fjmacagno @syedshameersarwar Does this happen when the auto-refresh is on, or whenever?

Whenever

**Comment by syedshameersarwar** [comment]
> @fjmacagno @syedshameersarwar Does this happen when the auto-refresh is on, or whenever?

Yeah, it's always the same for me, auto-refresh on or off

**Comment by bbovenzi** [comment]
Noted. Still looking into it.

**Comment by ldacey** [comment]
> I dont know if it is the same issue, but my large dags are showing up in tree view, but unusably:
>

I get this same weird (ugly) UI on tree view if I expand the number of runs from like 25 to 100 or 365 as well, it overlaps.

**Comment by brosenkrantz** [comment]
We are also seeing an empty tree view with a large DAG on 2.1.0. It has around 60 tasks.

**Comment by freget** [comment]
I did a bit of debugging. There is some magic going on that I do not quite understand. However, this issue almost certainly is caused by the following line:

https://github.com/apache/airflow/blob/6087a09f89c7da4aac47eab3756a7fe24e3b602b/airflow/www/static/js/tree.js#L76

Subtracting the `treeDepth * 50` leads to a negative squareX, and this causes problems. As each tree depth adds 25 pixels and not 50 to the width of the tree representation, changing this to `treeDepth * 25` seems reasonable and allows rendering of the tree view for all dags I have as reference.

By the way: The following lines of code feel wrong to me - I believe they are the cause that the colored squares sometimes are far away from the tree representation. That did look better in Airflow 2.0. I do not understand enough of the code to make a sensible correction, though. 

https://github.com/apache/airflow/blob/6087a09f89c7da4aac47eab3756a7fe24e3b602b/airflow/www/static/js/tree.js#L206-L208

**Comment by bbovenzi** [comment]
@freget good call. Let me take a deeper look on how we deal with squareX and how wide trees are

**Comment by bbovenzi** [comment]
@freget Do you want to make that a PR? I will happily review it.

**Comment by raajpackt** [comment]
Should this bug still exist in `airflow:2.1.0` ? 
Because i am using that version and it exists. Will this be resolved in future versions?

**Comment by potiuk** [comment]
See the milestone from merged bug - it's 2.1.1, so try this one

**Comment by potiuk** [comment]
Generally - you can safely upgrade to latest released version of Airflow. We are following SemVer, so there should be generally no breaking changes in 2.* seriers.
