### ISSUE TITLE
Make `XCom.get_one()` + `get_many()` accept run_id

### ISSUE THREAD

**Issue by ashb** [apache/airflow#16371]
XCom.get_* methods current accept an execution_date, and need to accept a run_id now.

We should add back-compat shims so that any python_operators that call these methods continue to work.

There needs to remain a kwarg called `execution_date` for DAGs/third party code to call, but any uses in Airflow (TI.xcom_pull for instance) should be updated to pass run_id directly)

**Comment by uranusjr** [comment]
Similar to how we plan to associate `TaskInstance` to `DagRun` via `run_id` (instead of implicitly via `execution_date`), would it make sense to also add a `run_id` column on XCom as well? That (plus backfilled values) would make this a lot easier; currently since XCom only has `dag_id` and `execution_date`, we need to do an SQL join to filter with `run_id`.

**Comment by ashb** [comment]
Closed by https://github.com/apache/airflow/pull/18084
