### ISSUE TITLE
Airflow helm chart web pod keep crashing in v2.1.0

### ISSUE THREAD

**Issue by garylau** [apache/airflow#16449]
Hi Folks,

I am deploying the [Airflow helm chart](https://github.com/airflow-helm/charts/tree/main/charts/airflow) `v8.2.0` and `apache/airflow:2.1.0-python3.7` docker image into our existing EKS cluster.

I am using the default value yaml file and only change I made was to increase the `memory` requests/limits in `web` and `worker` components.

However, the `web` pod keeps crashing and I can't find any other useful error log.

**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.19.7

**Environment**:

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

After deployment liveness probe and readiness probe both failed:
`Warning  Unhealthy  3m29s (x49 over 22m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500`

**What you expected to happen**:

All pod stays up and ready status

**How to reproduce it**:

- save the default values into local: `helm show values airflow-stable/airflow > default-value.yaml`
- change the airflow image tag to: `2.1.0-python3.7`
- deploy helm chart: 
```
	helm repo add airflow-stable https://airflow-helm.github.io/charts
	helm repo update
	helm upgrade --install \
		airflow \
		airflow-stable/airflow \
		--namespace risk \
		--version 8.2.0 \
		--force \
		--values ./default-value.yaml
```

**Anything else we need to know**: 

This is the logs in the `web` pod.
```
   ____________       _____________
  ____    |__( )_________  __/__  /________      __
 ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
 ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
 [2021-06-15 07:04:56,306[] {dagbag.py:487} INFO - Filling up the DagBag from /dev/null
 [2021-06-15 07:04:58,318[] {manager.py:565} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin
 [2021-06-15 07:04:58,403[] {manager.py:565} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin
 [2021-06-15 07:04:58,416[] {manager.py:565} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin
 [2021-06-15 07:05:00,400[] {manager.py:565} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin
```

**Comment by potiuk** [comment]
We won't be able to help too much, I am afraid without the logs. This is troubleshooting of your K8S installation not helm chart.

You need to dig deeper in the logs of k8s - there are for sure generic k8S logs that can tell you the reason why pods are crashing. . It usually is because of not enough resources - disk, memory, cpu etc. and you will see that in K8S logs rather than Airflow logs. You will have to find it in the EKS logs. 

Also I heartily recommend k9s tool for such investigations. https://github.com/derailed/k9s  it makes it much easier to see what's going on. 

Closing for now until some more information is available that will make it possible to investigate.
