### ISSUE TITLE
SFTPToS3Operator is not mentioned in the apache-airflow-providers-amazon > operators documentation

### ISSUE THREAD

**Issue by ecerulm** [apache/airflow#16730]
**Apache Airflow version**:  2.2.0  , apache-airflow-providers-amazon == 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

I would expect to find the documentation for
`airflow.providers.amazon.aws.transfers.sftp_to_s3.SFTPToS3Operator`
in one these locations 
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/index.html
or
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/transfer/index.html

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
@ecerulm - would you be willing to add it maybe ?

**Comment by ecerulm** [comment]
I can't do a PR in the short term, sorry.

**Comment by potiuk** [comment]
I will add it to the first-time-contributor's workshop then :).

**Comment by nareshkumaryadav** [comment]
@ecerulm Do you mean transfer from AWS SFTP to s3 operator or transfer from any SFTP to S3 ?

**Comment by ecerulm** [comment]
The SFTPToS3Operator is an already existing operator that can transfer a file from any SFTP server to s3 @nareshkumaryadav

**Comment by dwivedys** [comment]
This doesn't seem like a bug but more like a missing documentation issue?

**Comment by pyerbiz** [comment]
I would like to work on this issue. Based on the problem description the documentaion for SFTPToS3Operator can be made . Please see below:

1. The actual doc be mirrored on [glacier_to_gcs.rst](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-amazon/operators/transfer/glacier_to_gcs.rst) 

2. An example DAG for SFTPToS3Operator will have to built under [airflow/providers../aws/example_dags](https://github.com/apache/airflow/tree/main/airflow/providers/amazon/aws/example_dags)

3. I believe s3_to_sftp example dag is also missing, so documentation for this must also be missing.  

4. There are 14-15 transfer operators, under [/aws/transfers](https://github.com/apache/airflow/tree/main/airflow/providers/amazon/aws/transfers) but the documentaion is showing most of these under /operators instead of [operators/Amazon transfer operators](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/index.html). Therefor Amazon Tansfer Operators doc page only has Glacier Transfer Operator. Is this something to fix?

**Comment by potiuk** [comment]
1. yep
2. yep
3. Happy if you add it too :)
4. yeah. good catch. I think just moving the files should be enough, I think 
 
BTW. You can ran `./breeze build-docs -- --package-filter apache-airlfow-providers-amazon` to test if the documentation builds and looks nice (and then ./docs/start_doc_server.sh you should be able to browse the docs)

**Comment by pyerbiz** [comment]
@potiuk Is there an example dag for sftp_to_s3 transfer. Below is what I have so far

```
import os

from airflow import models
from airflow.providers.amazon.aws.transfers.sftp_to_s3 import SFTPToS3Operator
from airflow.utils.dates import days_ago

S3_BUCKET = os.environ.get("S3_BUCKET", "test-bucker")
S3_KEY = os.environ.get("S3_KEY", "key")

with models.DAG(
    "example_sftp_to_s3",
    schedule_interval=None,
    start_date=days_ago(1),  # Override to match your needs
) as dag:

    # [START howto_sftp_transfer_data_to_s3]
    create_sftp_to_s3_job = SFTPToS3Operator(
        task_id="create_sftp_to_s3_job",
        sftp_conn_id="sftp_conn_id",
        sftp_path="sftp_path",
        s3_conn_id="s3_conn_id",
        s3_bucket=S3_BUCKET,
        s3_key=S3_KEY
    )
    # [END howto_sftp_transfer_data_to_s3]
```

**Comment by potiuk** [comment]
Looks good. Is there a PR for that?

**Comment by pyerbiz** [comment]
Working on it
