### ISSUE TITLE
UrlParse not defined Failed to create a workload

### ISSUE THREAD

**Issue by harvetech** [apache/airflow#16813]
Dear all, I am trying to install airflow on a Kubernetes cluster managed by the open Telekom Deutschland. I am using the chart available here but I am getting an error at` line 162` in `webserver-deployment.yaml `that urlParse is not defined. Can somebody please guide me on what should I do?

**Comment by potiuk** [comment]
The description is far too vague - you have not provided details on how your deployment look like nor what you have done so far to analyse the problem. The chart is used and tested in production so it's unlikely we will be able to help without knowing more about your deployment, configuration, changes, which versions of which charts, images, airflow, and with what configuration you used. There is a good reason we provide template for issues of different kind (especially Bug has a lot of information to be filled in).

Also, unless you have a concrete bug and reproduction path, it's better to open a discussion for ti (see Discussions list at the top) rather than issue. I am closing this for now, can you please open it in discussion and provide more context? Otherwise I am afraid not much can be done. I am closing this one as invalid, and kindly ask you to open discussion and provide more details there.
