### ISSUE TITLE
Add support for Salesforce Bulk API

### ISSUE THREAD

**Issue by subkanthi** [apache/airflow#16921]
**Description**

Salesforce Bulk API is very popular to retrieve/push data to Salesforce, a maximum of 10k records can be pushed in the bulk API. Add a separate hook to support bulk Api SalesforceBulkApiHook
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_intro.htm

**Use case / motivation**

In a lot of organizations this might be useful for performing ETL from Bigquery or data storage platforms to Salesforce using Bulk API.

**Are you willing to submit a PR?**

Yes

**Related Issues**

**Comment by potiuk** [comment]
Assigned you :)

**Comment by alexbegg** [comment]
I just want to share that it is fairly simple to use a SalesforceHook for a SalesforceBulk connection, I am doing it at my company (you just have to `pip install salesforce-bulk`: https://github.com/heroku/salesforce-bulk):

```
from airflow.providers.salesforce.hooks.salesforce import SalesforceHook
from salesforce_bulk import SalesforceBulk

...

sf_hook = SalesforceHook()
sf_conn = sf_hook.get_conn()
bulk = SalesforceBulk(sessionId=sf_conn.session_id, host=sf_conn.sf_instance)
```

So it should be fairly simple to make this into a `SalesforceBulkHook` (I think "Api" in the name is a bit unnecessary since we aren't calling the existing hook SalesforceApiHook).

**Comment by eladkal** [comment]
@subkanthi are you still working on this?

**Comment by alexbegg** [comment]
I am the one who left the last comment. @eladkal you are welcome to work on this, but if not and if nobody else will work on this, I am open to possibly working on it.

**Comment by eladkal** [comment]
feel free

**Comment by ishiis** [comment]
@alexbegg Are you still working on this issue? May I submit a PR?

**Comment by alexbegg** [comment]
> @alexbegg Are you still working on this issue? May I submit a PR?

You may submit a PR, I haven't had time to work in this.
