### ISSUE TITLE
Scheduler stops running: psycopg2.OperationalError: SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by cris-b** [apache/airflow#16988]
**Apache Airflow version**:

2.0.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

1.19.7

**Environment**:

- Azure AKS
- Azure Postgresql
- Bitnami template

**What happened**:

Scheduler stopped running after processing a dag at 00:30.  Next dags at 00:45 did not get executed.

Errors relating to postgres in the log:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected

**What you expected to happen**:

All dags run.

**Anything else we need to know**:

Full scheduler pod logs:

[broken_scheduler_edit.txt](https://github.com/apache/airflow/files/6814563/broken_scheduler_edit.txt)

**Comment by eladkal** [comment]
The traceback shows:
```
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 817, in _checkout
    raise exc.InvalidatePoolError()
sqlalchemy.exc.InvalidatePoolError: ()
```

I guess it's similar/duplicate  to https://github.com/apache/airflow/issues/15496

does this error happens in 2.1 ?

**Comment by potiuk** [comment]
This is normal behaviour when there is a problem with database that scheduler (or any other component might crash in case of the database failure. There are some other problems in the log you provided (`Kubernetes resource version is too old, must reset to 0`) which might indicate that there is a problem with your K8S deployment. 

I assume what happened here (please double check and let us know if it did not).

If Airflow crashed (which is expect in case of DB failure after several internal retries by the SQLAlchemy - see #15496) and your deployment did not restart it, then you need to fix the deployment to restart airflow scheduler in case of failure. 

The problem could be because of the way the Bitnami chart is implemented. We are not controlling the bitnami Helm chart (which I believe you are using), so I am not sure if it properly restarts scheduler in case of failure - you will need to double check yourself.

Alternatively I recommend you to switch to the official Helm chart relased by the Apache Airflow project (available at https://airflow.apache.org/docs/helm-chart/stable/index.html) - it's done in the way that it will restart scheduler if it crashes and genarally supports wide number of options (and we will be able to support you here if you have problems with it. 

Closing it, unless there are more information indicating that this is an airflow, rather than deployment problem.
