### ISSUE TITLE
Improved SQL rendering within BigQueryInsertJobOperator

### ISSUE THREAD

**Issue by nathadfield** [apache/airflow#17032]
**Description**

`BigQueryInsertJobOperator` requires the submission of a `configuration` parameter in the form of a dict.  Unfortunately, if this contains a large SQL query - especially one that is formatted with new lines - then this cannot currently be rendered very nicely in the UI.

<img width="1670" alt="Screenshot 2021-07-15 at 15 39 33" src="https://user-images.githubusercontent.com/967119/125806943-839d57a9-d4a0-492d-b130-06432b095239.png">

**Use case / motivation**

The issue with this is that it's impossible to copy and paste the rendered query out of the Airflow UI, into a BigQuery browser and run it without lots of manual edits which is time wasted when troubleshooting problems.

**Are you willing to submit a PR?**

Yes.  My current thought process around this would be to add an optional SQL parameter to the operator which, if provided, would be added into the configuration and could therefore have its own template field and SQL renderer.

e.g.

<img width="1570" alt="Screenshot 2021-07-14 at 14 18 09" src="https://user-images.githubusercontent.com/967119/125808200-5f30b8f4-4def-48a7-8223-82afdc65c973.png">

**Comment by potiuk** [comment]
How about adding a general capability of having "view" on parameters that will not require copying? 

Simply add possibility of specifying jsonpath (https://goessner.net/articles/JsonPath/) expression that could generate a virtual parameter to render. This could be done on the operator static fields rather than as parameter. We could take kwargs and convert them to - essentially - json, using some well defined serialization (maybe even current serializaton we use would do).

I imagine something like that at operator level:


```
renderable_values= [
   ('sql', '$.configuration.query.query', 'sql'),
]
```
where 'renderable values will be an array of tuples ("<NAME>", "<JSONPATH>", "<RENDERER>"),

That would be very natural extension of the current rendering approach and something that can be generalized and easy to add for a number of operators (and no need for optional parameters).

**Comment by nathadfield** [comment]
@potiuk Thanks for the input.  When you talk about a general capability, where would this sit?  I don't really understand yet the relationships between the operator parameters and the UI rendering.

**Comment by kaxil** [comment]
Wouldn't just using `strip` where you define the large SQL suffice?

```python
❯ python
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> str1 = "\n Starbucks has the best coffee \n"
>>> newstr = str1.strip()
>>> print(newstr)
Starbucks has the best coffee

>>> str1 = "\n Starbucks has the best \n hi coffee \n"
>>> newstr = str1.strip()
>>> print(newstr)
Starbucks has the best
 hi coffee
>>>
```

**Comment by nathadfield** [comment]
@kaxil It doesn't look like it.

```
sql = '''
    INSERT INTO `target_project.target_dataset.target_table`
    (col1, col2, col3, col4)
    SELECT col1, col2, col3, col4
    FROM `source_project.source_dataset.source_table`
    '''

    test = BigQueryInsertJobOperator(
        task_id='test',
        gcp_conn_id='my_gcp_connection',
        configuration={"query": {"query": sql.strip(),
                                 "useLegacySql": False}
                       }
    )
```

<img width="1668" alt="Screenshot 2021-07-16 at 08 48 04" src="https://user-images.githubusercontent.com/967119/125911821-e86cc2ca-8eb7-4aef-a4bb-4fbaf907de7f.png">

**Comment by tswast** [comment]
A UI improvement seems like the right choice. https://github.com/apache/airflow/issues/17032#issuecomment-880795289

There are a ton of properties on job resource objects, so I'd be worried about the precedent for adding kwargs for each of them. Especially since query jobs aren't the only kind of job

**Comment by potiuk** [comment]
Yeah. I think it's a nice feature to have it in this generic way. It is very much like multi-language rendering in modern IDEs :).  @nathadfield are you up to the task :) ?

**Comment by potiuk** [comment]
Happy to guide on that one :)

**Comment by nathadfield** [comment]
@potiuk I would love to say yes, but I'm definitely lacking some knowledge.  So far I've figured out that there would need to be a change to BaseOperator to enable the provision of a `renderable_values` object on an operator.

I also can see that there would need to be some additional logic in [views.py](url) but this is about as far as I've managed to get so far.

Any guidance or tips you can provide would be most appreciated.

**Comment by kaxil** [comment]
Looks like usage of triple quotes adds line breaks -- https://stackoverflow.com/questions/19756715/remove-n-from-triple-quoted-string-in-python explains it better.

I think the DAG Author should handle this as for other instances a line break is on purpose and not just used for multi-line strings.

For the feature rendering, Jarek proposed, let's try to gauge the benefits of that feature first. Because any changes in serialization will increase the size of the payload to push during parsing in the scheduler and for the webserver to pull.

**Comment by potiuk** [comment]
If that works for now, cool.

 Just one question- the feature i proposed is UI-only really ( i believe ?) Why serialization would be impacted ? I think it's just one more class level field at the operator to tell UI to make a bit more work on json form of the operator that is already there. 

But maybe I am wrong? Is it because it is class -level field and we need to handle it differently? 

I do not know details of serialization that much and maybe I missed something. But I agree if it involves some changes in serialization protocol, it should not be taken lightly.

What i like about the idea however is that i see a lot of cases - especially in Google operators, where the parameters are complex structures and it would be nice to be able to format and see them with syntax coloring and copy-paste able . That's a nice feature.

**Comment by nathadfield** [comment]
@kaxil Thanks for that but, if I am being very nit-picky, it is a lot harder to copy a long query out of the UI if its spread over one line as it requires scrolling to the right without really knowing where it ends.  It is a lot easier to capture the query if it has been rendered as SQL with the intended formatting.

The impact of this is that pasting it into a BigQuery browser results in a single line query.

<img width="1200" alt="Screenshot 2021-07-20 at 09 00 40" src="https://user-images.githubusercontent.com/967119/126284116-eb0fefc4-6c20-4861-897c-3d9db2b960e8.png">

In this example its not a big deal but if its a complicated query that needs troubleshooting then I either need to reformat it, or get the untemplated query and insert the correct variables to replicate the query that run.

Both of these scenarios result in wasted time that we didn't have to worry about prior to 2.x BigQuery operators.

**Comment by kaxil** [comment]
>Both of these scenarios result in wasted time that we didn't have to worry about prior to 2.x BigQuery operators so I feel like there has been a bit of a regression here.


Oh ! if that's a regression, yes we should definitely fix it. I wonder it might be due to serialization too. I will take a closer look at it, if someone does not fix it before me :)

**Comment by nathadfield** [comment]
> > Both of these scenarios result in wasted time that we didn't have to worry about prior to 2.x BigQuery operators so I feel like there has been a bit of a regression here.
> 
> Oh ! if that's a regression, yes we should definitely fix it. I wonder it might be due to serialization too. I will take a closer look at it, if someone does not fix it before me :)

@kaxil When I say regression I'm more talking about from a UX perspective.

This operator didn't exist before v2 so we used [BigQueryOperator](https://github.com/apache/airflow/blob/main/airflow/contrib/operators/bigquery_operator.py) which is now deprecated as is [BigQueryExecuteQueryOperator](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/operators/bigquery.py#L487) in the provider in favour of `BigQueryInsertJobOperator`.

Using `BigQueryExecuteQueryOperator` gives the rendering we would like to see but at the expense of not having the full BigQuery job configuration available.

```
sql = '''
INSERT INTO `target_project.target_dataset.target_table`
(col1, col2, col3, col4)
SELECT col1, col2, col3, col4
FROM `source_project.source_dataset.source_table`
'''

test = BigQueryExecuteQueryOperator(
    task_id='test',
    gcp_conn_id='my_gcp_connection',
    sql=sql
)
```

<img width="626" alt="Screenshot 2021-07-20 at 12 36 53" src="https://user-images.githubusercontent.com/967119/126317609-c2fdc504-1341-4181-bb56-123f5b1c0c06.png">

**Comment by kaxil** [comment]
In that case what Jarek is proposing sounds reasonable to me

**Comment by potiuk** [comment]
Seems like other users also would like exactly this @nathadfield - see #17082

**Comment by mehmax** [comment]
Hi all, jut joining the conversation from another discussion. 
How about updating views.py so that it will show dicts and lists not as a whole, but with individual items:

Proof of concept:
views.py:
-> in this example, empty dicts and lists are not rendered
```
            if renderer in renderers:
                if isinstance(content, dict):
                    for key, value in content.items():
                        html_dict['.'.join([template_field, key])] = renderers[renderer](value)
                elif isinstance(content, list):
                    for index, value in enumerate(content):
                        html_dict['.'.join([template_field, index])] = renderers[renderer](content)
                else:
                    html_dict[template_field] = renderers[renderer](content)
```

this is the screenshot from before:
![image](https://user-images.githubusercontent.com/84371809/126745292-ade0e36e-60a2-4d8a-99e9-927483e52726.png)


after coding change:

![image](https://user-images.githubusercontent.com/84371809/126744743-7e90e124-93b6-41c6-8556-45cff30b36b3.png)

**Comment by potiuk** [comment]
> How about updating views.py so that it will show dicts and lists not as a whole, but with individual items:

I like this a lot. It's much simpler than the "jsonpath" solution and it will work out-of-the-box for most operators. This could also be enhanced a bit - if for example the name of the field (including whole path) after unfurling the dictionary, matches the "rendered_field" entry - we could use the right renderer and get syntax coloring as well.

In the BigQuery case 
```
template_fields_renderers = {"configuration.query.qyery": "sql"}
```

would lead to nice sql coloring:

```
configuration={"query": {"query": sql.strip(),
                                 "useLegacySql": False}
                       }
```

**Comment by nathadfield** [comment]
Thanks @potiuk! Have been looking at this at times today and I'm definitely making some progress although it depends on whether @mehmax beats me to it!

<img width="1564" alt="Screenshot 2021-07-23 at 16 48 20" src="https://user-images.githubusercontent.com/967119/126807940-f3ecad36-3f9e-4844-8505-9b292ed5a86b.png">

**Comment by kaxil** [comment]
Nice, let's race @mehmax  @nathadfield

**Comment by nathadfield** [comment]
Should have a PR for this tomorrow.

**Comment by mehmax** [comment]
Hi, I added a PR for this. Lets discuss: 
https://github.com/apache/airflow/pull/17239
#17239

**Comment by nathadfield** [comment]
@potiuk PR has now been raised. #17252 

@mehmax It looks like our aims are a little different.  I am trying to provide the capability for individual elements of a dict to be specified in an operator with an appropriate renderer rather then extracting every key:value.
