### ISSUE TITLE
Resource usage in Airflow monitor metrix

### ISSUE THREAD

**Issue by surapuramakhil** [apache/airflow#17104]
**Description**

Airflow, as a task / workflow management tool, states execution times at task and dag level. But it lacks resource usage information.

Like memory / Network / CPU usage, its max values at task level and DAG level

**Use case / motivation**

**Are you willing to submit a PR?**

**Related Issues**

**Comment by andormarkus** [comment]
Hi @surapuramakhil 

 - Kubernetes executor: these metrics are available on task level through Prometheus or your property monitoring provider
 - Celery executor: as I know, celery does not expose these metrics for each task.

**Comment by potiuk** [comment]
Resource monitoring is not really part of airflow -it's outside of the domain of Airflow. You could bring that under discussion at the devlist if you want to ask for opinion of the community https://airflow.apache.org/community/ but this is whole new big feature that would drag the focus of Airflow from being great at "scheduling" and not "resource management"

As mentioned by @andormarkus K8S provides good information already. Regarding the Celery, it makes no sense to have "per task" metrics, because Celery reuses running workers to run multiple tasks and they share resources, you can have all the insights you want into running Celery via Flower (when you use the Official Helm Chart from the Airflow community, flower is automatically enabled when you run Celery or CeleryKubernetesExecutor) - see https://airflow.apache.org/docs/helm-chart/stable/index.html

For now this one is "close/won't do" - but again, if you have good arguments you can start thread at the devlist.

**Comment by ganbaaelmer** [comment]
i also need to know resource metric in apache airflow web
