### ISSUE TITLE
Operators for orchestrating EMR EKS Jobs

### ISSUE THREAD

**Issue by wanderijames** [apache/airflow#17175]
**Description**

[EMR in EKS](https://aws.amazon.com/emr/features/eks/) is a new feature by AWS. For teams that heavily uses EKS for their workloads, it would make sense to submit Jobs (Spark Jobs) via [EMR Containers](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr-containers.html) and leverage execution with EKS.
This issue is request to add operators that would enable starting jobs in EMR EKS.

**Use case / motivation**

Enable EMR jobs on EKS orchestration through Airflow. This would enable airflow users to create dags that submit jobs to EMR that needs to use EKS for execution power.

**Are you willing to submit a PR?**

I have already created the operators and hooks to enable this. PR is on its way.

**Related Issues**

N/A

**Comment by mik-laj** [comment]
We currently have one operator that allows us to run Spark job on Kubernetes. It works with both EKS and GCP as well as any other Kubernetes platform. - [SparkKubernetesOperator](https://github.com/apache/airflow/blob/d72b363929c86eb03fc9583002459bd10bc7eaeb/airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py#L24). Why would anyone use this operator instead of the provided operator instead of the generic operator for Kubernetes?

**Comment by ferruzzi** [comment]
Is this still active or is it covered by https://github.com/apache/airflow/pull/16766 ?
