### ISSUE TITLE
Airflow dependencies not working in 1.10.15

### ISSUE THREAD

**Issue by sabarisan11** [apache/airflow#17254]
Hi Everyone,

We are trying to migrate our code from Airflow version **1.10.5** to **1.10.15** (bridge version) and having plans to use Airflow 2.0. But post migrating our code into 1.10.15 we are facing some dependency issues where the same code works fine in 1.10.5.

When looked further, we identified that upstream and downstream functions with parameter is causing the issue. we tried modifying it with >> & << and that works. We have around 100 DAG in our system and it would be a huge task to modify all 100 DAG and test those. we also have some interdependencies like Task A is upstream to 3 tasks & also serves as downstream to 5 other tasks. In such cases it would be really difficult to go for some automated way to modify our code

**Airflow Hanging Dependencies in 1.10.15**
![image](https://user-images.githubusercontent.com/88023717/127125837-aa5635ad-ad42-4b76-a6b8-cfea9a5e3156.png)

In graph view, dependencies appear like they are not properly connected but are actually connected. If I check the task instance details in this, upstream and downstream are set properly but it doesn't appear as expected

**Same Code works in Airflow 1.10.5**
![image (1)](https://user-images.githubusercontent.com/88023717/127125832-b0a103f1-b28d-48d1-93ff-db6c67961f95.png)

where the same code works properly and dependencies shows up in 1.10.5 version

**Sample Code snippet**
![image (2)](https://user-images.githubusercontent.com/88023717/127125824-8450c138-349f-483d-8b66-6deb46313151.png)

Code block that has function parameters, here if the dependencies is between the operator it works fine, but when we brought python function which returns operator that is working well for past 2 years in Airflow version 1.10.5 but shows up this graph dependency issues in new version

Kindly take a look at this and provide some advice on how to proceed further

**Comment by potiuk** [comment]
The 1.10 version of Airflow reached and of life as of June 17 2020 and it will not receive any more fixes (even critical ones). This looks like some If the code does not work in 1.10.15, it is highly unlikely it is going to work in Airflow 2 (which we encourage everyone to use). I am afraid fixing your DAGs to work with 1.10.15 is the only way to proceed. Since you already know it works, I think this is the only way you can proceed. 

Since we are not going to do anything with the issue, I am closing this one - feel free to copy it  to a Github discussion instead if you have hopes that you will find someone with similar issue and a fix.
