### ISSUE TITLE
Dag Serialization Speed is so slow

### ISSUE THREAD

**Issue by yansfil** [apache/airflow#17372]
**Apache Airflow version**:
2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.20

**Environment**:
gke

**What happened**:
when first initializing airflow project in 2.1.0, the time to complete serialization of dags is too slow.
it takes 30 minutes to complete serialize all dags (600 dags in my project). because of it, I should wait to execute all dags  at the first time. 
dag parsing process of airflow v1 is more faster because of no loading serialization dags to database. How can I make it more faster? 

**What you expected to happen**:
make dag serialization process more faster than now

**How to reproduce it**:
I assigned schedeuler resources, 1g for cpu and 1g for memory. 
and I configured airflow.cfg like below

AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL: "5"
AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL: "5"
AIRFLOW__SCHEDULER__PARSING_PROCESSES: "8"
AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "0" 
AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "10"

**Comment by potiuk** [comment]
This problem is already solved. You should run multiple schedulers.

One of the reasons Airflow HA scheduling is implemented is to allow scaling of serialization part. You can read more about HA scheduler, how it works and it's scalability characteristics in this blog post from Astronomer,

https://www.astronomer.io/blog/airflow-2-scheduler#:~:text=As%20part%20of%20Apache%20Airflow,once%20their%20dependencies%20are%20met.

Please try the same with multiple schedulers and let us know your experience.
