### ISSUE TITLE
Bug in the logic of Celery executor for checking stalled adopted tasks?

### ISSUE THREAD

**Issue by kosteev** [apache/airflow#17381]
**Apache Airflow version**: 2.1.1

**What happened**:

`_check_for_stalled_adopted_tasks` method breaks on first item which satisfies condition
https://github.com/apache/airflow/blob/2.1.1/airflow/executors/celery_executor.py#L353

From the comment/logic, it looks like the idea is to optimize this piece of code, however it is not seen that `self.adopted_task_timeouts` object maintains entries sorted by timestamp. This results in unstable behaviour of scheduler, which means it sometimes may not resend tasks to Celery (due to skipping them).

Confirmed with Airflow 2.1.1

**What you expected to happen**:

Deterministic behaviour of scheduler in this case

**How to reproduce it**:

These are steps to reproduce adoption of tasks. To reproduce unstable behaviour, you may need to do trigger some additional DAGs in the process.

- set [core]parallelism to 30
- trigger DAG with concurrency==100 and 30 tasks, each is running for 30 minutes (e.g. sleep 1800)
- 18 of them will be running, others will be in queued state
- restart scheduler
- observe "Adopted tasks were still pending after 0:10:00, assuming they never made it to celery and clearing:"
- tasks will be failed and marked as "up for retry"

The important thing is that scheduler has to restart once tasks get to the queue, so that it will adopt queued tasks.

**Comment by potiuk** [comment]
CC: @ephraimbuddy - maybe somethig worth looking at for 2.2 Seems like quite easy to reproduce.

**Comment by ephraimbuddy** [comment]
This is also another way to trigger the log: `Executor reports task instance <TaskInstance: datalake_db_cdc_data_integrity.check_integrity_core_prod_my_industries 2021-06-14 00:00:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None) Was the task killed externally?` which currently sets the tasks to failed state instead of up-for-retry if the task has retries. 

It seems that this message is too generous, probably need a way to know which event triggered it and determine how to react?
cc: @ashb
