### ISSUE TITLE
WARNING - Recorded pid 4969 does not match the current pid 4969

### ISSUE THREAD

**Issue by terryfugit** [apache/airflow#17394]
**Apache Airflow version**: 2.1.2

**What happened**:
Receive warning message "WARNING - Recorded pid 4969 does not match the current pid 4969", then the "INFO - Sending Signals.SIGTERM to GPID 23307" message terminating our task.

We see other reported issues where the PID numbers in the message are different, but ours are always the same, not always the same number but recorded=current.

Works fine 90% or the time.  This seems intermittent since upgrade to 2.1.2

**What you expected to happen**:  expected to finish as normal

**Comment by jedcunningham** [comment]
Likely related to `run_as_user`:
https://github.com/apache/airflow/blob/4dae4ec9a4148db6c32f15ccc122d42c93a2c58a/airflow/jobs/local_task_job.py#L198-L199

Do you have that set in your DAG or [default_impersonation](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#default-impersonation) set?

**Comment by nmehraein** [comment]
Can also be same problem as https://github.com/apache/airflow/pull/17333

**Comment by terryfugit** [comment]
But our PID is the same.  Always the same.  We don't understand why we would get it in this instance.

#17411 seems like a candidate.  Looking through logs it seems as though we get it after the heartbeat time has lapsed.  That doesn't, however, provide us an ideas on why we would get it in that case anyway since our PID is the same, nor an options for addressing the issue.

**Comment by ephraimbuddy** [comment]
> But our PID is the same. Always the same. We don't understand why we would get it in this instance.
> 
> #17411 seems like a candidate. Looking through logs it seems as though we get it after the heartbeat time has lapsed. That doesn't, however, provide us an ideas on why we would get it in that case anyway since our PID is the same, nor an options for addressing the issue.

Are you using impersonation as @jedcunningham asked above? You can also explain to us how we could reproduce this, e.g how long the dag takes to run, and also provide a simple dag if possible.

**Comment by terryfugit** [comment]
@ephraimbuddy We are going to apply this fix to see if it addresses the issue.
https://github.com/apache/airflow/pull/17333/commits/428cc76cc589efb73751bea6e925e8fa28bfe812

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy We are going to apply this fix to see if it addresses the issue.
> [428cc76](https://github.com/apache/airflow/commit/428cc76cc589efb73751bea6e925e8fa28bfe812)

Ok. Let us know if it resolved it

**Comment by terryfugit** [comment]
The reported code fis above did not resolve the issue.  However, back to the note from @jedcunningham , we removed the run_as_user= from the DAGs and have not seen the issue since.

**Comment by taizilongxu** [comment]
The same issue in Version: v2.6.1
remove run_as_user looks like OK

**Comment by potiuk** [comment]
> The same issue in Version: v2.6.1 remove run_as_user looks like OK

Hey @taizilongxu 

Is this possible to create another  (related) issue with 2.6.1 and all the details (describing your run_as_user approach, what kind of users you had, what were the permissions of the users and what you tried to achieve with run_as_user. Logs from those failed operations would be super useful as well @taizilongxu. Not haveing that information does not make us any closer to diagnosing and solving the problem. Seems that the root cause for this one ("suspected") has been fixed. But maybe there is another, similar problem that has similar log but triggered by a different condition.

We will never know until you help us by providing some evidences that might help us to diagnose the issue and having you as author might make it easier for us to ask you any questions specific to your case that can help us to diagnose the problem. 

Since we are open-source and volunteers - we need to rely in our investigations on whatever our users can provide as evidences of what happens, that's why we are asking them to provide all the information possible. Especially in your case if you have "run_as user" and disabling it helps, the issue is already quite narrowed down, so w just need to have more logs.
