### ISSUE TITLE
Clicking the "Update" button in the "Tree View" of the DAG deletes the DAG runs from UI

### ISSUE THREAD

**Issue by mongakshay** [apache/airflow#17413]
When clicking the "Update" button in the "Tree View" of a DAG ID, I notice that the below listed DAG runs get cleared on every click, and if I keep clicking, it first clears all the runs, and continued clicking brings them back.

**Comment by bbovenzi** [comment]
@mongakshay Could you provide more details?
- What version of Airflow are you using?
- Which button are you pressing? The refresh button in the graph below or the one that sits with the Run and Delete buttons?

**Comment by bbovenzi** [comment]
Nevermind, I have now replicated the issue.

**Comment by bbovenzi** [comment]
Ignore the 10 vs 1 second thing. That is just a coincidence with the DAG runs I was testing on.

They mostly appear to be off-by-one errors of the date provided to the dropdown. We should to make sure to round the second up instead of down.

I don't know yet where the 3 second difference in the screenshot is coming from though...

**Comment by johnson-jay-l** [comment]
I reproduced the issue with the following steps:

1. Go to any dag and click the "update" button next to the "runs" drop-down, with or without changing the value in the drop-down. 
2. Go to the "graph view" and them back to the "tree view"
3. The URL now has the base_date hardcoded.  When the next dagrun starts it will be hidden because of the base_date hardcoding in the url, and the previous dagrun will appear as if it's the current dagrun.

**Comment by bbovenzi** [comment]
We've completely changed this page since this issue was reported. We don't even have an "Update" button anymore.
