### ISSUE TITLE
Scan the DAGs directory for new files througth restfull API

### ISSUE THREAD

**Issue by fuguixing** [apache/airflow#17429]
**Description**

Scan the DAGs directory for new files througth restfull API

**Use case / motivation**

In my case, the app will automatically create dag files through python. After the app dynamically created a dag, I hope that the dag will be available immediately, but currently, I need to wait for the schedule to scan this file(dag_dir_list_interval = 300). Can I add a restful API to scan new dag files actively and make this dag available?

**Are you willing to submit a PR?**

Yes, I am willing to contribute the code of this feature to the community. Thank you for your approval!

**Related Issues**

No

**Comment by mik-laj** [comment]
This can be problematic as the webserver is stateless and does not have access to the DAG files.

**Comment by mik-laj** [comment]
Related PR: https://github.com/apache/airflow/issues/17437

**Comment by fuguixing** [comment]
Thanks for your reply!
In our env, I need to make the new specified DAG available immediately without waiting for Airflow call **_refresh_dag_dir**(in the dag_processing.py), if **dag_dir_list_interval** is too small, which may cause a waste of resources. I tried the following code, which can load the new specified DAG to the database and make it available immediately, and it uses **DagFileProcessor** in the scheduler_job.py. Can I encapsulate it as a restful API?

heartbeat()  in the dag_processing.py
`processor = self._processor_factory(file_path, self._zombies)`
`processor.start()`

**Comment by mik-laj** [comment]
Webserver is stateless, so it don't have access to DAG File.. Webserver can't load Dagfileprocessor.

**Comment by fuguixing** [comment]
OK, thanks. Let me think about it again

**Comment by eladkal** [comment]
Closing for the moment. If needed we can reopen.

**Comment by sankshit** [comment]
@eladkal Any updates on this? Is the REST API for detect changes coming anytime soon?

In our usecase, we have dynamic DAG(s) that the user can generate. If the user changes anything in the DAG file and triggers the DAG, many times, the old DAG version gets triggered( i.e Airflow has not detected the changes made to the file yet). Any idea on how to tell airflow to scan the DAG file for new changes before triggering it?

**Comment by potiuk** [comment]
> @eladkal Any updates on this? Is the REST API for detect changes coming anytime soon?

It will come when someone implements it. This is open-source and there is no way to answer that question authoritatively. But there is one way to make sure it's coming - if you or your company contributes it and creates a PR, or maybe fund work of somone who will do it. This is a certain way to make it happen. And you are absolutely welcome to do it. You seem to run buisness on top of Airflow so contributing back to get the feature you need seems like a good idea I think. Otherwise you need to wait until someone who has similar need will add it. But it might mean you will wait for a long time.\

> Any idea on how to tell airflow to scan the DAG file for new changes before triggering it?

No way currently. But you can add some markers to your DAG files (date, version etc.) and make an API call to check if the marker is present in the serialized form of the DAG. This is an easy (albeit somewhat active loop) to check if your latest change has been already processed by DAG File processor.

**Comment by potiuk** [comment]
Another option is to just use "last_parsed_date" when you want to make sure that whatever has been updated in the DAGs folder have already been parsed see https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag
