### ISSUE TITLE
Feature Request: Provide a next run field in the DAG details page

### ISSUE THREAD

**Issue by amommendes** [apache/airflow#17478]
**Description**
Provide a next run field in the DAG details page for scheduled dags

**Use case / motivation**
Schedules can be trick to get at a first glance (since it related to `start_date` and `schedule_interval`). We could help users to easily see when the DAG will run next time

**Are you willing to submit a PR?**

Maybe 😁

**Comment by raphaelauv** [comment]
duplicate -> https://github.com/apache/airflow/pull/2460

**Comment by uranusjr** [comment]
With AIP-39, we need to kind of distinguish which one you actually wan

1. the (approximated) next time this DAG will run
2. the `execution_date` of that approximated next DAG run
3. the end of the *current* DAG run’s data interval

The three are almost always the same with Airflow 2.1 (and everything below), but have very different semantic meanings after custom timetable scheduling is made possible by AIP-39.

**Comment by bbovenzi** [comment]
Last run is the `execution_date` right? So next run should be option 2, right?

**Comment by uranusjr** [comment]
If we want to show info on the next run, yes it should be option 2. But the question is _why_ you want to know when’s the next run’s `execution_date`. The reason given in #2460 was:

> The scheduler's DAG run creation logic can be tricky and one is easily confused with the `start_date + interval`
and period end scheduling way of thinking.

Which implies the reporter does not actually care about the next run, but only wants to show that field because the next run’s `execution_date` is also the end of _this_ run’s data period. I don’t know whether it’s the intention behind this issue or not, so we should first figure that before deciding what to add.

**Comment by ecerulm** [comment]
I don't know what the OP wants, but I personally ended here because I wanted to know 1 (the (approximated) next time this DAG will run)

**Comment by bbovenzi** [comment]
Next run now appears on all dag pages with #17732
