### ISSUE TITLE
Helm chart converts ' ' to '+' in passwords (and username)

### ISSUE THREAD

**Issue by EliMor** [apache/airflow#17489]
**Apache Airflow version**: 2.1.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.19

**What happened**:

When using the helm chart with postgres or redis passwords/username that have a ' ', the chart will convert the space to a '+' ~~due to the helm urlJoin function~~ (See below for details)

**What you expected to happen**:
~~Passwords provided should not be modified by code.~~ 
(Correction: Username & Pass should be properly encoded in the kube Secret)

**How to reproduce it**: write a dummy password in the values.yaml file that has a ' ' and see what the secret that gets generated looks like. You will see a '+' replaced. 

**Anything else we need to know**: 
~~Location of error;~~
~~https://github.com/apache/airflow/blob/main/chart/templates/secrets/metadata-connection-secret.yaml#L44~~
~~https://github.com/apache/airflow/blob/main/chart/templates/secrets/redis-secrets.yaml#L77~~
(Please see below for a better example and correct cause.)

**Comment by mik-laj** [comment]
Space is a character not allowed in the URI, so it should be percent-encoded. We used to have errors with the handling of special characters in passwords.
https://github.com/apache/airflow/issues/16000
Why do you think this character shouldn't be converted?

**Comment by potiuk** [comment]
Yeah @mik-laj is right. You can also see examples of that explained in our documentation - https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#handling-of-special-characters-in-connection-params according to https://datatracker.ietf.org/doc/html/rfc3986 both pasword and user should be percent-encoded. 

However I am a bit surprised to see '+' in your issue rather than %20 (which should be used in this case). 

The '+' replacing ' ' is part of another specification https://datatracker.ietf.org/doc/html/rfc1866 - there space might be replaced by '+' only in the context of form fields or form values - strictly when the HTML data is encoded with `application/x-www-form-urlencoded`  - which sounds as completely different case and should never be used in URI's (though from what I know a lot of URI parsers will happily accept + as 'space' in other places, but this is rather a side-effect not specification-conformance.

Could you please @EliMor provide us examples of such secrets generated (with some bogus passwords?) was it part of the URI or form? Or some other secret content?

**Comment by EliMor** [comment]
Hi people! 

I thought it was strange that it was encoded as '+' as well!! 

Here's a more clear example...

If I have in my values.yaml file:
```
  metadataConnection:
    user: airflow
    pass: top secret password
    protocol: postgresql
    host: fakedb.us-west-2.rds.amazonaws.com
    port: 5432
    db: postgres
    sslmode: disable
```

Here's how we get rendered in the Secret
```
postgresql://airflow:top+secret+password@fakedb.us-west-2.rds.amazonaws.com:5432/postgres?sslmode=disable
```

This will result in a connection error unless I manually update the secret to:
```
postgresql://airflow:top secret password@fakedb.us-west-2.rds.amazonaws.com:5432/postgres?sslmode=disable
```

Strange no?! 

No big on my end to just not have spaces. :D

**Comment by potiuk** [comment]
Actually it should work (and is the only correct way!!!) if you replace it with:

```
postgresql://airflow:top%20secret%20password@fakedb.us-west-2.rds.amazonaws.com:5432/postgres?sslmode=disable
```

Neither ' '  nor '+'  is  correct.

**Comment by potiuk** [comment]
@jedcunningham @kaxil -> I think this one is pretty legit, if ' ' is encoded as '+' in the URI, this is pretty wrong, possibly we could use different encoding function in the chart

**Comment by potiuk** [comment]
@jedcunningham @kaxil : from what I can see (and what seems to be confirmed by https://github.com/pallets/jinja/issues/17 - it seems that the "urlquery" filter we use is wrong.  It should be more complex. The problem is that urlquery replaces ' ' with '+' (and / with %2F) but 'urlencode` replaces " " with %20 but it does not replace "/" with %2F. I looked it up and seems that however strange it is, it is how it is. Unfortunately both user and password require STRICT percent-encoding.

Seems that for Jinja, this is the only right way we can do it::

```
{{ value|urlencode|replace("/", "%2f") }}
```

**Comment by EliMor** [comment]
Apologies for my bad assumption! 

That's annoying!

**Comment by EliMor** [comment]
So... 
Some questions I had lingering in my head, no response expected on my end. Please keep in mind I'm very naive/lacking any context and there are extra implicit assumptions here but...

- **Whats the rationale for constructing and encoding the URL to be saved and putting it in the Secret?** This is as opposed to plopping the secret as provided by the user in the values.yaml and then building and encoding the URL inside the containers using some standard encoding & url construction strategy. Is it because this seemed like wasted work done on every pod reboot?
- **Do we think that a preconnect check should happen in the migration pod?** I thought it was strange that it passed just fine and I didn't see connection errors until we were to the worker-pods this is why I initially assumed that some extra funky encoding was happening again behind the scenes and why using spaces raw seemed to work. I also thought it was strange that I did not see any of the other pods in a crashloop as well. Please correct me if I'm wrong about this.

Cheers.

**Comment by potiuk** [comment]
> * **Whats the rationale for constructing and encoding the URL to be saved and putting it in the Secret?** This is as opposed to plopping the secret as provided by the user in the values.yaml and then building and encoding the URL inside the containers using some standard encoding & url construction strategy. Is it because this seemed like wasted work done on every pod reboot?

Because Airflow takes URL as parameter and it's standard way for airflow (and airflow does it because this is the way how sqlalchemy does it) on one hand, or because it makes a unified way of passing not only the host/user/password/ but also extra parameters. If we want to construct the URL from secrets to Airflow, we would need some extra code to do that on the flight, rather than mapping the secret. In Airflow you simply "speak" URL when it comes to connections. You have to remember that Helm Chart and K8S are one of several ways Airflow can be deployed and in our choice we are airflow-centric not K8S centric. We feel that it's K8S that should bend to airflow ways, not the other way. You can see more at our talk from this year's summit: https://airflowsummit.org/sessions/2021/airflow-loves-kubernetes/

> Do we think that a preconnect check should happen in the migration pod? I thought it was strange that it passed just fine and I didn't see connection errors until we were to the worker-pods this is why I initially assumed that some extra funky encoding was happening again behind the scenes and why using spaces raw seemed to work. I also thought it was strange that I did not see any of the other pods in a crashloop as well. Please correct me if I'm wrong about this.

Of course it should. And maybe you discovered an issue there. Maybe you can track it down and provide a PR fixing that? That would be fantastic contribution back that would "pave the way" for others who have similar problem. Airflow is built by community and it's super helpful if users who get it for free are contributing back those kind of things.

**Comment by EliMor** [comment]
Thanks for the extra context. 
I admit I most likely would have the impulse to want to build some bridge between 'the airflow way' things happen and what I assume is an intuitive way to engage with the helm chart. I realize 'intuitive' is subjective though. 
... Maybe forcing the user to construct the string in the values.yaml/their own Secret, for example. Apologies if this is trodden terrain. 

Of course I'd love to contribute back, I'll test it out and give that PR a go.

**Comment by potiuk** [comment]
> ... Maybe forcing the user to construct the string in the values.yaml/their own Secret, for example. Apologies if this is trodden terrain.

This is already possible for SQLalchemy connection if you want. https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html#setting-configuration-options (see the _cmd option). You can write and execute your "glue" as a script (in python/bash or any other that is supported by your image)

**Comment by EliMor** [comment]
So, in your opinion, do you think simply explicitly enforcing ```AIRFLOW__CORE*``` as env variables OR providing an "airflow.cfg" as a Secret in the helm chart should be the ONLY way to do things?

**Comment by potiuk** [comment]
> So, in your opinion, do you think simply explicitly enforcing `AIRFLOW__CORE*` as env variables OR providing an "airflow.cfg" as a Secret in the helm chart should be the ONLY way to do things?

Strange statement. I do not understand what you are trying to ask and for what purpose. I simply do not understand what you are asking about? Could you elaborate and explain what you mean by "the ONLY way to do things?" - this is so general that I am not sure what you are asking about.

**Comment by EliMor** [comment]
Apologies. I'm a strange person and I struggle to communicate clearly at times.
This is what I am asking.

Is it correct that there are currently several ways of providing, in our case, the db connection details;

```
  metadataConnection:
    user: airflow
    pass: top secret password
    protocol: postgresql
    host: fakedb.us-west-2.rds.amazonaws.com
    port: 5432
    db: postgres
    sslmode: disable
```
And
```
extraEnv: AIRFLOW__CORE__SQL_ALCHEMY_CONN* 
```
And
mounting ```airflow.cfg``` from a secret or (configmap?) directly

If the above are true and if the argument is that the use of the helm chart should be 'intuitively' or 'naturally' the way Airflow does things (I'm extrapolating from your statement that kube should bend to Airflow), then it seems that the chart should be structured to look as close to Airflow directly as possible.
Ie. perhaps instead of a 'metadataConnection,' etc., there should just be an area that engages with this behavior:

 
> The universal order of precedence for all configuration options is as follows:
> set as an environment variable (AIRFLOW__CORE__SQL_ALCHEMY_CONN)
> set as a command environment variable (AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD)
> set as a secret environment variable (AIRFLOW__CORE__SQL_ALCHEMY_CONN_SECRET)
> set in airflow.cfg
> command in airflow.cfg
> secret key in airflow.cfg
> Airflow’s built in defaults

Please let me know if I'm making more bad assumptions here.

**Comment by potiuk** [comment]
> If the above are true and if the argument is that the use of the helm chart should be 'intuitively' or 'naturally' the way Airflow does things (I'm extrapolating from your statement that kube should bend to Airflow), then it seems that the chart should be structured to look as close to Airflow directly as possible.

You are extrapolating a bit more than what I wrote. Your assumptions do not take into account the audiences. I never said "human" providing the URL. I said "Secret" providing URL to Airflow. There is one more step between Human entering configuration and Secret Keeping it. The reason why you have it in helm chart, is because the Helm chart is for "Humans" to configure, while the "Secrets" is for "airflow" to consume. and for "Kunernetes" to store.  

What the helm chart does - It takes "user" input and converts it (on the flight) to "URL" format that is stored in "Secret" if you look under the hood. I cannot imagine "human" by hand providing "Secret". This is established practice in K8S that you prepare Kubernetes Resources (including secrets) via some kind of templating engine (usually Go-templating based) to make it easier for  "Human" to provide the right values. This is what Helm Chart is doing and it provides the right filters to convert the values.

Similarly in Airflow we provide a tool: https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#generating-a-connection-uri which allows Human to generate the URI to use by providing all the values separately.

Same princilple. pretty consistently applied across the board.

**Comment by EliMor** [comment]
Thank you for your time and patience to help me understand a little more.

Cheers.

**Comment by potiuk** [comment]
assigned
