### ISSUE TITLE
[BUG] Helm chart does not correctly support sslmode for PostgreSQL connection

### ISSUE THREAD

**Issue by timothyclarke** [apache/airflow#17574]
**Apache Airflow version**: 2.12

**Apache Airflow Provider versions** : not applicable - none / standard / unknown (delete as applicable).  I am installing the helm chart from this repo with very little customization

**Kubernetes version (if you are using kubernetes)** : not applicable - 1.20

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): linux
- **Kernel** (e.g. `uname -a`): not applicable - unknown 
- **Install tools**: helm
- **Others**:

**What happened**:

I am attempting to install airflow into a kubernetes cluster with a secure connection to the database

I am using the provided helm chart and my install command is
```
helm upgrade airflow airflow \
  --repo https://airflow.apache.org \
  --version 1.1.0 \
  --history-max 2 \
  --namespace airflow \
  --values helm/apache-airflow.overrides.yaml \
  --timeout 15m \
  --install
```
The pertinent part of `apache-airflow.overrides.yaml` contains
```
data:
  metadataConnection:
    sslmode: verify-full
```
I am using an AWS RDS instance and so the CA certs SHOULD be in the OS by default. If they are not then they are available in [the AWS RDS PKI truststore](https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem). 

Telling people to build a custom docker container to add ssl certs is not a realistic solution. 

**Errors** :
When installing for the first time the migrations job runs and generates the following error

```
[2021-08-12 09:30:42,956] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) root certificate file "/home/airflow/.postgresql/root.crt" does not exist
Either provide the file or change sslmode to disable server certificate verification.
```
```
psycopg2.OperationalError: root certificate file "/home/airflow/.postgresql/root.crt" does not exist
Either provide the file or change sslmode to disable server certificate verification.
```

**What you expected to happen**:

I expect the all sslmodes to be supported (or to be removed from the chart). If a custom or self signed SSL cert is needed then there should be an option to provide it to the chart

**How to reproduce it**:

1. Create an external database. 
2. When installing the chart provide database details with `.data.metadataConnection.*` ensure that .data.metadataConnection.sslmode` is set to a valid enabled state.

**Anything else we need to know**:

How often does this problem occur? whenever sslmode is enabled

**Comment by potiuk** [comment]
This is postgres' requirement, not airflow's (And for a very good reason). Postgres will never read from the certificate chain installed in the system for a very good reason. What postgres does during verification is to not verify if the service is signed with "a" certificate authority, but whether it is signed with "THE" certificate authorities that are specifically configured as "OK" when you configure the connectivity.

From https://www.postgresql.org/docs/9.1/libpq-ssl.html

> To allow server certificate verification, the certificate(s) of one or more trusted CAs must be placed in the file ~/.postgresql/root.crt in the user's home directory. (On Microsoft Windows the file is named %APPDATA%\postgresql\root.crt.)

You could map the certificates to the home directory via additional secrets mapping, however I recommend to follow the "recommended" way of configuring SSL using PGBouncer's configuration (that's why we have no easy option to do it in the chart).

 Configuring "direct" postgres connectivity is a bad idea. Airflow opens a number of connection to database and it is recommended (also default in the Official Helm Chart) that PGBouncer is used to provide proxy/pool functionality for  Postgres connections. This is fully supported by the Official Helm Chart, it's proven and working for a lot of huge production installation (and you get yourself into trouble of too many open connections if you try to connect directly to postgres and you have many tasks running). 

The SSL configuration of PGBouncer is fully supported by Helm Chart - https://airflow.apache.org/docs/helm-chart/stable/parameters-ref.html#pgbouncer and you should use that. Under the hood it works in the way that internally airflow talks to pgbouncer without SSL (this is on internal Kubernetes network and only Airflow Pods can talk to each other via this port) and then PGBouncer talks to the external DB using SSL. It's robust, secure, proven and tested.
