### ISSUE TITLE
Scheduler is not working

### ISSUE THREAD

**Issue by vengi57** [apache/airflow#17602]
The scheduler does not appear to be running. Last heartbeat was received 2 days ago.  The DAGs list may not update, and new tasks will not be scheduled.

Scheduler service is up and running due to unhealthy it cant able to execute any dag runs

![Screenshot from 2021-08-12 16-52-57](https://user-images.githubusercontent.com/32476102/129341623-fecbc039-7ca8-4700-a1f5-efd0421a1065.png)
![Screenshot from 2021-08-12 16-51-09](https://user-images.githubusercontent.com/32476102/129341676-6bb593b3-5eab-46b5-86fa-367f1d17df83.png)

**Comment by potiuk** [comment]
The information you provided are not nearly enough to help you. My wild guess is that you are using Sequential Executor and SQlite with indeed will work this way and make scheduler unhealthy. You should never use it beyond testing if that's the case.

Closing it for now until you provide some more details (in case you are not using the Sequential Executor).

**Comment by vengi57** [comment]
I was using executor ad LocalExecutor and Postgres as database which modified on airflow.cfg
I was triggering multiple dags one after the other and each dag is a little heavy it will take around 4 to 5 hrs to complete each. In-between scheduler got stuck and I am getting warning messages as "The scheduler does not appear to be running. The last heartbeat was received 2 days ago. The DAGs list may not update, and new tasks will not be scheduled." 
So that my next dag get stuck and task on the dag was on in-progress state and cant go further

**Comment by vengi57** [comment]
I have cross-checked whether the scheduler is running or not but it was running on the background
![Screenshot from 2021-08-12 16-58-26](https://user-images.githubusercontent.com/32476102/129389515-2bf87d37-b5d2-42d8-bde4-b0e5bc9e5974.png)

**Comment by potiuk** [comment]
I'd recommend you to restart the scheduler and see if it is really "stuck" - the fact that the process is running does not mean that it's "working" - there are many ways things can go wrong.

Have you checked your logs? did you make any investigation what happened?  Without any of that, we are not able to help - you need to provide us enough information (and show that you have done investigation). Actually I recommend you to fill-in the template of the issue when you raise the bug (it has all the information on what you need to provide in order to be able to investigate any problems). Can you please gather that information  and open a new bug, actually filling all the information, logs and results of your investigation. We are not able to help otherwise - only you have access to your system, only you know how it is configured, only you have access to logs and can investigate it . Only when we see some results of your investigation and when there is an indication that there is a bug in airflow (with reproduction path) we can try to help here.
