### ISSUE TITLE
Support git sync from multiple repositories

### ISSUE THREAD

**Issue by nareshurs** [apache/airflow#17661]
**Description**

Git sync feature with multiple git repositories

**Use case / motivation**

We have a use case where multiple tenants create DAGs and they dont work with common git repository. Its a security issue if we share one customer info with other

**What do you want to happen?**

Airflow should support git-sync of DAG's from multiple git repositories

**Are you willing to submit a PR?**

No

**Related Issues**
No

**Comment by EliMor** [comment]
seems related to: https://github.com/apache/airflow/issues/11708

**Comment by potiuk** [comment]
@nareshurs @Bash- @EliMor - could you please comment on that 'submodule' ? I am asking because i am not a fan of 'we could do it because.we can' but more of a fan of 'use what's already available' so i am tempted to 'implement' that one by describing how you can use submodules to achieve what you want rather than support multiple repos.

I believe it has all you need for that (and even more because it centralizes management of multiple versions of different repos and keeps chart configuration simpler. 

I would love to hear if submodule approach works for you and if not -  WHY it would not work ?

**Comment by potiuk** [comment]
Here is a nice video showing how Jagex has done it with submodules: https://youtu.be/a-4yRne3ba4 - I would still love to hear if this is something that prevents you from doing this @Bash- @EliMor ?
