### ISSUE TITLE
Support set logging level in Dag or Task layer

### ISSUE THREAD

**Issue by blackmidnight** [apache/airflow#17754]
**Description**
Currently, airflow support to set logging level in airflow.cfg or by setting environment variable. But this setting will apply on all dags, and can not modify logging level for specific dag or task. 

**Use case / motivation**
I want to ask if it's possible to provide parameter setting logging level in Dag or BaseOperator.

**Are you willing to submit a PR?**
Yes

**Related Issues**
None

**Comment by potiuk** [comment]
This is standard python logging feature, Just run `self.log.setLevel(logging.DEBUG)` at the moment you want to enable debug.

**Comment by dgronskij** [comment]
Hey, how is it supposed to be done on the client side without changing the operators' code (which are distributed as a package)?

**Comment by potiuk** [comment]
Did you check https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html#advanced-configuration ?

**Comment by dgronskij** [comment]
Yeah, sorry for the poorly worded question.

Here is our disposition:
- Airflow instance with no access to AF workers for developers
- 3rd party AF operators that do some logging
- Sometimes, there is a need to run specific DAG with custom log level in an ad-hoc manner, but we don't want to affect other runs since there are lot's of them and everybody would see verbose logs

Documentation that you cited suggests changing AF-wide configuration on the worker side. It seems that we could make a "debug node" worker, with debug level configured, and somehow route dags-to-be-debugged onto that.. but this is really complicated

**Comment by potiuk** [comment]
Ok. This sounds more interestin and cool. Marked is as good first issue, maybe someone would like to attempt implementing it? Note that this is an open-source. Opening feature proposal like this does not mean it will be implemented. Someone must pick an interest an implement it. If you or your team would like to develop or contribute such fix, this is the fastest way - otehrwise it will have to wait for someone to pick it up.

**Comment by dgronskij** [comment]
@potiuk  Thanks for the reponse!

I just came around the idea that what I wanted may be done via `on_execute_callback` / `pre_execute` callback functions. At the end of the day I'm not sure that there is a need of extra parameters since callbacks are the most flexible way to do anything. 

Probably, making parameters for `logging.rootLogger` loglevel or  `logging.basicConfig` kwargs would be a good compomise, but not sure -- my case is quite niche, as I see.

**Comment by potiuk** [comment]
Ah yeah. That is actually good way of doing it. :). Good idea. Will close it but will keep the idea for similar cases.
