### ISSUE TITLE
getting authlib error while using keycloak with airflow 2.1.1

### ISSUE THREAD

**Issue by debimishra89** [apache/airflow#17785]
### Discussed in https://github.com/apache/airflow/discussions/17784

<div type='discussions-op-text'>

<sup>Originally posted by **debimishra89** August 23, 2021</sup>
I am getting below error while logging in airflow 2.1.1 with keycloak for authentication
![image](https://user-images.githubusercontent.com/84674037/130436752-86a45596-0908-41f0-9d10-a1ed287513eb.png)

I have installed airflow at https://exp-3.dastc.stee.com:8090 in our private network

please find attached  airflow.cfg  and webserver_config.py
[airflow.cfg.txt](https://github.com/apache/airflow/files/7031369/airflow.cfg.txt)
[webserver_config.txt](https://github.com/apache/airflow/files/7031377/webserver_config.txt)

</div>

**Comment by potiuk** [comment]
This is not Airflow issue so it should not be open as such.

It is likely problem with your configuration/network that you should try to debug (and at the worst case raise as Flask Abby Builder issue if you think it's a problem.with oauth implementation). When you Google for the error, you will find a lot of probable causes and solutions, so I advise you to try those and report what did you try and what worked/did not work. Since you already opened the discussion, i invite you to explain there what you've done to try to solve it, so that you raise probability that someone will help.

Closing this as discussion already exists.
