### ISSUE TITLE
Circular Dependency in Apache Airflow 2.1.3

### ISSUE THREAD

**Issue by ashwin153** [apache/airflow#17795]
**Apache Airflow version**:

2.1.3

**OS**:

Ubuntu 20.04 LTS

**Deployment**:

Bazel

**What happened**:

When I tried to bump my Bazel monorepo from 2.1.2 to 2.1.3, Bazel complains that there is the following circular dependency.

```
ERROR: /github/home/.cache/bazel/_bazel_bookie/c5c5e4532705a81d38d884f806d2bf84/external/pip/pypi__apache_airflow/BUILD:11:11: in py_library rule @pip//pypi__apache_airflow:pypi__apache_airflow: cycle in dependency graph:
    //wager/publish/airflow:airflow
.-> @pip//pypi__apache_airflow:pypi__apache_airflow
|   @pip//pypi__apache_airflow_providers_http:pypi__apache_airflow_providers_http
`-- @pip//pypi__apache_airflow:pypi__apache_airflow
```

**What you expected to happen**:

No dependency cycles.

**How to reproduce it**:

A concise reproduction will require some effort. I am hoping that there is a quick resolution to this, but I am willing to create a reproduction if it is required to determine the root cause.

**Anything else we need to know**:

 Perhaps related to apache/airflow#14128.

**Are you willing to submit a PR?**

Yes.

**Comment by potiuk** [comment]
Yeah . HTTP provider has been brought back to be preinstalled and we had to release it to remove the circular dependency, This will be fixed with the next release of HTTP provider (https://github.com/apache/airflow/pull/17796)

BTW. Bazel is not supported as the way of installing Airflow.  The only official way of installing airflow is via `pip`and constraints  -https://airflow.apache.org/docs/apache-airflow/stable/installation.html#installation-tools.  

PIP can handle circular dependencies well. So it's really Bazel's problem not Airflow (we are happy to fix it anyway for the next release - thenks for reporting) .

**Comment by uranusjr** [comment]
FWIW circular dependencies are allowed in Python (in other words, a project’s Python package dependencies is not a DAG), so Bazel not supporting it is a bug (or missing feature).
