### ISSUE TITLE
SSH Operator No authentication methods available

### ISSUE THREAD

**Issue by benjcabalona1029** [apache/airflow#17888]
### Apache Airflow version

2.1.0

### Operating System

macOS

### Deployment

Docker-Compose

### What happened

Same issue with #8490. The container has python3 installed, so the answer in 8490 is not applicable. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
The issue there was posted long time ago. Creating "same issue" is not at all helping as - as you noted - it was python 2.7 so for sure your issue is not "The same". Please (as asked in the issues) provide logs and reproducible steps from your installation.

As you have been warned in the form, issues without reproduction steps will be closed, you can open Discussion instead (but you will have to provide some details there in order to anyone willing to help you). 

Besides you choose wrong issue type SSH is released as provider, so you should open provider bug not the core.
