### ISSUE TITLE
Some timezones in Web UI shows as number, not timezone name

### ISSUE THREAD

**Issue by baryluk** [apache/airflow#17906]
### Apache Airflow version

2.1.2

### Operating System

Linux

### Versions of Apache Airflow Providers

2.1.2

### Deployment

Other 3rd-party Helm chart

### Deployment details

n/a

### What happened

Go to Web UI,

search for example for "Chile/Continental" , after clicking it will be added to the list of timezones, but will be displayed as "-04 (-04:00)".

![Screenshot from 2021-08-30 10-25-55](https://user-images.githubusercontent.com/110322/131309861-762fee0a-5a41-4f4c-a785-dbd382c836f2.png)

It happens for many other timezones.

### What you expected to happen

"CLT (-04:00)" at this time of a year maybe?

### How to reproduce

Clear

### Anything else

n/a

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment]
This comes down to the intended behaviour of [moment-timezone](https://github.com/moment/moment-timezone), the JS package used for handling timezones in the UI. Here's the part of the source which populates that field:
https://github.com/apache/airflow/blob/dd386c81f50fe2a93cf0bff0c3da2c66f2dc6e6a/airflow/www/static/js/datetime_utils.js#L23-L33


You can replicate this behaviour by running the relevant line of code in the javascript console of the Airflow webserver:
```javascript
> moment().tz("America/Vancouver").format('z (Z)')
"PDT (-07:00)"

> moment().tz("Chile/Continental").format('z (Z)')
"-04 (-04:00)"
```

Looking into the discussion in [this issue](https://github.com/moment/moment-timezone/issues/841) on moment-timezone, I believe that this is intended behaviour for some timezones due to this [ICANN change from 2017](https://mm.icann.org/pipermail/tz-announce/2017-February/000045.html) in which it was decided to use numeric abbreviations for many South American time zones:

**Comment by baryluk** [comment]
Ok. Thanks.
