### ISSUE TITLE
Possible PyJWT dependency upgrade?

### ISSUE THREAD

**Issue by mark-carrington** [apache/airflow#18091]
### Description

Hi,

I have a project which currently depends on apache-airflow 2.0.2, which is using Poetry for dependency management. I would like to add Sentry as a dependency, so I can use this for application performance monitoring on some non-Airflow code, which is also present in the repo. I don't seem to be able to install recent versions of Sentry alongside recent versions of apache-airflow (including 21.3) since apache-airflow requires pyjwt (<2), whereas recent Sentry versions want PyJWT (2.1.0). 

Given the popularity of Sentry, I wondered if you'd consider upgrading to using a more recent version of PyJWT? I'm not sure if it's direct or transitive dependency. This would be huge win for those who want to use these 2 packages together.

Thanks
Mark

### Use case/motivation

(see above)

### Related issues

None

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
It is https://github.com/apache/airflow/blob/9496235959f6ffaacb69ed391a6ddb82214e9132/setup.cfg#L133

```
    # Required for flask-jwt-extended and msal 
    pyjwt<2
```

I looked at it and - unfortunately it's because of FlaskAppBuillder (which we already use in its latest version). It has requirements on Flask-jwt-extended < 4: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/setup.py#L60 and Flask-JWT-extended 3.25 (latest from 3 line) has PyJWT < 2.

Proposal: please open an issue to https://github.com/dpgaspar/Flask-AppBuilder with similar tone - and refer to that issue. I will support it :). We are working with Daniel pretty often and maybe he can tell if he could consider upgrading to PyJW4 for next release. I know there should be a release soon because - as we speak we are going through `setuptools` drama (see #18075) and it will - inevitably lead to new Flask App Builder release probably pretty soon.

**Comment by pritampbonde** [comment]
@potiuk : As per suggestion given have raise a new request but I found there is already one request one on similar lines https://github.com/dpgaspar/Flask-AppBuilder/issues/1691. I have added the comment on same issue, let us know if you require to raise a new request with Flask-AppBuilder team
