### ISSUE TITLE
DAGs are disappearing from UI when scheduler pod is restarting

### ISSUE THREAD

**Issue by KulykDmytro** [apache/airflow#18108]
### Apache Airflow version

2.1.2

### Operating System

Linux 5.4.0-73-generic #82-Ubuntu SMP

### Deployment

Other 3rd-party Helm chart

### Deployment details

Deployed by own-developed chart

### What happened

In case when scheduler pod is restarted DAGs are dissapearing for a while (about couple of minutes) until scheduler is fully started and read all DAGs again from DAGS folder

### What you expected to happen

DAGs should remain in UI despite of scheduler state

### How to reproduce

* kill/restart scheduler pod
* wait a bit until scheduler begin to initialize
* switch to webserver UI
* observe empty list of DAGs

### Anything else

image: apache/airflow2.1.2-python3.8
Content of `serialized_dags` are cleared at same time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is a problem with your deployment/custom chart.

You likely do not perform initial DAG sync when you restart the scheduler. 

Before scheduler starts you need to make sure (for example with an initcontainer) that the DAGs are synchronized  fully at least once. Otherwise scheduler starts with empty folder and thinks that the DAGs were deleted.

This is what is done using our Official Helm Chart (and I would recommend you switch to that method to avoid similar problems).

https://airflow.apache.org/docs/helm-chart/stable/index.html
