### ISSUE TITLE
Docker image - Migrate to 3.x-slim-bullseye from 3.x-slim-buster 

### ISSUE THREAD

**Issue by vmalakhin** [apache/airflow#18190]
### Description

Currently docker images are produced based on top of 3.x-slim-buster python and as a result output inherits related debian vulnerabilities. 

### Use case/motivation

Migrate to the latest debian release (bullseye was released around a month ago) for docker images.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Good point. Assigned you to it. It should be started with changing base image in both ci and  prod image but you should make sure to a) update documentation b) update all the scripts where some extra software is installed (for example we install libraries from buster repositories). And there will lilkely be few other problems - like installing Java (we have some recipes there that will likely need to be updated https://airflow.apache.org/docs/docker-stack/recipes.html).

Feel free to start working on it.

**Comment by vmalakhin** [comment]
Sure,  will do. Thanks.

**Comment by potiuk** [comment]
Unfortuntely we cannot move to bullseye (yet). The problem is that MSSQL ODBC driver (which is the only "reliable" and stable drirver for MSSQL for SQLAlchemy) does not support Debian Bullseye yet.

This has been documented and commented on by MSSQL driver maintainers:

- https://github.com/MicrosoftDocs/sql-docs/issues/6494
- https://github.com/MicrosoftDocs/sql-docs/issues/6789
- https://github.com/MicrosoftDocs/sql-docs/issues/6804
- https://github.com/MicrosoftDocs/sql-docs/issues/7255

The answer in all those issues given 28 Jan 2022:

> Debian 11 installation instructions will be added when msodbcsql17 supports. Debian 11.
> Regards,
> David

Let's hope it will be soon. This is the last blocker from migrating to Bullseye. All the rest seems to work

**Comment by potiuk** [comment]
I asked the maintainer for the expected timeline https://github.com/MicrosoftDocs/sql-docs/issues/7255#issuecomment-1037097131
