### ISSUE TITLE
A Facility to Share State Between Operators in a DAG instance (i.e. a specific run).

### ISSUE THREAD

**Issue by r39132** [apache/airflow#182]
I have the following use-case. My DAG loads data for a few days (e.g. because of late-arriving data, my daily run actually can load data for late-arriving data for previous days). I would like to get a sense of how many data rows were added. To do this, I would like to query my database before the run starts and then again at the end of the run. I would then like to send the results in an email at the end of the run. 

Since I can query the final row count before I send the email in a single PythonOperator, my challenge is to save the initial row count before the run starts in earnest, so that I can compute a diff at the end of the run. 

Where can I store this state so that I can access it between operators in the flow? This would be a good general facility to support. There is another ticket #170 However, I don't need that capability. 

The state will need to be cleared after the run completes, either in a successful or failed manner.

General Design Proposal : 
1. A Flow State table that has (dag_id,ds) as the unique key and a text column to support storing serialized structured text (e.g. Avro, Json)
2. A util function to allow Python operators to store to and retrieve from this table
3. An ability in the framework to delete this row on flow completion : successful or failed. I understand that if people CTRL+C or SIGKILL a backfill command, that this state might not be cleaned up, through I would expect subsequent executions would replace this row.

**Comment by jlowin** [comment]
I like this idea a lot (https://github.com/airbnb/airflow/issues/170#issuecomment-128401782). 

I think `Variable` provides the basic infrastructure to achieve this and we could build on top of it. See https://github.com/airbnb/airflow/issues/220, #133 and #12.

However, I'm not sure exactly what Variables are being used for but they don't feel like the right place for this specific use -- first because they're publicly/globally visible and we'd end up horribly polluting that namespace, and second because they don't enforce the dag/task/datetime id that this would require.

But I think they light the path. So I'd propose the following:
1. based on the code that defines Variables [here](https://github.com/airbnb/airflow/blob/1c322b007ec24aeaf9889be44f057d38af3f6c49/airflow/models.py#L1980), create a new table called `State` (or something) keyed by (dag_id, task_id, ds, time_) [_in case there are multiple runs per day?]
2. add class functions similar to `Variable.get()` which store and retrieve `State`s
3. add `get_state()` and `set_state()` methods to `PythonOperator` which handle json serialization/loading and creating the proper table key.

So users could do something like this:

``` python
def my_func(x, **kwargs):
    # get the calling task
    task = kwargs['task']

    # set_state handles json conversion and generating the 
    # appropriate keys (task_id, dag_id) for storing the value 
    task.set_state('my list', [1, 2, 3])

    # get_state retrieves the most recently saved state called 'my value', 
    # optionally restricting the query to a certain task, dag, or date.
    #
    # in this case, we're only getting 'my value' if it was written by a task called
    # 'my_other_task'
    state = task.get_state('my value', task_id='my_other_task', dag_id=None, date=None)
```

Maybe with a little magic we can get rid of needing to access kwargs/pass context, but let's leave that for the future. In fact, I guess users could do that by calling `State.set()` directly, but then they'd have to pass the `task_id` and `dag_id` that the `task` method handles automatically.

@r39132 your point number 3 could be handled with some of the callback functions that I believe were recently handled.

Critically, all the plumbing to do this already exists thanks to `Variable`; just need to write the utility functions. If this is interesting I'll take a crack at it.

**Comment by jlowin** [comment]
Maybe `save`/`load` or `store`/`retrieve` are the right semantics instead of `get`/`set`... open to suggestions!

**Comment by mistercrunch** [comment]
For reference, we're in solution mode here:
https://github.com/airbnb/airflow/pull/232
