### ISSUE TITLE
Use natural sorting while listing DAGs

### ISSUE THREAD

**Issue by siddharthvp** [apache/airflow#18316]
### Apache Airflow version

2.0.2

### Operating System

Linux

### Versions of Apache Airflow Providers

NA

### Deployment

MWAA

### Deployment details

NA

### What happened

When listing DAGs that have numbers in the IDs, Airflow lists DAGs in lexicographic order. 

Observed order:
test_dag_1
test_dag_10
test_dag_2
test_dag_3

### What you expected to happen

Desired order: 
test_dag_1
test_dag_2
test_dag_3
test_dag_10

### How to reproduce

Create a set of DAGs with IDs test_dag_N with various values of N.

### Anything else

https://softwareengineering.stackexchange.com/questions/127639/why-do-some-sorting-methods-sort-by-1-10-2-3/127644

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
We rely on sorting provided by databases.Can you check if MySQL and PostgreSQL support the sorting method you want? If not, what plans do they have to implement it?

**Comment by siddharthvp** [comment]
* https://stackoverflow.com/questions/9173558/postgresql-order-by-issue-natural-sort
* https://stackoverflow.com/questions/153633/natural-sort-in-mysql

Not supported in MySQL. Postgres [appears to support a collation](https://stackoverflow.com/a/67975489/9306016) that will enable natural sorting.

**Comment by potiuk** [comment]
I think there is no special treatment (and they will never be) of dag ids containing numbers. Dag id s are strings not numbers.

Especially that this is your own convention to use numbers and it's super easy to fix it.

 If you wan your DAGs to be sorted according to the number, simply format their ids with leading 0s:

test_dag_009, test_dag_010 will be sorted properly. And it, super easy to generate such DAG ids:

```
printf "%.5d\n" 4
00004
```

**Comment by siddharthvp** [comment]
> I think there is no special treatment (and they will never be) of dag ids containing numbers. 

Well, I wouldn't say that as file names are also strings but both Windows and macOS file explorers list files with numbers in the natural order. Similarly in Unix, `sort -V` handles strings with numbers correctly. So this is not exactly a new idea - more of a limitation with the databases.

**Comment by potiuk** [comment]
My point is not that "it's not possible" or that it's not "useful" or not that it's not "used elsewhere". I simply think comparing it with Windows or MacOS "Explorer/Finder" which is targeted for different users and use case is not very good comparison. The fact that you CAN do something does not mean that you SHOULD.

My point is that we are really not in general "filesystem" users camp where you have non-professional users who do not understand what leading zeros are and how they impact sorting.

The Dag ids we have are generated programmatically and company using them builds their own dags can use and enforce their own conventions for naming them. Rather than accepting and supporting (rather poor in terms of consistency and organisation) naming convention where you have natural numbering I think we should promote better organised ones,

Most of the users who create DAGs are data scientists/engineers who understand numbers, sorting, leading 0s etc. And most of all naming your dags with consecutive numbers: 0/1/2 etc. is actually a bad idea on it's own because it tells exactly nothing other than this is the "next" version of the same DAG (without giving any hint of the reasoning behind it). Having multiple versions of the same dag with only consecutive number difference is a terrible anti-pattern IMHO.

I believe it's good choice for Airflow to stick with lexicographic sorting and not to promote some "bad" conventions - and since it is rather easy to make your dags define and follow "good" conventions I see "natural sorting" as simply bad choice for Airflow that would promote bad naming conventions.

So to explain why I marked it as "won't fix":  not because I thought it as ("not new") idea. The idea is well known, but I think applying it Airflow DAG ids is a bad idea.

But if you have arguments why natural sorting might be useful for  production, setup where data engineers have to manage multiple DAGs, I am happy to hear the arguments.
