### ISSUE TITLE
downstream tasks "upstream failed" when upstream retries and succeeds

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#18401]
### Apache Airflow version

2.1.4 (latest released)

### Operating System

official docker image

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

using KEDA

### What happened

Somehow, downstream task ends in state 'upstream failed' even though the upstream task retried and succeeded.

![image](https://user-images.githubusercontent.com/15932138/134117913-5384a134-e060-4d05-9d48-a69b4b24c617.png)

### What you expected to happen

"upstream failed" should only happen when upstream task fails

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

But I have no ideas about cause here.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jorricks** [comment]
The DagRuns (circles at the top) make me think that the task first failed completely and then you manually asked it to retry. So the question: did you manually retry them or did the Airflow scheduler do it automatically for you?

**Comment by dstandish** [comment]
I did nothing manually.  The scheduler retried the tasks (which are green now because they succeeded on second try).  but the orange tasks never ran -- they seem to've gone immediately to "upstream failed"

**Comment by millin** [comment]
We faced the same issue

**Comment by Jorricks** [comment]
Hmmm. 
I remember there was an issue that if a task failed during imports and such, that it would fail completely without any retries.
This makes me think that it might be related to that fix.
Did you check your worker logs to see if anything turned up for the first run? Pretty sure there must at least be something as it probably won't go to failed without a reason.

**Comment by millin** [comment]
I haven't yet been able to find the reason, rolled back to 2.1.3

**Comment by ashb** [comment]
@ephraimbuddy I think should be fixed by https://github.com/apache/airflow/pull/17819, right?

@dstandish If you have time could you try out 2.2.0b2 which has that fix in it and let us know?

**Comment by ephraimbuddy** [comment]
Yes. It was resolved in #17819

**Comment by shubhamg931** [comment]
We are facing the same issue with Airflow 2.1.3, also tasks are getting queued randomly with logs similar to as mentioned in https://github.com/apache/airflow/issues/17370

**Comment by ashb** [comment]
I'm going to close this as it's been fixed in main and will be included in the next release coming in the next few days.

**Comment by millin** [comment]
@ashb Latest stable release 2.1.4 is broken and it looks like the next release won't be out in the next few days...
https://github.com/apache/airflow/milestone/33

I would recommend removing/yank 2.1.4 from the pypi or/and release a bugfix

**Comment by ephraimbuddy** [comment]
@millin what issue did you find?

**Comment by millin** [comment]
This issue makes it impossible to normally use dependent tasks if there are retries in the upstream

**Comment by ephraimbuddy** [comment]
If this is the reason, then you should wait for 2.2 which is being tested now, and you can participate in the testing. See https://lists.apache.org/thread.html/r3482fb574b40eb73cdf6a506361d908c6ab700e67acd80bfa47f3542%40%3Cdev.airflow.apache.org%3E

Airflow is a community project, you can contribute to making it better.

There are many others using 2.1.4. If you are getting this error all the time, you probably need to check your setup. This should rarely happen

**Comment by potiuk** [comment]
> I would recommend removing/yank 2.1.4 from the pypi or/and release a bugfix

Just to explain some misconceptions @millin  and maybe give you mor understanding of the process and to set the commo expectation and understanding (also for anyone reading it in the fufure).

We only yank software if it has catastrophic bugs that prevent the software from running. This is not the case by any means.

It's quite usual that there are bugs and they get fixed.  2.2 is doing exactly this (It has both new features and bugfixes). You might have misconception that we need extra bugfix release, but this is entirely not needed, as 2.2. will act as bugfix release as well.  

According to SemVer (which we are following): https://semver.org/ the minor release can contain both new features and bugfixes (not only new features) - see https://semver.org/#spec-item-7. And this is what 2.2 will have - it should be fully compatible with 2.1 (also according to SemVer).  

There is no way we can have 2.1.* releae faster than 2.2 since we are all busy making sure 2.2 is tested and released and contains all bug fixes. We will not throw everything down to fix that one fix of yours. Releasing new version of Airflow is a significant effort even if it contains very little changes, so we tend to do releases only when they are really needed.
 
Unless there is a serious reason (basically critical security fix which we need to patch immediately), there will never be 2.1.5 - 2.2.0 will be the release where some bugs from 2.1.4.

**Comment by millin** [comment]
@potiuk @ephraimbuddy Thanks a lot.

Apparently, it seemed to me that this problem is more frequent than it actually is, since in our case it happens every time when upstream task goes to retry.

**Comment by abhushansahu** [comment]
These are related issues
https://github.com/apache/airflow/issues/10604
and seems to still be active for 2.1.4

**Comment by ephraimbuddy** [comment]
Can anyone try this in 2.2.2?

**Comment by preethi670** [comment]
we are seeing this issue in 2.2.5 as well . Can you please suggest if this was resolved in later versions ?

**Comment by potiuk** [comment]
> I did nothing manually. The scheduler retried the tasks (which are green now because they succeeded on second try). but the orange tasks never ran -- they seem to've gone immediately to "upstream failed"

Can you simply upgrede to latest 2.4* and check if it is fixed? Airflow containst 1000s of bugfixes and some of the fixes are likely to fix issues that had been raised (and even closed). Your issue might or might not be the same. Checking if it occurs in the latest version is absolutely fastest way of answering your question - otherwise you might try to look at similar issues and make a guess, but that's basically what anyone else would have to do, so just upgrading is the fastest way. If it still will be happening there, I'd strongly advice to report a new issue based on that newest version.

In any case - upgrading is the only way you will get it fixed - so you will eventually have to do it anyway, and upgrading early and often is recommended (and good) because each time you have to deal with less potential issues (which shouldn't be many as Airflow SemVer approach makes it safe to expect backwards compatibility for the core - and you can usually downgrade providers separately if you find their "breaking" changes need some work).

**Comment by Nessa-x** [comment]
Facing same issue with v2.5.1
