### ISSUE TITLE
2.1.3/4 queued dag runs changes catchup=False behaviour

### ISSUE THREAD

**Issue by StewartThomson** [apache/airflow#18487]
### Apache Airflow version

2.1.4 (latest released)

### Operating System

Amazon Linux 2

### Deployment

Docker-Compose

### What happened

Say, for example, you have a DAG that has a sensor. This DAG is set to run every minute, with max_active_runs=1, and catchup=False.

This sensor may pass 1 or more times per day.

Previously, when this sensor is satisfied once per day, there is 1 DAG run for that given day. When the sensor is satisfied twice per day, there are 2 DAG runs for that given day.

With the new queued dag run state, new dag runs will be queued for each minute (up to AIRFLOW__CORE__MAX_QUEUED_RUNS_PER_DAG), this seems to be against the spirit of catchup=False.

This means that if a dag run is waiting on a sensor for longer than the schedule_interval, it will still in effect 'catchup' due to the queued dag runs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
> this seems to be against the spirit of catchup=False

What is your understanding to catchup? This does not match my understanding to it.

https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html?highlight=catchup#catchup

From the documentation’s description, catchup only matters for runs missed their turn. But since the scheduler is able to schedule those runs at the pace of once a minute, those runs did not miss their turn, so catchup does not matter to them. The behaviour you described for 2.1.2 and below sounds like a bug to me.

**Comment by StewartThomson** [comment]
Per the documentation:

"When turned off, the scheduler creates a DAG run only for the latest interval."

With the queued state, it creates dag runs for the latest interval and the next 16 intervals (by default)

**Comment by robinedwards** [comment]
If you take a look at the instructions beneath the example dag in my comment this is only used to get the dag behind schedule. It should then be amended to `catchup=False`

**Comment by ephraimbuddy** [comment]
That's true.

**Comment by robinedwards** [comment]
Here is the fix https://github.com/apache/airflow/pull/19130
