### ISSUE TITLE
Scheduler overloaded when backfilling by clearing DAG history

### ISSUE THREAD

**Issue by vlieven** [apache/airflow#18501]
### Apache Airflow version

2.1.2

### Operating System

Debian 10

### Versions of Apache Airflow Providers

apache-airflow-providers-apache-spark

### Deployment

Other Docker-based deployment

### Deployment details

Deployed on AWS EKS (Kubernetes version 1.21), backed by RDS database (Postgres API)
Using Kubernetes Executor

### What happened

I cleared +- 2000 runs of the same DAG in order to reprocess a dataset. This caused 10.000+ tasks to switch to the status "none". The amount of tasks in this DAG which is allowed to run is fairly limited (task_concurrency=2 for the tasks, max_active_runs=3 for the DAG). These limits seem to be honoured, and no excessive amount of tasks are being scheduled by this DAG.

However, what happened is that other DAGs were prevented from running their tasks. Given that no task limits were being hit, I suspect that this has to do with the 10.000 tasks with status "none" keeping the scheduler over-occupied, leading to no useful work actually getting scheduled.

### What you expected to happen

I expected the backfilling process not to block other DAGs from scheduling tasks. Potentially by having the scheduler ignoring tasks which violate the `max_active_runs ` limit.

### How to reproduce

- Take a DAG with 2000 DagRuns and 5+ tasks per run
- Set the state of all 2000 DagRuns to cleared
- Observe starvation of other DAGs trying to schedule tasks concurrently with the backfilling

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vlieven** [comment]
I'm willing to contribute on a fix for this, but I don't know where to start looking for the cause of the problem

**Comment by uranusjr** [comment]
Is there a reason for this specific setup? Since the global concurrency is set to 2, setting a DAG to have max three active runs seems… wrong.

**Comment by vlieven** [comment]
Suppose you have a DAG with tasks X -> Y -> Z. Setting task_concurrency=2 and max_active_runs=3 allows you to start task X for dagrun n+2, while task Z is still running in dagruns n and n+0. I'm open to suggestions for better ways to optimize DAG throughput while limiting the number of concurrent tasks though?

In any case, I don't think the exact parameter values are relevant to the problem described. I mentioned them to indicate that the problem is not with having no room in the cluster to execute tasks, but rather the tasks not getting scheduled.

**Comment by leonsmith** [comment]
So we just come across this issue.

Our reproduction steps are similar too.

We enabled a new daily dag with ‘catchup=True’ and a start date 3 years in the past, this caused the scheduler to correctly create all 1000+ dag runs and to start “catching up”.

However this starved other dagsruns from being executed in the environment until the dag was fully caught up, we also had a low max active dag runs which has helped identify the issue.

The new dagruns are moving from scheduled to running correctly in the scheduler loop and the scheduler correctly drops dagruns that have hit the dagrun limit.

However what appears to be happening is if a dagrun is under its max concurrent limit the dagruns per loop query will still return all the dagruns for this dag even though it can only launch a small number more up to its limit. 
It effectively limits the throughout of the scheduler loop because a high percentage of the dagruns are not actually eligible to run and the last scheduled decision date is not updated.

Fixing the last scheduled decision date as already merged in #17945 does allow other tasks to be picked up but only after every dagrun has been inspected once.

Thus this is actually a compound issue as once the above is fixed it turns into slower dag execution rather than a stalling/blocking issue.

The above fix also has a side effect of making the dagruns out of order but I don’t think that was every a guarantee that new dagruns would be executed in order unless they are marked to depend on the past.

**Comment by leonsmith** [comment]
So did more digging.

Looks like the above was already reverted out due to the side effect of the out of ordering.

But that's re-introduced the issue again. The fix that was proposed only works providing the max active dagruns is hit.
If you have a dag that is managing to complete dagruns between each loop of the scheduler it will continue to block other upstream dags until the catchup has completed

**Comment by leonsmith** [comment]
I think the fix here is to use a window function over [next_dagruns_to_examine](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L211) so it only returns dagruns up to the dags maximum concurrency.

I know this is the core loop so performance is a concern here. Is there any objection to something like the following approach before I put effort in writing some tests?

Are there any concerns for the other backends with this type of approach

```python
        if state == State.QUEUED:
            # For dag runs in the queued state, we check if they have reached the max_active_runs limit
            # and if so we drop them
            row_number_column = func.row_number().over(partition_by=DagRun.dag_id).label('row_number')
            query = query.add_columns(row_number_column)

            running_drs = (
                session.query(DagRun.dag_id, func.count(DagRun.state).label('num_running'))
                .filter(DagRun.state == DagRunState.RUNNING)
                .group_by(DagRun.dag_id)
                .subquery()
            )
            query = query.outerjoin(running_drs, running_drs.c.dag_id == DagRun.dag_id)

            open_dagrun_slots = func.coalesce(running_drs.c.num_running, 0) - DagModel.max_active_runs
            query = query.filter(row_number_column < open_dagrun_slots)

        query = query.order_by(
            nulls_first(cls.last_scheduling_decision, session=session),
            cls.execution_date,
        )
```

**Comment by ashb** [comment]
Before doing any work it is worth checking this behaviour on 2.2.0b2 as we did make a few changes in scheduling code.

**Comment by dstandish** [comment]
thing to consider: mysql 5.7 does not have row_number... not sure how careful we are about this kind of issue... maybe sqlalchemy rewrites it to use variables (the way to do row number on pre-window-function mysql)

suprisingly, apparently sqlite3 3.25 _does_  have window functions ...

**Comment by ashb** [comment]
> interestingly, sqlite3 3.25 does have window functions ...

That is because SQlite is more of a database than MySQL.

**Comment by theister** [comment]
We came across the same problem, but on `2.0.2`.

We recently migrated from 1.10.15 and we're also regularly doing backfills by clearing history via the UI and making the airflow catchup re-run them, which puts 100s of dag runs to `running` state.
While the reprocessing the data eventually succeeded, it completely starved out all other dags in the meanwhile, printing many lines of  
`DAG XYZ already has 10 active runs, not queuing any tasks for run 2021-06-30 00:00:00+00:00` .
to the scheduler logs. These were printed for the for the 10 next execution dates where no tasks were scheduled for just yet, which corresponds to our scheduler setting of `max_dagruns_per_loop_to_schedule=10`.

After digging into the code a little, my undertanding is that if the `max_active_runs` limit is hit, the 2.0.2 scheduler prints the above message, but returns from `_schedule_dag_run()` without actually updating the `last_scheduling_decision` timestamp of the DagRun (See https://github.com/apache/airflow/blob/2.0.2/airflow/jobs/scheduler_job.py#L1776), which to my understanding only happens in `update_state()`.

Since the `DagRun.next_dagruns_to_examine()` method returns the next DagRuns to check sorted ascending by last_scheduling_decision, this will effectively block any other dag runs from being scheduled, as long as the max_active_runs limit of the dag is being hit.

@leonsmith did you manage to find out if the issue is still present on 2.2.0?

**Comment by dstandish** [comment]
@theister  re

> @leonsmith did you manage to find out if the issue is still present on 2.2.0?

There _are_ still a few issues with 2.2.0; I think that you're going to want to go straight to 2.2.2, and there's an RC available to try:
```pip install 'apache-airflow==2.2.2rc2'```

**Comment by theister** [comment]
Well, I actually meant the latest release in the `2.2.*` line, I didn't check what the latest one was.

I'll see if I can find a way to reproduce the behaviour on a local setup on our current images next week, that will also help triaging if it's fixed on the latest stable 2.2.1 or RCs of 2.2.2.

**Comment by theister** [comment]
Short update:

I was able to reproduce the problem using the following minimal example on `2.0.2`

```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy import DummyOperator
from airflow.operators.bash import BashOperator

with DAG(
    "debug-long-replay-dag",
    schedule_interval="0 0 * * *",
    start_date=datetime(2020, 1, 1),
    max_active_runs=10,
    catchup=True,
) as long_dag:

    initial_task = DummyOperator(task_id="initial-task")
    sleep_task = BashOperator(bash_command="sleep 300", task_id="sleep-5-mins")
    initial_task >> sleep_task

with DAG(
    "debug-frequent-dag",
    schedule_interval="*/1 * * * *",
    start_date=datetime(2021, 1, 1),
    catchup=False,
) as hf_dag:

    sleep_task = BashOperator(bash_command="sleep 30", task_id="sleep-30-sec")
```

We're currently upgrading our instances to 2.2.2, and I can no longer reproduce it on the new version 🚀 
Clearing task instances for a large number of dag runs now sets all DagRuns to the newly introduced `"queued"` DagRun status, and the scheduler no longer is starved out.

@vlieven @leonsmith please check if 2.2.2 solves it for you, too.

**Comment by easontm** [comment]
just had this occur on 2.2.2
