### ISSUE TITLE
Deleting and copying DAG file from/to dags directory not triggering the DAG

### ISSUE THREAD

**Issue by yevsh** [apache/airflow#18665]
### Apache Airflow version

2.1.2

### Operating System

N/A runs as pod

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Openshift

### What happened

airflow-dags folder of airflow-scheduler pod/container mapped to external volume.

DAG file has property
 'is_paused_upon_creation': False

Once I copy this DAG into the mapped directory, airflow loads it (I see it in airflow webui)and runs it.
Then it continues  to run according to the schedule.

So far so good.

Now:

If I delete the DAG file from the directory, and copy again (same DAG file) airflow webui loads it but only after few minutes (keeps the execution history of previous runs),
 but doesn’t  start it immediately.

### What you expected to happen

Once new/old/same DAG copied to dags folder, it should appear in webui at once and tarted (if it has  'is_paused_upon_creation': False ).
With clean history - this one not mandatory.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by brki** [comment]
@yesvh personally I would not expect that behaviour.  In fact it would be rather annoying in some situations.

Imagine that your DAGs are mounted on a network file share, and the file share is unavailable for a while due to a network issue.  Your DAGs are scheduled to run once a day.  They've already run today.  You wouldn't want all of your DAGs to start running again when the network share is suddenly available again.

Would triggering the DAG via the CLI work for your use case?

Your using Kubernetes, so perhaps better would be triggering the DAG [via an API call]( https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_dag_run)?

**Comment by yevsh** [comment]
Thanks, I am aware of alternatives to trigger the DAG, I hoped their is also an OOB option that I wanted.

**Comment by potiuk** [comment]
This is not how Airflow works. The DAG that disappeared and appeared again wiht the same DAG is "the same" DAG. If you want to change the structure of DAG heavily you are supposed to create a new DAG with new DAG_Id and it will have new history.

See the comment here: https://airflow.apache.org/docs/apache-airflow/stable/index.html?highlight=slowly#beyond-the-horizon

We have a DRAFT "Airlfow Improvement Proposal" to handle DAG versioning  https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-36+DAG+Versioning - but it needs a lot of work and discussion on how DAG versioning should look like in various cases.
