### ISSUE TITLE
Airflow 2.2 removed Airflow group and moved into root group

### ISSUE THREAD

**Issue by Alien2150** [apache/airflow#18900]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

Debian GNU/ Linux 10 (buster)

### Deployment

Other Docker-based deployment

### What happened

When I try to build my own images and run a COPY command it fails on 2.2 because the Airflow group is missing:

```
COPY --chown=airflow:airflow src/python/dags ./dags/python/
COPY --chown=airflow:airflow src/python/hooks ./hooks
COPY --chown=airflow:airflow src/python/operators ./operators/
COPY --chown=airflow:airflow src/sql/ ./dags/sql/
COPY --chown=airflow:airflow src/python/requirements.txt /tmp/requirements.txt
```
It seems the the airflow group was removed on 2.2.0 and now put into the root group. This is not a good security practice (imho). Is there a reason to have airflow running as root?

docker run --rm -it apache/airflow:2.2.0-python3.9 bash 
cat /etc/group: 
`root:x:0:airflow
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
ssh:x:101:`

docker run --rm -it apache/airflow:2.1.4-python3.9 cat /etc/group:
`
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
ssh:x:101:
airflow:x:50000:airflow
`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
> It seems the the airflow group was removed on 2.2.0 and now put into the root group. This is not a good security practice (imho). 

Why? What kind of security practice it vilolates? What problem it might cause? I'd love to hear some arguments for it. So far I had this discussion several times and no-one was able to say why this would be a bad practices (as oppose to running as `root` user which definitely is a bad practice and there are good arguments for it)..
But I am open to hear more arguments.

> Is there a reason to have airflow running as root?
Yes. That was a deliberate choice. Runnign as `root` group is recommended practice introduced by Open Shift (that's why I claim to say it is not a bad or dangerous practice) - this allows the image to run as arbitrary user as described here https://airflow.apache.org/docs/docker-stack/entrypoint.html#allowing-arbitrary-user-to-run-the-container

I am converting this into discussion, as I am eager to hear what are the arguments for `root` group being dangerous.
