### ISSUE TITLE
Pushing to XCOM, but not from a task.

### ISSUE THREAD

**Issue by stefanondisponibile** [apache/airflow#18982]
### Description

Hello, I'd love to discuss the idea of a new feature allowing users to `push` to `XCOM` directly (not from a task).

### Use case/motivation

The motivation of this is allowing downstream tasks to pull XCOM values from the upstream whenever upstream tasks failed for whatever reasons.

One very common pattern is the following:

**Task-1 (upstream)**:
  - Upload something to an external repository (db, s3, ...).
  - Push to XCOM some reference to that data (its id, name, path, ...)

**Task-2 (downstream)**:
  - Pull from XCOM the reference to that data
  - Do something with it

Now let's say **Task-1** takes *very* long (hours, or even more), and let's say that **Task-1** completed the upload but for whatever reason if fails before pushing the XCOM.

**Task-2** won't be able to pull any values, but being able to pass new arguments to other tasks through manually updated XCOM may be useful (i.e. time-saving). In this particular example, the user could update the **Task-1** XCOM with the proper id.

What do you think are the drawbacks of this approach?
 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
What do you mean? Why would you want to use UI to push some data? What's the use case ? 

We do not have 'write' functionality in the UI to change any data - at most you can execute logical actions there  like rerunning tasks. Low level pushing of data which requires understanding of dogs and task code is certainly not part of the UI - also because of important security paradigm. Users of the UI should not be able (even admins) to modify execution paths and data of tasks being processed. 

Airflow 'task execution' is all about Python. UI is only for monitoring and management of what has been written in Python by those who have access to do so (which is separate from UI).

So unless we change some really basic paradigms of Airflow i see no place for it in the UI. 

But if you have valid case for that - you can bring it to the devlist - with all the arguments and reasoning
