### ISSUE TITLE
Manual dagrun logs to last scheduled dagruns log files

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#19058]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

MacOS 11.6

### Deployment

Virtualenv installation

### What happened

Task logs for manual runs are being appended to the last scheduled runs log file.

It seems like it isn't using the `logical_date` (aka `execution_date`) for determining the logfile path (though I haven't dug in at all).

### What you expected to happen

Each dagrun to have it own, unique log file.

### How to reproduce

If you enable this DAG:

```
from datetime import datetime
from airflow import DAG
from airflow.operators.bash_operator import BashOperator

with DAG(
    "manual_run_execution_date",
    start_date=datetime(2021, 10, 14),
    schedule_interval="0 0 * * *",
) as dag:
    test = BashOperator(task_id="test", bash_command="echo HI")
```

Once the scheduled runs finish, bring up the log for the last scheduled run (and keep the tab open).
Now schedule a manual run via the UI, wait for it to finish, then look at the log for the manual run.
Note that you'll see 2 runs, one from the scheduler run and one from the manual run.
Confirm with the last scheduled run tab you kept open.
Note at the top of both, you'll see it's pulling from the same log file:

```
*** Reading local file: /opt/airflow/logs/manual_run_execution_date/test/2021-10-17T00:00:00+00:00/1.log
```

### Anything else

This is a regression in 2.2.0, I wasn't able to reproduce this in 2.1.4.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Great analysis @uranusjr chapeau-bas ! I think there is another option for custom logs. I believe we could simply  ban using `ts` in the names of the logs. That would mean some additional analysis of the custom logging specification and failing airflow if we detect it - possibly with a very descriptive explanation on how to convert the old logging spec and maybe even a tool to help with it. 

Yes it means breaking (somewhat) backwards compatibility, but I think this is the kind of change that we can claim is a fix to behaviour that was previously coincidentally working fine. 

I think - when it comes to 'custom' logging we do not have an API specifying clearly what is and what is not breaking compatibility.

**Comment by jedcunningham** [comment]
Sounds good to me. Don't forget that `try_number` will probably need to be rendered in on-demand.

**Comment by uranusjr** [comment]
The problem is we need to finish all backfilling before we change the default filename format (or before the user changes the custom format based on our recommendation), otherwise the old format would be lost forever and we won't be able to backfill anymore, and there's no guarantee each past task instance (or DAG run) would be visited at least once before the change unless we artificially add something.

One workaround I can think of is to instead add a table in the database that records the current (i.e. old after we change the default) format. When we implement the filename format change, we'll insert one single row to that table for TIs with NULL format to use as the fallback. Not particularly elegant though.

**Comment by calfzhou** [comment]
what's the difference between `logical_date` and `data_interval_start`?

**Comment by uranusjr** [comment]
`data_interval_start` is the start of the DAG run's data interval, which `logical_date` is a date that identifies that DAG run. They are the same for runs scheduled via CRON and `timedelta`, but not the case for manual runs and `@once` runs. A custom timetable may also choose to not use the same value for them.

**Comment by uranusjr** [comment]
Tracking the rest of the work in #19625.

**Comment by iorilan** [comment]
Hi @uranusjr  this issue seems still reproducible when manually trigger the dag run.
for now using {{data_interval_start}} to replace {{ts}} to make it work .

**Comment by eliot1785** [comment]
I found this when reading the changelogs. I just wanted to make a comment on ds/ts/etc... personally I use these variables for things like determining the output names of files, like 'myoutput_[ds]_[ts]' (similar to how Airflow determines the log file names, I guess). I'm probably not alone in that respect. 

So I'm glad that the change was reverted, because otherwise when I had a manual run it sounds like I would have overwritten my output for my previous run, rather than creating new output files. 

I haven't yet learned about the data_interval feature, but I just wanted to say as a user that it would be pretty important to keep the behavior of ds/ts/etc stable - changing them would basically be a breaking change. Perhaps new context variables could be added for data_interval instead, leaving it up to the user which one they want to use.
