### ISSUE TITLE
REST API: allow filtering by state in Dag Runs queries

### ISSUE THREAD

**Issue by fbertos** [apache/airflow#19108]
### Description

Hi,

It would be very interesting to be able to filter DagRuns by using the state field. That would affect the following methods:
 - /api/v1/dags/{dag_id}/dagRuns
 - /api/v1/dags/~/dagRuns/list

Currently accepting the following query/body filter parameters:
   - execution_date_gte
   - execution_date_lte
   - start_date_gte
   - start_date_lte
   - end_date_gte
   - end_date_lte

Our proposal is to add the state parameter ("queued", "running", "success", "failed") to be able to filter by the field  "state" of the DagRun.

Thanks.

### Use case/motivation

Being able to filter DagRuns by their state value.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
I just realised this is a duplicate to #16844, so I'm going to close this one in favour of that earlier entry. A pull request (#16845) was filed against that issue but had unfortunately since gone stale, so feel free to work on that basing off the PR. It'd be awesome if you could comment in #16844 so I can assign you to the issue as well.
