### ISSUE TITLE
TriggerDagRunOperator External Link doesn't link with execution date to match to triggered DAG

### ISSUE THREAD

**Issue by ljades** [apache/airflow#19264]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

Debian

### Deployment

Docker-Compose

### Deployment details

Using base Docker image astronomerinc/ap-airflow:2.0.2-2-buster.

### What happened

The [TriggerDagRunOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html) embeds an external link that links to the DAG that's being triggered. The problem is, the link currently includes a parameter for restricting to execution dates EARLIER than the execution date of the triggering DAG itself.

This means that the external link is always guaranteed to not link to the right DAG run (and not even show it as an option until you manually change the execution date filter in the new page). It links to the DAG page but never to the right instance without some manual tampering after clicking on the link.

### What you expected to happen

The Triggered DAG should point to the execution date of the triggered dag, not the triggerING DAG.

If this is not feasible, it should at least point to the Triggered DAG page with no execution date constraints. At least this would show the latest run, and it will include in the dropdown the triggered run.

### How to reproduce

Create a DAG with a TriggerDagRunOperator that triggers another DAG. Run the former DAG, wait for the task to run. Click on the task, click on the "Triggered DAG" external link. It will not show the triggered run that just happened. You will need to manually adjust the date constraint in the upper left of the DAG views, and then select your run.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
> I think you're right. Honestly I don't feel the extra SQL query is that problematic, it's not like the link is rendered in a lot of places, and we can at least cache the result so there's only one additional query for each render.

Okay, I'll play around with this. I'm still not sure there is the required data for a query either, but I'll try some things out.

**Comment by o-nikolas** [comment]
So after poking at this a bit more, I don't think it's possible with the current schema:
At the point where we're creating the extra link we have access to the dag id, execution time and task_id of the trigger**ing** dag/task. From which we can also query for the dag run and the task instance objects. However, none of these are sufficient to query for the trigger**ed** dag run. We know the id of the trigger**ed** dag but we don't know the run_id or the execution time of the trigger**ed** dag run since these are computed in `execute` of the trigger**ing** dag (unless they are provided by the user as arguments to the operator, in which case we have them) and are not persisted or left as a bread crumbs.

When we create the trigger**ed** dag run, the only noteworthy thing we set is `externally_triggered=True`, but we don't set *what* externally triggered it. As far as I can tell we simply don't have a field in dag run model to represent what entity externally triggered the dag (whether it be by another dag like in this case, or the cli run dag api, etc). So until we add something like that I think it is impossible to link to the proper location in all cases. Please do correct me if any of the above is wrong though.

Paths forward:

1. Remove the execution time from the extra link and just link to the trigger**ed** dag id alone. This will show the full history of dag runs (up to the default 25 runs of course) and the user can do further filtering if required by hand
2. 1b) in addition to 1. add the execution time to the url or fetch it from the dag_run if the user provides those optional inputs to the operator. Though this will lead to differing behaviour depending on whether or not those inputs are provided and it may not be clear to the customer why they're seeing said differing behaviour. This is an optimization that may or may not be worth it.
3. Update the dag run model to include a new field which represents what **externally** triggered that dag run if `externally_triggered` is true. This way we can do a query in the future, when building the link, for all dag runs that were triggered by a specific previous dag run (hopefully that makes sense). This is easy to kludge but obviously any changes to the DB schema needs to be done with great care and thoughtfulness.

**Comment by augusto-herrmann** [comment]
By the way, since [`execution_date` has been renamed to `logical_date`](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#faq-what-does-execution-date-mean), but `TriggerDagRunOperator` [still uses this nomenclature](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html#airflow.operators.trigger_dagrun.TriggerDagRunOperator), shouldn't this be changed? Like so:
* rename the `execution_date` parameter to `logical_date`
* using the `execution_date` parameter in this class would call `logical_date` for backward compatibility, after raising a deprecation warning

If this makes sense, I can create a new issue about it.

**Comment by uranusjr** [comment]
Yes, but that’s an entirely different issue and should be worked on separately. Feel free to open a pull request for that, but let’s leave that discussion out of this particular issue.

**Comment by eladkal** [comment]
Closed in https://github.com/apache/airflow/pull/19410
