### ISSUE TITLE
GitLab OAuth2 Authentication 

### ISSUE THREAD

**Issue by saveriogzz** [apache/airflow#19387]
### Description

Something I would really like is the possibility to have the equivalent of [GitHub OAuth Authentication](https://airflow.apache.org/docs/apache-airflow/1.10.15/security.html#github-enterprise-ghe-authentication), but for [GitLab](https://docs.gitlab.com/ee/api/oauth2.html).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Airflow 1.10.15 is no longer supported. In Airflow 2+, we use Flask App Builder for web authentication, so you should report this issue to this project. Here are docs about authentication in Flask App Builder https://flask-appbuilder.readthedocs.io/en/latest/security.html

I am closing because we cannot take any additional actions.

**Comment by NK74** [comment]
Same issue, can you provide an example or a workaround for this ??

**Comment by potiuk** [comment]
@NK74 - as above - please ask your question in FlaskAppBuilder:  Here are docs about authentication in Flask App Builder https://flask-appbuilder.readthedocs.io/en/latest/security.html
