### ISSUE TITLE
Update Werkzeug requirements.txt for Safety checks

### ISSUE THREAD

**Issue by murilommen** [apache/airflow#19479]
### Description

I am not sure exactly how to contribute or modify this, but recently [safety](https://pypi.org/project/safety/) has started to flag a security issue for `Werkzeug<=2.0.2`. 
Since the latest Airflow distribution still relies on version 1.0.1, I am currently unable to pass on my CI pipeline and therefore to use Airflow in my project, since it requires to pass Python safety's check. 

### Use case/motivation

Being able to pass Python Safety checks

### Related issues

Not that I could find here

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Werkzeug <2.0 is required by Flask  which we are using. Upgrading to 2+ might require a lot of changes This is something that will not happen quickly (maybe even months), so I suggest you implement some exception in your pipeline.

**Comment by potiuk** [comment]
BTW. The fact that some tools flags a dependency as vulnerable, does not automatically mean that the application using it is vulnerable (otherwise pretty much any application out there would be vulnerable). If you do think there is a vulnerability that applies to airflow. you should follow the securitty policy and report it with all details via securty@apache.org : https://github.com/apache/airflow/security/policy

**Comment by mik-laj** [comment]
This may be problematic, because Flask==1.1.4 requires Werkzeug>=0.15,<2.0. Updating Flask may require updating many libraries including Flask-AppBuilder==3.3.3 (requires: Flask>=0.12,<2), Flask-JWT-Extended==3.25.1 (requires: Flask>=1.0,<2.0).

**Comment by murilommen** [comment]
Thank you so much for the inputs! I have just raised a specific exception for it in my automation pipeline. That was the kind of insight I was looking for 😄 Cheers!
