### ISSUE TITLE
Unable to enable ingress on Kubernetes 1.22

### ISSUE THREAD

**Issue by iAmGhost** [apache/airflow#19589]
### Official Helm Chart version

~main (development)~
1.3.0 (latest released)

Note: I've put this manually since there were no `1.3.0` choice on issue template even it's released.

### Apache Airflow version

2.2.1 (latest released)

### Kubernetes Version

v1.22.3-3+9ec7c40ec93c73 (microk8s)

### What happened

Displays error:

    Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

### How to reproduce

Install airflow with `ingress.enabled=true`

```bash
helm install airflow apache-airflow/airflow \
  --set ingress.enabled=true \
  --version 1.3.0 \
  --namespace airflow-test
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Can you please specify what version of Kubernetes do you have? To do it, you can use [`kubectl version`](https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_version/) command. Some Kubernetes distributions use a non-standard version format that can cause parsing problems.
https://github.com/apache/airflow/blob/73044af1c6908d1b075bd0127bc56c1db82b564b/chart/templates/_helpers.yaml#L604-L612

**Comment by iAmGhost** [comment]
I'm using microk8s on Ubuntu 20.04.3 Server, here's output of `kubectl version`

    $ microk8s kubectl version
    Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-3+9ec7c40ec93c73", GitCommit:"9ec7c40ec93c73c2281bdd2e4a75baf6247366a0", GitTreeState:"clean", BuildDate:"2021-11-03T10:20:42Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-3+9ec7c40ec93c73", GitCommit:"9ec7c40ec93c73c2281bdd2e4a75baf6247366a0", GitTreeState:"clean", BuildDate:"2021-11-03T10:17:37Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by potiuk** [comment]
Kubernetes 1.22 is not yet supported. We are adding 1.21 support in https://github.com/apache/airflow/pull/19557#event-5617189224 but 1.22 has not been even looked at yet.

**Comment by potiuk** [comment]
See https://github.com/apache/airflow/blob/main/README.md#requirements for the requirements of ours

**Comment by iAmGhost** [comment]
I was confused since [Apache Airflow Helm Chart](https://airflow.apache.org/docs/helm-chart/stable/index.html) only mentions Kubernetes 1.14+ cluster but not specific version.
Anyway thank you so much for support, I'll try lowering my cluster.

**Comment by sajod** [comment]
With the helm chart 1.4.0 version and with Kubernetes v1.23 the issue is still on!

I am receiving the upper mentioned error message when I turned ingress on.
I managed to fix the error by manually editing the chart:

chart/templates/webserver/webserver-ingress.yaml:
Instead of (line 22):
`{{- $apiIsStable := semverCompare ">= 1.19.x" (include "kubeVersion" .) -}}`
I changed to this:
`{{- $apiIsStable := true -}}`

chart/templates/flower/flower-ingress.yaml
Instead of (line 23):
`{{- $apiIsStable := semverCompare ">= 1.19.x" (include "kubeVersion" .) -}}`
I changed to this:
`{{- $apiIsStable := true -}}`

I am aware that for the chart version 1.4.0 only Kubernetes 1.21 is supported and I'm using 1.23.
You can still find this fix useful if you are in a similar situation.
