### ISSUE TITLE
Add configurable options to adjust branding (logo/title)

### ISSUE THREAD

**Issue by jscheffl** [apache/airflow#19848]
### Description

Dear Airflow Maintainer,

In our corporate environment we use Airflow to orchestrate custom workflows. We have extensions and use plugins to extend the use case coverage and implement project specific workflows.

We like the tooling and also the basic web UI but would like to adapt the web UI to corporate standards of branding.

So far we "patch" the navbar.html to
1) Adjust the title "Airflow" with a custom solution name
2) Replace the standard Airflow logo on the top-left.

Note that our intend is NOT to hide the base platform and that the solution is based on Airflow but we would like to have a look and feel (a bit) closer to other partner solutions. No heavy CSS customizations or re-layouting :-)

I'd request a feature for the Airflow web UI allowing to:
1) Use configuration (e.g. airflow.cfg) to set a custom application icon (to replace the standard Airflow SVG on the top left)
2) Use configuration (e.g. airflow.cfg) to set a custom application icon (favicon as used as browser icon)
3) Use configuration (e.g. airflow.cfg) to set a custom application name replacing the standard text "Airflow" besides the icon on the top navbar

I'd propose to put these configurations close to the existing options to adjust the navbar color (airflow.cfg --> [webserver] -->navbar_color)

I'd offer to contribute a PR to add this feature to one of the next releases of Airflow. Benefit for us is that we can drop the current mode of patching the navbar.html from the source tree and use a clean configuration option.

Before I would take the effort to create a PR please let me know your opinion if you would accept this feature. Counter proposals welcome. 

### Use case/motivation

As user group of Airflow who is extensively using the tool and integrates own features

We like to add our custom corporate branding to the web UI

In order to have a custom look and feel for a project solution with other partner tools
as well as in order to drop the current efforts to patch HTML code from airflow source tree and have a clean option

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
First of all - this is my personal opinion, so don't take it as "granted". I hope other PMC members will chime in, but if they don't - please reach out to the Apache Software Foundation Trademark team (as suggested below) if you are unsure. 

I personally think that such customization options are totally out of scope of our project.  Technically (and licence wise) you can modify the code in any way you want (as long as you keep attribution as specified in the licence) but adding a "customization" options where Trademarked Apache Project Logo and Trademarked log would be "customizable" might go against branding rules of the ASF. Since we are not lawyers and can't make decisions for you, it should be up to the users do such modifications and verification if they are "legal". 

The licence allows you to use the software in whatever way you want and modify it, so you are free to change it, but the names and logo of Apache projects are tradmarked and if you want to use them, you either use it as "Apache N" project or you follow "Powered by N" but you cannot connect your brand with Apache Airflow brand freely (if that's you are after).
One thing is adjusting colors of navbar (for example)  but totally different is to change/adapt logos and trademarked names - and especially to use them in conjunction with other brands.

I think if you are customizing the name and logos you use for Apache Project, first of all you should should make sure that your customisation with brand and logos are following the Apache Software Foundation rules. Names and logos of the ASF projects are trademarked and here are Apache Trademark FAQs that you should verify  - http://www.apache.org/foundation/marks/faq/. 

It's pretty much on your company and lawyers to judge and verify if what you do is fine with those or not. As a project we cannot make that decision for you, so giving a customisation option for that IMHO is not really something we should do (again we are not lawyers, and cannot make suggestions for you). 

By reading the guildeliens I believe  (but I am not a lawyer, so don't take my word for it) it's ok if you remove branding reference to Apache Airflow brand and logo and replace it with your own (keeping the attribution) - but you are not supposed to associate your brand with "Apache Airflow". You might refer to the logo and branding via "Powered by" scheme: http://www.apache.org/foundation/marks/faq/#poweredby but I am not sure if that's what you are after.

But regardless of what you can/can't do, I don't think we should make such decisions for our users and provide the customization optionf for name and logos.

**Comment by jens-scheffler-bosch** [comment]
Thanks for the feedback, the intent was not to run into legal constraints nor to get into any conflict with trademarks - of course the Apache rules like "powered by" would have been respected. Also the intent was not to modify any Apache/Airflow logo.

Closing this request for feature as well as the proposal to contribute.
