### ISSUE TITLE
Error setting dependencies on task_group defined using the decorator

### ISSUE THREAD

**Issue by jceresini** [apache/airflow#19903]
### Apache Airflow version

2.2.2 (latest released)

### Operating System

MacOS 11.6.1

### Versions of Apache Airflow Providers

$ pip freeze | grep airflow
apache-airflow==2.2.2
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-sqlite==2.0.1

### Deployment

Other

### Deployment details

`airflow standalone`

### What happened

```
AttributeError: 'NoneType' object has no attribute 'update_relative'
```

### What you expected to happen

Task group should be set as downstream of `start` task, and upstream of `end` task

### How to reproduce

* Add the following code to dags folder

```python
from datetime import datetime

from airflow.decorators import dag, task, task_group


@dag(start_date=datetime(2023, 1, 1), schedule_interval="@once")
def test_dag_1():
    @task
    def start():
        pass

    @task
    def do_thing(x):
        print(x)

    @task_group
    def do_all_things():
        do_thing(1)
        do_thing(2)

    @task
    def end():
        pass

    start() >> do_all_things() >> end()


test_dag_1()
```

* Run `airflow standalone`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by subkanthi** [comment]
Looking at this issue.

**Comment by subkanthi** [comment]
Looks like the problem is here for both the tasks, with pass or print, the task runs are not created, but replacing it with sleep, a task run is created and added to the DB. 
` @task
    def end():
        pass`
`@task
    def end():
        pass`

It might be useful to indicate this to the user, still trying to figure out where this logic is performed.

**Comment by moshederri** [comment]
Quick question about this - i tried changing the content of the function to something other than `pass` or `print` but for some reason i am still getting the same exception (i'm probably doing something wrong).  But regardless - working with the dag decorator, isn't the rshift misused here? 
i mean, shouldn't:
`start() >> do_all_things() >> end() `
be just:
```
start() 
do_all_things()
end()
```

**Comment by uranusjr** [comment]
I don’t recall any logic checking a function’s content, so this is very surprising. I can reproduce though; it seems like if the function does not have a body, even the _task_ itself is not created in the DAG.

**Comment by subkanthi** [comment]
Im able to reproduce this in `standalone` mode even without the taskgroup ` start() >> end()`

```
@dag(start_date=datetime(2023, 1, 1), schedule_interval="@once")
def test_dag_1():
    @task
    def start():
        pass

    @task
    def do_thing(x):
        print(x)

    @task_group
    def do_all_things():
        do_thing(1)
        do_thing(2)

    @task
    def end():
        pass

    start() >> do_all_things() >> end()


test_dag_1()
```

**Comment by uranusjr** [comment]
Oh I see what’s going on. This has nothing to do with the task function, but the task _group_ function. Currently, the `@task_group` decorator is intended to be used like this:

https://github.com/apache/airflow/blob/e8b5ab9efe93f826a2b521b5d1cac0404354c3b4/airflow/example_dags/example_task_group_decorator.py#L60-L63

Note how the task group function returns `task_3(...)`, which produces a BaseOperator.

In your example, however, the task group function does not return anything, i.e. implicitly returns None. This means `start() >> do_all_things()` becomes `DummyOperator(...) >> None`, which fails with the exception.

However, I don’t think the existing function-chaining syntax suits the need here, since `do_thing(1)` and `do_thing(2)` are supposed to be independent (and both depend on `start()` and depended by `end()`). So we need to extend the `@task_group` decorator a bit to make this work.

**Comment by uranusjr** [comment]
Actually there is a way to make this work under the current `@task_group` functionality; you need to do this:

```python
@task_group
def do_all_things():
    return [do_thing(1), do_thing(2)]
```

But this is totally not obvious and probably does not look nice, so #20671 is still useful.
