### ISSUE TITLE
Update Google provider package

### ISSUE THREAD

**Issue by yan-hic** [apache/airflow#20014]
### Description

The latest `Google` provider package, 6.10, contains quite old packages e.g. `google-cloud-container` is 1.0.1, which is 18 months old and 10+ versions back.
This was just to inquire on plans or a schedule to update - and what components if not all.

### Use case/motivation

We use `google-cloud-container` to administer existing clusters in GKE e.g. scale up and down node pools, query pod and service details, deploy on-the-fly,... For that we have today a Cloud Run service, that tasks in airflow interact with through http. 
We'd like to migrate and embed these in airflow taskflow, to get rid of the CR dependency, but we rely on a recent version of `google-cloud-container` (2.10).

Request is pretty much generic as other packages are old too.  

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
We already have generic open issue https://github.com/apache/airflow/issues/12120
We welcome PRs, if the provider doesn't support new libs versions feel free to open PRs to update.

**Comment by potiuk** [comment]
And BTW @yiga2 - since you are in the need of it - maybe you could simply take on the task of updating it? Usually in the open source world things will not happen if there is no-one doing it, so opening an issue does not change much - but doing the PRs actually do. Airflow has > 1800 contributors and such contribution would be most welcome. There are few other similar changes as you can see in the related PRs, so you could simply take on that particular one and try to fix it.

**Comment by potiuk** [comment]
AH I just now see that @eladkal wrote the same, shorter :)
