### ISSUE TITLE
Configurable UI clock format

### ISSUE THREAD

**Issue by edwardwang888** [apache/airflow#20045]
### Description

There has been some interest expressed in having a configurable UI clock datetime format (#18866). The options currently proposed are:
* Adding a toggle to show/hide the date
  * We can include other common formatting options that are requested
* Accepting a datetime format string specifying a custom format
  * I imagine the simplest way to implement this is to ask the user to enter a valid format string of the datetime formatting library that is in use at the time. For example, if we are using `moment.js`, then ask the user to enter a valid `moment.js` format string. Since I expect this option to be used mainly by advanced users, I think it is fine to ask them to look up the valid format string syntax.

### Use case/motivation

The date was removed from the UI clock in Airflow 2 - some liked it, and others didn't. Everyone has different preferences, so making it configurable would be a suitable approach.

### Related issues

The original PR with some previous discussion: #18866

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
@edwardwang888 are you still working on this issue?

**Comment by edwardwang888** [comment]
@eladkal Sorry for the delay - yes, I am aiming for the next few weeks if that is okay.

**Comment by eladkal** [comment]
Just sharing my take on this
If this is configurable I would prefer it to be configurable by user and not some cluster wide definition in `airflow.cfg`
I have dozens of devs working on the same Airflow instance - each one of them can have their own point of view and preference. I as cluster administrator should not / can not decide for them which clock format is best.

I don't know if this is doable but if this is to be configurable I would feel more comfortable if this could be set by each user individually via `/users/userinfo/`

**Comment by bbovenzi** [comment]
Is this just the time display in the top nav bar or the date format to use across the whole UI?

**Comment by edwardwang888** [comment]
This is just for the top nav bar. Yes that's correct, the intention is to make it configurable per user, similar to how each user can choose their display timezone.

**Comment by alexbegg** [comment]
> Just sharing my take on this If this is configurable I would prefer it to be configurable by user and not some cluster wide definition in `airflow.cfg` I have dozens of devs working on the same Airflow instance - each one of them can have their own point of view and preference. I as cluster administrator should not / can not decide for them which clock format is best.
> 
> I don't know if this is doable but if this is to be configurable I would feel more comfortable if this could be set by each user individually via `/users/userinfo/`

I also think that makes the most sense to not make it only an installation-wide configuration.

However, I don't think the user info that you can see at `/users/userinfo/` would be the best place for that configuration, because user info is meant to be something an admin sees/edits/creates, such as a user's "role", and admins won't know what a user's datetime format preference is when creating a user.

I think it would be the most convenient if if can be configured the same way you can change your time zone in the UI, via the clock dropdown on the menu. So, like the user's selected time zone, the setting can also be stored via LocalStorage if we go that route. However I also would not want to complicate the UI of the time zone dropdown, so a toggle to show/hide the date would be the easiest.

If we go with the user info setting then I think it would be fine to provide a full datetime format text input box, since it is a full-page form anyways.
