### ISSUE TITLE
Scheduled DAG Runs with Custom Parameters

### ISSUE THREAD

**Issue by theis188** [apache/airflow#20073]
### Description

Feature request: add the ability to attach multiple schedule/parameter pairs to a DAG. For example

```
SCHEDULE = [
   ("0 0 * * 1", MONDAY_PARAM),
   ("0 0 * * 2", TUESDAY_PARAM)
   ...
]
```

Currently, scheduling DAGs can be accomplished by using the `schedule_interval` kwarg on the DAG initialization [Link](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#dag-runs)

The documentation for DAG Run, describes the custom parametrization as follows [link](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#passing-parameters-when-triggering-dags):

> When triggering a DAG from the CLI, the REST API or the UI, it is possible to pass configuration for a DAG Run as a JSON blob.

So presumably (and in practice), any scheduled DAG Run will only use the default parameters.

An internet search also did not indicate a way of scheduling DAGs with custom parameters.

### Use case/motivation

When managing many similar jobs that run on different schedules, our approach so far has been to create one DAG per job type. In terms of code, we can efficiently create these DAGs using DAG and task factory functions, but DAG management on the Airflow frontend becomes cluttered (although mitigated by Tags and search features). The DAG scheduled with custom parameters would provide an alternate means of managing these types of workflows.

Scheduling with custom parameters is a feature in, for example, Jenkins. We have adjusted by using functional DAG creation as described, but this would be a nice feature as well.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
"triggering" time is a bad idea for specifying custom schedules, because the  DAGs area already created and scheduled.

The DAG Run that you mention is only single DAG execution, and since you are triggering it - by definition it has no schedule, because this is jus single "execution" of the DAG Run - it has "no schedule" at the point you trigger it (because this is a DAG Run , not DAG).

There is no way we can change "schedule" by submitting a DAG Run at this point - it's just logically impossible :).

And It simply not the right "place" - the UI / API are not supposed to change anything in DAG definition (at least not yet). For now the only way how you can modify the DAG is via parsing DAG file coming from the DAG_FOLDER directory. There is no other way (for now)

However as of Airflow 2.2 you hav custom timetables that might help you a bit to manage complex schedules  There is no way we can change "schedule" by submitting a DAG at this point. It simply not the right way - also the UI / API are not supposed to change anythin in DAG definition.(stll with using DAG Factories ) but I am not sure if it addresses your problem.

https://airflow.apache.org/docs/apache-airflow/2.2.0/howto/timetable.html

Also there are some AIPs - Airflow Improvement Proposals  (which we are not actively working on right now) - for example https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher - that might better fit your rrequirements. But this will take quite a while likely as it is not at all priority for anyone that I know would work on

**Comment by potiuk** [comment]
If this is just if Monday =-> use this parameter, if Tuesday -> use that parameter this should be super-easily achieved if youhave a common `get_parameter(logical_date)` method that you could use in your tasks that would return diferent value based on which date the logical date is for:

```
def get_parameter(logical_date):
    if Monday: 
        return x
   if Tuesday: 
       return y
```
You could even base it on cron expressions if you would like to using croniter. What's the problem with that?

**Comment by potiuk** [comment]
(still won't fix BTW)

**Comment by potiuk** [comment]
Remember that your DAG is python. You can run any code in your task definition and have it behave dynamically. You should not tthink "declaratively" on what you can declare but rather what flexibillty the custom python code gives you.

**Comment by potiuk** [comment]
I think you just (same story) do not really get the powers it gets you to use Python to define the variations and not "declarative" way. That's a basic misunderstanding of how Airflow works. You ARE supposed to generate multiple DAGs using DAG Factories. This is how in Airflow you define parameterized DAGs. This is the only pattern that will work - and we have the whole tutorial on how to do it: 

https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#dynamic-dag-generation

The way how you can do it involves storing your parameters in a json file. environment variables, or even generated DAG code.  Simply - use your parameters, to generate DAGs, not the other way round.

**Comment by paavanb** [comment]
Ah, what is the point of the DAG configuration JSON then? Having trouble understanding why that is an option at all, if it is never meant to be used.

**Comment by potiuk** [comment]
IT's to provide parameters to single DAG run - triggered or via API if you want to override any of the default parameters for that SINGLE DagRun. That's it.

**Comment by potiuk** [comment]
https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#passing-parameters-when-triggering-dags

**Comment by potiuk** [comment]
DAG and DAGRun are two different entities. Even the parameters are passed as "dag_run.conf", not "dag.conf". You seem to mix the meaning of the two entities.

**Comment by paavanb** [comment]
Right, I get that: I can go into the UI and provide parameters for a single dag run. That feature is very useful, since we have DAGs that are usually manually triggered with different parameters. But I can't provide parameters to a _scheduled_ dag run?

**Comment by uranusjr** [comment]
Because a scheduled DAG run have not happened and does not exist anywhere when you want to provide it params, so how do you tell the scheduler to do it for something that does not exist yet? It is of course theoratically possible, but would require a much more involved design (semantics, storage infrastructure to persist the user request until the run actually happens, and UI elements to create, inspect, and edit the user-supplied params). instead of be trivially added. Feel free to work on a pull request to provide this.

**Comment by potiuk** [comment]
And it makes also no sense to do it, because what you essentially want to do is to provide a way to dynamically generate parameters based on the actual run being executed. Which in airflow is done by imperative code rather than declarative definition. The whole idea of DAG in Airlfow is that it is imperatively generated by Python code. In this case it's the same - you should write a code that derives the parameters for scheduled run, rather than "declaratively" describe the relation between the dag run and the  parameters it does. 

Doing it declaratively is very, very limiting and whatever you come up with there, can also be done (very easily) writing a Python code. Defining DAGs IS writing Python code. Just follow the Airflow way of doing things.

**Comment by paavanb** [comment]
Actually, it turns out that the `params` option is very close to what I'm looking for: it allows me to specify a dictionary that is then accessible to the DAG run, even if the run was scheduled. However, I don't seem to be able to specify multiple schedules with different `params` . I do see how this would be difficult to manage in the UI though.

**Comment by ashb** [comment]
> However, I don't seem to be able to specify multiple schedules with different params in Python

Yes, that is on the roadmap but isn't possible yet.

**Comment by ashb** [comment]
A work around for now is to have a "trigger" dag that has a single operator, a TriggerDagRun operator to kick off runs of the parameterized dag with the right params each time.

**Comment by paavanb** [comment]
Thank you!
