### ISSUE TITLE
Hook inside the plugin folder does not recognized new conn_type and UI will not show it

### ISSUE THREAD

**Issue by harlequin** [apache/airflow#20317]
### Apache Airflow version

2.2.2 (latest released)

### What happened

A custom connection hook inside the plugin folder will not displayed and listed inside the UI.
```python
class PowerBiHook(BaseHook):
    conn_name_attr = 'powerbi_conn_id'
    default_conn_name = 'powerbi_default'
    conn_type = 'powerbi'
    hook_name = 'PowerBI'

    @staticmethod
    def get_connection_form_widgets() -> Dict[str, Any]:
        """Returns connection widgets to add to connection form"""
        from flask_appbuilder.fieldwidgets import BS3TextFieldWidget
        from flask_babel import lazy_gettext
        from wtforms import StringField

        return {
            "extra__azure_batch__account_url": StringField(
                lazy_gettext('Batch Account URL'), widget=BS3TextFieldWidget()
            ),
        }

    @staticmethod
    def get_ui_field_behaviour() -> Dict:
        """Returns custom field behaviour"""
        return {
            "hidden_fields": ['schema', 'port', 'host', 'extra'],
            "relabeling": {
                'login': 'Batch Account Name',
                'password': 'Batch Account Access Key',
            },
        }
``` 

### What you expected to happen

The UI shall show the new connection type and UI changes

### Operating System

docker

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
To register a new connection type, you need to create a new provider.

**Comment by harlequin** [comment]
Can a new provider be programmed and load dynamically from the plugins folder?

Or shall it be always a sperate package with pip install ?

**Comment by uranusjr** [comment]
It must provide some package metadata to be recognised as a provider, and `pip install` is the easiest way to generate that metadata.

**Comment by potiuk** [comment]
It's not possible now and it's pretty deliberate. For multi-tenant scenarios, adding custom code that modifies your UI **should** only be possible by adding new packages rather than adding new code on the side. This might change in the future. We are working on "multitenancy" features for Airlfow and we are going to gradually add new improvements. One of the changes there should be a possibility to add new configuration by "declaration" (currently you literally inject a code that is executed in the Webserver context, which makes it not really cool for security). 

But it won't be fast as it will require connection UI changes which are part of the modern web UI changes.

**Comment by harlequin** [comment]
Thanks for detailed explanation.
I absolutly understand your doubts.

Issue can bei closed.
