### ISSUE TITLE
infinite recursion in StreamLogWriter

### ISSUE THREAD

**Issue by derkuci** [apache/airflow#20500]
### Apache Airflow version

2.2.2

### What happened

When a task customizes logging (add a stream handler) and throws an exception, the airflow logging code goes into an infinite loop, doubling the log buffer every time, and quickly using up all the memory.  The call stack is something like:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1390, in _run_raw_task
    self.handle_failure(e, test_mode, error_file=error_file, session=session)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1704, in handle_failure
    self.log.error("Task failed with exception", exc_info=error)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/log/logging_mixin.py", line 119, in write
    self.flush()
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/log/logging_mixin.py", line 126, in flush
    self._propagate_log(b)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/log/logging_mixin.py", line 109, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/lib64/python3.9/logging/__init__.py", line 1512, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
<and so on ...>
```

### What you expected to happen

No log recursion.

### How to reproduce

Raise an exception within a `PythonOperator` (below is an example of a function to be called).
```
        import logging
        logging.getLogger().addHandler(logging.StreamHandler())
        raise RuntimeError('trigger logging')
```

### Operating System

CentOS 8 with Python 3.9

### Deployment

Other

### Deployment details

pip3 install apache-airflow[celery,mysql,ssh]==2.2.2 'celery<5.2' 'click<8' 'SQLAlchemy<1.4'

### Anything else

I am not sure if this is indeed a bug or a misuse of the logging handlers.  Any suggestion is highly appreciated!

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Airflow tasks' stderr and stdout are by default redirected to the task log. this is necessary to capture all the output from the tasks to the log. You cannot really write logs to stderr to the task.

You can send the logs to other loggers but not to stderr - because this is exactly what is happnening - the stderr of your task is routed to the logger, sent to stderr and routed back. 

You can see here for details on how you can customize the logging, but adding logger to write to stderr is not going to work.: https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html#advanced-configuration

It's a limitation of Airflow in order to handle all the output for tasks (including even unintended stderrr wrting.

**Comment by potiuk** [comment]
We might consider this in the future to make it possible but unti we revamp the logging mechanism of airflow this is actually a feature, not a bug.

**Comment by derkuci** [comment]
I have no problem with calling this a feature, but would suggest a few things to help (others) debug when the circular logging indeed happens.
* `StreamLogWriter.write()` could be slightly modified to swap the buffer before sending another message to `_propagate_log`.  Something like
  ```python
     buf, self._buffer = self._buffer, ''
     self._propagate_log(buf.rstrip())
  ```
  This will change the growth of buffer from exponential to linear, and the users may hit the recursive stack limit before the out-of-memory error, and would more easily figure out the issue.
* There are cases where users don't have much control over the code (tasks) run in airflow.  It's also quite possible some weird import statement pulls in the unwanted redirection.  If airflow could detect such misuse, or even better, could separate its own log from users (sorry, I don't know how), that would be much nicer.

Anyway, just hope this would save others some time when they deploy the new versions.

**Comment by potiuk** [comment]
>   This will change the growth of buffer from exponential to linear, and the users may hit the recursive stack limit before the out-of-memory error, and would more easily figure out the issue.

Unfortunately this would change the logging behaviour. which we do not want to do as it would affect legitimately written logs and use extra memory when not needed. What we do with log writtng is correct - we should not use extra buffer nor strip messages. The problems is that by the time  you write log to stderr, stderr is directly routed back to the stream writer that propagates the logs further. It's not intended to redirect to itself. Yet by adding StreamHandler it happens. 

It happens extremely rarely, I think it makes little sense to make any workarounds  without revamping the logging infrastructure - it would be a band-aid and not worth the effort. I think. But If you find a solution that will prevent this situation from happening - for example failing if the redirection is detected. without unnecessary performance overhead on existing logging, then PRs are most welcome.

> * There are cases where users don't have much control over the code (tasks) run in airflow.  It's also quite possible some weird import statement pulls in the unwanted redirection.  If airflow could detect such misuse, or even better, could separate its own log from users (sorry, I don't know how), that would be much nicer.

Surely. It can happen and it is impossible to detect unless you know exactly what to look for (for example we have protection agains infinite recursion in secret masker).  But then we know exactly what to do. If the user does something wrong and perfoms (jsut tried it myself):

```
def task(s):
      task(s + '   '*len(s))

task(' ')

```

there is not much one can do. This is Python. You can do anything. 

> Anyway, just hope this would save others some time when they deploy the new versions.

I hope so too. This is one of the legitmate uses f github issues and discussions. They are searchable and if somoene has similar issue, I hope they will find it. That might be actually the cheapest and most effective solution overall.

**Comment by derkuci** [comment]
> > This will change the growth of buffer from exponential to linear, and the users may hit the recursive stack limit before the out-of-memory error, and would more easily figure out the issue.
> 
> Unfortunately this would change the logging behaviour. which we do not want to do as it would affect legitimately written logs and use extra memory when not needed. What we do with log writtng is correct - we should not use extra buffer nor strip messages. The problems is that by the time you write log to stderr, stderr is directly routed back to the stream writer that propagates the logs further. It's not intended to redirect to itself. Yet by adding StreamHandler it happens.

Please be noted that the stripping is in the current airflow code; I copied the behavior to keep things the same when nothing bad happens (and if we don't strip, we get extra blank lines in the log).  And since Python uses references, I don't see any "extra" buffering here.  The only changed part is when the buffer (that StreamLogWriter keeps log messages) is cleared, before or after the recursion.

**Comment by potiuk** [comment]
> Please be noted that the stripping is in the current airflow code; I copied the behavior to keep things the same when nothing bad happens (and if we don't strip, we get extra blank lines in the log). And since Python uses references, I don't see any "extra" buffering here. The only changed part is when the buffer (that StreamLogWriter keeps log messages) is cleared, before or after the recursion.

Then I simply did not understand what you proposed. Maybe open a PR and we can discuss it with others and see if it makes sense?  It's always best to discuss stuff when there is a draft PR showing the change and explaining the reasoning.

**Comment by derkuci** [comment]
Here you go, #20541 

Thanks for your time.

**Comment by 0ersted** [comment]
I encountered the same issue when my code accidentally use `coloredlogs` to set its log format. Then the next line of airflow log or sys.out redirected to airflow will enter the infinite loop.

Airflow version: 2.2.2; coloredlogs version: 14.0. However, this issue does not exist on my legacy deployment of Airflow 1.10.10.

I hope this issue can be addressed as it takes me several days to find out the root cause. The redirect feature is good but the misuse apparently becomes a bug in this extreme case. I will appreciate it if you can manage to fix it.

**Comment by casper-voltgoed** [comment]
I have the same problem where I import a python package that contains its own logger, how do I remove this logger then. I tried removing the StreamHandler object from the "imported" logger, but then I get no logs at all anymore.

I am probably understanding loggers wrong, but I have no idea how to solve this, other than to not import the package at all, which is not a good option

**Comment by potiuk** [comment]
Can you please (as asked) opena A NEW Issue about it. 

> opening a new issue and providing similar level of details as submitted in here might be a good idea.

This might be a different issue and commenting on a closed issue that have been resolved/closed makes it quite a bit more difficult for those who want to help you, to actually help you. Empathy towards those who want to help you to solve your problem is a good idea. I understand that it  is  A BIT more difficult to open a new issue, because you have to provide all the details in it, but providing all the details in the issue that we asked for, is exactly for the reason that you make it easier for anyone who wants to help you to do it (mostly people here help others in their free time, so spending a bit of  time on your side, to help those who want to help you to spend less of their time on asking for the details is something we pretty much expect.

**Comment by potiuk** [comment]
Can you please (as asked) open A NEW Issue about it. 

> opening a new issue and providing similar level of details as submitted in here might be a good idea.

This might be a different issue and commenting on a closed issue that have been resolved/closed makes it quite a bit more difficult for those who want to help you, to actually help you. Empathy towards those who want to help you to solve your problem is a good idea. I understand that it  is  A BIT more difficult to open a new issue, because you have to provide all the details in it, but providing all the details in the issue that we asked for, is exactly for the reason that you make it easier for anyone who wants to help you to do it (mostly people here help others in their free time, so spending a bit of  time on your side, to help those who want to help you to spend less of their time on asking for the details is something we pretty much expect.

**Comment by casper-voltgoed** [comment]
I'm sorry I read over that part of your reply, will open an issue 👍
