### ISSUE TITLE
How to trigger an Operator when the other one finished?

### ISSUE THREAD

**Issue by nouseforacode** [apache/airflow#207]
I would like to trigger an Operator when the other task is done, but no matter if the upstream succeeded or not.

I have tried to use a single-slot pool and priority_weights, but it seems not to work the way I need. It puts tasks to the queue accordingly to the weights but then runs them randomly.

I guess in my case I have to create some sort of Sensor like `ExternalTaskSensor`. Is this the only way?

**Comment by r39132** [comment]
Hi!
You need to connect your operators with a  `set_upstream` or `set_downstream` command.

For example.

```
OP1  = BashOperator( ... )
OP2 = PythonOperator( ... )
OP2.set_upstream(OP1)
OP3 = EmailOperator( ... )
OP3.set_upstream(OP2)
```

This will create a chain, one of the simplest DAG topologies : `OP1 ==> OP2 ==> OP3`

You don't need pools or priorities. Just run `airflow scheduler` and let it execute your DAG. If you haven't created these dependencies, then the scheduler will just likely assume they are not related and execute them in random order. When you set it up as I am shown above, the scheduler will not execute downstream operators until and unless upstream operators have succeeded.

**Comment by nouseforacode** [comment]
Hi! 
Thanks for your quick reply.

Sorry if I wasn't clear enough. I need to keep the order of jobs execution but my jobs doesn't depend on each other and they never should be skipped. In your example OP3 will not run if OP2 fails. But what if I need to just ignore OP2 failure and execute OP3 after it?

**Comment by r39132** [comment]
It sounds like you want the operators to make a best-effort attempt at doing some work. Regardless of the outcome, you want the chain to proceed. 

In this case, I would just use a Python operator for all of my tasks. In each Python operator, I would catch and eat any errors or exceptions raised inside the task code body so that the next operator could proceed. In the end, all of your PythonOperator tasks will appear on the UI as having succeeded, even if they did not. 

If you actually want to retain information about what passed and what failed, it sounds like we need support for a new configuration parameter at the task level : `continue_on_failure =  True`. Is that what you are asking for? 

If so, then it does sounds dubious at first glance, especially if I think about typical ETL-style workloads. In ETL-style work-loads, it's generally a bad practice to `continue_on_failure`. However, I can envisage use-case where you are trying to load some 3rd party data or keep some cache fresh, and you don't have control over the availability of that 3rd party data source. In these cases, best-effort is all you can do. And in such cases, having an accurate history, especially a visual history such as shown below, would be very useful. If this is what you are thinking, then I would add my vote.

<img width="856" alt="screenshot 2015-07-31 00 38 08" src="https://cloud.githubusercontent.com/assets/581734/9002728/7d97bf64-371c-11e5-8422-4117730a1a39.png">

**Comment by r39132** [comment]
BTW, as a user of this project, I don't believe `continue_on_failure` exists today. It would need to be a feature request. I'd suggest changing the title to `Feature Request : Support optional continue_on_failure task instance semantics`

**Comment by nouseforacode** [comment]
I think we are on the same page. I have a bunch of tasks that provide updates for the database. These tasks can die because of bad input, 3rd party data unavailability or some unexpected throw. I want to give them a chance to prepare updates but even if all of them fail I still need to rebuild the database.

This behavior can be achieved with `continue_on_failure` you described. And I believe we have some other options:
1. Create a sensor like `ExternalTaskSensor`. The only difference will be filter arguments: 
   https://github.com/airbnb/airflow/blob/master/airflow/operators/sensors.py#L127
2. Use a single-slot pool and priority_weights. I think it is the most proper way, but I couldn't make it work.

**Comment by r39132** [comment]
Now that I understand what you are trying to accomplish, both of your approaches seem valid. It does look like no. 2 is a bug. I'd file that as a separate bug and link that bug here. It would be good to provide your code or sample code in the bug -- I find that always results in the fastest turn-around from the Airbnb team.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/airflow/pull/209

**Comment by r39132** [comment]
Very cool. @nouseforacode can you beta test this and give feedback? I don't have an immediate need for this feature.

**Comment by nouseforacode** [comment]
Many thanks to you both! I am testing now a similar Operator which I created soon before #209. Everything looks good except a small issue with Airflow UI. Dependencies established with the help of the Sensor aren't visible on the Graph View tab.  But it is still useful if we pay attention to the tasks creation order.
![airflow-issue](https://cloud.githubusercontent.com/assets/10090277/9059237/e1e81f8a-3ab0-11e5-8bcb-a25e43e26d84.png)

**Comment by mistercrunch** [comment]
ExternalTaskSensor assumes that you have a dependency to another DAG, so it doesn't draw any dependency, using it on the same DAG with a previous date is a bit of a hack. 

The only dependencies drawn are the ones coming through the normal task dependencies mechanism.
