### ISSUE TITLE
Write access to /home/airflow for "default" user in docker

### ISSUE THREAD

**Issue by ghislainp** [apache/airflow#20776]
### Apache Airflow version

2.2.3 (latest released)

### What happened

The airflow home directory in the docker official image has rights:
drwxr-xr-x 1 airflow root 4096 Jan  9 19:49 /home/airflow/

It is not writable by the group. The "default" user created by entrypoint_prod.sh can not write in its home.

### What you expected to happen

I expected the rights to be drwxrwxr-x /home/airflow as documented here: https://airflow.apache.org/docs/docker-stack/entrypoint.html

### How to reproduce

try in a apache/ariflow:2.2.3 running container id xxxx: 
sudo docker exec xxxx touch /home/airflow/iswritable

it fails with permission denied

### Operating System

PRETTY_NAME="Debian GNU/Linux 10 (buster)" NAME="Debian GNU/Linux" VERSION_ID="10" VERSION="10 (buster)" VERSION_CODENAME=buster ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### Deployment

Docker-Compose

### Deployment details

use the official docker-compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by fredthomsen** [comment]
Have you modified the provided compose file at all?  I had a similar sort of issue; however, I realized that in customizing the compose file to my needs I had swapped `AIRFLOW_UID` to another variable, thus leading me to running processes in that container as the `default` user.

The `default` user created by the entrypoint script is not suppose to have write access to the `airflow` user home directory.  That home directory is created via the `adduser` command in the `Dockerfile` and has the standard home directory permissions.

**Comment by potiuk** [comment]
Thanks @ghislainp for reporting it - this will be fixed in #20238! 

@fredthomsen:

> The default user created by the entrypoint script is not suppose to have write access to the airflow user home directory. That home directory is created via the adduser command in the Dockerfile and has the standard home directory permissions.

True. The thing is that we should indeed treat all the users in the image in the same way. Our image is Open-Shift compatible, which means that it allows to run the image as arbitraty user as long as it belongs to group 0  (https://airflow.apache.org/docs/docker-stack/entrypoint.html#allowing-arbitrary-user-to-run-the-container). There was indeed a bug there that the home directory (unlike ~/.local) was not group-writeable. This allowed arbitrary user to install pip packages (by default PIP_USER="true" makes all the packages installed to ~/.local) but if the user wanted to store anything in Home dir, it was not (by default) possible.

The PR #20238 fixes it.

**Comment by potiuk** [comment]
```
jarek@Hyperion:~/code/airflow] optimizes-dockerfile+ ± docker run -it ghcr.io/apache/airflow/main/prod/python3.9 bash                  

airflow@cc852b02eff7:/opt/airflow$ cd
airflow@cc852b02eff7:~$ ls -la
total 36
drwxrwxr-x 1 airflow root 4096 Jan 11 00:55 .
drwxr-xr-x 1 root    root 4096 Jan 11 00:55 ..
-rw-rw-r-- 1 airflow root  220 Jan 11 00:55 .bash_logout
-rw-rw-r-- 1 airflow root 3526 Jan 11 00:55 .bashrc
drwxrwxr-x 1 airflow root 4096 Jan 11 00:55 .local
-rw-rw-r-- 1 airflow root  807 Jan 11 00:55 .profile
```

**Comment by fredthomsen** [comment]
Thanks for explaining this @potiuk.
