### ISSUE TITLE
Spark Submit Operator reporting job failure. Not able to poll the successful completion of Spark Job.

### ISSUE THREAD

**Issue by karthyk16** [apache/airflow#20949]
### Apache Airflow Provider(s)

apache-spark

### Versions of Apache Airflow Providers

2.0.3. Same issue in 2.0.1 as well.

### Apache Airflow version

2.1.2

### Operating System

Red Hat Enterprise Linux

### Deployment

Other

### What happened

We have used Spark Submit operator from Airflow to submit a Spark job on Standalone cluster mode. Spark job gets submitted successfully and we have used spark.standalone.submit.waitAppCompletion = true as a conf. So, the client waits for the application to complete. On successful completion of the application and executor termination, airflow is not able to poll the successful completion of job and mark the job as successful. Instead it marks the job as failure even though the job was successfully finished. Status of application in Spark History shows Finished.

[2022-01-18, 20:49:37 UTC] {spark_submit.py:523} INFO - 22/01/18 20:49:37 INFO ClientEndpoint: State of driver driver-20220118204802-0000 is FINISHED, exiting spark-submit JVM.
[2022-01-18, 20:49:37 UTC] {spark_submit.py:523} INFO - 22/01/18 20:49:37 INFO ShutdownHookManager: Shutdown hook called
[2022-01-18, 20:49:37 UTC] {spark_submit.py:523} INFO - 22/01/18 20:49:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-1b7f430e-2cb8-493e-83b3-07b1a9c5728b
[2022-01-18, 20:49:38 UTC] {spark_submit.py:456} DEBUG - Should track driver: True
.
.
.
.
[2022-01-18, 20:50:08 UTC] {spark_submit.py:587} DEBUG - polling status of spark driver with id driver-20220118204802-0000
[2022-01-18, 20:50:08 UTC] {spark_submit.py:409} DEBUG - Poll driver status cmd: ['spark-submit', '--master', 'spark://ip-10-150-101-107.ap-south-1.compute.internal:7077', '--status', 'driver-20220118204802-0000']
[2022-01-18, 20:50:10 UTC] {spark_submit.py:541} DEBUG - spark driver status log: 22/01/18 20:50:10 WARN RestSubmissionClient: Unable to connect to server spark://ip-14-1XXXX-127.ap-south-1.compute.internal:7077.
[2022-01-18, 20:50:10 UTC] {spark_submit.py:541} DEBUG - spark driver status log: Exception in thread "main" org.apache.spark.deploy.rest.SubmitRestConnectionException: Unable to connect to server
[2022-01-18, 20:50:10 UTC] {spark_submit.py:541} DEBUG - spark driver status log: at org.apache.spark.deploy.rest.RestSubmissionClient.$anonfun$requestSubmissionStatus$3(RestSubmissionClient.scala:163)

### What you expected to happen

Airflow hook should be able to poll the status correctly and mark the job status appropriately.(Failed in case of genuine failure and successful in case of successful completion of job.

### How to reproduce

Create an airflow DAG with Spark submit operator. Use "spark.standalone.submit.waitAppCompletion = true" in conf so that client will wait for application to complete. Enable Debug logs in Airflow to see the log trace.

### Anything else

Happens every time and its a blocker for using spark submit operator.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you @karthyk16  - feel free to fix it!

**Comment by karthyk16** [comment]
> Assigned you @karthyk16 - feel free to fix it!

Thanks @potiuk  : Our team member has fixed it using a custom operator. Our team member will raise the PR for this issue in the next couple of days. Hope that's fine.

**Comment by potiuk** [comment]
> > Assigned you @karthyk16 - feel free to fix it!
> 
> Thanks @potiuk : Our team member has fixed it using a custom operator. Our team member will raise the PR for this issue in the next couple of days. Hope that's fine.

Perfect :)

**Comment by poluektik** [comment]
hi @karthyk16 
We hit the same issue, do you mind to share the solution or submit PR?

**Comment by dgslv** [comment]
hey, same issue here. any suggestions on how to proceed?

**Comment by prajvan** [comment]
@dgslv @poluektik @karthyk16 can you guys shed some light on how you guys are tackling the issue, we are running into this at times.

**Comment by poluektik** [comment]
We've implemented our own Operator.

**Comment by hunnguye** [comment]
I would like to revive this issue.
We are working with AIrflow 3.3 and a Spark Standalone Cluster deployment.

The main issue is, that this kind of deployment has two endpoints.
* 7077: the binary endpoint for submitting an application
* 6066: the REST endpoint, in this case especially relevant for status polling.

https://github.com/apache/airflow/blob/f8b8461e8191f88e72ad8c05b248e0385c21db99/providers/apache/spark/src/airflow/providers/apache/spark/hooks/spark_submit.py#L671
After a spark submit, the hook tries to poll the status using the method above.
However, it conditionally branches depending on whether the port is 6066 or not using either a curl or the spark binaries to poll the job status.

If we submit an application using the binary endpoint (7077), it will therefore try to invoke a `spark-submit --master url --status driverid` for polling the status, which will cause the error message as described in the inital issue statement. This is because the spark submit binary internally apperently executes a rest call when requesting the status which requires the endpoint at 6066. 


Although submitting an application through the REST endpoint to spark should be possible, Airflow only supports the binary approach anyway. Therefore, the defined connection_id has to point to the binary endpoint
https://github.com/apache/airflow/blob/f8b8461e8191f88e72ad8c05b248e0385c21db99/providers/apache/spark/src/airflow/providers/apache/spark/hooks/spark_submit.py#L650


The workaround as other mentioned, is to override the method of the hook to not conditionally branch on port 6066 or use some other logic, to invoke a curl call to the restendpoint (on 6066) even if the master url doesn't mention port 6066.

However, I also noticed that with recent spark provider development, this issue has already been partially solved by the spark submit operator. 

https://github.com/apache/airflow/blob/f8b8461e8191f88e72ad8c05b248e0385c21db99/providers/apache/spark/src/airflow/providers/apache/spark/operators/spark_submit.py#L204

Starting with Airflow 3.3, a task retry would check on job_status first to figure out, whether the previous try actually succeded and also uses a status request (similiar to that of the polling). I believe it contains the logic to create a correct url based on the "master url" even though the master url might point to the binary endpoint. However this logic resides in the Operator.

Unfortunately, I'm not familiar with developing and contributing to such a complex project. If maintainers agree with my oservation and see the need to fix this issue (if it even is one, maybe its by design), I'd like to work on a patch with some guidance.

**Comment by MeltonSmith** [comment]
@hunnguye Hi! I think it's better to create a new issue, since you observe it on a new major version.
Moreover, this one is closed as tagged as "stale".
