### ISSUE TITLE
Add "last updated timestamp" field to API endpoints

### ISSUE THREAD

**Issue by SangwanP** [apache/airflow#21168]
### Use case/motivation

I would like to have a field added to API endpoints which reflects when a record, that is received in the API response, was last updated. It would be nice to have such a field added to as many endpoints as possible.
For example: last_scheduling_decision field can be exposed via the DAG Run API endpoint. This will give the user information on when a given DAGRun record was last updated.

I think it's common practice to expose when a record was created and/or last updated, through API's.

Particular use case: Our team is running an ETL using the Airflow API as the source system. We would like to load this data incrementally, however we will be unable to do so without a 'last updated' timestamp field exposed through the API endpoints.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is not possible - because we do not have such information. That woudl require havy changes to the database of airlfow. And this is more of an "auditing" part of Airflow. Due to the size of this - this is not a feature IMHO, this is changing a lot the approach of Airlfow to creating database records. 

Due to the size and impact of it (especially performance, migratio etc) - this one  is of a much bigger caliber than featuere -  it requires a separate discussion on the devlist and proably even AIP (Airflow Improvement Proposal) than just a "feature". I will close this one, but if you want to follow it @SangwanP  - please start a discussion at the devlist - you will find all the details here https://airflow.apache.org/community/
