### ISSUE TITLE
ERROR: 404 Client Error: Not Found for constraints 

### ISSUE THREAD

**Issue by edison12a** [apache/airflow#21184]
### Apache Airflow version

2.2.3 (latest released)

### What happened

ERROR: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/apache/airflow/constraints-2.2.3/constraints-3.10.txt

### Operating System

MacOSx, Python 3.10

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Python 3.10 is not officially supported yet.

**Comment by potiuk** [comment]
We are going to release Python 3.10 support in Airflow 2.3.0. If you really want to try, we are going to update and evolve constraints for "development" version of Airflow over the next few weeks - but almost for sure they will not work for released Airflow version 2.2.3  https://raw.githubusercontent.com/apache/airflow/constraints-main/constraints-3.10.txt - so please do not report any errors which might be caused by this.

**Comment by potiuk** [comment]
BTW. If you want https://github.com/apache/airflow/issues/19059 tracks the support of Python 3.10 for Airflow.

**Comment by asyncverse** [comment]
Thanks, @potiuk. I'm going to give the Python-3.10-constraints a test run and report back any errors.

**Comment by potiuk** [comment]
Pleasae DON't. They won't work and we know it.:)  Wait at least until we get a CI working with Python 3.10 in main.
