### ISSUE TITLE
Automatically pkill zombie processes on worker and webserver on SIGTERM/SIGINT

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#214]
I started airflow with the 3 command
airflow worker >> airflow/logs/worker.log 2>&1&
airflow scheduler >> airflow/logs/scheduler.log 2>&1&
airflow webserver -p 8080 >> airflow/logs/webserver.log 2>&1&

I kill the 3 command pid for stop the airflow.

However, I found there are lots of celeryd process alive after I killed ariflow.

[root@dev01 ~]# ps aux | grep celery
kpiserv  27404  1.2  0.4 400488 65364 ?        S    09:50   0:03 [celeryd: celery@ctu-gi-dev01:MainProcess] -active
kpiserv  27456  0.0  0.3 394904 58132 ?        S    09:50   0:00 [celeryd: celery@ctu-gi-dev01:Worker-1]
kpiserv  27457  0.0  0.3 394904 58136 ?        S    09:50   0:00 [celeryd: celery@ctu-gi-dev01:Worker-2]
kpiserv  27458  0.0  0.3 394904 58136 ?        S    09:50   0:00 [celeryd: celery@ctu-gi-dev01:Worker-3]
kpiserv  27459  0.0  0.3 394904 58136 ?        S    09:50   0:00 [celeryd: celery@ctu-gi-dev01:Worker-4]

What is the correct method to stop airflow?

Thanks.

**Comment by mistercrunch** [comment]
I believe Celery requires 2 SIGTERM signals, the first one corresponds to a warm shutdown, where the main process waits for the tasks in the threads to finish. The second is a cold shutdown where it sends SIGTERMs to the subprocesses.  I noticed it sometimes leaves zombie processes around.

This command kills zombies:
`ps auxww | grep 'celery worker' | awk '{print $2}' | xargs kill -9`

 Maybe I need to add some logic in Airflow to handle this properly since apparently Celery doesn't.

More info here:
http://celery.readthedocs.org/en/latest/userguide/workers.html
