### ISSUE TITLE
airflow command error with airflow upgrade_check

### ISSUE THREAD

**Issue by vito-detullio-finconsgroup** [apache/airflow#21496]
### Apache Airflow version

2.2.3 (latest released)

### What happened

`apache-airflow-upgrade-check` seems it's not working as [intended](https://airflow.apache.org/docs/apache-airflow/2.2.3/upgrading-from-1-10/upgrade-check.html):

```bash
# pip freeze | grep airflow
airflow-multi-dagrun==2.2.0
apache-airflow==2.2.3
apache-airflow-providers-amazon==2.4.0
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-microsoft-azure==3.4.0
apache-airflow-providers-mongo==2.2.0
apache-airflow-providers-mysql==2.1.1
apache-airflow-providers-sqlite==2.0.1
apache-airflow-upgrade-check==1.4.0
```
```bash
# airflow upgrade_check
usage: airflow [-h] GROUP_OR_COMMAND ...

positional arguments:
  GROUP_OR_COMMAND

    Groups:
      celery         Celery components
      config         View configuration
      connections    Manage connections
      dags           Manage DAGs
      db             Database operations
      jobs           Manage jobs
      kubernetes     Tools to help run the KubernetesExecutor
      pools          Manage pools
      providers      Display providers
      roles          Manage roles
      tasks          Manage tasks
      users          Manage users
      variables      Manage variables

    Commands:
      cheat-sheet    Display cheat sheet
      info           Show information about current Airflow and environment
      kerberos       Start a kerberos ticket renewer
      plugins        Dump information about loaded plugins
      rotate-fernet-key
                     Rotate encrypted connection credentials and variables
      scheduler      Start a scheduler instance
      standalone     Run an all-in-one copy of Airflow
      sync-perm      Update permissions for existing roles and optionally DAGs
      triggerer      Start a triggerer instance
      version        Show the version
      webserver      Start a Airflow webserver instance

optional arguments:
  -h, --help         show this help message and exit

airflow command error: argument GROUP_OR_COMMAND: invalid choice: 'upgrade_check' (choose from 'celery', 'cheat-sheet', 'config', 'connections', 'dags', 'db', 'info', 'jobs', 'kerberos', 'kubernetes', 'plugins', 'pools', 'providers', 'roles', 'rotate-fernet-key', 'scheduler', 'standalone', 'sync-perm', 'tasks', 'triggerer', 'users', 'variables', 'version', 'webserver'), see help above.
#
```

### What you expected to happen

I expect to have a "working" `airflow upgrade_check` command

### How to reproduce

I'm just using a `python:3.9` docker image as base and installing airflow via

`pip install "apache-airflow[password,mysql,celery,amazon,azure,mongo]==2.2.3" \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.3/constraints-3.9.txt"`

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

### Versions of Apache Airflow Providers

```bash
# pip freeze | grep apache-airflow-providers
apache-airflow-providers-amazon==2.4.0
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-microsoft-azure==3.4.0
apache-airflow-providers-mongo==2.2.0
apache-airflow-providers-mysql==2.1.1
apache-airflow-providers-sqlite==2.0.1
```

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
`apache-airflow-upgrade-check` if for airflow 1.10
The tool is to help users migrate from Airflow 1.10 to Airlfow 2

There is no reason to install it on 2.2.3

**Comment by vito-detullio-finconsgroup** [comment]
uhm...
I'm not sure to understand how this works

I have a set of dag, configurations, etc written and working on airflow 1.10.
I want to upgrade and use airflow 2.

I expect to
* keep my old dags/configs/...
* upgrade airflow to version 2
* install the upgrade check tool.
* check with the compatibility tool if the dags/configs/... need changes

what kind of workflow should I use?

by the way, the documentation for `apache-airflow-upgrade-check` that I linked in the issue description is present on the 2.x branch, not on the 1.10.x one (rightfully, as there is no meaning of a "upgrading-from-1-10" if I'm using airflow 1.10)

**Comment by potiuk** [comment]
Follow https://airflow.apache.org/docs/apache-airflow/stable/upgrading-from-1-10/index.html. Every step is detailed there.

**Comment by potiuk** [comment]
Just make sure you follow it dilligently.

**Comment by potiuk** [comment]
```
After upgrading to Airflow 1.10.15, we recommend that you install the "upgrade check" scripts. These scripts will read through your airflow.cfg and all of your DAGs and will give a detailed report of all changes required before upgrading. We are testing this script diligently, and our goal is that any Airflow setup that can pass these tests will be able to upgrade to 2.0 without any issues.

pip install apache-airflow-upgrade-check
```

**Comment by potiuk** [comment]
It does say "after upgrading to Airflow 1.10.15 we recommend that you install the "upgrade check" ::)

**Comment by thesuperzapper** [comment]
@potiuk in the interest of preventing `apache-airflow-upgrade-check` from being installed alongside airflow 2 (as it does not work alongside any version of `2.X.X`), I think we should release a very small patch version of `apache-airflow-upgrade-check`.

This `1.4.1` version would change the `apache-airflow` version pin to `apache-airflow>=1.10.14,<2` instead of the current:

https://github.com/apache/airflow/blob/d3b066931191b82880d216af103517ea941c74ba/airflow/upgrade/setup.cfg#L49

__This has the additional benefits of:__

1. preventing people who `pip install apache-airflow-upgrade-check` (without airflow installed) from being unable to use `airflow upgrade_check`
2. preventing those who (dangerously) run `pip install --upgrade apache-airflow-upgrade-check` from breaking their python environment and ending up with whatever the latest airflow version is

**Comment by potiuk** [comment]
I think it makes very little sense to do it now. Our survey https://airflow.apache.org/blog/airflow-survey-2022/ shows that Airflow 2 adoption is high and I think it makes very litle sense to make such upgrade now -I have not seen a single person having problem with it.

> 1. preventing people who pip install apache-airflow-upgrade-check (without airflow installed) from being unable to use airflow upgrade_check

Why would anyone do that? 

> 2. preventing those who (dangerously) run pip install --upgrade apache-airflow-upgrade-check from breaking their python environment and ending up with whatever the latest airflow version is

There are many other ways to break airflow by running random `pip install` command. I do not see why this particular command (which is neither endorsed or promoted by us) should be special?

I think the real problem is with (dangerous like crasy and we spoke about it many times and warned against doing it) is promoting the installation of packages in docker via env variables as "production ready". This is exactly the kind of problems we foresaw and expected people to have. It's not the problem of the upgrade check, really. 

I think a better way to handle it (if you still want to continue to support dynamic installation of packages) is to detect dangerous commands and prevent them. I think this is the only reasonable approach.

**Comment by thesuperzapper** [comment]
@potiuk My main concern is that our docs currently [tell the user to run `pip install apache-airflow-upgrade-check`](https://airflow.apache.org/docs/apache-airflow/stable/upgrading-from-1-10/upgrade-check.html), which may result in unexpected upgrades/downgrades of pre-installed packages.

We can update those docs to suggest using constraints ([like we already do when explaining how to install `apache-airflow` locally](https://airflow.apache.org/docs/apache-airflow/stable/start/local.html)), for example:

```shell
AIRFLOW_VERSION=1.10.15
PYTHON_VERSION="$(python --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

pip install "apache-airflow-upgrade-check" --constraint "${CONSTRAINT_URL}"
```

----

Also, might consider extending the `_PIP_ADDITIONAL_REQUIREMENTS` feature of the docker image with something similar to `airflow.protectedPipPackages` from the [`Airflow Helm Chart (User Community)`](https://github.com/airflow-helm/charts/tree/main/charts/airflow), which causes dynamic pip-installs to fail if they would upgrade/downgrade the pre-installed `apache-airflow` version.

_Note, this may mean that people's airflow contains fail to start, but it means they never unexpectedly change their airflow version._

The new `_PIP_ADDITIONAL_REQUIREMENTS` pip-install code might look something like this:

```bash
pip freeze | grep -i -e "apache-airflow==" > protected-packages.txt
pip install --constraint ./protected-packages.txt --user "${_PIP_ADDITIONAL_REQUIREMENTS}"
```

**Comment by potiuk** [comment]
> We can update those docs to suggest using constraints ([like we already do when explaining how to install `apache-airflow` locally](https://airflow.apache.org/docs/apache-airflow/stable/start/local.html)), for example:

Feel free :)

> Also, might consider extending the _PIP_ADDITIONAL_REQUIREMENTS feature of the docker image with something similar to airflow.protectedPipPackages from the [Airflow Helm Chart (User Community)](https://github.com/airflow-helm/charts/tree/main/charts/airflow), which causes dynamic pip-installs to fail if they would upgrade/downgrade the pre-installed apache-airflow version.

Nope. This is  a cery bad practice and users should not do it in production. We discussed it many times, and we are NOT going to make our users install packages in production - the only proper way of adding extra packages is to build your own image if you use Helm. Nothing changed since the last time we disussed it. `_PIP_ADDITIONAL_REQUIREMENTS` is deliberately development-only feature and we are not going to make it 'safer'. Actually, this is a FEATURE of that development-only variable to make it unsafe and be careful. If someone (ignoring many warnings, including one written in the logs when they use it) will be burned this is the best way for the users to learn not to use it in production. If we make it 'safer' to use, this totally undermine our vision of steering the users towards learning how to build their images.

The thing is, your proposal are turning the dynamic installation into a feature, and we deliberatly want to make it "non-feature". Our goal is not to make it "safer" to use it, but for people to "stop" using it.

**Comment by potiuk** [comment]
Those are really two differrent goals we have in mind and they are entirely opposite, so there is really no point in bringing it back if your goal is to make it "safer" to use _PIP_ADDITIONAL_REQUIREMENTS in production. If you have proposals on how to make it "less safe" - I am happy to accept it, but "more safe" is simply entrely opposite direction to our vision.
