### ISSUE TITLE
Airflow UI exposing AWS S3 secret credentials in XCOM screen when using BigQuery Data Transfer Service

### ISSUE THREAD

**Issue by bernyag** [apache/airflow#21827]
### Apache Airflow version

2.2.3

### What happened

When using BigQueryDataTransferServiceStartTransferRunsOperator in Airflow to initiate BigQuery Transfer jobs reading data from an AWS S3 bucket, the S3 access key ID as well as the S3 secret access key are being exposed in plain text via the XCOM screen on the Airflow UI when the DAG runs.

### What you expected to happen

Do not share sensitive information on the XCOMs screen.

### Versions of Apache Airflow Providers

composer-1.18.0-airflow-2.2.3

### Deployment

Composer

### Deployment details

Cloud Composer integrated with BigQuery Data Transfer Service and AWS S3 Bucket

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You can configure your users and revoke them resource.XCOM permissions if you do not want them to be able to access xcom

**Comment by thelastmessiha** [comment]
@potiuk I think the root cause issue here is not access control to XCOM but that secret keys should not be stored in the metadata database of Airflow in plain text to begin with (which then propagates to the UI's XCOMs screen). Shutting off user access to XCOM does not solve that underlying security issue.

**Comment by potiuk** [comment]
This is a choice of the operator to store it in Airflow. If you think it can be improved - feel free to provide a PR to that.

**Comment by potiuk** [comment]
Airflow has ~ 2000 contributors and you can simply become one of those, this is a great way to contribute back.

**Comment by thelastmessiha** [comment]
Yes, I agree this is an issue with the Google operator. @bernyag from Google opened this issue to track it as a result of a Google Support case I opened. My understanding is that it is being internally tracked at Google as well, and that it will be addressed through that channel.

**Comment by potiuk** [comment]
Still feel free to provide a PR yourself if you want.

BTW. This is not really a "Security" issue, really as anyone who have access to write DAGs can also dump the value as needed to log or anywhere else. And there are plenty other operators where potentially sensitive data is stored in XCom - this is because XCom is used often to pulll/push data from external systems  - and this is more decision of Dag Authors what to put there. If you really want to prevent the users in UI from seeing it, disabling access to XCom is the only "real" way.

**Comment by thelastmessiha** [comment]
Thanks for that information. If that's the case, then it sounds like a good reason to let Google internally decide if it should be addressed at all, and if so, then should that be in the operator or should that be in the API to the BigQuery Transfer Service which makes the secret key available to the operator in the first place.

**Comment by potiuk** [comment]
> Thanks for that information. If that's the case, then it sounds like a good reason to let Google internally decide if it should be addressed at all, and if so, then should that be in the operator or should that be in the API to the BigQuery Transfer Service which makes the secret key available to the operator in the first place.

Very much so.
