### ISSUE TITLE
Google Ads Hook broken for Composer 2 (and presumably others)

### ISSUE THREAD

**Issue by akerone** [apache/airflow#21940]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google==5.1.0

### Apache Airflow version

2.1.4

### Operating System

Google Cloud Composer (GKE Autopilot, composer-2.0.1-airflow-2.1.4)

### Deployment

Composer

### Deployment details

Using Composer 2 which uses Workload Identity as the way to interact with GCP services, rather than the traditional Service Account Key in the connection extras.

### What happened

The Google Ads Hook is broken for Composer 2.

Trying to use the airflow.providers.google.ads.hooks.ads.GoogleAdsHook on Composer 2 raises:
`KeyError: 'extra__google_cloud_platform__keyfile_dict'`

This is due to Composer 2 using Workload Identity rather than a Service Account Key in the connection extras. Creating a key is *not* an option for us, since it creates an avoidable security risk on a highly privileged SA.

The `"path_to_private_key_file"` key is also completely unnecessary in the config YAML, and we've successfully called the REST API without it.

### What you expected to happen

We expect the hook to work in Composer 2.

As Composer 2 is being rolled out, this will happen to more and more users.

A possible solution would make the path_to_private_key_file key optional, so the hook doesn't have to retrieve it if it's not necessary.

### How to reproduce

1. Create a Composer 2 environment on GCP
2. Create a connection to Google Ads
3. Create a DAG with a task using the GoogleAdsHook that uses the default GCP connection provided by Composer
4. Run it the dag

### Anything else

We lost the logs so I can't provide a full stack trace, but this happens on line 206 of [airflow/providers/google/ads/hooks/ads.py](https://github.com/apache/airflow/blob/2c57ad4ff9ddde8102c62f2e25c2a2e82cceb3e7/airflow/providers/google/ads/hooks/ads.py) 

There's *nothing* in the extras section of the GCP default connection in Composer 2, so  secret_conn.extra_dejson["extra__google_cloud_platform__keyfile_dict"] will always fail.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Maybe you can provide a fix for that @akerone ? Otherwise you will have to wait if there is someone who would like to fix it (Airflow has many contributors and marking it as goo first issue might help, but if you need it - making PR and becoing one of the almost 2000 contributors it is the fastest way to fix it.

**Comment by TreyYi** [comment]
I understand that "path_to_private_key_file" is not required since Cloud Composer 2 is implemented to use Workload Identity which is pre-configured by GCP, but still there could be a chance of using it in Cloud Composer 1 with Standard mode.

@potiuk @akerone , would you mind provide some ideas of how to implement ads.py? 
I was trying to add if statement like below but "extra__google_cloud_platform__keyfile_dict" is needed for Cloud Composer 1 with Standard mode.
```
    def _update_config_with_secret(self, secrets_temp: IO[str]) -> None:
        """
        Gets Google Cloud secret from connection and saves the contents to the temp file
        Updates google ads config with file path of the temp file containing the secret.
        Note, the secret is optional in extra since Cloud Composer 2 does not require path_to_private_key_file.
        (Workload Identity is used instead of Service Account)
        """
        secret_conn = self.get_connection(self.gcp_conn_id)
        
        if "extra__google_cloud_platform__keyfile_dict" in secret_conn.extra_dejson:
            secret = secret_conn.extra_dejson["extra__google_cloud_platform__keyfile_dict"]
            secrets_temp.write(secret)
            secrets_temp.flush()

            self.google_ads_config["path_to_private_key_file"] = secrets_temp.name
```

Also, I am wondering how to distinguish whether GCP users use Composer 1 or 2..

**Comment by potiuk** [comment]
Composer is not relevant for the community release. I think both cases should be supported via different keys.

**Comment by potiuk** [comment]
It could be auto-detected - if one fails, you can fall-back to the other.

**Comment by akerone** [comment]
While Composer might not be relevant for the Airflow community release, I can imagine simple Airflow deployments in which someone might want to configure default application credentials within the environment and not have to worry about rotating keys for security.

I'm not as well versed in python as I'd like but I'm happy to provide ideas if that helps. 

I think I agree with @potiuk in that the connection can be tested and the extra retrieved only if it didn't succeed.

**Comment by potiuk** [comment]
I think it would be great if someone involved here picks this one and provide a PR with it. Does not seem to be complex.

**Comment by eladkal** [comment]
Please check if the issue still happens with latest version of google provider

**Comment by potiuk** [comment]
I consider that fixed. We had completely revamped Ads support with the dependencies upgrade and the "mayhem" caused by ads dropping support for v11 . Closing this one. We can always re-open if someone still has problem (or more likely opening new issue should happen - because of the major changes in API/dependncies in the meantime).

**Comment by VictorValar** [comment]
I'm facing the same issue, was anyone able to solve this?
