### ISSUE TITLE
Allow showing more than 25 last DAG runs in the task duration view

### ISSUE THREAD

**Issue by zartstrom** [apache/airflow#22015]
### Apache Airflow version

2.1.2

### What happened

Task duration view for triggered dags shows all dag runs instead of n last. Changing the number of runs in the `Runs` drop-down menu doesn't change the view. Additionally the chart loads slowly, it show all dag runs.

![screenshot_2022-03-05_170203](https://user-images.githubusercontent.com/7863204/156891332-5e461661-970d-49bf-82a8-5dd1da57bb02.png)
 

### What you expected to happen

The number of shown dag runs is 25 (like for scheduled dags), and the last runs are shown. The number of runs button should allow to increase / decrease the number of shown dag runs (respectively the task times of the dag runs).

### How to reproduce

Trigger a dag multiple (> 25) times. Look at the "Task Duration" chart.

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by duke8585** [comment]
any movement here?
running into the same problem on [v2.3.4](https://pypi.python.org/pypi/apache-airflow/2.3.4)
the deployment is similar to the one of @zartstrom

**Comment by potiuk** [comment]
As it is in all OSS projects, such features are implemented, when someone implements it. I.e. somoeone out of > 2300 contributors must get an interest in such a feature and implement it. The best way to make sure it gets implemented is ... to implement it yourself and contribute it. If you are not up to the task, the second best thing is to find somene who is and convicing/encouraging them to implement it. Otherwise it is plain waiting for someone to pick it up.

So if you want to speed it up - act now! Commenting wiht asking for update does not change much, but I marked it as good first issue now to increase a chance that someone will actually pick it up.
