### ISSUE TITLE
Allow custom redirect for provider information in /provider

### ISSUE THREAD

**Issue by frankcash** [apache/airflow#22248]
### Description

`/provider` enables users to get amazing information via the UI, however if you've written a custom provider the documentation redirect defaults to `https://airflow.apache.org/docs/airflow-provider-{rest_of_name}/{version}/`, which isn't useful for custom operators.   (If this feature exists then I must've missed the documentation on it, sorry!)

### Use case/motivation

As an airflow developer I've written a custom provider package and would like to link to my internal documentation as well as my private github repo via the `/provider` entry for my custom provider.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

As this is a UI change + more, I am willing to submit a PR, but would likely need help.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
@frankcash SGTM. Assigned.

**Comment by uranusjr** [comment]
I wonder if we should do this with the `Project-URL` package metadata. The provider package can add a URL like this (using `pyproject.toml` for example, there’s an equivalent for `setup.py`):

```toml
[project.urls]
# Other URLs...
Airflow-Provider-Info: "https://example.com/myprovider"
```

**Comment by potiuk** [comment]
> I wonder if we should do this with the `Project-URL` package metadata. The provider package can add a URL like this (using `pyproject.toml` for example, there’s an equivalent for `setup.py`):

We could - but I think we should do it if / when we separte providers to separate repositorry(ies).
Also Providers are available for developers to change their sources in checked-out airflow code, so there has to be an alternative way of retrieving provider meta-data that does not use packages. 

Currently provider's metadata is kept in one place - provider.yaml  - and the information is basically available as an entrypoint returning the provider-info.yaml -schema compliant dictionary (and for non-community providers it's just the dictionary tha shoudl be returned) 

This was really done this way to match "plugin" approach. And there was some reasoning behind it - because next step after the entrypoint is anyhow instantiations of some classes (Hooks mainly) to be able to add customisations to UI.  It was done literally weeks before 2.0 release (actulally last changes were added in alphas and betas) as we decided that providers will also be split for 2.0 rather late in the process of preparation. 

I would rather stick with the current approach (we coudl simply add optional "pip-installation-url" attribute to the provider-info schema for now and work out the plan on moving to metadata-only approach for providers when we get rid of the connections customizations (at least in the form we have today when we literally execute Provider code in the UI to add the customizations. But this requires transitioning away fromt the FAB-Based Connections screen. The second thing that is done the same way are operator extra links and those might be harder to turn into declarative.

So my proposal for now is to add it to provider.yaml, but - as soon as we will get rid of the connections screen we could also implement more "meta-data" driven approach (still we will have to figure out a way to enable people to edit the metadata in providers and see the result of without them having to build the provider packages and install them on top of airlfow. This might be connected with splitting-off the provider repos from core. But the last thing I would like with this split is to add extra pain for people who develop community providers. They should be able to add things like extra links or customisations to connections "on-the fly"- without having to go through the hoop of building and installing provider packages every time they change a single line of code. So no matter if we use entrypoint or metadata, we should have alternative "source driven" rather than "package driven" way of retrieving the metadata by Airflow.

**Comment by uranusjr** [comment]
Sorry I should’ve clarified, my comment was specifically toward _third-party_ providers. First-party providers that are included in the apache/airflow repository already have a working URL (as mentioned in the original report) and don’t need this additional metadata.

**Comment by potiuk** [comment]
But is this a workable long term solution? Are we going to keep it this way in the future?

We would have to change the documentation for custom providers and add it as explanation:
"this is the way you should do it".

And then when we split and possibly change the approach for both "community" and "3rd-party" proiders and change the way how custom connections are defined they will have to change again likely (And we will have to support - for compatibility):

1) provider.yaml
2) provider_info from entrypoint
3) metadata for the doc url
4) and the future way we will come up with (I think what we will likely end up in some sort of YAML with all the infor embedded as meta-data entry (maybe) ?? 

That includes explaining in the docs relation between 2) and 3) and having to explain the users that they have to combine both solutions for now - some information in provider_info entrypoint, some information in package metadata as separate, unrelated entry. And when we introduce 4) we will have to explain again the change (and for quite a while suport all 2) 3) 4) for compatibility for 3rd-party providers.

Do we really want to add 3) now ? 

Or should we simply add another optional key in provider.yaml/info (especially that it already has all support for validating the schema, optional extending of the yaml (we've already added some extra stuff there) 

I'd say we should rather keep 1) 2) (with new key in yaml)  and in the meantime figure out the way how we will do 4) when we work out how we get rid of the "customised code" in connections.

**Comment by potiuk** [comment]
Also - for all practical purposes I really want to treaat all the providers - no matter if they come from community or not - the same way, so whatever we intrroduce for "doc" url, I would like to add for community providers too (with the fallback of automatically figuring out the URL for older providers).

**Comment by potiuk** [comment]
Ah... But we have ANOTHER way.. I think we can do it without introducing 3) - because it is there already!

I realized that we already use the standard metadata in Airflow ... And we could just use it immediately (all past packages have it for a long time:

```
project_urls=
   Documentation=https://airflow.apache.org/docs/{{ PACKAGE_PIP_NAME }}/{{RELEASE}}/
```

So slightly modifying your proposal @uranusjr:

```
info_url = package_metadata["Project-URL"]["Documentation"]
```

I can even get it in 2.3.0 and it will be fully compatible with released packages :)

**Comment by potiuk** [comment]
Fix in https://github.com/apache/airflow/pull/23012 (however I think the one who came up with the interface for the importlib_metada should go to jail).

**Comment by potiuk** [comment]
Closing as #23012 is merged.
