### ISSUE TITLE
if deleted, the `dag_processor_manager.log` file is never recreated

### ISSUE THREAD

**Issue by thesuperzapper** [apache/airflow#22614]
### Apache Airflow version

2.2.4 (latest released)

### What happened

If a user deletes the `dag_processor_manager.log` file (stored at `AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION`), then the file is only re-created if the scheduler is restarted, which means that all logs until the scheduler next restarts are lost.

It probably has something to do with our logging configuration, which can be found at [`airflow/config_templates/airflow_local_settings.py#L131-L149`](https://github.com/apache/airflow/blob/c58b5e583bcad83048fdee72bc9ddf6c3a7b4229/airflow/config_templates/airflow_local_settings.py#L131-L149).

### Operating System

N/A

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
this is expected behaviour on POSIX systems. When Rotating file Handler is used, the file it writes to should not be removed because that removes only link to the file from teh directory but the actual file is not removed until there is any process writing to it (and all processes that opened the file for wrting are unaware that the file has been removed from a folder). The file can be hard-linked somewhere else and in this case it wont even be deleted. 

The solution is to only remove the "rotated" files.

**Comment by potiuk** [comment]
BTW. It would be possible to write a handler to "open" and "close" the file for every log - but this would be TERRIBLY slow.
