### ISSUE TITLE
Providing Composite Sensors

### ISSUE THREAD

**Issue by pateash** [apache/airflow#22816]
### Description

I found some of the use cases where it is useful to have a sensor, 
which encapsulates 2 sensors and succeeds when any of them are passed.

I would like to also know, How others are trying to solve similar usecase.

### Use case/motivation

We can provide a Composite Sensor that can take more than one sensor and pass based on predicates like  
 _**If any of them completed**_

### Related issues

NONE

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pateash** [comment]
@potiuk @kaxil @eladkal @mik-laj,

I would like to know your opinion on this one.

**Comment by eladkal** [comment]
Isn't that just?
```
s1 = Sensor()
s2 = Sensor()
op = Operator(trigger_rule='one_success')
[s1, s2] >> op
```

I guess what missing to make it complete is when `op` starts then all running upstream tasks should terminate.

**Comment by pateash** [comment]
> Isn't that just?
> ```
> s1 = Sensor()
> s2 = Sensor()
> op = Operator(trigger_rule='one_success')
> [s1, s2] >> op
> ```
> 
> I guess what missing to make it complete is when `op` starts then all running upstream tasks should terminate.

Yeah, agree
This is kind of a workaround.

Ideally, We should have a sensor, which allows this

**Comment by potiuk** [comment]
> Ideally, We should have a sensor, which allows this

Why?

**Comment by pateash** [comment]
> > Ideally, We should have a sensor, which allows this
> 
> Why?

Why not?
 this is a really common scenario.
and as @eladkal pointed out the following workaround has the issue that id doesn't stop the sensor which has not ran successfully yet.
`
s1 = Sensor()
s2 = Sensor()
op = Operator(trigger_rule='one_success')
[s1, s2] >> op
`

**Comment by eladkal** [comment]
>and as @eladkal pointed out the following workaround has the issue that, it doesn't stop/skip the sensor which has not ran successfully yet.

Yes but this is is not limited to sensors.
The ability to change upstream task status based on downstream task.

**Comment by potiuk** [comment]
> Why not?

No. I specifically ask Why? - because when you want to add something you have to justify it rather than someone should justify why you should not do it. That's very simple. Any new stuff adds complexity. 

More - any new way of interacting with Airflow adds confusion - shoudl I do it this or that way. So yes by all means you should make plenty of effort to justify things and show alternatives that you considered and explain why the current alternatives are not good. 

The Python zen says:

>  there should be one — and preferably only one — obvious way to do it
 
We already can compose tasks - sensor and operators, and dependencies between them via - yes - task dependencies. Airflow DAG is all about it. Seems that you want to add "yet another" way of composing tasks at a different level. 

That immediately "feels" wrong. I am not saying it is wrong for sure - but it definitely "feels" wrong immediately. 

Putting Two Operators where everyone expects one is totally, and utterly unexpected and alien to Airflow. You can compose Hooks in Python operators - this is perfectly fine, but composing two Operators (Sensors are just specialized operators) is just "don't do it" and it raises immediate questions about lifecycle:

* when pre/post_installs are running, in which sequence would they be run
* what happens if one of the pre_installs fail - will it fail the other too? 
* what happens if one of the executes raisees exception? Will the other fail or continue running or throw exception?
* what is the retry pattern of such compose operators?
* can you compsoe more than two?
* can you compose them  in more complex fashion (two failed/one succeeed?)

And suddenly it looks like you want to develop whole complexity of whole Airflow DAG as a single composed task. Again.

(And please don't even try answering those questions - they ar rethorical questions at this stage of discussion).

And this is **just** the beginning. You try to add new abstraction, which (unlike dependencies, tasks, relations in airflow) have completely undefined and not hashed out lifecycle, properties, behaviours, people are unfamiliar with it, etc. etc. 
when shoudl people use which ? Why they should choose this composition over the already familiar one - DAG ? etc. etc.  

That's why It's YOU you whe have to explore all the alternatives and prove that what you want to achieve:

a) is needed
b) you cannot do it using current composition method 
c) you cannot modify current composition method to fit the cases you want.

The c) is the most difficult amd requires creativitiy - and before you start justifying new composition, I'd rather try to come up with few creative ways how current dependencies and tasks could be modified to achieved what you want (if you cannot achieve it today).

I wholeheartedly agree with Elad that it feels much better to compose sensors using already existing compositions.

```
op = Operator(trigger_rule='one_success')
[s1, s2 ] >> op3 
```

Is immediately understood by anyone who wrote a single DAG in python and already has plenty of more functionality for example:

```
[s1, s2 ] >> op3 
```

will wait for both sensors (and there are many more cases).

So before you dive into composing sensors - please, please, please. Do not "anchor" on your "solution".  Think about the use case you have in hand. Spend very good deal of time on thinking whether we really miss some functionality and if we do - how we can achieve it using current relations and tasks without adding completely new abstraction.

And yes. This is your task to come and discuss those ideas and propose some brainstorming before we all conclude that 

a) indeed the use case is missing that we want to handle
b) we cannot creatively think of any ideas how we can extend the current approach rather than add completely new abstraction

**Comment by pateash** [comment]
@potiuk,
I didn't mean to be rhetorical or disrespectful.

I just wanted to have some discussion around this.
As I have faced this scenario before as well in our usecases..

I have already looked into some possible solutions -

**_1. Using above work around_** 

```
op = Operator(trigger_rule='one_success')
[s1, s2 ] >> op3 
```
Problem - the sensor which didn't run will fail after timeout even though only one success is required. and will cause alerts and doesn't look good.

**Possible Solution -**
* we make other Sensor to Skip after timeout and not fail. ( I am not sure if this is possible in current composition or not )

**_2. Something along the lines of following_** 
```

    def poke(self, context: Context):
        self.log.info("sensors:" + str(self.sensors))

        success = False
        for sensor in self.sensors:
            success |= sensor.poke(context)
            if success:
                self.mark_others_skipped(sensor, self.sensors)
                return True

Problem - as you correctly pointed out, it add additional complexity and reduces transparency.

**Comment by potiuk** [comment]
I don't say you were disrespectful. I was (and yeah I aften am just very, very direct) asking "why not" we should add someting is very wrong for Airflow in this stage. "Why we should not remove something?" is what we should be asking more.

I think simply another composition method is wrong and if we miss something - we don't we add it.

How about adding new dependency type:

* "alll_success_and_fail_others_if_succeeded"  -> working name

This is fa more in-line with what we have in Airflow now and follows all the patterns of Airflow.

**Comment by potiuk** [comment]
BTW. We already have a PR in progress to even have a possibility to ad pluginable dependencies to Airflow: https://github.com/apache/airflow/pull/22698 

So - (again in the spirit of Airflow becoming a platform and adding extensibility - once this one is merged, even if Airflow has no such dependency built-in - you could add one yourself.

So I'd argue even - maybe (?) we don't need to add such rule to Airflow (I think it would be useful though), but give the user an opportunity to tap into the plugin model and add such dependency.

**Comment by hankehly** [comment]
@pateash

> I would like to also know, How others are trying to solve similar usecase.

I find the [TaskGroup](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#concepts-taskgroups) feature useful for this purpose. I can visually group things together, and if something fails, it's easy to determine what went wrong because each task has it's own log.

**Comment by pateash** [comment]
> BTW. We already have a PR in progress to even have a possibility to ad pluginable dependencies to Airflow: #22698
> 
> So - (again in the spirit of Airflow becoming a platform and adding extensibility - once this one is merged, even if Airflow has no such dependency built-in - you could add one yourself.
> 
> So I'd argue even - maybe (?) we don't need to add such rule to Airflow (I think it would be useful though), but give the user an opportunity to tap into the plugin model and add such dependency.

Thanks @potiuk @hankehly @eladkal for feedback.

I agree this is not required at the moment, so closing this issue.
