### ISSUE TITLE
GCP Composer v1.18.6 and 2.0.10 incompatible with CloudSqlProxyRunner

### ISSUE THREAD

**Issue by leahecole** [apache/airflow#23292]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

6.6.0 or above

### Apache Airflow version

2.2.3

### Operating System

n/a

### Deployment

Composer

### What happened

Hi! A [user on StackOverflow](https://stackoverflow.com/questions/71975635/gcp-composer-v1-18-6-and-2-0-10-incompatible-with-cloudsqlproxyrunner
) and some Cloud SQL engineers at Google noticed that the CloudSQLProxyRunner was broken by [this commit](https://github.com/apache/airflow/pull/22127/files#diff-5992ce7fff93c23c57833df9ef892e11a023494341b80a9fefa8401f91988942L454) 

### What you think should happen instead

Ideally DAGs should continue to work as they did before

### How to reproduce

Make a DAG that connects to Cloud SQL using the CloudSQLProxyRunner in Composer 1.18.6 or above using the google providers 6.6.0 or above and see a 404

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by leahecole** [comment]
I believe @enocom was interested in submitting a PR for this!
cc @kurtisvg for raising it initially

**Comment by enocom** [comment]
To summarize, the Cloud SQL Proxy is available in the follow formats:

![image](https://user-images.githubusercontent.com/1175430/165588728-ce6ca510-5474-4ee4-9c0e-71d8392a4a3c.png)

When https://github.com/apache/airflow/pull/22127 was merged, the CloudSQLProxyRunner started looking for a binary with an x86_64 suffix instead of amd64. To fix this, we should probably replace x86_64 with amd64.

**Comment by jackwotherspoon** [comment]
PR that is linked should hopefully fix the `x86_64` broken download links
