### ISSUE TITLE
Move grid_data endpoint to REST API

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#23417]
### Description

Migrate the `object/grid_data` endpoint [here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L3455) to the REST API.

With https://github.com/apache/airflow/issues/23415, we can simplify this endpoint too and only return the `groups` object.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
@bbovenzi I can take this. Please add a permalink to the github code that you want to migrate to rest API . I couldn't find `objects/tree_data` endpoint in current views.

**Comment by bbovenzi** [comment]
oh yes, we renamed it to `grid_data`. I updated the link too.

We probably don't need to return the `dag_runs` part of the response and instead use the list dag runs endpoint. Message me before you start work on this, I may want to change a few other things.

**Comment by bbovenzi** [comment]
Semi-related: https://github.com/apache/airflow/issues/23772

Either before or after this issue we should try to optimize the function to generate this grid data.

**Comment by tirkarthi** [comment]
@bbovenzi I can start working on it now. I see that you have made some optimizations as part of https://github.com/apache/airflow/pull/23813 too. It will be helpful to have a sample response so that I can give a first draft attempt since you already mentioned dag_runs are not needed.

**Comment by bbovenzi** [comment]
This should be an internal API endpoint, not a public one. Being in the webserver and views.py is fine for now.

**Comment by bbovenzi** [comment]
@karakanb what is your use-case? I would still want to keep it separate so that we can quickly iterate on the grid view. But maybe the existing task instances REST API endpoints can be improved.

**Comment by potiuk** [comment]
I think "Generic" bulk retrieval of Airflow tasks (not optimized for UI but for bulk retrieval of data) could be added. Maybe you would like to design and contribute such an endpoint @karakanb - you seem to know hat you are doing with Python, adding yet another API endpoint should be easy following the exisitng ones and if you get it "generic" enough, it would be useful for others too.

**Comment by potiuk** [comment]
> I could try to do that, for sure; however, it'd be pretty much the same as the grid data endpoint, no?

The difference is that we might want to change grid data endpoint in a backwards-incompatible way in the future, to serve Airflow UI better. It might have some optimisations and more (or less) data retrieved to speed-UI responsiveness. And eventually we might make it an async endpoint as well.

Contrary to that I am talking about "bullk "retrieval of the data" that should be stable. I think extending "dagRuns" is not great because it follows REST semantics, so in principle it only shoudl return dagRuns. I think having separate endpoint to retrieve "joined data" might be better. But I also know @bbovenzi and others discussed about the APIs we need so maybe they have other ideas.
