### ISSUE TITLE
401 error while using Airflow API

### ISSUE THREAD

**Issue by megha120** [apache/airflow#23663]
### Apache Airflow version

2.1.0

### What happened

Getting the following error while trying out the Airflow API:
{
    "detail": null,
    "status": 401,
    "title": "Unauthorized",
    "type": "https://airflow.apache.org/docs/apache-airflow/2.1.0/stable-rest-api-ref.html#section/Errors/Unauthenticated"
}

### What you think should happen instead

The API should work properly as I am passing the username and password as required for basic authentication.
<img width="540" alt="auth" src="https://user-images.githubusercontent.com/65885522/168012616-ab344035-765c-42ca-a7ee-e608a30099e8.png">

Even with the swagger ui I am getting the same error.
![image](https://user-images.githubusercontent.com/65885522/168012732-55106a4e-dab4-4772-a183-7ddd60cb52be.png)
![image](https://user-images.githubusercontent.com/65885522/168012792-41166ecc-dc40-4d94-96bd-2bf7aafc8333.png)

### How to reproduce

I am using the local installation of Apache Airflow (https://airflow.apache.org/docs/apache-airflow/stable/start/local.html)

### Operating System

Linux

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment]
You need to set the configuration for basic authentication properly. See https://airflow.apache.org/docs/apache-airflow/2.1.0/security/api.html, let me know if it worked for you, if not I will reopen the issue

**Comment by megha120** [comment]
I have set the configuration to airflow.api.auth.backend.basic_auth. You can check in the screenshot below, 
<img width="540" alt="auth" src="https://user-images.githubusercontent.com/65885522/168017997-f3360931-3deb-4ed9-8796-060e2e32f63e.png">

But it is still not working.

**Comment by megha120** [comment]
> You need to set the configuration for basic authentication properly. See https://airflow.apache.org/docs/apache-airflow/2.1.0/security/api.html, let me know if it worked for you, if not I will reopen the issue

@ephraimbuddy It is still not working for me, kindly assist.

**Comment by potiuk** [comment]
I am afraid it does not work this way - if you have some findings and want to discuss it and share with others your errors - feel free to open  discussion and discuss it. Unless you can point out to the exact issue of airlfow - you can just hope on someone who has an experience with setting to help you - but this is not a "bug" of airflow and people here help in their free time/when they have enough knowledge and experience (maybe - there is no guarantee). I think you have some configuration problem - because the authorization works for basically many people (including our tests) - but unless you show logs and set that there is an airflow issue, this is at most a discussion. 

BTW. I think you might have webserver misconfigured. The fact that your CLI works does not mean that the webserver is configured the same way - make sure your configuration is the same everywhere and that your websever properly reads it. Also you should look at the log files to try to understand what happens.
