### ISSUE TITLE
Postgres BaseHook.get_connection(conn_id).get_uri() returns "postgres" dialect 

### ISSUE THREAD

**Issue by jrggggg** [apache/airflow#23701]
### Apache Airflow version

2.3.0 (latest released)

### What happened

Postgres BaseHook.get_connection(conn_id).get_uri() returns "postgres" dialect

### What you think should happen instead

It should return "postgresql"

### How to reproduce

```
BaseHook.get_connection(conn_id).get_uri()
```

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-postgres==4.1.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Because you have it defined this way. Make sure that your connection is properly defined with postgresql:// or postgres:// prefix, then it will be returned properly.

**Comment by jrggggg** [comment]
Hi Jarek, the connection was configured via the Airflow GUI, so I don't explicitly set the dialect anywhere. The connection works perfectly when used in a PostgresOperator task for example, but not when retrieving the uri via BaseHook.

**Comment by potiuk** [comment]
What is your connection URI ?

**Comment by jrggggg** [comment]
This connection was just created via the Connections gui 

```
from airflow.hooks.base import BaseHook

conn = BaseHook.get_connection("postgres_k8s_qa_new").get_uri()
    [2022-05-13 14:17:07,179] {base.py:68} INFO - Using connection ID 'postgres_k8s_qa_new' for task execution.

print(conn)
    postgres://airflow:******@masked.myorg.edu:5432/qa
```

**Comment by potiuk** [comment]
Ah sure. it will be like that you just use it wrongly:

```
BaseHook.get_connection(conn_id).get_uri()
```

**Comment by potiuk** [comment]
Ah - I think you have wrong expectations.

The connections of Airlow have different URI schemes thatn those of sqlalchemy. Many of Airflow connections are not "sqlalchemy" connections and they have different semantics - in Airflow, "postgres://" is the only way you can refer to postgres conection. This is valid and expected. That's why - the connection itself will never return postgresql://. 

I wonder why do you think connection.get_uri() shoudl retturn postgresql:// ? where this expectation came from? Could you please explain?

What indeed returns postgresql: // is `PostgresHook().get_uri()` - this one comes from the fact that PostgresHook derives from DBApi and DBApi.get_uri() is used to get SQLAlchemy connection.. But this is DBApi.get_uri() method - which is completely different method (it is DBAPi's methodd not Connection's) .While the method name is the same, DBApi's get_uri() returns SQLAlachemy URI, not Airflow's, that's why we replace postgres://  with postgresql://.

See here:

```
    def get_sqlalchemy_engine(self, engine_kwargs=None):
        """
        Get an sqlalchemy_engine object.

        :param engine_kwargs: Kwargs used in :func:`~sqlalchemy.create_engine`.
        :return: the created engine.
        """
        if engine_kwargs is None:
            engine_kwargs = {}
        return create_engine(self.get_uri(), **engine_kwargs)
```
