### ISSUE TITLE
Postgres dependency failed

### ISSUE THREAD

**Issue by KulykDmytro** [apache/airflow#24174]
**Official Helm Chart version** main (development)

**Apache Airflow version** 2.2.5

**Kubernetes Version** 1.22

### What happened

when fetching a chart Bitnami's `postgres` chart dependency cannot be honored
```
dependency build error: failed to add remote dependency 'postgresql': no 'postgresql' chart with version matching '10.5.3' found  
```

### Anything else

Seems like `Bitnami` retained all `postgres` chart versions older than 2022-01-01 (<10.14.3)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is caused by Bitnami breaking development versions of about a million charts out there - se the huge (and growing) thread here: https://github.com/bitnami/charts/issues/10539 

Basically we lost trust in Bitnami to host anything and we are going to change it to vendor-in the chart. For now you can switch to the main to use the workaround we applied there or you can manually apply the change here that uses old index of Bitnami to fetch postgres chart

https://github.com/apache/airflow/pull/24115/files

I would also recommend to express your experience with Bitnami in  https://github.com/bitnami/charts/issues/10539 .
