### ISSUE TITLE
Adding explicit apache-airflow version to constraints file

### ISSUE THREAD

**Issue by Stegallo** [apache/airflow#24427]
### Apache Airflow version

2.2.2

### What happened

When installing additional libraries to an airflow environment version 2.2.2 using a requirements file including 
`--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.7.txt"` 
it erroneously installs also `apache-airflow==2.2.3`, causing the WebServer UI to break.

This happens specifically when using AWS MWAA.

### What you think should happen instead

the version installed of apache-airflow should be 2.2.2.

### Operating System

Linux

### Deployment

MWAA

### Anything else

I guess `https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.7.txt` should explicit set the version of `apache-airflow==2.2.2`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Nope. It makes compleely no sense to add apache-airflow==2.2.2 to constraints that are used to install apache-airflow==2.2.2. 

The problem is not constraints, but you extra dependencies you add . I do not know what you want to install but what you want is easily achievable by:

`pip install apache-airflow==2.2.3 --constraints https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.7.txt ... whatever other libraries you want to install`
