### ISSUE TITLE
Create DAG with Airflow REST API

### ISSUE THREAD

**Issue by luiztauffer** [apache/airflow#24537]
### Description

Given that all DAGs are serialized in the database ([reference](https://airflow.apache.org/docs/apache-airflow/stable/dag-serialization.html)), it feels like a POST request in the [Airflow REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html) for creating DAGs would be a very useful improvement! It could accept already serialized dags, for example.

Is this something that might be considered for an upcoming version?

Thanks for all the great work, I’ve been loving working with Airflow!

### Use case/motivation

My context: I’m working on a project where I start with JSON files defining newly created DAGs, and then I see myself having to turn those into Python files (I use Jinja2 templates for that) and having to upload these newly created .py files to a storage somewhere, where a running instance of Airflow can read the new DAGs. 

The above approach works, but certainly things could be better. The necessity of actual python files stored somewhere unnecessarily increases the complexity of each deployment.

I would also appreciate other ideas to possibly circumvent this limitation.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vinicvaz** [comment]
following

**Comment by potiuk** [comment]
The serialization only stores dag structure and configuration not python code. So basic assumption here does not hold unfortunately because what your serialization idea is, it is different that the serialization we have in Airflow.

Python DAG is much more than just a single python file - it is the byte code of the class but also potentially imported classes and even potentially files that are read by the Python code placed in the dag folder and any of the subfolders. Potentially loaded in dynamic way by your python code based on any factors

There area number of discussions on how to do what you want resulting in a number of ideas like DAG Fetcher https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=109445755 or DAG Manifest https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-20+DAG+manifest and it involves changing the way and limiting how DAGs are being written and potentially annotated (and serialized including all the information necessary to not only know the DAG structure but also to execute it). 

A lot of the challenges and problems to solve have been very nicely described in the recent talk from the Airflew Summit 2022 where AirBnB explained how they have done something similar internally and what kind of limitations they had to introduce and how much they had to enforce internally to make it happen. 


https://youtu.be/5Ap2t9qJE18

This is PRECISELY about making Dags submittable via rest API. I recommend anyone who wants to take part further in the discussion to watch that talk as it explains everything you need to know to understands complexities involved.

Speaking ilof which - once you or anyone else who wishes to discuss it watches the talk, think about those issues and understands complexities involved, you are free to propose, discuss (on devlist) an AIP for that. Like everyone in the community you are free to do it and start devlist discussion. 

Just be prepared that you have to lead and get consensus on how to solves those issues in a generic way. People will have different opinions and ideas there, and the biggest complexity of the approach will be to get to consensus   - what trade-offs to make, how to implement serialization, how to handle dependencies, how to handle different python versions (pickle!). Most of the issues (without ready solutions) are mentioned in the talk.

I personally think it would be great to have it, but it will be months of discussions at least and years of implementation in incremental steps to get there.

So just be prepared for a marathon not a sprint - whoever wants to lead that discussion.
