### ISSUE TITLE
DAGs with Dynamic Task Mapping are not rendered when cluster policies overwrite a parameter

### ISSUE THREAD

**Issue by mariotaddeucci** [apache/airflow#24547]
### Apache Airflow version

2.3.2 (latest released)

### What happened

Using cluster policies, I set a default `on_failure_callback`.
This works great with all tasks expect with task new task mapping.

### What you think should happen instead

Policies should work on all tasks, including the dynamic mapping or generate an exception with the error.

### How to reproduce

Overwrite any parameters using the `task_policy`.

### Operating System

Official docker image

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Can you provide an example `task_policy` that you expect should work?

**Comment by cccs-seb** [comment]
@uranusjr  Piggybacking this issue. Datahub's plugin attempts to overwrite the `on_failure_callback` and `on_success_callback` methods for tasks through its task_policy. See the code here: https://github.com/datahub-project/datahub/blob/8a8b667a529ef728584a489f2555d2416fa60683/metadata-ingestion/src/datahub_provider/_plugin.py#L297

That bit of code breaks with `AttributeError: can't set attribute ` due to `MappedOperator` is annotated by `attrs.define` (defaults to slots=True). See here : https://github.com/apache/airflow/blob/5802469fbc452a5727c938f033f2753571989d92/airflow/models/mappedoperator.py#L230

Could we allow cluster policies to modify MappedOperators or was this a design decision?

**Comment by uranusjr** [comment]
Ah OK, so the main issue is the callback property being read-only. This is not actually related to `attr.define`; `on_failure_callback` is a property, not a plain attribute, and we don’t define any setters for those properties.

**Comment by uranusjr** [comment]
So I’m relabelling this to a feature since everything is working “as we designed it” and nothing’s out of ordinary, but our current design does not meet user expectation and should be improved. This also means the fix would not need to constrain 2.5.1, although I’m still keeping it in the milestone since it’d be totally fine to backport the feature if it’s ready by then.

The simplest fix to this would be to implement setters for the `on_*_callback` callbacks on MappedOperator. A pull request would be much appreciated.

**Comment by cccs-seb** [comment]
@uranusjr  Ah gotcha, I misunderstood `attr.define` here.

Sounds good - I'll look into putting up a PR very soon. Thanks!

**Comment by uranusjr** [comment]
Fixed in  #28313
