### ISSUE TITLE
Legal short option pattern regex confirmation

### ISSUE THREAD

**Issue by kevinsunny1996** [apache/airflow#24587]
Hi everyone , was referring how to write tests and was checking airflow repo , for the following code snippet:
https://github.com/apache/airflow/blob/main/tests/cli/test_cli_parser.py#L36

The comment contained # Only can be `-[a-z]` or `-[A-Z]`

However the regex seems to be missing Z in the test code.

Wanted to check if my finding is correct , I can contribute to the same by fixing the regex and raise a PR for the same

**Comment by potiuk** [comment]
But yes - seems it needs fixing. But issues should not be used for questions. If you want to discuss something - open "Github Discussions" instead - but discussing stuff on a code are much better done with a PR - because you can discuss directly on the code - and if you submit a change, there is no doubt what you want to do (and it's as easy to close a PR as it is to close an issue or discussion).
