### ISSUE TITLE
Duplicate dag ids lead to confusing outcome rather than error.

### ISSUE THREAD

**Issue by hterik** [apache/airflow#24701]
### Apache Airflow version

2.3.2 (latest released)

### What happened

I accidentally created two dags with the same name.
No errors were given.
Code-tab in web-ui showed one of the versions.
Running the task actually executed the second version.

### What you think should happen instead

One, or both DAGs should be rejected and pop up a dag import error in the UI
Starting the dag should not be possible.

### How to reproduce

Create two dags with same name.
Start dag

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.0.2
apache-airflow-providers-docker==3.0.0
apache-airflow-providers-ftp==2.1.2
apache-airflow-providers-http==2.1.2
apache-airflow-providers-imap==2.2.3
apache-airflow-providers-postgres==5.0.0
apache-airflow-providers-sqlite==2.1.3

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Tehis is rather a feature than a bug and it is next to impossible to fix it, because in general case each DAG is parsed separately from each other.

We are not likely going to fix it - because of dynamic nature of dag id generation, and continious parsing/re-parsing mutliple dags and this is happen in "aysynchronous way"  we neverk know when the snapshot of our DAGs is complete. We never process DAGs from file as "complete list". We are parsing them in batches, and you do not have "snapshots" of all the directory  available.  For example if you have a DAG that moves from one file to another, even if you see second dag, it might be that either of the two dags have been already removed and will disappear next time when you get there, but if you have many dags, this parsing is continuous and you are never sure what is the "complete snapshot". Parsing of the DAGs take time and you cannot do it "instantly" for all DAGs to keep consistent snapshot. 

The current approach is a compromise - such clashes are possible, but it also makes it possible to handle cases where there are huge folders that you won't pay performance penalty of snapshotting the whole directory with all DAG files and making sure tha this snapshot is consistent. It's just price to pay for speed. 

But if you hve an idea how to implement it, feel free to continue discussing it - maybe you can find a good solution to that. 

Converting it into discussion.
