### ISSUE TITLE
DAGs View: make Owner column hyperlink for a predefined URL 

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#24728]
### Body

Currently when clicking on specific owner user is forward to search endpoint
`/home?search=owner_name`

My suggestion is to define in airflow.cfg `dag_view_owner_url`.
for example:
`dag_view_owner_url = https://www.something.com/users?search=`

If using this setting an icon will be added to the column (or something else we can decide) by clicking on the icon it will forward the user to the url defined `https://www.something.com/users?search={owner}`

**The motivation:**
Organizations have internal phone book or ownership tag system, I find myself very often trying to find the contact details of the dag owners. Having the ability to do it in a single button click is very helpful.

This is something that probably can be done using browser plugin however I feel that having it in Airflow core might be helpful.

What do others think of the idea?

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by eladkal** [comment]
> desire to avoid "config sprawl" if we make everything an config option

I agree completely (I just didn't have a better idea than the one I suggested).

> Owner can be anything. Including URL

This is good as it allows flexibility but also create hussle, if the endpoint is change you need to edit all dags (can be solved using function to bring the prefix but still not the nicest thing)


Alternatively, maybe we can allow to add custom options using the Links:
![Screen Shot 2022-06-29 at 18 41 57](https://user-images.githubusercontent.com/45845474/176478860-5aed3330-d7cf-4332-b776-38251ee3c95d.png)
And the option will have the ability to access any information of the DAG in that row

**Comment by potiuk** [comment]
Something like Base Operator Link but on DAG level ? Might be possible actually .

**Comment by alexkruc** [comment]
Hey guys! :) 
With your permission please, I might have some suggestions for relatively small and maybe "easy" implementations of this feature, that does not involve config sprawl, let me know what you think :) 

First, I want to say that I think it sounds like a really good enhancement to Airflow. From the organizations that I worked in, and talking with people in several other companies, Airflow is often a multidisciplinary tool, that a lot of various team uses. Communication can be a hassle, and it can be very benifieical to the eco-system making a step forward in helping with the matter :) 
Currently I work in an organization that we have a web based system that defines ownership, then for us, having the link to be natively as `https://www.something.com/ownership/{OWNER}` can be enough :)
BUT - 
I think that if the Owner column will become a hyperlink, in most cases, people will use the link to use a specific Slack channel/person, or a `mailto` link to identify an email of the owner, and it can be really beneficial IMO :) 

I think that having something like the following options can really help, and doesn't sound as a bad thing to maintain in Airflow:

- Having the `owner=` field to accept dict instead of string, and for example `{"name": "data-team", "link":"<LINK_TO_DATA_TEAM_SLACK>"}`. We could write the `owner['name']` to the DB as Airflow currently does, but add the `owner['link']` to the `href=`.
I understand that this is not solving the "issue" that a single DAG has multiple owners inside it, and to know this, you need to go to each task and first understand who is the proper owner, but at least it gives the notion that people can add their own "communication channels" (whether it's a ownership-url as in our organization, Slack channel, ldap link, mailto....) to each owner, so the owner won't be just an abstract string :) 

- Another option, is adding something like `owner_channel_link=` param inside the `DAG()` object, that will allow to use this link somewhere (whether it's the owner in the DAGs page, or some other UI link), that again, will be the value of the `href=` tag.


The best thing about these 2 methods, is that Airflow admins could enforce/create this as part of Cluster Policies, and it gives a more "real" feeling to the owner, rather than just a string without any context..

Regarding the comment:
> Wild idea. Well. Owner can be anything. Including URL. Why don't we simply detect in the UI if a field (any sutiable field/property coming from Airflow DB) is a URL, and make it clickable then?

As I see it, a common usage of this "feature" will be setting a slack channel.. Slack channel URL's basically looks like this:
`https://yourteam.slack.com/archives/XXXXXXXXX`. If we will detect the owner from the URL, it will leave us with the owner of `XXXXXXXXX`, a strange hash for each dag as the owner is kinda beats the purpose of owner :( 
And also, it's limiting the use, for example, by customizing the value that we pass to `href` tag, we can also use ` "mailto:airflow-admins@your-org.com"`, for an email-based companies :) 

I would love to have your opinion of this, and as mentioned before, I think that it's solves a real issue in Airflow, and gives a proper and actual weight on the "owner" notion :)

**Comment by ashb** [comment]
I like the idea of accepting a dict -- one thing we do need to be careful of there is that we don't allow "stored XSS" in there. I.e. I shouldn't be able to do `{"name": "data-team", "link":"javascript:alert(1)"}` or _anything_ like that. (And this can be a suprisingly hard thing to defend against. It's worth it, just FYI)

**Comment by alexkruc** [comment]
Good point, I haven't thought about this.
Adding validation on the input of `owner['link']` for it to actually be an HTTP link or a `mailto` or something like this is necessary. Thanks for adding this!

**Comment by potiuk** [comment]
Yeah. Owner as dict with some conventions to be displayed in UI is nice. Generic enough, no configuration creep. nicely "commonalised" between dags (you can have default args, comon imported code etc.) and you have also full flexibility on the dag author's side.

And yeah. shout-out to @ashb - anything that dag-author provides that the UI renders, needs to be sanitized for XSS.
