### ISSUE TITLE
When creating a duplicated dag name no warning is shown to web UI

### ISSUE THREAD

**Issue by Anze-** [apache/airflow#25187]
### Apache Airflow version

2.3.3 (latest released)

### What happened

Testing airflow docker installation, checking correct dir mapping by copying one of the default dags into the `./dags` folder.
The new dag is not added as a duplicate because duplication is detected, but the addition fails silently in the web UI while in command line tool the error `Error: Failed to load all files. For details, run airflow dags list-import-errors` is presented.

### What you think should happen instead

As the cli warns about the error, the web UI should warn about the duplication occurence. 

### How to reproduce

Copy a default dag into the mapped `./dags` of a docker-compose install.

### Operating System

manjaro linux

### Deployment

Docker-Compose

### Anything else

Evvverytime a good soul tries to test the docker-compse deployment :D

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
We know about it. This is not easy to fix due to the way how dags are parsed sequentially in batches. The problem is that it does not scale, because you would have to parse all the dags in order to know all of them at once and there are edge cases such as moving dag to another file. This will likely not be fixed.
