### ISSUE TITLE
Strip white spaces from values entered into fields in Airflow UI Connections form

### ISSUE THREAD

**Issue by drdenzy** [apache/airflow#25240]
### Apache Airflow version

2.3.3 (latest released)

### What happened

I accidentally (and then intentionally) added leading and trailing white spaces while adding connection parameters in Airflow UI Connections form. What followed was an error message that was not so helpful in tracking down the input error by the user.

### What you think should happen instead

Ideally, I expected that there should be a frontend or backend logic that strips off accidental leading or trailing white spaces when adding Connections parameters in Airflow.

### How to reproduce

Intentionally add leading or trailing white spaces while adding Connections parameters.
<img width="981" alt="Screenshot 2022-07-22 at 18 49 54" src="https://user-images.githubusercontent.com/9834450/180497315-0898d803-c104-4d93-b464-c0b33a466b4d.png">

### Operating System

Mac OS

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add a PR. Assigned you.

**Comment by amoghrajesh** [comment]
@Dr-Denzy @potiuk I would like to take this up. Any starting point here would be nice :)

**Comment by potiuk** [comment]
It's a UI things. I keep a bit away from that - it looks like some javascript update and needs understanding how FAB connection view form maps into the UI - that's basically the starting point. When I did work there I was just running it locally and debugging what's going on when I opened the form - seeing what was produced on the web/javascript page - more discovery than knowledge. And I forgot all that I learned then since :). Long time ago.
