### ISSUE TITLE
Give every Airflow component a UUID

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#25252]
### Description

It would be great if every scheduler, webserver, worker, and triggerer had their own UUID that they emit as part of logs so that when logs from multiple components are put together in a log search tool you can easily track the logs from a specific component.

I would suggest the new UUID 7 so that they can be sorted by start time.

There's a similar argument to be made for giving each task instance a UUID, so depending on discussion here I may open a separate issue for that.

### Use case/motivation

Although it is possible to enrich Airflow logs with information about their source using many log aggregators, this still falls a bit short. For instance, if a scheduler running in a Kubernetes pod fails a liveness check, the container will restart. The new scheduler will have the same pod name and container name within that pod as the old scheduler, so telling them apart requires knowing about the restart for other context.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You should take a  look at our OpenTelemetry planned feature https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-49+OpenTelemetry+Support+for+Apache+Airflow  - it has already been voted and approved at the devlist and we will likely start implementing it soon.  And various unique IDs (especially for traces) are part of it. Rather than modify existing behaviour, we should focus on implementig Open Telemetry. Feel free to contribute to that effort when it starts. 

Closing as won't fix.
