### ISSUE TITLE
GCSToSnowflakeOperator with feature parity to the S3ToSnowflakeOperator

### ISSUE THREAD

**Issue by sfc-gh-druthven** [apache/airflow#25395]
### Description

Require an operator similar to the S3ToSnowflakeOperator but for GCS to load data stored in GCS to a Snowflake table.

### Use case/motivation

Same as the S3ToSnowflakeOperator.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Marked it as good first issue - maybe someone will pick it up- but FYI @druthven - in OSS project like this, such features like this get implemented when .... someone implements it. So the best way (if you are really into getting this to happne) is to implement it yourself and become one of the many contributors (> 2100)  - most of them users like you who had the need for something and implemented it.

**Comment by blcksrx** [comment]
I would like to do it

**Comment by Taragolis** [comment]
@potiuk @blcksrx Just want to mention that right now S3ToSnowflakeOperator it is just wrapper around [COPY INTO \<table>](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#syntax) where location is `externalStage`.  Due to the fact that operator only uses internal snowflake capabilities: [STAGE](https://docs.snowflake.com/en/sql-reference/sql/create-stage.html) it should work not only with AWS S3 but also with GCS and Azure Containers.

Might be better rename(deprecate)`S3ToSnowflakeOperator` to something like `CopyIntoTableFromExternalStageOperator`, change `s3_keys` to `files` and mention that it works with AWS S3, GCS and Azure Containers

cc: @druthven

**Comment by eladkal** [comment]
@Taragolis can you start a PR?

**Comment by Taragolis** [comment]
@eladkal I could start but at the moment I have problems with time balance. So if I start with this PR I am afraid it wouldn't happen before mid of August.

If someone want work on this feature right now I will be happy to give the opportunity to extend the existing operator to someone else.

In case if it won't implements at moment when I ready to work on this PR I will create PR definitely.

**Comment by blcksrx** [comment]
I can work on it
