### ISSUE TITLE
Unable to mark_tasks.set_state to SKIPPED

### ISSUE THREAD

**Issue by ghost** [apache/airflow#25463]
### Apache Airflow version

2.3.3 (latest released)

### What happened

Crash while trying to call set_state from module common.mark_tasks with state SKIPPED. 
TaskInstanceState can be set to SKIPPED but while trying to set the same state to downstream dags the app crashes at DagRunState does not accept SKIPPED state. 

### What you think should happen instead

Either:

- allow DagRunState to be SKIPPED (more difficult)
- while skipping tasks set downstream dags to state FAILED (easy)

### How to reproduce

call common.mark_tasks.set_state with state SKIPPED

### Operating System

macOs 12.5

### Versions of Apache Airflow Providers

2.3.3

### Deployment

Virtualenv installation

### Deployment details

The error happens even when running airflow locally.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
That function is an internal helper that should not be called directly. Why are you doing it?

**Comment by meryll** [comment]
Unfortunately we are calling this function from our custom airflow plugin. And currently, I am in the process of migrating it from airflow 2.2.3 to 2.3.3..
Is there any other way to set airflow tasks to SKIPPED?

**Comment by uranusjr** [comment]
The official way is to use the REST API. If you _must not_ send HTTP requests, [`set_state` on `TaskInstance`](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/taskinstance/index.html#airflow.models.taskinstance.TaskInstance) is currently considered supported, although direct access to `airflow.models` is generally strongly discouraged.

In the mean time, I’ll close this issue since we don’t support such use cases. Feel free to open a new issue if the REST API does not work as desired.
