### ISSUE TITLE
BigQueryGetDataOperator does not support passing project_id

### ISSUE THREAD

**Issue by sudohainguyen** [apache/airflow#25781]
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow-providers-google==8.3.0

### Apache Airflow version

2.3.2

### Operating System

MacOS

### Deployment

Other

### What happened

Can not actively pass project_id as an argument when using `BigQueryGetDataOperator`. This operator internally fallbacks into `default` project id.

### What you think should happen instead

Should let developers pass project_id when needed

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gustavom2998** [comment]
Found an issue/bug while using the code from the last merge. In [line 443](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/operators/bigquery.py#L443) we need to add the following row to the get_schema operation, otherwise the check goes to the wrong project - so the operator won't work. I managed to get it working locally by making the following change:

```python
schema: Dict[str, list] = hook.get_schema(
    dataset_id=self.dataset_id,
    table_id=self.table_id,
    project_id=self.project_id
)
```
