### ISSUE TITLE
Connection test just shows red rectangle

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#26042]
### Apache Airflow version

main (development)

### What happened

I was walking through this tutorial: https://astro-sdk-python.readthedocs.io/en/stable/getting-started/GETTING_STARTED.html which had me create an aws connection.  After doing so, I clicked the "test" button, and saw this:

<img width="403" alt="Screen Shot 2022-08-29 at 10 54 35 AM" src="https://user-images.githubusercontent.com/5834582/187253551-bbcace51-b203-444d-805e-e7608ec41b0e.png">

And this in the webserver logs:
```
[2022-08-29 10:52:59,759] {base.py:69} INFO - Using connection ID 'hSL34Jpz' for task execution.
[2022-08-29 10:52:59,759] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='hSL34Jpz', conn_type='aws') credentials retrieved from login and password.
[2022-08-29 10:52:59 -0600] [64218] [WARNING] Worker with pid 64227 was terminated due to signal 11
```

### What you think should happen instead

I'm assuming that the error message was empty because the worker which was supposed to populate it died before it got a chance.  If this happens, I'd still like to get *something* in the UI. For instance, it could say: `Worker with pid 64227 was terminated due to signal 11` which would at least give me something.

### How to reproduce

test a connection.  I've also seen this with the snowflake provider, so I don't think it's aws specific

### Operating System

Mac OS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==5.0.0
apache-airflow-providers-common-sql==1.1.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-snowflake==3.2.0
apache-airflow-providers-sqlite==3.2.0

### Deployment

Virtualenv installation

### Deployment details

I've been setting up airflow venvs like this (nothing especially weird in this case)

1. clone airflow (currently at 018f1d5ebb )
2. `python scripts/ci/pre_commit/pre_commit_compile_www_assets.py`
3. run postgres in docker in a separate shell and set up the venv like so:
```
ENV_NAME="$(pwd | sed 's#/#_#g')"
pyenv virtualenv 3.10.6 $ENV_NAME
pyenv activate $ENV_NAME
export AIRFLOW_HOME=$(pwd)
pip install psycopg2
pip install ~/src/airflow
pip install 'astro-sdk-python[amazon,snowflake]>=0.11'
airflow info
sed -i .bak 's#^sql_alchemy_conn = .*$#sql_alchemy_conn = postgres://postgres:postgres@0.0.0.0#g' airflow.cfg
sed -i .bak 's#^load_examples =.*$#load_examples = False#' airflow.cfg
sed -i .bak 's#^executor =.*$#executor = LocalExecutor#' airflow.cfg
rm *.bak
airflow db init
airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.org
```
5. modify airflow.cfg to include the following
```
[core]
enable_xcom_pickling = True

[astro_sdk]
SQL_SCHEMA = ASTRO_SDK_SCHEMA
```
5. `airflow webserver`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatrixManAtYrService** [comment]
I've been having signal 11-related problems lately (ever since I stated messing around with providers).  Probably the core of this has something to do with a provider and is not a core airflow bug.  Still I think we should be a little more verbose when it comes to communicating this error.

**Comment by potiuk** [comment]
> I've been having signal 11-related problems lately (ever since I started messing around with providers). Probably the core of this has something to do with a provider and is not a core airflow bug. Still, I think we should be a little more verbose when it comes to communicating this error.

Surely. Signal 11 is SIGSEGV which generally means that there is a serious error with your installed libraries. I.e. we have completely no idea what is the error because likely your deployment is messed up (for example you have broken libraries installed. It's generally rather bad error indicating that you have done something, airflow maintainers could not foresee and generally it crashes python interpreter, so in-general there is no way to provide any information, because at the moment it crashes, we have no way to handle it.

But If you think there is a better way and you would like to submit a fix to make a bettter message in this case - we are absolutely open to accept a fix. Since we do not know what is the root cause (somewhat broken environment in the way that crashes C-level library) you are probably one of the best people to be able to provide the fix - because you have the unique environment that generates this error. 

And since Airflow is created by > 2100 contributors - people like you who often contributed a fix when they had problem, you are most welcome to join the team.

I will convert it to discussion and if you will be able to provide a fix that will provide a better description, that would be fantastic.
