### ISSUE TITLE
API Endpoints - /xcomEntries/{xcom_key} cannot deserialize customized xcom backend

### ISSUE THREAD

**Issue by hayt0n** [apache/airflow#26174]
### Description

We use S3 as our xcom backend database and write serialize/deserialize method for xcoms.
However, when we want to access xcom through REST API, it returns the s3 file url instead of the deserialized value. Could you please add the feature to support customized xcom backend for REST API access?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Can you provide the traceback emitted in the logs when the error occurs?

**Comment by herunyu** [comment]
![image](https://user-images.githubusercontent.com/5023850/188603574-1fef43b7-4f24-4aa7-812f-cef5fcec95d5.png)

**Comment by herunyu** [comment]
There is no error. So what we did is save the json into a pickle file by overwriting the serialize_value method. And we deserialized it when we do ti.xcom_pull. So we will get the actual value we saved.
But now when we get xcom through REST API, we will get the pickle file url like in the airflow UI
![image](https://user-images.githubusercontent.com/5023850/188605045-f0541599-0765-4c47-9a98-d3d77f88ea32.png)
And we check the API code and it seems it did not call deserialize_value to get the actual value we want.
![image](https://user-images.githubusercontent.com/5023850/188603661-ee3bb40a-5fc8-4d07-afd0-f8e99b7ae173.png)

**Comment by uranusjr** [comment]
Ah I see, thanks for the additional context. I think calling `deseralize_value` would be problematic because not everything deserialised can be sent through the wire, which is probably why the current implementation doesn’t do that.

One way I can think of to make this work would be to add an additional function in the XCom backend protocol for “serialise for API”. The default (JSON) backend would simply use the same serialisation logic used to save the value to the database, but custom backends can implement it differently to dump data.

**Comment by herunyu** [comment]
Cool. That's what we want with the API. We look forward to having this feature in 2.4. Thanks in advance!

**Comment by uranusjr** [comment]
Note that we’re quite close to the feature freeze now (it should happen sometime this month), so I can’t guarantee this will make it into 2.4.

**Comment by herunyu** [comment]
I see. We will do some workaround at this moment. No worries. Thank you.
