### ISSUE TITLE
Continuously logging and Batch logging mode for the aws Glue job's execution logs

### ISSUE THREAD

**Issue by nikhi-suthar** [apache/airflow#26203]
### Description

Currently Airflow does not print the **`Glue job`** execution logs due to the bug highlighted in **Related Issue**. This feature will enable the **Continuously logging** and **Batch logging**  of **`Glue jobs`** in **`Airflow`**  based on the **`GlueJobOperator`** input parameters. 

### Use case/motivation

I have orchestrated multiple Glue jobs with Airflow, Due to existing code  bug and no option for continuously logging, I have to check **`AWS Cloudwatch`** explicitly for Glue job's logs. After this feature, we will not require to check the logs at  **`AWS Cloudwatch`**, **the same logs will be available at **`Airflow`** for monitoring the Glue jobs.** 

### Related issues

https://github.com/apache/airflow/issues/26196

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment]
There have been a lot of updates to this code since this issue was cut. After having a closer look, while we wait in a while loop for the job to complete we call `self._handle_state(...)` each iteration. Within that we call:
https://github.com/apache/airflow/blob/ba20d06b5e8ae47cf684306c55dbef14c4e791f1/airflow/providers/amazon/aws/hooks/glue.py#L324-L329

So I suspect we're "continuously" getting glue logs these days while waiting for a job. Can you confirm that latest main solves your original concern @nikhi-suthar? Thanks!
