### ISSUE TITLE
Documentation unclear about multiple LocalExecutors on HA Scheduler deployment

### ISSUE THREAD

**Issue by vitaly-krugl** [apache/airflow#26565]
### What do you see as an issue?

According to Airflow documentation, it's now possible to run multiple Airflow Schedulers starting with Airflow 2.x.

What's not clear from the documentation is what happens if each of the machines running the Scheduler has executor = LocalExecutor in the [core] section of airflow.cfg. In this context, if I have Airflow Scheduler running on 3 machines, does this mean that there will also be 3 LocalExecutors processing tasks in a distributed fashion?

### Solving the problem

Enhancing documentation to clarify the details about multiple LocalExecutors on HA Scheduler deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You got an explanation in https://github.com/apache/airflow/discussions/26564#discussioncomment-3702194 - if you would like to enhance documentation - feel free to open PR. It's as easy as opening the documentation on our website and clickling "suggest a change on this page". The PR will open and you will be able to modify the docs and open a PR.

Airlfow is created by almost 2200 contribuors like you and many of them provided fixes and docs changes when they found it is missing in return for the free software they got.  You are likely the best person now - since you looked for the information to formulate it and find the best place and way to describe it. Such user-provided-documentation is most valuable as we have far too many assumptions in our heads.

Looking forwar to a PR and happy to review it when ready.

**Comment by shashwata27** [comment]
@potiuk im opening the PR
