### ISSUE TITLE
"task_fail" contains duplicates for FK to "task_instance" table

### ISSUE THREAD

**Issue by kosteev** [apache/airflow#26627]
### Apache Airflow version

Other Airflow 2 version

### What happened

Airflow 2.3.3.
Task instance failures produce duplicates in "task_fail" table for this constraint (dag_id, task_id, run_id, map_index).

### What you think should happen instead

Recently FK constraint between task_fail and task_instance tables was introduced:
https://github.com/apache/airflow/pull/22260
And then there was a change to purge duplicates for this constraint from task_fail table (on db upgrade):
https://github.com/apache/airflow/pull/22769

Removing duplicates on db upgrade to Airflow 2.3+ before establishing FK between tables makes sense, however these duplicates can occur in running Airflow 2.3+ instance (see "How to reproduce").

What is rationale for removing duplicates once on upgrading to Airflow 2.3+ but keeping this possibility to generate duplicates again? Isn’t it going to break foreign key and integrity of these two tables?

### How to reproduce

Trigger DAG with task that fails multiple times for different tries, it will produce duplications in "task_fail" table.
Example (two tries with 5 mins interval for retries):
```
id | task_id |    dag_id    |          start_date           |           end_date            | duration | map_index |                run_id
1  | task    | dag1_failing | 2022-09-23 09:11:44.102894+00 | 2022-09-23 09:11:44.469007+00 |        0 |        -1 | scheduled__2022-09-22T00:00:00+00:00
3  | task    | dag1_failing | 2022-09-23 09:16:44.995269+00 | 2022-09-23 09:16:45.310398+00 |        0 |        -1 | scheduled__2022-09-22T00:00:00+00:00
```

### Operating System

Linux

### Deployment

Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
I tend to believe this is not the intention, and feel free to submit fixes where duplicates can be created. (Can you provide examples? You didn’t explain _when_ duplicates happen.)

**Comment by kosteev** [comment]
Sorry, I didn't stated it clearly, basically multiple failures of the same task instance produce duplicates in task_fail table.

**Comment by uranusjr** [comment]
Hmm yeah that makes sense. I’m guessing the duplicated entries should be expected, and deleting them on upgrade could be an accident…? Not sure. cc @dstandish

**Comment by dstandish** [comment]
Yes I think that removing the duplicates is not necassary.

**Comment by dstandish** [comment]
I'm taking a look at how we use taskfail though... i the effort is not super great, it would be best if we can figure out what is actually the key of this table and enforce it.  i know it's used in the `dags/./duration` view ... not sure what the consequence is of having the duplicates.

but from a referential integrity perspective, there's no issue because it is TF -> TI and not the other way around

**Comment by uranusjr** [comment]
From a “recording the history” perspective, I’d expect repeated TaskFail events be all be kept, and if the UI can only show one, it should have logic to only pull in the last failure for a ti.

**Comment by dstandish** [comment]
Yeah, sigh... PR to remove the check:  https://github.com/apache/airflow/pull/26714

I think in my head the FK ref direction was flipped so in my mind the TF records had to be deduped before adding the key.  My mistake.  Fortunately, it seems of little consequence.

I looked at the code in the task duration and gantt views, the two locations where some processing of taskfail records is done.  It doesn't seem to work quite correctly.  

For the task duration view, task fails are only accounted for in the cumulative view (they are ignored in the non-cumulative view), and the cumulative view seems broken because it can go down with increasing time.

For gantt view, it seems that taskfail records do not have an effect on the chart.

**Comment by Jaxing** [comment]
Maybe this belongs to a new issue but I think it stems for the same problem.
When upgrading to 2.3.0 from 2.2.5 we got a similar issue, i.e. duplication in the task_fail table.

During the upgrade the duplicates are moved to _airflow_moved__2_3__duplicates__task_fail. However the schema of this table is quite different from the task_fail table 

Here is the columns from the `_airflow_moved__2_3__duplicates__task_fail`:
id  | task_id | dag_id | execution_date | start_date | end_date | duration
----|----|----|----|----|----|----

And here is the columns from the new (?) `task_fail`:
 id  | task_id | dag_id | start_date | end_date | duration | map_index | run_id 
----|----|----|----|----|----|----|---

So it's not clear how I could revert this delete if I'd like to since I'm missing data like map_index and run_id.

**Comment by dstandish** [comment]
Closing this issue; check removed here https://github.com/apache/airflow/pull/26714
