### ISSUE TITLE
Variables set via environment not accessible via HTTP API

### ISSUE THREAD

**Issue by m1racoli** [apache/airflow#26861]
### Apache Airflow version

2.4.1

### What happened

Considering that an Airflow variable had been set via the environment variable `AIRFLOW_VAR_HELLO`, we were able to access it via the HTTP API `/api/v1/variables/HELLO`.

Since Airflow 2.4.1 this is not possible anymore.

### What you think should happen instead

We should be able to access Airflow Variables via the HTTP API in the same way as they can be retrieved via code.

### Operating System

Debian

### Deployment

Astronomer

### Deployment details

Local docker compose via astro dev command.

### Anything else

Since upgrading to Astronomer Runtime 6.0.2 (Airflow 2.4.1). We did not have issues in Runtime 5.0.8 (Airflow 2.3.4).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
This is due to commit 98f16aa7f3b577022791494e13b6aa7057afde9d (https://github.com/apache/airflow/pull/25370) where database query is used instead of `Variable.get` where `get` method went through all backends to fetch the variable value.

**Comment by tirkarthi** [comment]
Looking further into this it seems the variables set through environment variables are not returned in the list of all variables endpoints. There is also a note on this in docs that environment variables are not listed in web UI. I have a patch that restores the previous behavior along with keeping the changes from commit https://github.com/apache/airflow/commit/98f16aa7f3b577022791494e13b6aa7057afde9d . But this creates a discrepancy where the variable is present in get variables endpoint and not in the list variables endpoint. Shall I proceed with the patch or this can be closed as not a bug?

https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#storing-variables-in-environment-variables

> Variables set using Environment Variables would not appear in the Airflow UI but you will be able to use them in your DAG file. Variables set using Environment Variables will also take precedence over variables defined in the Airflow UI.

Sample patch with tests : 

```diff
diff --git a/airflow/api_connexion/endpoints/variable_endpoint.py b/airflow/api_connexion/endpoints/variable_endpoint.py
index 25f8969d46..a80c31756d 100644
--- a/airflow/api_connexion/endpoints/variable_endpoint.py
+++ b/airflow/api_connexion/endpoints/variable_endpoint.py
@@ -46,10 +46,17 @@ def delete_variable(*, variable_key: str) -> Response:
 @provide_session
 def get_variable(*, variable_key: str, session: Session = NEW_SESSION) -> Response:
     """Get a variable by key"""
-    var = session.query(Variable).filter(Variable.key == variable_key)
-    if not var.count():
-        raise NotFound("Variable not found")
-    return variable_schema.dump(var.first())
+    var = session.query(Variable).filter(Variable.key == variable_key).first()
+    if var:
+        return variable_schema.dump(var)
+    else:
+        try:
+            val = Variable.get(variable_key)
+        except KeyError:
+            raise NotFound("Variable not found")
+
+        variable = Variable(key=variable_key, val=val)
+        return variable_schema.dump(variable)
 
 
 @security.requires_access([(permissions.ACTION_CAN_READ, permissions.RESOURCE_VARIABLE)])
diff --git a/tests/api_connexion/endpoints/test_variable_endpoint.py b/tests/api_connexion/endpoints/test_variable_endpoint.py
index 1f490fb9eb..4cc4f49d83 100644
--- a/tests/api_connexion/endpoints/test_variable_endpoint.py
+++ b/tests/api_connexion/endpoints/test_variable_endpoint.py
@@ -138,6 +138,14 @@ class TestGetVariable(TestVariableEndpoint):
         assert response.status_code == 200
         assert response.json == {"key": "foo/bar", "value": expected_value, "description": None}
 
+    def test_environment_variable(self, monkeypatch):
+        monkeypatch.setenv("AIRFLOW_VAR_HELLO", "bar")
+        response = self.client.get(
+            "/api/v1/variables/HELLO", environ_overrides={'REMOTE_USER': "test"}
+        )
+        assert response.status_code == 200
+        assert response.json == {"key": "HELLO", "value": "bar", "description": None}
+
 
 class TestGetVariables(TestVariableEndpoint):
     @parameterized.expand(
```

**Comment by tirkarthi** [comment]
cc: @norm

**Comment by m1racoli** [comment]
I believe that the Airflow UI and the HTTP API serve fundamentally different purposes. The Airflow UI not showing variables can be considered an inconvenience to an end user.

In contrast the HTTP API serves as an extension to the Python API, accessed by other tools and services.

Removing the ability to access variables as they would be available to the code would remove it as a source of truth. In particular it breaks our integrations for test automation we have built for our Airflow setups.

**Comment by potiuk** [comment]
I am inclining to close it as "not a bug" but would love to hear also what others say.

While this change is indeed breaking old behaviour, one might say it is bringing back consistency to the behaviour of the API with other API's and fixing an incidental behaviour that the API shown before. 

Nowhere it is mentioned, needed or even expected that the API is "single source of truth" - in this case there is not even single "truth" that we can talk about. It all depends on definition the `get_variable` function has.

If we define "variable" APIs as exclusively showing and managing variables that are defined via DB then:

a) it is consistent wihth list, update, create delete methods - it is impossible to modify in any way the variables defined via env variables or even secrets, so naturally, those methods do not work. Similarly it is just "standard" airflow behaviour that listing a variables defined by env variables or secrets is impossible. You need to know they are there. 

b) if the variable is defined in both DB and env, then this is impossible to read DB variable which you just set with PATCH. That turns effectively the DB variable in "write-only"  - you can create, update, delete it. But you can't read it. That was very inconsistent behaviour that #25370

c) the new behaviour is consistent with UI/Web behaviour - you cannot list/read env variables via web.

d) if we leave the env variable reading, we open up for behaviour where it might be wrong anyway. The API endpoint runs on the webserver, so if you set variable via ENV variables only on workers and scheduler, but not on the webserver, the API will not return the right "ENV" variable value anyway. And TBH - the env variable for variables set on webserver are useless because none of the webserver code uses variables (except from manipulating the DB variables) - the only way you can actually use variables is in workers (and if you are a bit sloppy and do not follow our best practices - in DagFileProcessor - but this should be discourage due to performance reasons).

That means that it cannot even be considered as "source of truth" because the "truth" will depend on whether the ENV is set consistently everywhere. It is not required either to have same ENV variable everywhere. You could even imagine that you have different types of workers and each worker has a different ENV variable set. For example you could use variable to get the right URL you should use for this particular worker to communicate - and the URL could be different for different workers. This is a very viable use of ENV-defined variables and nowhere in Airlfow we prevent or discourage doing it. It will "just work". In this case it's even IMPOSSIBLE to get the source of truth because the value of the variable from env will be different on each worker and `get_variable` would be completely meaningless in this context.

Taking into account all of the above I have strong opinion that we should close it. I am going for holidays now, but if there are other committers who think similarly, and agree with me, then I think we should close that one.

**Comment by m1racoli** [comment]
Alright, after letting the issue think in a bit I ended up implementing a custom endpoint via webserver plugins. :)

**Comment by potiuk** [comment]
Sounds cool
