### ISSUE TITLE
Ooops! Something bad has happened. Please consider letting us know by creating a bug report using GitHub.  Python version: 3.7.10 Airflow version: 2.0.2 Node: redact .Error! Please contact server admin.

### ISSUE THREAD

**Issue by Maheshbbc** [apache/airflow#26900]
### Apache Airflow version

Other Airflow 2 version

### What happened

When tried to load Airflow UI in first place it errors out with below error Ooops!
Something bad has happened.
Please consider letting us know by creating a [bug report using GitHub](https://github.com/apache/airflow/issues/new/choose).

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.

### What you think should happen instead

The Airflow page should load instead of the error. Which it fails in first place.

### Operating System

Python version: 3.7.10 Airflow version: 2.0.2 Node: redact

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-sqlite==3.2.1

### Deployment

MWAA

### Deployment details

Running this with cloud formation stack to build MWAA.

### Anything else

Every time I click on Open Airflow UI the page loads for few seconds and the gives error 
Ooops!
Something bad has happened.
Please consider letting us know by creating a [bug report using GitHub](https://github.com/apache/airflow/issues/new/choose).

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
There is not enough information to act on it. Please take a look at your logs and try to give at least a clue of what's going on. Note that the invitation to open an issue, does not mean we can solve your issue if you do not describte what the issue is - with logs, configuration information, and at least some indication that this is an airlfow issue that allow us to investigate what airflow but it is

Since you are on MWAA you should rather follow 'Error! Please contact server admin.' - which is MWAA team in this case.
