### ISSUE TITLE
Queries to automate workflow on AWS

### ISSUE THREAD

**Issue by sarveshgupta89** [apache/airflow#270]
Hi,

I came across airflow and set it up. It is working fine. However, want to understand if airflow can be used to automate a custom workflow in amazon web services for spinning the cluster, executing the jobs and bringing down the cluster.

Regards,
Sarvesh

**Comment by tokenmathguy** [comment]
Via PythonOperator and boto you should be able to do such stuff.

On August 18, 2015, at 15:59, Sarvesh Gupta notifications@github.com wrote:

Hi,

I came across airflow and set it up. It is working fine. However, want to understand if airflow can be used to automate a custom workflow in amazon web services for spinning the cluster, executing the jobs and bringing down the cluster.

Regards,
Sarvesh

**Comment by r39132** [comment]
Can you provide more details on exactly what you want to do? For example, if you want to run Spark/MapReduce jobs in AWS but don't want to keep these clusters running long term, you could use Airflow to leverage EMR. If you are planning on spinning up your own clusters in EC2 using automation like Ansible/Vagrant, then you may want to think twice, since you may need a more complete orchestration framework, such as consul, to deal with errors.

**Comment by cvarelaruiz** [comment]
I agree with @tokenmathguy you can DIY with boto. However, it would be nice to encapsulate common AWS tasks in ready-made operators to deal with things like spinning up/down instances in auto-scaling groups or send messages to SQS ...

**Comment by mistercrunch** [comment]
Operators and hooks are useful as a way to provide a simple/common interface to an underlying libraries, and hooks abstract away having to manage connection information or mechanics in your pipeline logic.

**Comment by r39132** [comment]
At Agari, we use airflow to spin up EMR clusters, execute steps, and spin down the cluster. We are hoping to generalize this as EMR operators. Otherwise, we use boto and the PythonOperator for everything on AWS (e.g. SQS, S3, SNS, etc...). Stay tuned for this coming functionality.
