### ISSUE TITLE
test_heartbeat_failed_fast not failing fast enough.

### ISSUE THREAD

**Issue by o-nikolas** [apache/airflow#27069]
### Apache Airflow version

main (development)

### What happened

In the #14915 change to make tests run in parallel, the heartbeat interval threshold was raised an order of magnitude from 0.05 to 0.5. Though I frequently see tests failing in PRs due breaching that threshold by a tiny amount. Do we need to increase that theshold again? CC @potiuk 
Example below where the time was `0.5193889999999999`, `0.0193...` past the threshold for the test:
```
   =================================== FAILURES ===================================
  _________________ TestLocalTaskJob.test_heartbeat_failed_fast __________________
  
  self = <tests.jobs.test_local_task_job.TestLocalTaskJob object at 0x7f4088400950>
  
      def test_heartbeat_failed_fast(self):
          """
          Test that task heartbeat will sleep when it fails fast
          """
          self.mock_base_job_sleep.side_effect = time.sleep
          dag_id = 'test_heartbeat_failed_fast'
          task_id = 'test_heartbeat_failed_fast_op'
          with create_session() as session:
      
              dag_id = 'test_heartbeat_failed_fast'
              task_id = 'test_heartbeat_failed_fast_op'
              dag = self.dagbag.get_dag(dag_id)
              task = dag.get_task(task_id)
      
              dr = dag.create_dagrun(
                  run_id="test_heartbeat_failed_fast_run",
                  state=State.RUNNING,
                  execution_date=DEFAULT_DATE,
                  start_date=DEFAULT_DATE,
                  session=session,
              )
      
              ti = dr.task_instances[0]
              ti.refresh_from_task(task)
              ti.state = State.QUEUED
              ti.hostname = get_hostname()
              ti.pid = 1
              session.commit()
      
              job = LocalTaskJob(task_instance=ti, executor=MockExecutor(do_update=False))
              job.heartrate = 2
              heartbeat_records = []
              job.heartbeat_callback = lambda session: heartbeat_records.append(job.latest_heartbeat)
              job._execute()
              assert len(heartbeat_records) > 2
              for i in range(1, len(heartbeat_records)):
                  time1 = heartbeat_records[i - 1]
                  time2 = heartbeat_records[i]
                  # Assert that difference small enough
                  delta = (time2 - time1).total_seconds()
  >               assert abs(delta - job.heartrate) < 0.5
  E               assert 0.5193889999999999 < 0.5
  E                +  where 0.5193889999999999 = abs((2.519389 - 2))
  E                +    where 2 = <airflow.jobs.local_task_job.LocalTaskJob object at 0x7f408835a7d0>.heartrate
  
  tests/jobs/test_local_task_job.py:312: AssertionError
  ```
  (source)[https://github.com/apache/airflow/actions/runs/3253568905/jobs/5341352671]

### What you think should happen instead

Tests should not be flaky and should pass reliably :) 

### Operating System

Linux

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think better solution would be to make it independent of the time. This is an inherent problem of tests that depend on particular timing that they might and will fail eventually. So better solution would be to fix the tests so that they do not dependen on timing. This can be handled better by introducing events and waiting for those. 

And I encourage you to try to do it :) 

But since this is often difficult to do and might require huge investment, if we can asses that we can safely increase such timers, we can do it to as "good-enough". There is never a "0-1" answer, this is left to the judgment of the person proposing such PR.

**Comment by potiuk** [comment]
BTW. In this particular case, i think the problem is that either test does not test what it should, or maybe the hearbeat mechanism should be changed to better match expectations.

The fact that hearbeats come wiht significant delays on a heavily loaded system if we expect them to come regularly, is actually disconnect between the expectations and reality. 

We should either have more relaxed expectations of the heartbeat frequency  (for example accept and communicate that heartbeats coming with 100% delay are still ok) or  make sure heartbeats are generated with very good regularity independent from the load of the system. I think regularity Is hard to achieve in case of Python due to mutli-processing /GIL and the fact that heartbeats use database while generating heartbeats  - this combination make it nearly impossible to guarantee that heartbeat will come  with great regularity. So I'd s relaxing it and looking at what is the consequence of it is likely better way.

**Comment by o-nikolas** [comment]
> We should either have more relaxed expectations of the heartbeat frequency (for example accept and communicate that heartbeats coming with 100% delay are still ok) or make sure heartbeats are generated with very good regularity independent from the load of the system. I think regularity Is hard to achieve in case of Python due to mutli-processing /GIL and the fact that heartbeats use database while generating heartbeats - this combination make it nearly impossible to guarantee that heartbeat will come with great regularity. So I'd say relaxing it and looking at what is the consequence of it is likely better way.

Yupp, agreed on the latter. We hear this a lot from customers, who are worried about scheduler heartbeat delay. And while it is a good indicator of load, that's about it (unless it stops entirely, then you have a problem :sweat_smile:). So if we "rebrand" the heartbeat to be just that, users will hopefully be less concerned when it falls behind when the environment is being pushed hard.

> But since this is often difficult to do and might require huge investment, if we can asses that we can safely increase such timers, we can do it to as "good-enough". There is never a "0-1" answer, this is left to the judgment of the person proposing such PR.

Indeed, I don't have the time to invest in this particular area at the moment (which is why it's good to document these things in issues because someone else might!). So if this becomes a nuisance, then I agree that we could just bump the limit for a stopgap solution, but not resolve this issue (which will represent a more long term solution).
