### ISSUE TITLE
Add support for compression for remote logs

### ISSUE THREAD

**Issue by malthe** [apache/airflow#27436]
### Description

Since remote logs are sent only on completion, Airflow should support compressing them to save disk space.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I will convert it into discussion. this is far from clear what expectation we have here.

What do you mean by remote logs in this context? Airflow has a number of handlers to send the remote logs to and how they are implemented depends on the system to send the logs to. Some habdlers handle only sending full logs (S3) and some are streaming (cloudwatch). Also I am not sure what do you mean by "compression" in this case. I'd understand if it was for actual local stored logs (but even then compression should be done by external scripts rather than by Airflow IMHO - or at the worst case if someone wnats they can install and configure logger handler such as this one https://pypi.org/project/compressedlogger/  - not sure why we would have to implement something like that in Airflow.

Could you please explain what do you mean by the request ? 

Converting into a discussion until this is clear :)
