### ISSUE TITLE
Remove the additional constraints  from the Airflow installation script

### ISSUE THREAD

**Issue by winsont1** [apache/airflow#27632]
### What do you see as an issue?

Remove the additional constraints  from the Airflow installation script
pip install \
 apache-airflow==1.10.12 

![image](https://user-images.githubusercontent.com/16263869/201460873-59272909-e051-4ce5-a6c6-34fc00358d39.png)

### Solving the problem

Kindly remove the additional constraints  from the Airflow installation script, as I was encountering a legacy error when installing it on Windows WSL (Linux) using the constraints. Once the constraints were removed, the installation went through.
(Error pic included)
![image](https://user-images.githubusercontent.com/16263869/201460953-6a4b92d5-f50c-451c-b043-28fc2b772a55.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Airflow 1.10 is not supported any more for more than a year and users should not install it as it contains multiple security vulnerabilities that have been fixed since.. Removing constraints is not a good solution. You should use very old version of 'pip' when you are installing 1.10 (but you really, really, really should not do it). The version that should work is pre 20.3. (20 is version from 2020 when 1.10 was still active). If you want to reliably install airflow 1.10, just install old pip first and it should work with constraints.

Removing constraints is not a good solution also because it will not work without them when you install extras so it is not good solution.

Pleas migrate to airflow 2.
