### ISSUE TITLE
ERROR: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/apache/airflow/constraints-2.4.3/constraints-3.11.txt

### ISSUE THREAD

**Issue by bertiewooster** [apache/airflow#27676]
### Apache Airflow version

2.4.3

### What happened

When I tried to install via the [Quick Start instructions](https://airflow.apache.org/docs/apache-airflow/stable/start.html), using Python 3.11 in a venv, I got this error when I ran `pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"`:

`ERROR: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/apache/airflow/constraints-2.4.3/constraints-3.11.txt`

### What you think should happen instead

I believe there is no url set up for Airflow 2.4.3 and Python 3.11. When I ran the same instructions using Python 3.10 in a venv, there was no error at `pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"`

### How to reproduce

1. Create a Python venv based on Python 3.11
2. Follow the [Quick Start instructions](https://airflow.apache.org/docs/apache-airflow/stable/start.html) through `pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"`
3. The error should appear 

### Operating System

MacOS 12.5.1

### Versions of Apache Airflow Providers

Not applicable

### Deployment

Other

### Deployment details

This is just on my local machine

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Python 3.11 is not yet officially supported. See #27264.

**Comment by bertiewooster** [comment]
Fair enough. Suggest the tutorial note this--this is going to happen to many people.

**Comment by potiuk** [comment]
> Fair enough. Suggest the tutorial note this until 3.11 is supported--this is going to happen to many people, and a note will prevent them from either giving up or opening tickets like this.

It is already mentioned in https://airflow.apache.org/docs/apache-airflow/stable/installation/prerequisites.html and https://github.com/apache/airflow/blob/main/README.md#requirements. For some reason you missed that part @bertiewooster 

If you think there is a better place it should be mentioned, I suggest you make a PR in the documentation in the appropriate place. Airflow has more than 2200 contributors - most of them people like you who spotted some problems and corrected them

It's equally easy (or even easier) than writing a comment here - just find the documentation page that you think it should be added, click "Suggest a change on this page" and PR will be opened for you and you will be able to use the same GitHub UI interface you are using now. 

And you are probably absolutely the best person in the world to know where to look for it, because you just missed explicitly stated prerequisites - undoubtedly you know where to add this information to make it more obvious.

Looking forward to seeing your PR @bertiewooster

**Comment by potiuk** [comment]
That would be a great help for others who will make the same mistake BTW.

**Comment by bertiewooster** [comment]
That "Suggest a change on this page" button is a slick, low-barrier-to-entry way to let newcomers propose changes to documentation. I'd like to suggest it for another repo I work on. Is there documentation on how to install that button?

**Comment by potiuk** [comment]
It's just s standard sphinx theme feature. For example here you can read about the version we use i think  https://sphinx-book-theme.readthedocs.io/en/stable/customize/source-files.html . Other tools and doc systems might have their own ways to approach it.
