### ISSUE TITLE
Can't build from Airflow dockerfile using Azure Container Registry due to BuildKit requirement

### ISSUE THREAD

**Issue by MohnJadden** [apache/airflow#27690]
### What do you see as an issue?

I am using Azure Container Registry to test out Airflow.  When I try to build an image using the Dockerfile as saved directly from this repo, the build fails.  

I am running the command `az acr build --registry mycontainerregistryname --image apache/airflow:latest --file Dockerfile .` as described by [this Azure quickstart](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-quickstart-task-cli?source=recommendations).  

Some research brought up the fact that this Dockerfile requires BuildKit support to be enabled.  Azure Container Registry doesn't seem to have any option to enable BuildKit or set environment variables.  Thus, I can't build a container image using Azure Container Registry.

### Solving the problem

The documentation should include steps to either fix the Dockerfile and deploy via Azure Container Registry, or a different Dockerfile should be made available for ACR users.  

### Anything else

I can reproduce the issue at will, in any Azure tenant.  I do not have Docker Desktop installed nor do I plan on doing so, this is meant to be cloud-only as a proof of concept.

The output errors out as follows:

```
Packing source code into tar to upload...
Uploading archived source code from 'C:\Users\me\AppData\Local\Temp\build_archive_f21856754d2244b3b4b1b2db63ca5941.tar.gz'...
Sending context (244.851 MiB) to registry: mycontainerregistry...
Queued a build with ID: ca1
Waiting for an agent...
2022/11/15 14:28:42 Downloading source code...
2022/11/15 14:28:50 Finished downloading source code
2022/11/15 14:28:50 Using acb_vol_2bf0e2cb-ca55-4dd7-99b9-b55345553be4 as the home volume
2022/11/15 14:28:50 Setting up Docker configuration...
2022/11/15 14:28:51 Successfully set up Docker configuration
2022/11/15 14:28:51 Logging in to registry: mycontainerregistry.azurecr.io
2022/11/15 14:28:52 Successfully logged into mycontainerregistry.azurecr.io
2022/11/15 14:28:52 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2022/11/15 14:28:52 Scanning for dependencies...
2022/11/15 14:28:52 Successfully scanned dependencies
2022/11/15 14:28:52 Launching container with name: build
Sending build context to Docker daemon  1.233GB
Error response from daemon: dockerfile parse error line 76: unknown instruction: SET
2022/11/15 14:29:00 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1

Run ID: ca1 failed after 19s. Error: failed during run, err: exit status 1
Run failed
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MohnJadden** [comment]
Let me clarify: this is using Azure Container Registry, which is a managed Azure service.  It isn't using Docker on a machine running Linux or Windows, nor is it building the image on any local machine - ACR builds/launches/terminates containers as a managed service.  There's no Windows environment involved; the issue replicates whether it's run from a Windows machine, Linux machine, or Azure Cloud Shell running bash.  

The link you provided deals with Azure Devops pipelines, which are not in use in this situation.  

I have done my research and googling, and was unable to find any clear details on whether ACR as a service can support Buildkit, but if you were able to find something, I'd love to have a look at the link.  Meanwhile, the issue does still remain in that the project cannot build with the available documentation.  Not everyone is a Docker pro, so having some of documentation that covers Azure Container Registry or AWS Elastic Container Registry would help Airflow gain traction and usage.  

I'm mostly commenting here for the record - I'll head to the Slack documentation channel rather than spam with requests to reopen - but I can't be the only person who was asked to look into implementing Airflow in a cloud provider container registry environment.  Having documentation that covers this use case and tech stack would be beneficial to increasing Airflow usage.

**Comment by potiuk** [comment]
Buildkit is available for building images for > 3 years (as far as I remember) in all docker versions released since and it can be enabled by setting `DOCKER_BUILDKIT=1` variable (this is what the solution I linked to does if you look closely). And it is explicitly described in our changelog here https://airflow.apache.org/docs/docker-stack/changelog.html#airflow-2-3

We even figured out recently how to use buildking in engine-less `colima` (documentation of it is being contributed soon by one of the contributors who tried it recently).

We only switched to use it after more than 2 years of trying an experimenting with it and after it became available in all docker versions that you might possibly imagine to run (I specifically hold on with the switch waiting for a long time to pass and making sure all operating systems people would like to use have it.  

> Having documentation that covers this use case and tech stack would be beneficial to increasing Airflow usage.

Absolutely. By all means. I recommend you to try to figure it out on your own and if you think others  would benefit from your investigation, I heartily recommend you @MohnJadden to improve our documentation and describe how to do it (like more than 2000 other contributors did when they found that they could help others solving some of their specific problems). It is super easy - you go to our docs in the place you think it should be added you click "Suggest a change on this page" and it will open a PR where you will be able to add appropriate instructions. No development needed - it will take less time than even responding to that comment, and I heartily recommend this route for you. We have more than 2000 contributors in Airflow and most of them were users like you who got a free software, lacked some documentation, found a solution and proposed a PR with their findings so that others can benefit from that. This is the least you can do as a contribution back for the software you get for free which is built and maintained by the community. 

If you won't find a solution - I recommend you create an issue in Azure Container Registry and ask for this capability. This is their problem of not supporting it, not ours if you cannot enable it. Maybe they need to improve their documentation, or enable this feature, or maybey you are doing something wrong, but this is the case between you and them and there is no way Airflow can base their decision on some platform sticking to technology that is more than 3 years old. If they do, then I think personally you should consider switching to something else. But I serioulsy doubt it and - since you are paid user - i believe if you reach out to them they will help you to understand how to do it.
