### ISSUE TITLE
Add AWS Neptune hook and operators

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#28289]
### Body

[Neptune](https://docs.aws.amazon.com/neptune/index.html) is a graph db offered by AWS.
boto3 endpoints can be seen [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/neptune.html)
I think for start we need the following:
```
NeptuneHook
NeptuneStartDbOperator
NeptuneStopDbOperator
```

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by swapz-z** [comment]
Hello @eladkal 
I would love to take this up

**Comment by Taragolis** [comment]
@swapz-z assigned to you

**Comment by ChhaSahil** [comment]
Hello @eladkal 
I would also love to take this one!

**Comment by eladkal** [comment]
@ChhaSahil the issue is already assigned.
Maybe you can find other issue that you like to work on? https://github.com/apache/airflow/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by eladkal** [comment]
@swapz-z are you still working on the issue?

**Comment by swapz-z** [comment]
Yes @eladkal.
Will raise a PR this week

**Comment by shubham22** [comment]
@swapz-z - are you still looking into this? Let us know if you need any help. cc: @o-nikolas

**Comment by swapz-z** [comment]
Thanks for the patience @shubham22 @o-nikolas 

I am finished with the implementation.
However, for writing tests for operators, I am not sure, how to proceed with the same, since mypy or moto is not available for neptuneDB 

Your inputs on the PR and possible guidance of tests implementation is awaited
Thanks

**Comment by o-nikolas** [comment]
> Thanks for the patience @shubham22 @o-nikolas
> 
> I am finished with the implementation. However, for writing tests for operators, I am not sure, how to proceed with the same, since mypy or moto is not available for neptuneDB
> 
> Your inputs on the PR and possible guidance of tests implementation is awaited Thanks

You do not need Moto necessarily, it's a nice way to test hooks, but not strictly required. Just mock what you need to in order to test the functionality of the Operator and the Hook and then add a System Test to functionally test the Operator (which will test the hook).

You can see a recent example PR which has done this [here](https://github.com/apache/airflow/pull/28964/files) (it's a transfer operator, but the principles are the same).
You can see more details about writing AWS system tests in [this README](https://github.com/apache/airflow/blob/9b643c7201cb8b5d02c8fbd6b5917d35772101b7/tests/system/providers/amazon/README.md).

**Comment by eladkal** [comment]
>However, for writing tests for operators, I am not sure, how to proceed with the same, since mypy or moto is not available for neptuneDB

moto 4.1.4 add neptune coverage
http://docs.getmoto.org/en/latest/docs/services/neptune.html

**Comment by pateash** [comment]
@eladkal could you please assign this to me

**Comment by ellisms** [comment]
I'll take this one.

**Comment by pateash** [comment]
> I'll take this one.

Sure
