### ISSUE TITLE
Add a way to skip Docker Operator task

### ISSUE THREAD

**Issue by emil-k** [apache/airflow#28951]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow 2.3.3

Raising the `AirflowSkipException` in the source code, using the `DockerOperator`, is supposed to mark the task as skipped, according to the [docs](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#special-exceptions). However, what happens is that the task is marked as failed with the logs showing `ERROR - Task failed with exception`.

### What you think should happen instead

Tasks should be marked as skipped, not failed.

### How to reproduce

Raise the `AirflowSkipException` in the python source code, while using the `DockerOperator`.

### Operating System

Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-125-generic x86_64)

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
DockerOperator execute command outside of Airflow Worker and as result It can't catch any of exception raised in isolated environment (which could be any, not only Python).

**Comment by potiuk** [comment]
@Taragolis  is right, but It made me recall something. What we could do (and I will update the description appropriately) is to add `skip_exit_code` parameter to the DoclerOperator. I think we should be able to get the exit code resulting in skipping rather than failing as we did in Bash Operator: From https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/bash/index.html

```
skip_exit_code ([int](https://docs.python.org/3/library/functions.html#int)) – If task exits with this exit code, leave the task in skipped state (default: 99). If set to None, any non-zero exit code will be treated as a failure.
```

Adding this parameter and possibly updating documentation of AirlfowSkipException to clarify the behaviour would be a nice thing to add.

Marking it as good first issue bue mayne @emil-k  you could add a PR for that if you think you would like to become a contributor ?
