### ISSUE TITLE
sqlite conn id unclear

### ISSUE THREAD

**Issue by aamster** [apache/airflow#29113]
### What do you see as an issue?

The sqlite conn doc here https://airflow.apache.org/docs/apache-airflow-providers-sqlite/stable/operators.html is unclear.

Sqlite does not use username, password, port, schema. These need to be removed from the docs. Furthermore, it is unclear how to construct a conn string for sqlite, since the docs for constructing a conn string here https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html assume that all these fields are given. 

### Solving the problem

Remove unused arguments for sqlite in connection, and make it clearer how to construct a connection to sqlite

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by atharvmishra1999** [comment]
Can i work on this?

**Comment by potiuk** [comment]
sure

**Comment by atharvmishra1999** [comment]
I need a few clarifications here please:
1) from what I understand, I need to make changes in airflow/docs/apache-airflow-providers-sqlite/operators.rst file. Basically I need to remove username, password, port, schema fields since sqlite doesn't need them. Is that correct?
2) Second I need to make it clearer how to construct a connection to sqlite. But I already see an example and that seems fine. What more I need to do?
(thanks in advance for entertaining these trivial question ... i am new to this project)

**Comment by potiuk** [comment]
Just make A PR with what you think is needed and we can discuss it there.

**Comment by atharvmishra1999** [comment]
Since the PR is approved ... i wanted to know when will the code owners merge it and close this issue?

**Comment by Taragolis** [comment]
> Since the PR is approved ... i wanted to know when will the code owners merge it and close this issue?

Well, There are no exact timelines when particular PR would merged into the main so nobody could answer for this question, usual doc only changes merged quicker rather than code related. But in any cases all changes appear in next release, in particular this case in the next SQL Provider release, so there is no rush for committers for merge PR and they could focus on daily routine tasks, many of them have full-time job/projects

Better track on PR, there is might be https://github.com/apache/airflow/pull/29139#pullrequestreview-1268619921 some suggestion and other related question.
