### ISSUE TITLE
Add support for custom code when deleting dags

### ISSUE THREAD

**Issue by aru-trackunit** [apache/airflow#29192]
### Description

When deleting dag via API/CLI, it could perform an additional action declared in additional file/script in order to:
- delete dag file from s3
- delete dag from the local webservers dags folder 
- delete dag file from scheduler's dags folder?

There is already a similar approach taken in webserver config https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/security/webserver.html
```
from flask_appbuilder.security.manager import AUTH_OAUTH
import os

AUTH_TYPE = AUTH_OAUTH
AUTH_ROLES_SYNC_AT_LOGIN = True  # Checks roles on every login
AUTH_USER_REGISTRATION = True  # allow users who are not already in the FAB DB to register
# Make sure to replace this with the path to your security manager class
FAB_SECURITY_MANAGER_CLASS = "your_module.your_security_manager_class"
AUTH_ROLES_MAPPING = {
    "Viewer": ["Viewer"],
    "Admin": ["Admin"],
}
# If you wish, you can add multiple OAuth providers.
OAUTH_PROVIDERS = [
    {
        "name": "github",
        "icon": "fa-github",
        "token_key": "access_token",
        "remote_app": {
            "client_id": os.getenv("OAUTH_APP_ID"),
            "client_secret": os.getenv("OAUTH_APP_SECRET"),
            "api_base_url": "https://api.github.com",
            "client_kwargs": {"scope": "read:user, read:org"},
            "access_token_url": "https://github.com/login/oauth/access_token",
            "authorize_url": "https://github.com/login/oauth/authorize",
            "request_token_url": None,
        },
    },
]
```

### Use case/motivation

After browsing airflow issues regarding deleting dags, there is a misunderstanding what it should do vs what it does. From user perspective when someone deletes dag it should never appear again (but currently user needs to know internals to understand why it's not deleted). 

However it very depends on the implementation how the dag should be deleted. It can be deleted from the file system, s3 bucket etc.

In my case I would add the code that removes the dag from an s3 repository by calling an external client.

Using airflow inside AWS (MWAA), I tried to delete the dag from the UI and it disappeared till next dag sync was performed and popped up again, because it was still present on s3 bucket.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
That goes exactly against the way how Airflow DAG philosophy about distributing DAG files is. Airflow REST API is NOT about adding or modifying DAGs. It's about managing DAGs that ar distributed using other mechanism. Your interface to deal with DAG files is not Airflow REST API. Your API forr that is the API of the filesytem  that you are using for distributing DAGS:

* S3 -> use S3 API
* Shared EFS volume -> use Shared EFS
* GitSync -> use Git commands
* etc. etc. 

This is NOT the question of doing post/pre-processing of what happens with the remote call over the API. This is also (and most importantly) the question of security and separation of concerns. Airlfow's REST API and Webserver have very, very low permissions when it comes to producing or manipulating an executable Python Code.

Simply speaking, by interfacing with webserver or REST API, it's just impossible to modify any code that is submitted by a DAG Author and executed as part of tasks, It's not "disallowed" - it's far more than that - it's not POSSIBLE, because neither API nor webserver have (in serious deployments) have access to the DAG files on the shared volume, git sync. More often than not the webserver (due to the fact that it is exposed to external world via http/https and security requirements) will be running with it's own sandbox with only necessary ports and IP addresses it can communicate with for outwards communication - which will make it imposible to directly talk to s3 for example.

The webserver / API server does not only miss credentials to do so, but they don't even have shared folders with DAGs mounted. AT ALL.  Being able to delete a file, means that you have to have credentials to do so exposed to the webserver/api as well as you have to have those files mounted/accessible. 

So what you are asking for is breaking absolutely basic and foundational assumptions of Airlfow about security. And it's very straightforward "no-go".

And it makes no sense whatsoever even from your perspective as someone who wants to automate this. If you were to write the python code to communicate with S3 for example and delete the files, you not only have to implement the code to do it and use the right API (S3 for example), but you also need to deploy that code with Airflow, and make sure it is integrated with this new futnctionality, distribute and (somehow) protect the credentials that are needed to do so (possibly to multiple Webserver/API components). If you do it directly in the client of yours that originate the "delete" request and does such removal directly, you have MUCH simpler job, and also you are not limited to using Python. You can for example write a bash script that runs:

```
aws s3 rm "generated URL to your dag file"
```

as part of your client deletion process. And all the credentials might be precisely where you need them and when you can secure them (via oauth or any other mechanism) - at the client which runs the deletion request. It's just **simpler** for you than wrapping the same code with Airlfow REST API call and integrating it with Airflow installation.


If you want to delete DAG files, please continue using S3 API to delete your if you use S3. Or EFS API if you use EFS. Or "Git commit" if you are using Git Sync. Those are excellent APIs for managing files. Far better than REST API can ever be. They are very good for automation and you can make sure in your system that you have the right, properly secured credentials on the client side that originates the delete action. Do not push responsibility for that to Airflow webserver/ API server and do not add extra REST layer on top of those. It makes no sense.
