### ISSUE TITLE
Auto refresh DAG state in UI

### ISSUE THREAD

**Issue by aamster** [apache/airflow#29243]
### Description

The state of the DAG tasks updates in the graph view, but the overall state of the DAG does not update. I have to refresh the page in order to see it update. It would be nice if it also updated. 

### Use case/motivation

Monitoring DAG run state in realtime. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Could you please show the exact case you are talking about in the screenshots (and make some statement about the version of the Airlflow you are referring to (and check if latest version of Airlfow has it already). There were some changes in Airlfow auto-refresh in recent versions.

**Comment by aamster** [comment]
Using 2.5.1.


![Screen Shot 2023-01-30 at 1 46 11 PM](https://user-images.githubusercontent.com/5454341/215567401-3e9ca13a-2b3a-4efa-ac4f-9596fc863d95.png)

**Comment by potiuk** [comment]
Do you have DAG autorefresh turned on @aamster ? This is the crucial part of the screenshot that is missing.

**Comment by potiuk** [comment]
Also the screenshot does not show what the stae of the DAG is and why you think running is wrong there.

**Comment by aamster** [comment]
Not sure what you mean by DAG autorefresh

here is an example where a task is running but DAG state is "queued". I need to refresh for it to say "running"

**Comment by potiuk** [comment]
I see. That is a nice screenshot showing what's up. If you do have an auto-refresh enabled on that page (I mean THE "auto-refresh" you see on the dag view) and the overall state of the DAG does not change, then it is a bug.

**Comment by potiuk** [comment]
BTW. Marked it as good first issue for someone to pick up

**Comment by yxiao1996** [comment]
interesting idea. may I give it a shot?

my question is shall we also have task state auto-refresh in grid view, I remember I was refreshing my page a lot there(actually was tree view as my team is still on 1.10)

**Comment by potiuk** [comment]
> interesting idea. may I give it a shot?
> 
> my question is shall we also have task state auto-refresh in grid view, I remember I was refreshing my page a lot there(actually was tree view as my team is still on 1.10)

Grid view has much more "auto-refresh" already. I think mostly @pierrejeambrun and @bbovenzi added a lot of those gradually when things are now auto-refreshing and this is a continuous process to convert more of the views/places to add it (basically it is all mostly about converting the views to be react-driven because then refreshing of each component can be done separately following the react-UI patterns rather than refreshing whole pages. 

This is all being done as part of the AIP-38 https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-38+Modern+Web+Application - which is an on-going effort and any small improvements in what is refreshed when is most welcome by anyone I think. 

There are still a lot of views that are not converted to react (for example the logs mentioned by @aamster in #29242 . And yes we are well aware that those are still there, and rather than pointing out those by issues we prefer PRs improving it (there are probably far too many places to add individual issues for all such cases and this is needless buearaucracy to create such issues). 

So yes improving any part of those is most welcome - and PRs can be created without even creating issues for it.

**Comment by bbovenzi** [comment]
I'm going to remove the "good first issue". It's not a trivial change.

That `state_token` is defined by Flask App Builder and not in js, and the auto-refresh in the graph view currently only checks for new task instances, not the dag run state. So we'd have to add in another endpoint to refresh and then update the `<span>`. 

Meanwhile, I'm actively working on a new graph view for 2.6:
<img width="1289" alt="Screenshot 2023-01-31 at 11 02 38 AM" src="https://user-images.githubusercontent.com/4600967/215813495-8710b2cb-7bc3-4724-8b84-6aa6a7bc75a2.png">

**Comment by potiuk** [comment]
I see. Makes sense. Thanks @bbovenzi

**Comment by bbovenzi** [comment]
Closing since the fix is non-trivial and it will be better to replace that element entirely.
