### ISSUE TITLE
(psycopg2.errors.FeatureNotSupported) This ALTER TABLE command is not yet supported .While deploying airflow with Postgres

### ISSUE THREAD

**Issue by Bhawana-Barfa** [apache/airflow#29281]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow Version : 2.2.3 
I am trying to deploy airflow with postgres on cluster with helm chart . When I install helm , upgrade-db goes into Error with the log error sqlalchemy.exc.NotSupportedError: (psycopg2.errors.FeatureNotSupported) This ALTER TABLE command is not yet supported.
[airflow_err.txt](https://github.com/apache/airflow/files/10554275/airflow_err.txt)
Which is coming from https://github.com/apache/airflow/blob/main/airflow/migrations/versions/0008_1_6_0_task_duration.py
<img width="1440" alt="Screenshot 2023-02-01 at 12 32 36 PM" src="https://user-images.githubusercontent.com/124127106/215976314-5755f151-11ba-4778-8afd-a2615420afc2.png">

Please let me know if Im doing anything wrong here, or suggest what need to done here. 

### How to reproduce

vi values.yaml
externalDatabase:
type: postgres
Insert postgres host port user and secret.

helm install -f values.yaml -n airflow my-airflow-cluster .

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by snjypl** [comment]
what postgresql version are you using?

**Comment by Bhawana-Barfa** [comment]
> what postgresql version are you using?

2.8.10.0-b21

**Comment by potiuk** [comment]
Postgres DB not library. Look for postgres support in Airflow. It start from postgres 11. (Find it in docs). No idea whar

**Comment by Bhawana-Barfa** [comment]
> Postgres DB not library. Look for postgres support in Airflow. It start from postgres 11. (Find it in docs). No idea what the number you posted is

Postgres DB version is 11.2

**Comment by potiuk** [comment]
I think you failed to mention that you are not using Postgres but something else that claims that it is Postgres compatible (Yugabyte?). Apparent kk y this database is - as opposed to the claim - 100% compatible with postgres because - as mentioned in the message - it does not support some statements.

Switch to regular postgres DB. We aren't going to support something that is not Postgres. See docs for which versions of Postgres are supported.

For the future - please  transparent on what you are using.  Be mindful to time of other people.
