### ISSUE TITLE
Mounting all volume in init/side containers breaks my setup (introduced in PR 27420)

### ISSUE THREAD

**Issue by iJanki-gr** [apache/airflow#29426]
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2.5.1

### Kubernetes Version

1.24.4

### What happened

I tried out the new 1.8.0 release of the chart. I found there is a backwards incompatible change introduced in 
https://github.com/apache/airflow/pull/27420 that causes all extraVolumes and extraMounts to be added to all init and sidecars.

This causes issues for us when using subPath mounts causing folders to be wrongly created by init containers that have nothing to do with the volume.

### What you think should happen instead

Can this opinionated change be at least opt-out, guarded by some value? 
Something like:
```
mountAllExtraVolumes: true
```
We would like to keep using this chart as is without forking.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Can you please explain what is the exact problem you have and why it gets broken ? I think any decisions to change anything should be based on the assessment if this is a product problem or approach of yours that is the problem. There are good reason why volumes are mounted now (see the original PR) and adding options is often worse than opinionated decisions - maybe just you use the chart wrongly and it's better from the product point of view is you change it rather than add another option - especially that you would also need to explain consequences and maybe your case will have a variant when mounting volumes is still needed.

Can you please explain the problem you have in detail
