### ISSUE TITLE
Update constraints file for 2.3.4

### ISSUE THREAD

**Issue by erdos2n** [apache/airflow#29594]
### What do you see as an issue?

Apache Airflow 2.3.4 constraints file uses

```
apache-airflow-providers-amazon==5.0.0
```

Which has a circular import error. The latest minor version of v5.x.x should be added instead.

```
apache-airflow-providers-amazon==5.1.0
```

### Solving the problem

Update the constraints.txt file

### Anything else

No

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
What do you mean by circular import  @erdos2n ? We almost never update constraints for past releases and I doubt we have a problem here with constraints otherwise we would have thousands of people screaming and our image would not have passed the tests.  Could you explain it please? 

Converting it into discussion until then
