### ISSUE TITLE
Postgres secret Bug when upgrading helm chart version (1.7.0 -> 1.8.0)

### ISSUE THREAD

**Issue by V0lantis** [apache/airflow#29632]
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2.4.3

### Kubernetes Version

v1.21.14-eks

### What happened

When trying to applying our deployment configuration with the new helm-chart release, we faced the following issue:
```
COMBINED OUTPUT:
  Error: UPGRADE FAILED: execution error at (airflow/charts/postgresql/templates/secrets.yaml:17:24): 
  PASSWORDS ERROR: The secret "airflow-postgresql" does not contain the key "postgres-password"
```

Although, when I go look for the secret, I find it but with the key `postgresQL-password` (Trailing **ql** at the end)

### What you think should happen instead

It should work fine. Although I think the issue come from the postgresql bitnani version

### How to reproduce

Create a Airflow deployment with helm-chart 1.7.0 and with a `postgres.enabled: true`. Then upgrade your helm chart to 1.8.0 and try to deploy again. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by V0lantis** [comment]
Find the previous version I probably used for my deployment [here](https://github.com/bitnami/charts/blob/e2404c63cc5e72d5dee91e50b4597fd9e0b1ab0c/bitnami/postgresql/templates/secrets.yaml#L20) and the PR is bitnami/charts#8827. I guess a similar issue is bitnami/charts#4416.
A potential workaround is to update the secret in place and add a second line with the same password. (Tested and worked in my environment). Feel free to close my issue if you think it is fixed.

**Comment by potiuk** [comment]
Yeah. This is expected - see Release Notes: https://airflow.apache.org/docs/helm-chart/stable/release_notes.html#airflow-helm-chart-1-8-0-2023-02-06  where we explain the migration steps. The bult in postgres is really a "development" feature and if you go production, you should switch to external one, so we do not consider that as a breaking change - that's why we left 1.* version but we also provided migration steps in release notes in case somoene would like to upgrade their development setup.
