### ISSUE TITLE
Call backs issue

### ISSUE THREAD

**Issue by durgadeshi** [apache/airflow#29784]
### Apache Airflow version

2.5.1

### What happened

After creating the DAG and Task using decorators, I found following observations:
1. Task related call backs calling every time without considering the executed task status. Ideally, it should call only one call back based on success or failure but it calling both success and failure call backs.
2. DAG related to call backs not working.
3. For both scenarios, logs are not getting printed (Used print function to print statements). 

### How to reproduce

Create a DAG and Task with decorators and use callbacks to reproduce the issue.

### Operating System

Windows

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Please provide reproducible case (example DAG) which shows the behaviour and some logs around the problem you observe (ideally logs of airflow that are showing the callbacks being called). 

This is for sure not that happens to everyone, so also explaining details about your details are needed in order to reproduce it and the more detailed minimum reproduction scenario you provide, the better - ideally something that someone will be able to run exactly as you do to confirm that they can reproduce the scenario.
