### ISSUE TITLE
Migrate fully to new graph view

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#29852]
Now that https://github.com/apache/airflow/pull/29413 is merged. We should get that graph to fit all user needs to and migrate to it fully, removing the legacy graph view.

Steps needed:
- [ ] Add more UI tests for new graph
- [x] Add Filter Tasks button
- [x] Add task state hover highlighting
- [x] Store graph in url params
- [ ] Redirect /graph urls to new graph
- [x] Add an expanded screen mode to easily see large DAG graphs

**Comment by set92** [comment]
Couldn't find a Slack channel of feedback, so I suppose the best option is here. I was testing the new UI in 2.6.0rc1, and wanted to note a couple of things I think the new UI doesn't do as good as the old one.

- Too plain, before I could easily see the different types of tasks by color, now is harder to locate some of them, or I have to zoom more. Also, the background is white, the boxes are white... It is hard to see what is inside a Taskgroup and what not.
- Tiny text to open Taskgroups. Before I could click on any part of the box to open them. Think this is problematic if you have a high resolution, a mouse with high DPI, or maybe a person who has a real problem and shakes a lot. Also is hard when you open one with 7 tasks, and you remember that it wasn't that one, and you want to close, and then you have to move, search for the text...
- Bit picky I think, and probably not needed, is only because of inconsistency. If you click a task in graph view, it only highlights the task in grid view, which makes it hard to find it when you have a lot of Taskgroups. It would be great if it could take you to the task you selected.
- Likely too picky, but I think there is too much space at the footer. It also happened before, but didn't notice it because didn't scroll. I think that's important because if the space didn't exist, all the buttons would be visible without scrolling. For example, if you enter a DAG, click a task in the grid view and think Want to see it in the graph view, you will then click Graph view, and scroll to click `Center selected task`, but then you want to check the Gantt view to check why it took so long, or maybe go to Audit Log, or check the DAG Docs, but at least in my computer I couldn't see them and I had to scroll up again. Thought in removing the header (with Admin, Docs...), but then I thought that could be useful, and I noticed the space in the footer that didn't bring any utility. Also, the annoying part was that I was unable to scroll back up easily because in the graph view the scroll is to zoom, and in the grid view the scroll goes up and down the task list, so I had to find an empty space where the scroll worked to go up the page.
- The DAG Flow is not visible at all. Our main DAGs has around 300 Taskgroups (they are nested, so probably are less of the ones visible in the DAG Flow). In a DAG with 15 Taskgroup great, but in the normal ones can't see anything.

Bugs?
- When you expand a Taskgroup, the last task has a symbol like a ball and an arrow. When there are only a couple Taskgroups the arrow doesn't appear, but if there are a lot the arrow appears and as the number of Taskgroup increases it starts changing. Example:
![image](https://user-images.githubusercontent.com/1332249/234009543-414e0b11-f7cd-48b5-b956-85ed04457932.png)
- If I open a Taskgroup in the graph view, and then I press it, the backgroud of the Taskgroup becomes light blue, and the lines between tasks they go up a couple pixels. We could call it a fun feature for when we are mad because things are not working :smile:, clicking repeatedly makes the line go up and down, becoming more noticeable.

**Comment by chriscardillo** [comment]
Hey hey! Just as an FYI I am seeing some graphs that only render with the pre-2.6.0 graph and not the new 2.6.0 graph. It looks like a task group issue.

Reprex:

- Clone [this demo repo](https://github.com/pipeline-tools/gusty-demo-lite)
- Follow [Running the Demo](https://github.com/pipeline-tools/gusty-demo-lite#running-the-demo) instructions to spin up Airflow.
- Inspect `airflow_tutorial` and `gusty_tutorial` DAGs - no issues with either new or legacy graph views.
- Inspect `more_gusty` DAG - by default the new graph shows nothing.

![image](https://user-images.githubusercontent.com/38569601/235726046-a9d0d79b-70c3-48f9-ac88-5b2e40223d92.png)

However, if you expand the tasks, then the graph will render:

![image](https://user-images.githubusercontent.com/38569601/235726171-80fc2b2f-d004-4ed6-aa5f-b0f7a492209a.png)

My browser's console is giving the following errors when everything's closed:

![image](https://user-images.githubusercontent.com/38569601/235726416-ef519d31-ece1-4195-add5-e31de7839e37.png)

Hope this is helpful. The new view is looking great!

**Comment by bbovenzi** [comment]
@chriscardillo Thanks! Looks like if  `prefix_group_id` isn't true we have some issues. I'll work on a fix, but for now you can edit the task config and it should work.

**Comment by bbovenzi** [comment]
Also, I see you have `suffix_group_id` is that a valid field? I don't see that in the source code

**Comment by chriscardillo** [comment]
The implementation for both `prefix_group_id` and `suffix_group_id` in gusty are separate from the Airflow TaskGroup's `prefix_group_id`, the latter of which will always be `False`, so if you're trying to develop a fix for what we're seeing, you can probably just use an Airflow TaskGroup directly with `prefix_group_id` set to `False`.

Sorry for any confusion, I just caught the issue while bumping Airflow versions in the demos, and it was the easiest way to share what I was seeing, but I think just using an Airflow TaskGroup directly with `prefix_group_id` set to `False` will be enough to troubleshoot.

**Comment by NilsJPWerner** [comment]
> If you click a task in graph view, it only highlights the task in grid view, which makes it hard to find it when you have a lot of Taskgroups. It would be great if it could take you to the task you selected.

I came here to say the same thing. It would be great if the graph jumped to the task selected from grid.

**Comment by NilsJPWerner** [comment]
> Hey hey! Just as an FYI I am seeing some graphs that only render with the pre-2.6.0 graph and not the new 2.6.0 graph. It looks like a task group issue.
> 
> Reprex:
> 
> * Clone [this demo repo](https://github.com/pipeline-tools/gusty-demo-lite)
> * Follow [Running the Demo](https://github.com/pipeline-tools/gusty-demo-lite#running-the-demo) instructions to spin up Airflow.
> * Inspect `airflow_tutorial` and `gusty_tutorial` DAGs - no issues with either new or legacy graph views.
> * Inspect `more_gusty` DAG - by default the new graph shows nothing.
> 
> ![image](https://user-images.githubusercontent.com/38569601/235726046-a9d0d79b-70c3-48f9-ac88-5b2e40223d92.png)
> 
> However, if you expand the tasks, then the graph will render:
> 
> ![image](https://user-images.githubusercontent.com/38569601/235726171-80fc2b2f-d004-4ed6-aa5f-b0f7a492209a.png)
> 
> My browser's console is giving the following errors when everything's closed:
> 
> ![image](https://user-images.githubusercontent.com/38569601/235726416-ef519d31-ece1-4195-add5-e31de7839e37.png)
> 
> Hope this is helpful. The new view is looking great!

I'm having the opposite issue to this. The graph doesn't show if all the task groups are expanded, but does show if I close a bunch of them. THis dag has 100s of tasks in nested task groups so maybe it is hitting some limit of the number of tasks it is able to show.
