### ISSUE TITLE
hostAliases for scheduler and webserver

### ISSUE THREAD

**Issue by funes79** [apache/airflow#29957]
### Description

I am not sure why this PR was not merged (https://github.com/apache/airflow/pull/23558) but I think it would be great to add hostAliases not just to the workers, but the scheduler and webserver too.

### Use case/motivation

Be able to modify /etc/hosts in webserver and scheduler.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
@funes79  It has not been merged, because the author had not lead it to completion. Changes in airflow are implemented by > 2300 contributors - often people like you who want some change and make the effort to create a PR, pass all the tests and pass the review of the maintainers (including pinging them if needed). So if you deeply care about some thing to be implemented - the best thing you can do is to ... implement it.  When you create an issue like that, what we can do as maintainers, we can mark it as "good first issue" if it is something like that (which I did). Then, if there is someone who will pick it up and lead it to completion, and it will get merged - then it will be implemented.

This is how things work here. Things get implemetned, when someone decides to care for it and implement them.

So if you think you need it and do not want to wait for someone to pick it up, implementing it yourself and contributing a PR is the next best thing you can do.

**Comment by amoghrajesh** [comment]
@potiuk @funes79 i don't mind taking it up and finishing it. Guess there's enough context too around it

**Comment by eladkal** [comment]
@amoghrajesh assigned to you

**Comment by amoghrajesh** [comment]
@eladkal @potiuk @funes79 Added a PR for this: https://github.com/apache/airflow/pull/30051
Can you take a look?
