### ISSUE TITLE
Streaming vs Batch 

### ISSUE THREAD

**Issue by BradRuderman** [apache/airflow#301]
It seems airflow is really powerful for batch jobs in managing dependencies, scheduling, retries, alerts. However how about streaming pipelines? I am assuming airbnb does't use this for streaming pipeline. Also has anyone compared this to LinkedIn's Azkaban http://azkaban.github.io and to Spotify's luigi (https://github.com/spotify/luigi)?

Thanks!

**Comment by mistercrunch** [comment]
Yeah no streaming pipelines, it's out of scope for Airflow as Python probably isn't the right language for this and there are great solutions out there (Storm, Spark Streaming, Samza, ...). Airflow is really just an "orchestrator", mostly telling other systems what to do. It can take on some serious workload since it is a distributed system, but real computation at scale should be shipped off of Airflow to a real computation solution.

As for Azkaban and Oozie, one of the key difference is a static declarative approach (xml/yaml config files) versus Airflow's dynamic approach to programmatically define pipelines (a DSL). Luigi is also programmatic, but creating a task requires deriving a class as opposed to instantiating it (in Airflow), which makes it somewhat less dynamic. 

From the Airflow docs: "When workflows are defined as code, they becomes more dynamic, maintainable, versionable, testable, and collaborative."

If are interested in streaming pipelines in Python, Luigi or Spark Streaming are probably a better solution.
