### ISSUE TITLE
task_group dynamically mapping does not show log in airflow UI

### ISSUE THREAD

**Issue by MaiHoangViet1809** [apache/airflow#30276]
### Apache Airflow version

2.5.1

### What happened

When trying dynamic task_group mapping, it work, but current UI did not show each task_group index nor child task log.

### What you think should happen instead

Current airflow UI did not cover this case.

### How to reproduce

```
from airflow.decorators import dag, task_group, task
from pendulum import datetime


@dag(dag_id="test_task_group",
    start_date=datetime(2022, 12, 1),
    schedule=None,
    catchup=False,
)
def task_group_mapping_example():
    # creating a task group using the decorator with the dynamic input my_num
    @task_group(group_id="group1")
    def tg1(my_num):
        @task
        def print_num(num):
            return num

        @task
        def add_42(num):
            return num + 42

        return add_42(print_num(my_num))

    # a downstream task to print out resulting XComs
    @task
    def pull_xcom(data):
        print(data)

    # creating 6 mapped task group instances of the task group group1 (2.5 feature)
    tg1_object = tg1.expand(my_num=[19, 23, 42, 8, 7, 108])

    # setting dependencies
    pull_xcom(tg1_object)


task_group_mapping_example()
```

### Operating System

docker

### Deployment

Docker-Compose

### Deployment details

Custom Airflow docker composer using dask executor

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Correct. It's not implemented yet.

**Comment by romanzdk** [comment]
Is there any plan on the roadmap to implement this?

**Comment by romanzdk** [comment]
?

**Comment by potiuk** [comment]
Just to explain how it works here (maybe you are not aware of it and your impatience and expectations of answer show iup here). This is an Open Source project, so thing are done when they are done basically

There is no "roadmap" in Airflow. Things get implemented when someone implements them Airflow is developed mostly by volunteers. And if people would like to speed up implementation of some feature, the best way to do it, is to roll up their sleeves and do it themselves or maybe supporting somoene who would volunteer their time to do it. 

So just to set your expectations: it is at most hope or work in progress observation, that someone does it. There is no single entity or body or person that can authoritatively tell "this is on the roadmap" and "this is not". 

So answering your question "it's not on the roadmap, because there is no roadmap". 

I personally have not seen any recent activities on that one,. But from what I've seen from earlier discussion, i know that last time @uranusjr has been discussing this and implementing the backend of group task mapping feature (not sure if this is complete). This is what I remember at least. Maybe he can provide more insight.

Whether there is any work to implement the UI part, I do not know - maybe @bbovenzi or @pierrejeambrun could tell what is missing and whether there is any work there done - they are mostly looing at that part. 

I think this is a useful feature though, and maybe people like @romanzdk could start implementing it or maybe they will express interest in sponsoring someone to the job if that is so important for them 

@romanzdk - would your company be willing to sponsor someone to do it ? Maybe that can attract someone to do it if no-one is working on it now?

**Comment by bbovenzi** [comment]
Can you include screenshots of what is missing? I am testing this locally and am seeing the logs I expect.

**Comment by MaiHoangViet1809** [comment]
First of all, it does not show log of child task of a task_group decorator expanded:
![image](https://user-images.githubusercontent.com/95363968/233459431-e288ced2-6ce9-46d2-af73-9551d68e0b42.png)

Secondly, if we are using task_group decorator and expand it, it should have some method to see instance of that expanded task group (like when we using task decorator, it will show mapping task on the right panel), each instance have 1 index position in UI and can click to see detail log. 
I suggest for task_group decorator expanded, we should show its instance in UI, and when we click on it, it will expand into multiple child task of that instance, then we can click to child task to see their log.
currently we can't see anything in UI to debug or view log:
![image](https://user-images.githubusercontent.com/95363968/233460520-3b821adb-0a91-4179-80a1-337cffe9c8b3.png)

if we change UI support this idea, then user can use taskgroup of taskflow api as a pipeline template, and run or reuse this pipeline in many dags using various input dynamically.

**Comment by bbovenzi** [comment]
Yes, this has been [fixed](https://github.com/apache/airflow/pull/28208) for 2.6.0 which is in rc1 right now and should come out soon.

<img width="963" alt="Screenshot 2023-04-21 at 12 12 17 PM" src="https://user-images.githubusercontent.com/4600967/233684626-694b40b5-9b19-4ad5-80bb-1709b8a25d60.png">

**Comment by MaiHoangViet1809** [comment]
So good to hear that, will contribute another thing soon when I know how to turn the airflow dev env on 😅 too much thing need to read and study here for this project.
