### ISSUE TITLE
Build a new task duration view in react

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#30328]
The current task duration view can be hard to read. We should build a better one.

In the grid view, a user can select a column (a dag run) or a row+column (task instance), but cannot select just a row (a task). We could add that ability and then one can see how a task has performed across dag runs.

Another idea is to create a summary gantt chart, when a user doesn't have a single dag run selected, that shows the min/max and average duration for each task across its entire history in the dag.

**Comment by tquazi** [comment]
@bbovenzi @eladkal Can I pick this one? Thanks!

**Comment by bbovenzi** [comment]
Sure thing! Although this will change a lot of how the grid view works so let me know if you want me to get it started for you.

**Comment by tquazi** [comment]
I was planning on adding the following functionality:
1. Add ability to select a task/task_group in the grid view. (task_group is clickable today, it just expands the sub tasks)
2. Chart view based on grid selection:
    a. If nothing is selected: Build a Gannt chart with Min/Max/Avg for all task. ?
    b. If TaskGroup is selected: Regular task duration chart for all the tasks under that task group.
    c. If Task is selected:  Regular task duration chart for that specific task.
    d. If DagRun is selected: Display bar chart with all tasks on x-axis?
    e. If TaskInstance is selected: ?? Same as DagRun view?

Let me know your thoughts on this.

Please go ahead and add any additional changes that are needed to the grid view. Thanks

**Comment by tirkarthi** [comment]
@tquazi Are you still working on this? We wanted to build an internal version of the same and have a prototype to receive feedback from users. I thought to create a PR of the same so that it can serve as a base. Currently it involves selecting a task instance and display durations for the task. Currently, we have gantt char to see which task took more time in a given dagrun and normal grid view to see which dagrun took more time. This would help in cases where one task instance took more time than usual or a spike or slowness. It uses echarts used in cluster activity page and on hover the task instance and run id in url is synced since I don't know how to do it inside click where the chart component needs on click. My frontend experience is limited but I will be happy to contribute this to get feedback.

Thanks
