### ISSUE TITLE
merge breeze's --test-type and --test-types options

### ISSUE THREAD

**Issue by vandonr-amz** [apache/airflow#30407]
### Description

using `breeze testing tests` recently I noticed that the way to specify which tests to run is very confusing:
 * `--test-type` supports specifying one type only (or `All`), allows specifying which provider tests to run in details, and is ignored if `--run-in-parallel` is provided (from what I saw)
 * `--test-types` (note the `s` at the end) supports a list of types, does not allow to select specific provider tests, and is ignored if `--run-in-parallel` is NOT specified.

I _think_ that the two are mutually exclusive (i.e. there is no situation where one is taken into account and the other isn’t ignored), so it’d make sense to merge them.

Definition of Done:

- --test-type or --test-types can be used interchangeably, whether the tests are running in parallel or not (it'd be a bit like how `kubectl` allows using singular or plural for some actions, like `k get pod` == `k get pods`)
- When using the type `Providers`, specific provider tests can be selected between square brackets using the current syntax (e.g. `Providers[airbyte,http]`)
- several types can be specified, separated by a space (e.g. `"WWW CLI"`)
- the two bullet points above can be combined (e.g. `--test-type "Always Providers[airbyte,http] WWW"`)

### Use case/motivation

having a different behavior for a very similar option depending on whether we are running in parallel or not is confusing, and from a user perspective, there is no benefit to having those as separate options.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
If you have a good idea how to improve it - sure but also note that there are different defaults. --test-types get the list of all test types, where --test-type default is "All". Also when you run `--help`  you will see that `--test-types` is in separate "parallel" options. Maybe a good solution would be to call it "--parallel-test-types" instead (and replace all the places in CI where it is used also by TEST_TYPES variable to PARALLEL_TEST_TYPES.

 That would remove all the confusion). If you would like to implement it - feel free and I think it is a better option than to combine the two options with different defaults and behaviours.

I think we need  people  the contributions of the contributors to breeze - this will significantly improve the "bus factor" of breeze if people like you will do more fixing of such small things and learn how it works along the way. It's all python, using pretty good structure, so should be easy to find your way in it.

If not, I will just mark it as good-first-issue and possibly some other person will contribute it (which I am happy to help with).

**Comment by vandonr-amz** [comment]
Are the defaults really different ? What's the difference between `the list of all test types` and `All` ? They sound like they should be the same thing to me.

I started to take a look but it looks like more work than I initially imagined, so I created this issue. I might work on it if I have time.

**Comment by potiuk** [comment]
* None test type means to run "pytest tests" (everything you find there)

* default `test-types`  list means run whatever tests types you should have  in parallell:

<img width="1180" alt="Screenshot 2023-04-01 at 00 50 25" src="https://user-images.githubusercontent.com/595491/229246228-14755b51-8bf4-4780-88d1-f8f3c2ec806a.png">

Also `test-type` allows you to select a subset of tests that are NOT included in `--test-types` as default list (because the selection is "cross-cutting" - i.e. subset of tests that are partialy also present in other tests :

<img width="2027" alt="Screenshot 2023-04-01 at 00 53 19" src="https://user-images.githubusercontent.com/595491/229246853-6f56c8a8-3c14-40e0-b7aa-b2f66cf07ff5.png">

* Postgres or MySQL -> runs all test that are tagged with (@backend("postgres') - but they might be in CLI, or Core, or Other
* Quarantine -> they are separate "quarantine" tests (tagged with (@quarantined) that have a completely separate job in CI because failure of Quarantine tests is not failing for the build (so this job is marked with     `continue-on-error: true`. Those tests are skipped by default when you run the default "All" tests BTW via "pytest tests" 

So those two parameters are rather different, and if they are confusing, they should rather be renamed.

**Comment by potiuk** [comment]
BTW. Happy to help if you are stuck
