### ISSUE TITLE
airflow task duration calculate mistake when use reschedule mode

### ISSUE THREAD

**Issue by yh2388** [apache/airflow#30552]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

version: v2.3.4

Sensor use reschedule mode;

As you can see, according to the log information, start_date is not the time when the real task started, but the time of the last reschedule, so the calculation of duration is wrong
![image](https://user-images.githubusercontent.com/20351485/230777555-676e31c7-7528-4ccc-9c7f-6a5a54d1e350.png)
![image](https://user-images.githubusercontent.com/20351485/230777563-0947b7a1-8b5a-431d-8af9-8cc93cb7cae0.png)
![image](https://user-images.githubusercontent.com/20351485/230777573-153e3211-ed7d-4e7d-9974-2208e10fad9f.png)

### How to reproduce

N/A

### Operating System

centos

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
I checked the table `task_instance` and I found the the `start_date` is updated on each poke when use the reschedule mode.

The unit test added for this part
https://github.com/apache/airflow/blob/1cf1fc46e95c889c8c81bb2ed2c3f08a681bf7e3/tests/sensors/test_base.py#L192-L193
is a bit tricky because we provide the `start_date` for each poke
https://github.com/apache/airflow/blob/1cf1fc46e95c889c8c81bb2ed2c3f08a681bf7e3/tests/sensors/test_base.py#L123-L124

**Comment by EbrahimKaram** [comment]
This is still an issue for airflow 3.1.3
It's also emitting a new start event on each reschedule which overflows the Marquez events
