### ISSUE TITLE
remote logging not accessible for Google Cloud Storage

### ISSUE THREAD

**Issue by kuikeelc** [apache/airflow#30991]
### Apache Airflow version

2.6.0

### What happened

Hi, since Airflow version 2.3.2 we can't read the remote logging on Google Cloud Storage from Apache Airflow. The message in v2.6.0 is the following:
  
`*** No logs found in GCS; ti=%s <TaskInstance: mydag.my_task manual__2023-05-01T12:25:55.937029+00:00 [success]>`

We do see the logfiles on Google Cloud Storage though. They are situated in the correct spot.

The logging configuration is the following:

```
[logging]
                base_log_folder = /home/airflow/logs
                remote_logging = True
                remote_base_log_folder = gs://{{ .Values.airflow.logs.bucket }}
                colored_console_log = True
                colored_log_format = [%%(blue)s%%(asctime)s%%(reset)s] %%(log_color)s%%(levelname)s%%(reset)s - %%(log_color)s%%(message)s%%(reset)s
                colored_formatter_class = airflow.utils.log.colored_log.CustomTTYColoredFormatter
                log_format = [%%(asctime)s] %%(levelname)s - %%(message)s
                simple_log_format = %%(asctime)s %%(levelname)s - %%(message)s
                log_filename_template = dag_id={{ "{{" }} ti.dag_id {{ "}}" }}/run_id={{ "{{" }} ti.run_id {{ "}}" }}/task_id={{ "{{" }} ti.task_id {{ "}}" }}/{%% if ti.map_index >= 0 %%}map_index={{ "{{" }} ti.map_index {{ "}}" }}/{%% endif %%}attempt={{ "{{" }} ti.try_number {{ "}}" }}.log
                log_processor_filename_template = {{ .Values.airflow.logs.log_processor_filename_template }}
                dag_processor_manager_log_location = /home/airflow/logs/dag_processor_manager/dag_processor_manager.log
```

We did change some of the logging settings, to see it that resulted in the bug, but to no avail.

I have posted this request earlier, but it was never solved. The bug remains.

### What you think should happen instead

When logging in to the Airflow webserver and go to a task run. And we would then click on the log button, we would expect to the logfile. We can however ONLY see the logs, when the task is running. Not when it is in the e.g. success or failed state.

### How to reproduce

Use remote_logging=True and upload them to GCloud storage

### Operating System

Linux, but this is a Python issue

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.0.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==6.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-docker==3.6.0
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==10.0.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-azure==6.0.0
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-odbc==3.2.1
# Editable install with no version control (apache-airflow-providers-onesecondbefore==71.0.0)
-e /home/airflow/logs/.hidden/providers/apache-airflow-providers-onesecondbefore
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.5
apache-airflow-providers-sqlite==3.3.2
apache-airflow-providers-ssh==3.6.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

docker, helm, k8s

### Anything else

It always occurs.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Could you please post more detailed logs, enable debugging and see what kind of logs are being accessed by our webserver   when you access the logs? You should see them in the webserver logs and they should show what log is being accessed  - also comparing that wiht the log being present in the GCS.

Also while doing the check - could you please check if this is not "Access" problem. Note that there is a different set of permissions for writing and reading logs (and it has a lot to do with security). Logs are written by your tasks, where they are read by your webserver and your webserver machine needs to have the right permissions to read the logs 

You can see more (and follow all the notes and details of authorisation described in https://airflow.apache.org/docs/apache-airflow-providers-google/stable/logging/gcs.html.

Pleasee double check that you are have all the permissions properly configured and see if the right log files are pulled by the webserver - once we see if there is a problem there, we might be able to help. In the meantime - please try to provide those details.

**Comment by potiuk** [comment]
> Hi Potiuk. All details and logs are provided above. Airflow does not provide more info. It is not an access problem. If it was Airflow would mention it.

Then, unfirtunately, there is not enough information to help you with your problem until more information is provided. I suggested some extra checks that you could do, and until they are done, 

You might not realise that this is not a helpdesk, this is a place where some people help other people who have problem with issues they might have when running airflow.  The software you have is free and those people try to help you in their free time, so if you do not provide enough information that they can help you, or that might assess that this is an airflow issue (especially if you are asked to the do some concrete investigation and provide more information), then simply no-one will have any incentive to look at the issue and help you - especially that it is likely it is your deployment issue. 

Please. pretty please, help yourself and be cooperative in providing more information, otherwise this issue will be in "pending_response" status and not much will change. If your goal is to get helped with the problem, cooperation is the strategy that works best here.

BTW. Even if there is more information provided and we can't reproduce it, there is no guarantee that the problem of yours is diagnosed and fixed. This is open-source software that comes without guarantees of any sort, so it might be that no-one will be able to reproduce it and hep you to solve your problem. By adding more information and investigation on your side, you increase your chances, that's it.

**Comment by kuikeelc** [comment]
I fully understand. But we don't have any extra info that I can share. If I would I would share it. Airflow does not seem to be very verbose on this. I'll see if we can find a way to fix this, but it would probably mean moving away from GCS for remote logging. We consider it broken.

**Comment by potiuk** [comment]
> I fully understand. But we don't have any extra info that I can share. If I would I would share it. Airflow does not seem to be very verbose on this. I'll see if we can find a way to fix this, but it would probably mean moving away from GCS for remote logging. We consider it broken.

Pity. You could have helped others with similar issues, I consider it's not broken, but badly configured but it's hard to say without your help. 

And while possibly airflow could be more verbose, it's also hard to say without knowing what the issue is, generally the user is responsible for putting airflow and monitoring it, people here are just volunteers, working on airflow for free so that users could use it for free and this often means that users need to invest into their deployments into making sure that the software that deploy run smoothly. I guess price to pay to use software that you use for free (also known as "there is no free lunch". This is also a reson why there are managed versions of Airflow where you pay others for doing it (making sure things run smoothly and **just work**). 

But on  the I do agree GCS is not the best logging interface out there, there are other better (Stackdriver for example).

**Comment by kuikeelc** [comment]
Thanks Potium. We were looking at Stackdriver. It's probably better for different reasons. Thanks again!

**Comment by oguzhangur96** [comment]
We have faced a similar issue (with the same error) and found out that our local logging folder owner user is **root** but the user `apache/airflow:slim-2.7.3-python3.10` image uses to write the logs is **airflow** . 

This results seeing a log like `*** No logs found in GCS; ti=%s <TaskInstance: mydag.my_task manual__2023-05-01T12:25:55.937029+00:00`  from the logs tab of task UI but after checking the scheduler logs we found out that scheduler was unable to write the logs to local folder. This results empty logs at GCS, since logs are written to GCS after task completion and task is failed because it can't write logs.

You can change the owner of local logs directory to user **airflow** or if you are using kubernetes (deploying without helm) and mounting a persistent volume you can add below setting to your _deployment.yaml_ which makes user **airflow** owner of mounted volume directories.   
```
      securityContext:
        fsGroup: 50000  
   
```

I guess, this should not happen if you are using [official helm chart](https://airflow.apache.org/docs/helm-chart/stable/index.html).
