### ISSUE TITLE
New graph view renders incorrectly when prefix_group_id=false

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#31025]
### Apache Airflow version

2.6.0

### What happened

If a task_group in a dag has `prefix_group_id=false` in its config, the new graph won't render correctly. When the group is collapsed nothing is shown and there is an error in the console. When the group is expanded, the nodes will render but its edges become disconnected. As reported in https://github.com/apache/airflow/issues/29852#issuecomment-1531766479

This is because we use the prefix to determine where an edge is supposed to be rendered. We shouldn't make that assumption and actually iterate through the nodes to find where an edge belongs.

### What you think should happen instead

It renders like any other task group

### How to reproduce

Add `prefix_group_id=false` to a task group

### Operating System

any

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@chriscardillo Mind adding your screenshots for context here?

**Comment by chriscardillo** [comment]
Without expansion:

![image](https://user-images.githubusercontent.com/38569601/235753488-201ffb58-ca01-4422-a555-caae4af874d8.png)

With expansion:

![image](https://user-images.githubusercontent.com/38569601/235753567-b9be7dd9-14b0-48bd-a450-b8e34b033d5f.png)

Initial error in browser console:

![image](https://user-images.githubusercontent.com/38569601/235753617-cb94651b-749c-490a-a096-ab08a5c8c178.png)

**Comment by HadarSha** [comment]
Is this issue planned to be resolved anytime soon? I see that it was originally planned for sometime around Airflow 2.6.1, and then 2.6.2, but since removed?

**Comment by potiuk** [comment]
There are few ways to get it addressed fast. But the fastest way is you, or someone from your company that apparently depends on it, roll their sleeves up and fixes it. Like > 2500 other contributors to airflow who saw a problem and had an inncentive in fixing it, and ... fixed it.

Also paying someone to spend their time to fix it is another good idea.

Other than that, I guess the best thing you can do is to wait untils someone finds it important enough to fix it. 

But I am always of the opinion that "making a change to reality when I want a change and think it is important" is better than "waiting for someone else to fix it for me".

That's how at least I think about Open Source contributions, getting the software for free (with you do) and giving back to the community by spending time and effor to help others.

But yeah, other than taking matters in your hands and implementing it or paying for it, you are at the mercy of somoene thinking it is important enough to fix it.

**Comment by HadarSha** [comment]
@potiuk I wasn't by any means insinuating that someone should "take care of matters for me" - I simply saw that this issue was already assigned to a contributor and that it was previously also assigned a milestone, which means it was already under consideration for being a part of a past release, and at some point was pushed back for some reason I am not aware of, since there are no comments here since.

I am merely highlighting the importance of this issue for those who use `prefix_group_id=False`, for the sake of getting more information about the progress perhaps already made.

**Comment by bbovenzi** [comment]
Sorry, the fix requires me to redo a good amount of the graphing logic and I've gotten distracted by other things so I didn't have the time to focus on this yet.

**Comment by HadarSha** [comment]
@potiuk It's all understandable, of course. As for my question - I refrained from directly mentioning @bbovenzi since I had noticed there were quite a few maintainers modifying this issue, and hoped anyone at all could say something about it, since - you have indeed guessed it - it's an important one for us.

In fact, I would gladly partake in fixing this issue myself, if only I had any front-end knowledge at all (React, is it?). 

Truth is, at this time, I am definitely not qualified to assist @bbovenzi here, but kudos to him for this promising graph view 😃 we will patiently await any new developments.
