### ISSUE TITLE
Logs no longer shown after task completed CeleryExecutor

### ISSUE THREAD

**Issue by juraa14** [apache/airflow#31059]
### Apache Airflow version

2.6.0

### What happened

Stream logging works as long as the task is running. Once the task finishes, no logs are printed to the UI (only the hostname of the worker is printed)
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/16529101/236212701-aecf6cdc-4d87-4817-a685-0778b94d182b.png">

### What you think should happen instead

Expected to see the complete log of a task

### How to reproduce

Start an airflow task. You should be able to see the logs coming in as a stream, once it finishes, the logs are gone

### Operating System

CentOS 7

### Versions of Apache Airflow Providers

airflow-provider-great-expectations==0.1.5
apache-airflow==2.6.0
apache-airflow-providers-airbyte==3.1.0
apache-airflow-providers-apache-hive==4.0.1
apache-airflow-providers-apache-spark==3.0.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-oracle==3.4.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-sqlite==3.3.2

### Deployment

Virtualenv installation

### Deployment details

Celery with 4 workers nodes/VMs. Scheduler and Webserver on a different VM

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohan472000** [comment]
This issue could be related to the logging configuration of your Airflow instance. By default, Airflow uses a logging level of WARNING, which means that only log messages with severity levels of WARNING, ERROR, and CRITICAL will be shown in the UI.

To check the logging configuration, you can go to your Airflow home directory and open the `airflow.cfg` file. Look for the `[logging]` section and check the values of the following parameters:

    
    logging_level = WARNING
    logging_config_class = log_config.LOGGING_CONFIG
    

If you want to see more log messages in the UI, you can set the logging level to a lower value, such as INFO or DEBUG:


    logging_level = INFO


Save the changes to the `airflow.cfg` file and restart the Airflow services.

**Comment by zachliu** [comment]
i closed https://github.com/apache/airflow/issues/30997 because although the line
https://github.com/apache/airflow/blob/ab54c63940a99646df974d4bcf2e37415e277e69/airflow/utils/log/file_task_handler.py#L323
is hard to read, it does fulfill the expected logic cases as i mentioned https://github.com/apache/airflow/issues/30997#issuecomment-1530767179
|case# | remote_logs     | task state | triple not logic final output |
|-----|-----------------|------------|-------------------------------|
| 1 |no remote logs  | unfinished | True (read local)             |
| 2 |got remote logs | finished   | False (don't read local)      |
| 3 |no remote logs  | finished   | True (read local)             |
| 4 |got remote logs | unfinished | True (read local)             |

i didn't know case 2 was causing issues for other people :thinking: 
in my use case, i only care about case 1,3,4 (i do have remote logging as permanent records but i have my own `log_config.LOGGING_CONFIG` to force remote logs to be empty so that airflow always go to case 1,3,4 because reading from local is much faster)

**Comment by potiuk** [comment]
Can you please explain what logging configuration you have @juraa14  (cc: @dstandish I guess that's something to look at quickly).

**Comment by juraa14** [comment]
Logging level set to INFO.

**Comment by dstandish** [comment]
@juraa14 let me know if i understand this correctly.

you have airflow configured running celery.

each celery worker runs on a distinct VM.

webserver runs on distinct VM.

when task is running, webserver reads through log server.

when task is done, webserver does not read through logs server.

correct?

this makes sense.  the current logic is to only attempt to read from the worker (over the log server running on celery)while the task is running and otherwise to just read local or remote.

i think in general the assumption is that celery workers cannot be relied upon to stick around forever.  so you should either set up your logs to go to a folder shared by all of your services (e.g. celery, webserver, scheduler) or you should set up remote logging.  doing otherwise is not a good practice because your logs can easily be lost. and since it's not a good practice, it's not expected that people will do it like this, and therefore we can optimize webserver performance by not attempting to read from the logs server in this case.

so my recommendation would be that you set up a shared drive for logs or enable remote logging (it's very easy to do)

let me know your thoughts

**Comment by juraa14** [comment]
You understood correctly
If it's the expected outcome, then yes I agree with you. Will set up remote logging probably in the near future. Thanks for the help, I'm closing this issue then.

**Comment by yamrzou** [comment]
In my case, we are deploying Airflow on-premise without celery, just one VM for the webserver and one VM for the scheduler which uses a `LocalExecutor`. So the general the assumption is that celery workers cannot be relied upon doesn't hold.

**Comment by dstandish** [comment]
> > In my case, we are deploying Airflow on-premise without celery, just one VM for the webserver and one VM for the scheduler which uses a `LocalExecutor`. So the general the assumption is that celery workers cannot be relied upon doesn't hold.
> 
> yep. That's what I expected unfortunately.

So do you think @potiuk we should always check logs server?  Or perhaps we can add a case "or if we found no logs at all"

**Comment by adminidever** [comment]
the problem returned in 2.7

**Comment by potiuk** [comment]
PLese open a new issue about it and add all details -what you see in your logs, what configuration you have etc. etc. All the things that can help to diagnose your issue. This is likely similar issue but it's impossible to help you @adminidever or @MartinLutherdale, so I suggest you spend a bit of time describing your case to help those who might help to diagnose it and solve it. 

It's impossible to investigate it now by just hearing "I also have similar issue".
