### ISSUE TITLE
ImportError: cannot import name '_ENABLE_AIP_52' from 'airflow.settings' 

### ISSUE THREAD

**Issue by dominik-werner-casra** [apache/airflow#31064]
### Apache Airflow version

2.6.0

### What happened

After updating to Airflow 2.6.0, none of the DAGs can be imported anymore.

![image](https://user-images.githubusercontent.com/128682537/236251340-8824c670-021e-44ee-b83a-835336ef8222.png)

### What you think should happen instead

The DAGs should be imported like in version 2.5.1.

### How to reproduce

The airflow webserver needs to be running. Then navigate to the /home and the errors import errors appear at the top.

### Operating System

Ubuntu 22.04.1 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.3.3
apache-airflow-providers-ftp==3.3.0
apache-airflow-providers-http==4.1.1
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-sqlite==3.3.1

### Deployment

Other

### Deployment details

Airflow is installed via pip on the Ubuntu server system. No containers (nor orchestrators) involved.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think  you have a broken installation. It almost looks like part of airflow files in your installation come from one airflow version and part comes from another. Can you please take a look at the installation process you have and any custom steps you do there, because I think this problem you have might only happen if somewhere in your installation process you manually replace the settings.py file that comes with airlfow with one that is your custom settings.py - which of course you absoluttely should not do. You have `local_setings.py` that you can replace but the "settings.py" that comes from airflow should never be replaced.

**Comment by potiuk** [comment]
Conveting it to a discussion. We both wiht @jedcunningham agree there is no way you get this error unless you do something really bad to airflow during installation. We would love to hear what is what you are doing @dominik-werner-casra
