### ISSUE TITLE
`breeze restart` does not exist, yet referred to in the docs.

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#31324]
### What do you see as an issue?

https://github.com/apache/airflow/blob/4dea64eca6d2cff2703f54020bcff1879a1de591/BREEZE.rst?plain=1#L1985

The command `breeze restart` is referred to in the docs, but currently does not exist.

### Solving the problem

- Removing the comment for now.
- If possible and necessary, restoring the functionality (I could create a new issue for that)

### Anything else

1. assume this command existed in the past -  I'd be happy to understand why it was removed.
2. I came across this issue while trying to restart Breeze [after installing a provider to verify it](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors
).

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Remoiving the comment is good-enough. There is no restart really it's a remnant for very old dark days

**Comment by potiuk** [comment]
longer explanation - we have no "start" command either, so having `restart" makes no sense really. The `breeze stop` merely stops whatever is running in the background (database, volumes, integrations) but really it makes little sense to "restart" any of those - they will be restarted when needed automatically when you run whatever you need.

In fact maybe a better approach would be to rename `stop` to `down` - that is more appropriate name. And we can even add `stop` alias to work (we have a few aliases like `breeze build-image`  which do not show up in --help but you can still use them) so that if someone got used to `breeze stop` it will continue to work and print warning that you should use `down` instead.

**Comment by hussein-awala** [comment]
> In fact maybe a better approach would be to rename stop to down

@potiuk I agree, this would be more appropriate

and yes, IMO `breeze restart` is not necessary, where `Ctrl-c` + restarting the service  (`up` then `enter`) are enough to test the installed packages.
