### ISSUE TITLE
Manually marking dag run state will change end date

### ISSUE THREAD

**Issue by bbovenzi** [apache/airflow#31555]
### Apache Airflow version

main (development)

### What happened

![May-25-2023 14-22-49](https://github.com/apache/airflow/assets/4600967/848444cd-e6c2-46d2-9b15-388b3f12601c)

When manually marking a dag run as success or failure, the end date of the run will also change. This is most noticable in the grid view since the duration will immediately change.

This has been the case for a while.

### What you think should happen instead

We probably shouldn't alter the end_date.

### How to reproduce

Manually mark a dag run, especially an old one, and see the dag run duration bar charts change dramatically with one outlier, ruining the value of the rest of the chart.

### Operating System

any

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Came across this one when testing 2.7.0rc1
I think it's not intuitive that marking DagRun as failure/success changes the end date of the DagRun thus causing the UI effect as seen in the gif.

This bug can also easily mess metrics collectors.

**Comment by boushphong** [comment]
I just tried to fix this.
I have no clue how `dag_run.end_date` field here is always equal to the `timezone.utcnow()` to be honest. Even before assigning  `state == DagRunState.RUNNING:` at line **368**. This seems to be the problem, it just doesn't get the `end_date` from it's latest run but always resolves to the value of `timezone.utcnow()`. Hence the `session.merge(dagrun)` will always alter the `end_date`.
https://github.com/apache/airflow/blob/270e2190b8bd15594af5a936fd54d35cb3a3b8ac/airflow/api/common/mark_tasks.py#L360-L369

perhaps someone could pick this up from my clue maybe. Maybe the code below would work after one could resolve the above problem. I suspect the problem comes from the `@provide_session` decorator. But I'm not too sure.
```python
if state == DagRunState.RUNNING: 
     dag_run.start_date = timezone.utcnow() 
     dag_run.end_date = None 
elif state == DagRunState.QUEUE: 
     dag_run.end_date = timezone.utcnow()
session.merge(dagrun)
```
