### ISSUE TITLE
Airflow Connection Type Azure Blob Storage - Shared Access Key field

### ISSUE THREAD

**Issue by manmeetkaur** [apache/airflow#31811]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow Version 2.5.2

Issue: Create a connection of type azure blob storage using the method #3 described in [OSS docs](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/wasb.html). 

When we use the storage account name and the access key as in the below screenshot, the connection works just fine.
<img width="637" alt="connection-blob-storage-access-key" src="https://github.com/apache/airflow/assets/75730393/6cf76b44-f65f-40c0-8279-32c58b6d57ba">

Then what is the purpose of the extra field called `Blob Storage Shared Access Key(Optional)`? When I tried to put the access key in this field, then connection fails with the below error on testing: 

```
invalid url http://
```
Code reference: https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/azure/hooks/wasb.py#L190-L192

### How to reproduce

- Create a Azure Storage account
- Go to Access Control (IAM), copy the key
- Spin up new local airflow environment using Astro CLI with runtime version 7.4.1
- Go to Airflow UI -> Admin -> Connections -> create a new connection of type Azure blob Storage
- Enter the name of the storage account in Blob Storage Login and the key copied from Azure to Blob Shared Access Key (Optional) and click on Test connection. 

### Operating System

Astro runtime 7.4.1 image on MacOS

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adaverse** [comment]
Will take this up!

**Comment by potiuk** [comment]
feel free.

**Comment by Adaverse** [comment]
> Then what is the purpose of the extra field called Blob Storage Shared Access Key(Optional)?

To answer above question, we neeed to look into the signature of `BlobServiceClient` - 
`BlobServiceClient(account_url: str, credential: str | Dict[str, str] | AzureNamedKeyCredential | AzureSasCredential | TokenCredential | None = None, **kwargs: Any)`

We can see account_url is required but credential is optional. The reason why credentail is optional because the account_url can itself contain the credential (example SAS). Since you are filling the `shared access key` field, it expects the `account_url` field to be filled as well of the form `https://{account_name}.blob.core.windows.net` and since this field is blank in your case hence the error. The `Blob Storage Login` is completly ignored in this case.

The first case works just fine because URL is being built [here](https://github.com/apache/airflow/blob/fe7a1aa0962538a99f5e73dbd3890a6f210d22ed/airflow/providers/microsoft/azure/hooks/wasb.py#L217) using `Blob Storage Login`

Will create a PR to handle this case. But I hope it clears the doubt here.
