### ISSUE TITLE
Improve the docs around deferrable mode for Sensors

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#31819]
### Body

With Operators the use case of deferrable operators is pretty clear.
However with Sensor new questions are raised.

All Sensors inherit from `BaseSensorOperator` which adds [mode](https://github.com/apache/airflow/blob/a98621f4facabc207b4d6b6968e6863845e1f90f/airflow/sensors/base.py#L93) parameter a question comes to mind what is the difference between:
`SomeSensor(..., mode='reschedule')`
to:
`SomeSensor(..., deferrable=true)`

Thus unlike Operators, when working with Sensors and assuming the sensor has defer implemented the users have a choice of what to use and both can be explained as "something is not ready, lets wait without consuming resources".

The docs should clarify the difference and compare between the two options that might look the same but are different.
We should explain it in two fronts:
1. What happens in Airflow for each one of the options (task state in `defer` mode vs `up_for_reschedule`) etc...
2. What is the motivation/justification for each one. pros and cons.
3. Do we have some kind of general recommendation as "always prefer X over Y" or "In executor X better to use one of the options" etc... 

also wondering what `SomeSensor(..., , mode='reschedule', deferrable=true)` means and if we are protected against such usage.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by rohan472000** [comment]
can you provide me that doc path or link so that I can contribute into it?

**Comment by eladkal** [comment]
That depends on scope but I'd say adding a paragraph here
https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/deferring.html#using-deferrable-operators

**Comment by potiuk** [comment]
I think this is a bit problematic to write it in this documentation because we have no standard for it.

So far, the `deferrable = True` in sensors  is merely a convention used in a few of them. but it is not a "common" behaviour. 

One could argue that there is really no need for a "deferrable" sensor because technically it could be a regular operator with deferrable method (and it could be behave like sensor - it could defer itself until something happens and complete). But yes, I see where you might want to have a sensor with the two modes, it allows to do more DRY sensors and it's easier to grasp by users.

I mean - I see why we could make it a common convention, but I think we should agree on it first (devlist?).

**Comment by shubham22** [comment]
I agree that we need additional documentation to clarify the differences between sensors in various modes, particularly when the sensor is deferrable.

> the deferrable = True in sensors is merely a convention used in a few of them. 

Exactly! It isn't a convention and we shouldn't treat it as such, because it can be difficult to enforce. However, we could improve our documentation with general statements, such as distinguishing between a `deferrable sensor` and a `non-deferrable sensor`.

> One could argue that there is really no need for a "deferrable" sensor because technically it could be a regular operator with deferrable method

This was my line of thinking when prioritizing deferrable tasks for Amazon provider. If both an operator and sensor exist (like RedshiftCreateCluster), we are choosing to develop only a deferrable operator for now; if only a sensor exists (like S3KeySensor), the we add deferrable support to it. However, I have observed differing approaches from other providers who are prioritizing deferrable sensors over operators.

**Comment by eladkal** [comment]
I created this issue because I got some questions about it and I did not have a good answer thus when the answer is "it depends" then we need to have a doc that explains what is to be considered.

> So far, the deferrable = True in sensors is merely a convention used in a few of them. but it is not a "common" behaviour.

That is true but even if we have 1, then the question of what is the difference is legit and we should try to clarify the mystery.

**Comment by potiuk** [comment]
> That is true but even if we have 1, then the question of what is the difference is legit and we should try to clarify the mystery.

Maybe we are talking about the same :). I do not think we argue here about the need, it's more on the fact that currently we simply do not have any standards there.

I believe currently when "defferable=true" is just an internal convention in some of the sensors  - GCS/S3/RedshiftCluster, the documentation should be there I think, because this is not a pattern we even have as a "common one". So far it just "happened" that we are using similar approach. I am not arguing we the need of documentation, I just think the place where it should be documented (if we do not make it a common approach) should be in those operators.

However, what I see from this discussion is that we DO have an emerging pattern, that is worth explaining, but I think we should propose a PR describing why/how other priovider can apply it as well. 

Maybe this is exactly what you proposed, and we are just phrasing it differently @eladkal.

I read the idea here is "let's discuss and agree what pattern we can apply for current and future sensors" rather than "let's improve the docs". The point here is that we have no patterns here (yet) because we've never discussed it. 

The pattern is clearly emerging and it's a good thing, and what I think here is that it should be a proposal  - maybe just discussion here + summarising it to the devlist after we get some clear conclusions and proposed PR describing it is enough.

I already see a few good things: @shubham22 explaining why sometimes you choose to do Operator and why sometimes you want to do a Sensor that can have a deferrable mode. So what I think here, we need to introduce it as a pattern, and have a document that:

* describes when you might consider to implement a Sensor with deferrable=parameter and when you want to stick with deferrable Operators
* agree that this is a common convention and pattern that is typically used (possibly with some examples)
* explain the difference and use cases for those

So maybe we are talking about the same.

**Comment by eladkal** [comment]
I read the idea here is "let's discuss and agree what pattern we can apply for current and future sensors" rather than "let's improve the docs". The point here is that we have no patterns here (yet) because we've never discussed it.

Yep. I started  this issue is only about explaining the users what is the difference between the 2 patterns. Thus the output should be 1-2 paragraphs in the docs.

We can extend the discussion to cover how we want to implement deferrable sensors if needed.
