### ISSUE TITLE
Improved error logging for failed Dataflow jobs

### ISSUE THREAD

**Issue by Srabasti** [apache/airflow#32107]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

When running Dataflow job in Cloud Composer composer-1.20.12-airflow-1.10.15 Airflow 1.10.15, Dataflow job fails throwing a generic error "Exception: DataFlow failed with return code 1", and the reason for the failure is not evident clearly from logs. This issue is in
Airflow 1:
https://github.com/apache/airflow/blob/d3b066931191b82880d216af103517ea941c74ba/airflow/contrib/hooks/gcp_dataflow_hook.py#L172https://github.com/apache/airflow/blob/d3b066931191b82880d216af103517ea941c74b
This issue still exists in Airflow 2.
Airflow 2:
https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/hooks/dataflow.py#L1019

Can the error logging be improved to show exact reason and a few lines displayed of the standard error from Dataflow command run, so that it gives context? 
This will help Dataflow users to identify the root cause of the issue directly from the logs, and avoid additional research and troubleshooting by going through the log details via Cloud Logging.

I am happy to contribute and raise PR to help out implementation for the bug fix. I am looking for inputs as to how to integrate with existing code bases. 

Thanks for your help in advance!
Srabasti Banerjee

### What you think should happen instead

[2023-06-15 14:04:37,071] {taskinstance.py:1152} ERROR - DataFlow failed with return code 1
Traceback (most recent call last):
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 985, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/gcs/dags/X.zip/X.py", line Y, in task
    DataFlowPythonOperator(
  File "/usr/local/lib/airflow/airflow/contrib/operators/dataflow_operator.py", line 379, in execute
    hook.start_python_dataflow(
  File "/usr/local/lib/airflow/airflow/contrib/hooks/gcp_dataflow_hook.py", line 245, in start_python_dataflow
    self._start_dataflow(variables, name, ["python"] + py_options + [dataflow],
  File "/usr/local/lib/airflow/airflow/contrib/hooks/gcp_api_base_hook.py", line 363, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/airflow/airflow/contrib/hooks/gcp_dataflow_hook.py", line 204, in _start_dataflow
    job_id = _Dataflow(cmd).wait_for_done()
  File "/usr/local/lib/airflow/airflow/contrib/hooks/gcp_dataflow_hook.py", line 178, in wait_for_done
    raise Exception("DataFlow failed with return code {}".format(
Exception: DataFlow failed with return code 1

### How to reproduce

Any Failed Dataflow job that involves deleting a file when it is in process of being ingested via Dataflow job task run via Cloud Composer. Please let me know for any details needed.

### Operating System

Cloud Composer

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rohan472000** [comment]
@Srabasti , Is above error is from composer logs or dataflow logs? for dataflow failures It is better to look into dataflow logs in dataflow `jobs`.

**Comment by Srabasti** [comment]
Thanks for your reply @rohan472000 ! The log above is from Cloud Logging. Since no Failed Dataflow Job Id was generated for this, hence could not look up in Dataflow logs or jobs via UI. After research, the reason for the failure was found in Cloud Logging.

**Comment by rohan472000** [comment]
One thing I'm not getting is that in above description u are saying that dataflow is failed - `Exception: DataFlow failed with return code 1` and if it failed then it must be shown in composer logs or may be in dataflow logs, plz explain a bit more about what was u doing and where u had encountered the error?

**Comment by Srabasti** [comment]
Thanks for sharing your concern! To clarify further details, I have a Cloud Composer DAG, that is running Dataflow jobs to check if a file exists in GCS, and then loads into BigQuery using Dataflow, and then moves to processed folder. 
After the Composer DAG has been triggered, the generic error "Exception: DataFlow failed with return code 1" is shown in Composer log. 
Ideally, once Dataflow job is triggered, it should be showing the success/failure logs in Dataflow. However, no logs are shown in Dataflow. The log from above is from Composer task that failed.
Since the log is not specific enough to determine the Root Cause. as a result had to go through details in Cloud Logging, and found the reason is that the file is getting deleted.  
If the log is specific and shows a few lines displayed of the standard error from Dataflow command run, this will help users give a context and figure out the easily. However since the error message is generic in Composer, it is difficult to figure out the RCA. 
Hence the request to display a couple of lines above this generic output, so it gives context to the user, for both Airflow versions.
Please let me know for any questions!

**Comment by rohan472000** [comment]
Got it now, since the error message is generic, yes it is difficult to figure out the root cause.

**Comment by potiuk** [comment]
Simple answer is "won't fix".  You should upgrade your Airflow because you are using version that stopped receiving any fixes 3 years ago - you are using extremely old, outdated, likely insecure version of software that is never going to receive any fix. Upgrade to Airflow 2 as soon as you possibly can, you are shooting yourself in the foot by using software that has reached EOL (end-of-life) 3 years ago.

While I understand your request, this is a wrong forum to raise it. composer-1.20.12-1.10.15. is based on Airflow 1.10.15 that is end of life for almost 3 years now (which means that it stopped receiving any fixes - even including Critical security fixes 3 years ago. Since then there were more than  10.000 chnages in Airlfow 2 - including thousands of bugfixes. And none of the changes, bugfixes will ever be applied to 1.10.15 - we stopped adding any fixes to 1.10 3 years ago. 

If you look https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html#changelog - there were ~30 reeleases or so of  just google provider that is used in Airflow 2 to communicate with Dataflow.

This has been clearly communicated about 4.5 years ago and user had 1.5 year time to prepare back then. Since then - if somoene wants to keep 1.10.15 running, they have to maintain it themselves. For example if Composer team released 1.10 they had longer maintenance window - and they would be responsible for adding any fixes, not the community here. Airlfow is open-source and anyone can apply their own patches.

But I believe this has ended long time ago as well for any changes. You might check with Composer (unlike free, volunteer, as-people-have-time support - there you likely have paid support), but they likely do not support any changes or fixes other than critical ones for 1.10. I would be heavily surprised if they do.

Airflow community we will **never** provide any fix any more according to this policy (even if there is a super critical security issue). It means "never" literally. In fact there maybe few people in the community that even remember what Airflow 1.10 was and wer around when it was released.

Your best bet is to upgrade to some of the latest (maybe even latesst available version of Airflow.

**Comment by Srabasti** [comment]
Glad I was able to clarify the details of the issue @rohan472000  

Thanks for your reply and suggestion @potiuk, however that does not resolve the issue, this issue persists in Airflow 2 as well If you observe the link shared above, when opening the request

Airflow 2:
https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/hooks/dataflow.py#L1019

Both Airflow 1 and Airflow2 have this bug. Hence raised this request. Please let me know for any questions. 

Appreciate your help and support in this regard!
Srabasti Banerjee

**Comment by potiuk** [comment]
> Thanks for your reply and suggestion @potiuk, however that does not resolve the issue, this issue persists in Airflow 2 as well If you observe the link shared above, when opening the request
> Airflow 2:
https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/hooks/dataflow.py#L1019

Unfortunatley, I only focused on the first part. I am a bit allergic to see people reporting issues and expecting fixes for a version of Airlfow that is 3 years end of life. So when I see someone starting "I use Airflow 1.10" I stop reading and my answer is prettym much always the same: UPGRADE. Apologies that I missed that.

> I am happy to contribute and raise PR to help out implementation for the bug fix. I am looking for inputs as to how to integrate with existing code bases.

And here, my answer is actually much the same as above  - the only "easy" way to contribute a fix is to fix it in main wait for it being released and (wait for it) - you will need to UPGRADE to Airflow 2.4+ to use the new provider we will release in couple of weeks.. So if you still want to contribute - by all means, feel free. Actually you do not  need to ask for permission or approval - just contribute PR (with tests of course). We do not need to have this issyue at all. likely the PR to contribute is way shorter than it was to wite all the comments here. And you are absolutely welcome to do it - there is not even a need to reopen that issue, just contribute PR, get it reviewed and merged.

But then... Really - the only easy way you will be able to use it is (wait for it) - for you to upgrade to Airlfow 2.4+ and the new provider we release. We do not support nor provide instructions (because there are none) on how to apply it to version of the software that reached EOL more than 3 years ago. You are on your own if you want to patch your old version, but since you have it on composer, you likely won't be able to effectively patch the Pythhon code - because that's what effectively you will have to do patch the code manually.  After 3 years of EOL you are completely on your own if you want to do it.

So in a way, my answer was actually a good solution: PR with fix, then upgrade to newest (preferrably) airlfow, then upgrade to the new provider with your fix and you are done.
