### ISSUE TITLE
Try number is incorrect

### ISSUE THREAD

**Issue by aamster** [apache/airflow#32290]
### Apache Airflow version

2.6.2

### What happened

All tasks were run 1 time. The try number is 2 for all tasks

### What you think should happen instead

Try number should be 1 if only tried 1 time

### How to reproduce

Run a task and use the UI to look up try number

### Operating System

centos

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adaverse** [comment]
I looked into it, the endpoint `api/v1/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}` and it was giving the right result. In the code, it is seems to be attached to the field `_try_number`
```
_try_number = auto_field(data_key="try_number")
```
but the one we see in the UI is `try_number` attribute from `TaskInstance` model which is `_try_number + 1`. So we can instead of showing `try_number` we can show `_try_number` in the UI as seen below - 
```
    @hybrid_property
    def try_number(self):
        """
        Return the try number that this task number will be when it is actually
        run.

        If the TaskInstance is currently running, this will match the column in the
        database, in all other cases this will be incremented.
        """
        # This is designed so that task logs end up in the right file.
        if self.state == State.RUNNING:
            return self._try_number
        return self._try_number + 1
```

Will open a PR for this.
