### ISSUE TITLE
= instead of : in type hints - failing Pydantic 2

### ISSUE THREAD

**Issue by Iceazy** [apache/airflow#32301]
### Apache Airflow version

2.6.2

### What happened

airflow doesn't work correct UPDATE: with Pydantic 2 released on 30th of June UPDATE:, raises 
`pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `dag_id = <class 'str'>`. All model fields require a type annotation; if `dag_id` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.`

### How to reproduce

just install apache-airflow and run `airflow db init`

### Operating System

Ubuntu 22.04.2 LTS

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Iceazy** [comment]
https://github.com/apache/airflow/blob/main/airflow/serialization/pydantic/dataset.py#L41

**Comment by potiuk** [comment]
good. Point - we will fix it for the 2.6.3 version.

The root cause of your problem is that you are not followiing Airlflow documentation when installing airflow. The only way to install airflow from the scratch is using the constraints: https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html  and you should adatpt your scripts to do so.

The reason this installation fails for you is that you are not following the constraint routs and Pydantic 2 released yesterday caused the issue (constraints approach is exactly the way to battle this kind of problems you have and you should just follow it). 

We will fix it for the new version of Pydantic for 2.6.3 (including the constraints).

**Comment by potiuk** [comment]
And thanks for reporting it - this is really helpful
