### ISSUE TITLE
Git Sync 4 support

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#32335]
### Body

Git Sync 4 - about to be released-  introduces a lot of changes (including changed names for env variables).That heavily impacts our Helm Chart and we should fix those incompatiblities before the next release

Info about the changes here: https://github.com/kubernetes/git-sync/releases/tag/v4.0.0-rc2

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment]
cc: @jedcunningham @dstandish @ephraimbuddy

**Comment by potiuk** [comment]
FYI: Our chart variables - for one - are completely not working (for example GIT_SYNC_WAIT -> GITSYNC_PERIOD.

**Comment by Swalloow** [comment]
Is anyone assigned? If not, I will do it.

**Comment by bakome** [comment]
I was able to implement git-sync v4 but faced interesting problem there. I also open a PR on git-sync because I think airflow instances can be heavily impacted by this weird behavior. In my case it was implementation with NFS, but this bug can be repeated with other implementations.

https://github.com/kubernetes/git-sync/issues/827

**Comment by potiuk** [comment]
> https://github.com/kubernetes/git-sync/issues/827

Interesting. I see you proposed a fix (cool!)

**Comment by eladkal** [comment]
v4.1.0 is released with the fix of https://github.com/kubernetes/git-sync/pull/828
