### ISSUE TITLE
Sub-hour scheduling without catchup result in unaligned data intervals

### ISSUE THREAD

**Issue by AlexisBRENON** [apache/airflow#32346]
### Apache Airflow version

2.6.2

### What happened

I setup a DAG to run every 15 minutes, with a start date aligned on hour start, to have it scheduled with data interval like:
- hh:00 - hh:15
- hh:15 - hh:30
- hh:30 - hh:45
- hh:45 - hh+1:00

But if I disable catchup, the resulting intervals are not hour aligned, whatever the start date, but aligned with the time when I unpaused the DAG.

### What you think should happen instead

I expect the DAG schedules to still be hour aligned, but just skip any "missed" schedule.

### How to reproduce

Create two similar DAGs (with just the `catchup` argument changing):
```python
from airflow.models.dag import DAG
from airflow.operators.empty import EmptyOperator
import datetime

with DAG(dag_id="with_catch",
         start_date=datetime.datetime(2023, 7, 4, 12, tzinfo=datetime.timezone.utc),
        schedule=datetime.timedelta(minutes=30),
    catchup=True) as dag1:
        EmptyOperator(task_id="task")


with DAG(dag_id="no_catch",
         start_date=datetime.datetime(2023, 7, 4, 12, tzinfo=datetime.timezone.utc),
        schedule=datetime.timedelta(minutes=30),
    catchup=False) as dag1:
        EmptyOperator(task_id="task")
```

### Operating System

Arch Linux

### Deployment

Other Docker-based deployment

### Deployment details

```bash
docker run --rm -it -v /tmp/dags:/opt/airflow/dags -p 8080:8080 --entrypoint airflow apache/airflow:2.6.2 standalone
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Have you tried setting the `schedule="*/15 * * * *"` as an alternative so that you can ensure it is scheduled really at time points you expect?
I have never worked with `timedelta` but suspect this is an offset from any start time and might collect delays from scheduling over time.

**Comment by jens-scheffler-bosch** [comment]
Looking at the code in https://github.com/apache/airflow/blob/main/airflow/timetables/interval.py#L235 it is in deed a commented feature in the code, so in case a "fesh start" is needed the new time slots are calculated based on `utcnow`.

Therefore I suppose if you really want to have fixed minute times, I'd recommend using a classic cron expression and not a timedelta for the schedule.

**Comment by AlexisBRENON** [comment]
You are right, using the cron expression instead of a timedelta make the data interval hour-aligned whatever the `catchup` value.
I don't really understand the comment in the function, but it seems that when you use a `timedelta` object as schedule and when the scheduler jumps to the latest interval, it computes it base on the current UTC timestamp.

Is it an explicit, desired, documented behavior, or does it make sense to update this code to behave as the CronDataIntervalTimetable one ?

**Comment by potiuk** [comment]
> Is it an explicit, desired, documented behavior, or does it make sense to update this code to behave as the CronDataIntervalTimetable one ?

Yes it seems explicit from the code, so likely desired. Re: documentation - I am not sure. But I strongly encourage you look it up in documentation (where you would normally look for) and if it is not documented, submit PR fixing it.

Airflow is created by > 2500 contributors and many of them are providing changes and fixes and clarifications like this to the documentatotion in order to help other users. Airflow is a free OSS software that all those contributors helped to develop, so if you think that clarifying such behaviour is needed and helpful, this is one of the best ways you can give back to the community of people who - mostly in their free time - are developing the software that others can use for free. This is also a simple way to become a contributor to Airflow after being helped to understand how it works. Yes - our docuementation is not perfect, but people like you who have ideas how to improve and describe certain things olriginal authors have not thought about are really welcome to add such improvements and help others. 

And it is super-easy - obviously you looked at the docs before, when you tried to use the feature, so probably you know best where and how to document it - usually it is as simple as clicking "Suggest a change on this page" and it will automatically open PR where you will be able to add documentation without leaving the GitHub UI. also you are probably best person to explain it in the way that will help others like you to unrderstnd

Can we count on it @AlexisBRENON please?

BTW. Closing it as invalid, we do not need to have issues for PRs, so we do not have to keep it open even if result of it will be a documentation PR by @AlexisBRENON.
