### ISSUE TITLE
Fix the broken link in Apache git hub

### ISSUE THREAD

**Issue by vijayasarathib** [apache/airflow#32660]
### What do you see as an issue?

The "Suggest a change on this Page" link in the provided Airflow documentation at https://airflow.apache.org/docs/apache-airflow/2.3.2/modules_management.html is leading to a 404 error in GitHub.

### Solving the problem

It should be directed to the correct file

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
This is because all PRs  should be created for the main branch, and merging is not allowed in the release branches. Since this file was relocated in later versions, you will not be able to locate it when suggesting an edit from version 2.3.2. If you want to fix something, you need to check the doc in the last release (it could be already fixed).

I close it since there is no issue with that, and we can re-open it if you still think that there is something to fix/improve.

**Comment by jens-scheffler-bosch** [comment]
I found a dead link in current documentation pointing to pypi.org (relative, missing `http://` prefix - if the issue was pointing to this, feel free to push a fix PR using the "Suggest a PR for this page" on lower right of current stable documentation tree (https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/modules_management.html#creating-a-package-in-python)
