### ISSUE TITLE
UI displays the wrong version of a dag source file

### ISSUE THREAD

**Issue by ii700** [apache/airflow#33026]
### Apache Airflow version

2.6.3

### What happened

UI should show the source file of a DAG stored in the file system, not some historical version of the file with newer timestamp.

1. I installed a new dag file version 2 and the ui displays it correctly. 

2. I rolled back the old version of the file version 1, but UI stills displayes the source code of the version 2. 
   The scheduler processes the correct version of the file (version 1), luckily.

3. I change the timestamp of the dag file (version 1)  (apply Linux command touch). 
  And UI starts displaying the correct source file again.

### How to reproduce

See description above.

### Operating System

Red Hat Enterprise Linux release 9.2 (Plow)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
Hello! This sounds like expected behavior. DAGs are processed every [dag_dir_list_interval](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#config-scheduler-dag-dir-list-interval) seconds. You can review the docs on [DAG File Processing](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dagfile-processing.html) for more info.

Feel free with to reopen this Issue and follow up with more information if you think this has been closed in error.
