### ISSUE TITLE
Templating and using params in SQLSensor

### ISSUE THREAD

**Issue by funes79** [apache/airflow#33071]
### Description

In a dynamically generate DAG with waiting sql sensors I would like to use templating and access a DAG parameter. The DAG parameter is a default list and I would like to enable users to change this list and run the DAG. The list should be an exception list, so that the success criteria function will read this list and if the dataset is in the list, it will always return True.

From my testing it seems that this is now not supported in Airflow, as the templating {{ params['exceptions'] }} does not work.

```
...
@dag(dag_id=dag_id,
     schedule="0 0 * * *",
     params={'exceptions': ["A","B"]}
     )
def dynamic_generated_sensors():
    for d in datasets:
        prefix, table = d.uri.split(':')
        query = f"select SYSTEM$LAST_CHANGE_COMMIT_TIME('{table}')"
        task_name = d.uri.replace(':', '_')
        task_id = f"waiting_sensor_{task_name}"
        waiting_sensor = SqlSensor(
            task_id=task_id,
            conn_id="SF",
            # I would like to make the DAG parameters available as an argument to my get_success_function callable
            success=get_success_function(exceptions="{{ params['exceptions'] }}"),
            poke_interval=30,
            mode="reschedule",
            timeout=12 * 3600,  # it times out after noon
            sql=[query],
        )

        dummy = PythonOperator(python_callable=dummyfn,
                               task_id=f"set-ready-{task_name}",
                               outlets=[d])
        waiting_sensor >> dummy
```

### Use case/motivation

The motivation is to be able to let users define and affect the DAG logic and the sensors.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
If I understand correctly, the concept of `exceptions` in this context seem fairly bespoke/unique to your use case. Could you create a custom operator that inherits from `SqlSensor`, but adds a new parameter and [associated template field](https://airflow.apache.org/docs/apache-airflow/stable/howto/custom-operator.html#templating)?

**Comment by dzhigimont** [comment]
I think it's better to convert to discussion. I understand your idea but in the way that you proposed it's impossible to implement because SQLSensor or another operator during execution doesn't have any idea about the arguments of your Python functions. Probably it's possible to implement the same way as in the python operator, add an additional argument something like op_kwargs/op_args, or add the possibility to provide context to the callables.  In your case, if the list of exceptions is the same between dag runs it's better to put it to Variables and read them directly from the python function.

**Comment by jens-scheffler-bosch** [comment]
As Jinja2 parameters are rendered as string per default, have you tried to use the parameter `render_template_as_native_obj=True` in your DAG as described in https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/operators.html#rendering-fields-as-native-python-objects ?
Whereas I assume the challenge might be that this only applies to parameters directly passed as member of the operator, not to the result of functions passed.

So Option #2 could be that you ass the `params`definition to your task as well, DAG params will be applied to task `params` then in the `git_success_function()` you need to get the params from the `TaskInstance` context.

Otherwise I'd agree to implement your own Operator, you can inherit from `SqlSensor` and just extend this one function as you need.
