### ISSUE TITLE
Mapped task with trigger rule `all_done` or `none_failed_min_one_success` results in mapped task being skipped

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#33078]
### Apache Airflow version

2.6.3

### What happened

Consider the following DAG:

```python
from pendulum import datetime

from airflow.decorators import (
    dag,
    task,
)
from airflow.exceptions import AirflowSkipException


@dag(
    schedule="@daily",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    default_args={
        "retries": 2,
    },
    tags=["example"],
)
def trigger_rule_mapped_task_bug():
    @task
    def run_me():
        return [1]

    @task
    def run_me_too():
        return []

    @task
    def skip_me(x):
        return None

    @task(trigger_rule="none_failed_min_one_success")
    def map_me(x, y):
        print(x)

    skipped = skip_me.expand(x=run_me_too())

    map_me.expand(x=run_me(), y=skipped)


trigger_rule_mapped_task_bug()
```

The task `map_me` is marked as `skipped` for both the `all_done` and `none_failed_min_one_success` trigger rules.

### What you think should happen instead

I would expect `map_me` to execute for both `all_done` and `none_failed_min_one_success` as the `trigger_rule`.

### How to reproduce

Use the above DAG to reproduce.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

n/a

### Deployment

Astronomer

### Deployment details

LocalExecutor using Astro CLI

### Anything else

Here's the graph view for the broken path for visualization:
<img width="1097" alt="image" src="https://github.com/apache/airflow/assets/25823361/83ca9264-60ad-4ec8-8cf4-18005e6de469">

Note that if the downstream task with the `none_failed_min_one_success` or `all_done` trigger rule is _not_ a mapped task, everything works as normal:
![image](https://github.com/apache/airflow/assets/25823361/acc89769-9f27-4398-84c9-cf7db0638f37)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
Mhm, I have a wild guess but am not sure:

If the `skip_me` mapped taks ist skipped, it obviously will have no results. Therefore the mapped output of the taks is an empty array ==`[]`. Such empty array is used as parameter `y` for the maping of the follow-up `map_me` task. As the two dimensional mapping tries to generate a cross-product it will generate `1 * 0 == 0` elments... = skipped.

Can you please try again and remove the results from `skip_me` from the mapping and add it to the normal parameters of `map_me`?

**Comment by RNHTTR** [comment]
I'm not sure I understand, because `map_me(y=skipped).expand(x=run_me())` is invalid. However, `map_me.partial(y=skipped).expand(x=run_me())` _does_ work as expected.

**Comment by jens-scheffler-bosch** [comment]
- The usage of `map_me(y=skipped).expand(x=run_me())` because the first part of `map_me(y=skipped)` creates a concrete task _instance_. This can not be expanded.
- In contrast the `map_me.partial(y=skipped).expand(x=run_me())` creates a Python functools partial instantiated base on which expand will multiply. This is in your case the only way to make it not skipped, `y` will be initialited with an array of results of `skip_me`, potentially an empty array.
- If you pass both `x` and `y` to the expansion function it will create a cross product of list of `x * y`. If `skip_me` has an empty list the cross product is zero length.

**Comment by RNHTTR** [comment]
I believe that makes sense as to why this behavior is occurring, but I don't think it's the correct behavior, and it's certainly counterintuitive. 

```
@task(trigger_rule="none_failed_min_one_success")
def map_me(x, y):
    ...
```

There are valid reasons to execute this task if either `x` or `y` are `None` (e.g. `if not y: raise Exception("missing y!")`)

**Comment by jens-scheffler-bosch** [comment]
If you want an empty value to be mapped you need to tell the system to.

If you think about this the other way around: Mapping with a zero length result (because task was skipped) would mean you need to make the mapping wither with an empty value (`None`) and then the logic need to accept empty vlaues (might fail?) or you need to add a kind of "fallback mapping" like "if no result then take _something==what?_ as fallback mapping value. Airflow can not guess and just mapping with `None` would also be inconsistent.

So I'd propose if you want to have a kind of "use `None`if mapping skipped" or `if nothing resulting take `something`as fallback then you need to add this logic via e.g. a `PythonOperator` in between. I see this rather as feature, that you can make yourself, not a bug.

My leftover concern your be that others might stumble over the same problem again, so it would be good to have some kind of logging for this. You probably see logs of details of mapping results in the last task executed before your mapped task as the scheduling of follow-up tasks is happening distributed on the workers at time of ending task execution. But if you stumble over this really hard to understand. If you have any ideas how to expose this in logs explicitly, ideas welcome (e.g. print a warning if empty mapping is used as input).

**Comment by RNHTTR** [comment]
Yeah, I see what you're saying. I think the best path would be a boolean parameter in the [MappedOperator](https://github.com/apache/airflow/blob/main/airflow/models/mappedoperator.py#L243) such as `use_none_if_empty_map` (or something to that effect).

An alternate, less invasive option would be to update the UI for the task instance when this happens. What do you think?

**Comment by eladkal** [comment]
cc @uranusjr WDYT?

**Comment by uranusjr** [comment]
Copying comments from private convo with @RNHTTR and @dstandish:

> There’s always at least one ti, if the upstream is empty we’d have one with `map_index=-1, state=SKIPPED` now. And I believe the only case a ti can end up with that particular combination (if the task is mapped) is if the upstream is empty, so we can do some detection and special-case it. I’m not quite sure where the special case should be implemented yet though.
