### ISSUE TITLE
impossible constraints file -- snowflake-connector-python==2.9.0 and pyarrow==9.0

### ISSUE THREAD

**Issue by erg** [apache/airflow#33241]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I'm trying to upgrade to Airflow 2.5.1 to install in AWS's hosted mwaa airflow instance. It seems that some of the constraints are impossible.

I need `snowflake-connector-python[pandas]` which the constraints file locks to `2.9.0`. This snowflake-connector-python also pulls in `pyarrow<8.1.0 and >=8.0.0`

The problem is that the same constraints file also locks `pyarrow==9.0.0` which is impossible because (again) `snowflake-connector-python[pandas]` wants `pyarrow<8.1.0 and >=8.0.0`

Here's a constraints file for 2.5.1 and python3.10: https://raw.githubusercontent.com/apache/airflow/constraints-2.5.1/constraints-3.10.txt

Here's a file generated 3 days ago with the same issue: https://github.com/apache/airflow/blob/constraints-2.5.1-fix/constraints-3.10.txt

### What you think should happen instead

The contraints file should not have impossible requirements like a package that requires `pyarrow<8.1.0 and >=8.0.0` when the constraint is `pyarrow==9.0`

### How to reproduce

easy repro:

```sh
# Create a venv, activate it, and install airflow 2.5.1 and snowflake-connector-python[pandas]
python3.10 -m venv airflow-2.5.1 
source airflow-2.5.1/bin/activate
pip install --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.1/constraints-3.10.txt" "apache-airflow[crypto,celery,statsd]==2.5.1" 'snowflake-connector-python[pandas]'


ERROR: Cannot install snowflake-connector-python[pandas]==2.9.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    snowflake-connector-python[pandas] 2.9.0 depends on pyarrow<8.1.0 and >=8.0.0; extra == "pandas"
    The user requested (constraint) pyarrow==9.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

```
python3.10 --version
Python 3.10.10
```

### Operating System

macbook pro m1

macos 13.4

### Versions of Apache Airflow Providers

celery,crypto,snowflake,statsd

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
There is no points in installing extra dependencies with constraints. It's wrong. See our documentation. 

I will simply copy explanation from https://github.com/apache/airflow/issues/33169#issuecomment-1667720954

This is a misunderstanding on how constraints work. When you read details on constraints, the main (and only) reason for constrainst is to provide a reproducible installation for airflow and all community providers released at the moment of airflow release). However that does NOT include case when you are installing optional dependencies of some of the dependencies of airflow. If they are not included during installation of airflow, one of it's extras or one of it's providers constraints might be conflicting. There are no guarantees of any sort.

People also often make the mistake to install anything "new" with constraints on top of airflow. This is wrong. This is now clearly describe in the docuemntation (as Elad pointed out) and I am going to give a whole talk about it at the upcoming Airflow Summit - https://airflowsummit.org/sessions/2023/mastering-dependencies-the-airflow-way/ - recording will be published after that.

Constraints are there to provide reproducible installation of Airflow. Full stop. Constraints is something that you SHOULD use if you are installing airflow with constraints in a clear venv. And this where constraints role ends.

If you are adding anything on top of it, constraints makes simply no sense. You should use the usual dependency mechanism. Using snowflake-connector-python[secure-local-storage] adds a different dependency specified in "secure-local-storage' extra of snowflake-connector-python. And as long it does not conflct with other requirements of other packages, this is fine to upgrade or downgrade the version. Ths is PRECISELY why we are using constraints - because the do not limit you in upgrading and downgrading other packages as your OTHER dependencies/new requirements you specify might need them.

Also, it would be great if we could figure out what all versions require keyring. I'll more than happy to investigate this.

This is a very good question. But this is a question for snowflake-connector-python team, documentation and changelog. If you choose one of our dependencies (snowflake-connector-python) and decide to manually install an optional dependency of it (this is is what [secure-local-storage] extra does), then you should check whatever the documentation, changelog etc. of snowflake-connector-python. Airflow has 650 dependencies (including transitive ones). It would be entirely infisible to bring to airflow documentation or anyhow to our user's attention - every single variation of every single optional extra of every single dependency. This is likely a matrix of likely of a 10s of milions of entries including all combinations. This is why - when you are actually diverging and installing some "other" dependencies than the ones that default airflow installation covers, it's up to the user to make sure that all the dependencies are ok.

So - look at snowflake-connector-python documentation and see what they say. If the documentation is lacking - look at the package content and requirements they have. We cannot do much here in Airflow about all those optonal things.

**Comment by potiuk** [comment]
Specifically this: https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#installation-from-pypi


> While there are some successes with using other tools like [poetry](https://python-poetry.org/) or [pip-tools](https://pypi.org/project/pip-tools/), they do not share the same workflow as pip - especially when it comes to constraint vs. requirements management. Installing via Poetry or pip-tools is not currently supported. If you wish to install airflow using those tools you should use the constraints and convert them to appropriate format and workflow that your tool requires.

> Typical command to install airflow from scratch in a reproducible way from PyPI looks like below:

pip install "apache-airflow[celery]==2.6.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.7.txt"

> Typically, you can add other dependencies and providers as separate command after the reproducible installation - this way you can upgrade or downgrade the dependencies as you see fit, without limiting them to constraints. Good practice for those is to extend such pip install command with the apache-airflow pinned to the version you have already installed to make sure it is not accidentally upgraded or downgraded by pip.

> pip install "apache-airflow==2.6.3" apache-airflow-providers-google==10.1.0

Can you please explain @erg how after reading thos chapter you think you should use constraints to install "snowflake-connector-python with pandas extra using constratints? Where does it say so ?

**Comment by potiuk** [comment]
I am really REALLY curious to know it as I am on the quest to remove this miscnception.

**Comment by erg** [comment]
Thanks for your detailed answer. I had not read the explanation about constraints from issue #33169 from two days ago, I wish it were around when I struggled with trying to get airflow 2.2 mwaa deployed last year for the same exact reason. 

The misconception starts from the very name of the file--`constraints.txt`. Why would you install something with constraints into an environment and immediately afterwards go and violate those constraints? Knowing that it is meant to be used per-command and not on the entire environment at all times makes it all self-explanatory. Yet the name invites you to use it with every command, or worse yet, trying to include the constraints file when you create your entire virtual env from a requirements.txt file.

For people who have to work with an SRE team, getting the deploy wrong on AWS means letting down other people, lots of frustration all around, potential downtime for users, lost revenue, etc. What if it deploys but then things just start breaking because of version incompatibilities between python libraries and constraints file? People who think too much and don't understand the illogicalness of violating constraints.txt will have these thoughts, yet once you learn the constraints are per-command and don't apply to the environment overall, it all seems so obvious.

You know what would help? Adding the instructions to the top of the constraints.txt file.

constraints.txt:
```
#
# This constraints file was automatically generated on 2023-01-18T18:46:04Z
# via "eager-upgrade" mechanism of PIP. For the "v2-5-test" branch of Airflow.
# This variant of constraints install uses the HEAD of the branch version for 'apache-airflow' but installs
# the providers from PIP-released packages at the moment of the constraint generation.
#
# Those constraints are actually those that regular users use to install released version of Airflow.
# We also use those constraints after "apache-airflow" is released and the constraints are tagged with
# "constraints-X.Y.Z" tag to build the production image for that version.
#
# This constraints file is meant to be used only in the "apache-airflow" installation command and not
# in all subsequent pip commands. By using a constraints.txt file, we ensure that solely the Airflow installation step
# is reproducible. Subsequent pip commands may install packages that would have violated the constraints
# required for Airflow installation step. Finally, pip commands that might change the installed version of apache-airflow
# should include `apache-airflow==2.5.1` in the list of install targets to preserve the Airflow version.
APScheduler==3.6.3
Authlib==1.2.0
Babel==2.11.0
ConfigUpdater==3.1.1
Deprecated==1.2.13
...
```

Places that constraints.txt files are not adequately explained as per-command rather than per-environment:

- https://pip.pypa.io/en/stable/user_guide/#constraints-files
- https://docs.aws.amazon.com/mwaa/latest/userguide/connections-packages.html
- literally everywhere else besides #33169 and now this ticket

I have wasted so much time with python/pip/poetry/conda/miniconda/anaconda/venv/python2...

Anyway, thanks for your help.

**Comment by potiuk** [comment]
Thanks a lot for that. 

That explanation will definitely help me to make my talk better focus on dispelling some misconceptions.

> Thanks for your detailed answer. I had not read the explanation about constraints from issue https://github.com/apache/airflow/issues/33169 from two days ago, I wish it were around when I struggled with trying to get airflow 2.2 mwaa deployed last year for the same exact reason.

This is why I am giving the talk on the Summit. I hope it will help. 

> The misconception starts from the very name of the file--constraints.txt. Why would you install something with constraints into an environment and immediately afterwards go and violate those constraints? Knowing that it is meant to be used per-command and not on the entire environment at all times makes it all self-explanatory. Yet the name invites you to use it with every command, or worse yet, trying to include the constraints file when you create your entire virtual env from a requirements.txt file.

Well actualy I believe (the name is from `pip` ) this is quite different I see constraint as name. **REQUIREMENTS** are hard, **constraints** are softer. The whole idea of constraints is that they just "constraint" you to a subset of things while you run particular operation and they are not "required". 

> For people who have to work with an SRE team, getting the deploy wrong on AWS means letting down other people, lots of frustration all around, potential downtime for users, lost revenue, etc. What if it deploys but then things just start breaking because of version incompatibilities between python libraries and constraints file? People who think too much and don't understand the illogicalness of violating constraints.txt will have these thoughts, yet once you learn the constraints are per-command and don't apply to the environment overall, it all seems so obvious.

Yes - but this is where SRE people have take responsibility. If they don't then, well, what else their job is?

A bit philosophical rant ....

You can't have cake and it eat it too. Airflow has 650 dependencies. About 30% of them have also extras (which means there are other dependencies and limits they apply optionally when you specify them). It's IMPOSSIBLE to satisfy all the combinations of those with a single file. What I recommend instead if you want to keep control is to make an environment as SRE is to build the environment, add your dependencies, run all your tests if all is right (you do have some way to test it) and [produce your own constraints](https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#using-your-own-constraints)  for your environment. We as community can give you constraints that help to install airflow in a reproducible way to start with - and you know all this has been tested before. But if you add your own variations - we cannot test all combinations of all variations for our users. This is where community role ends. This is where impossible task (test all the possible combinations in the community) has to be turned into possible task (I test MY combination of extra dependencies I have). Also if you consider that you are paid to do the SRE job, and the testing done in the community is done mostly by 2500 volunteers who spend their nights and weekends, and that you get the software for free, then you will likely understand that what you are requesting is for somone to do for free many order of magnitude complex work that you can do in your paid time. 

Just being brutally honest - trying to push that responsibility down to the open-source community is quite a bit unfair game.

> You know what would help? Adding the instructions to the top of the constraints.txt file.

That's a VERY GOOD suggestion. Thank you! I will do it right away.

**Comment by potiuk** [comment]
> That's a VERY GOOD suggestion. Thank you! I will do it right away.

I really love that idea. BTW. I even have a tool just PR-ed few days ago , that will allow me (with slight modifications) to update all the released constraints to include the comment https://github.com/apache/airflow/pull/33144

**Comment by potiuk** [comment]
First part of this improvement (thanbks again for the ideas @erg is here https://github.com/apache/airflow/pull/33367. I am also adding updating historical constraints with it.

**Comment by potiuk** [comment]
All right all our released constraints have now updated instructions. Example here: https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.7.txt

Thanks for the suggestion @erg
