### ISSUE TITLE
When copy DAG name from UI don't include schedule info

### ISSUE THREAD

**Issue by alejandrofm** [apache/airflow#33444]
### Description

Currently, if I double-click on the DAG name and copy the text it brings unselected text (schedule info)
Like:
MyDag123
Schedule: 0 11,13 * * * info Next Run: 2023-08-16, 10:00:00

It would be nice if just the name is copied.

### Use case/motivation

Usually when you talk about a dag you don't type it, just copy-paste, and it brings along the scheduling data unless you paste it as unformatted text.
Thanks!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
@alejandrofm Can you confirm where exactly you mean? And which Airflow version are you on? Copy-paste DAG ID works fine for me as you can see in the below gif. 

![dagID_copy_paste](https://github.com/apache/airflow/assets/10206082/f2fb102e-d9ac-45e0-af48-67bfe46f2d6d)

**Comment by pankajkoti** [comment]
hi @alejandrofm . Yes, I confirmed that this issue is present in 2.4.2. However, the copy-paste works fine as I tested in 2.6.3. Tried to paste into Slack, Gmail, and other Editors. And see that the issue has gone away :) 

Suggest you to upgrade your Airflow versions as that would be the only way to get the fix :)
