### ISSUE TITLE
Airflow webserver going to hung status without any logs

### ISSUE THREAD

**Issue by venugopal009** [apache/airflow#33465]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow version : 2.2.2

Airflow web server went into the hung status and We haven't seen any issue pertaining to scheduler, worker and web server logs.We have checked different metrics published by the Airflow and no issue found on it as well. connectivity to the backend database also working fine.

However the Dag's status is running and task is in the queued state for a longer time, until there is a scheduler, worker restart and it fixed the issue.

### How to reproduce

This issue occurred only once and it is not reproducable.

### Operating System

Linux

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajkoti** [comment]
It still looks like some issue with your deployment. Could you try updating your Airflow version to one of the latest releases?
Since there are no reproducible steps and it is an older Airflow version, and it sounds like a troubleshooting question rather than an issue, I am converting this to a discussion.

Please let us know if there are some reproducible steps for this.

cc: @eladkal
