### ISSUE TITLE
Web server restart from airflow cli

### ISSUE THREAD

**Issue by theskycow** [apache/airflow#33484]
### Description

The cli currently (2.6.3) allows starting the webserver, but not stopping or restarting.

When running in docker with the provided docker-compose.yaml (https://airflow.apache.org/docs/apache-airflow/2.6.3/docker-compose.yaml), restarting the container will remove installed python libraries.

When testing and adding new packages.  Previously broken DAGs that failed import because of missing libraries will persist in the UI, even after a successful 'airflow dags reserialize' Listing the DAGs on the command line will show with 'airflow dags list' but they will not show up in the web UI.

'systemctl restart airflow' does not work because systemctl does not exist in the container.  While the workaround is to add the library installations to the container build files, rebuilding, then restarting means iterations take longer.

### Use case/motivation

The use case is quicker iterations after installing new providers and/or python libraries.  The web UI does not stay in sync with what is visible in the airflow cli.  Forcing a restart and/or clearing caching will speed up testing before updating container configurations.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is your misunderstanding how docker and docker compose works not airflow CLI missing,

Docker and docker compose work in the way that they are immutable and one containr = one process. once the container is closed, it disappears and it can be recreated from the image that it was created. This is the basic docker feature and you have to understand that if you want to use docker and docker compose. If you want to iterate and change dependencies dynamically and restart Python interpreters, you shuld likely not use docker compose. Though (if you read the docmentation and docker compose of ours) you can have some ways of achieving it:

* standard docker compose approach - you can add your own Dockerfile with your requirements and get it rebuild when you restart it. see this comment in the docker compose of ours:

```
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.3}
  # build: .
```

* we also have `_PIP_ADDITIONAL_REQUIREMENTS` - see https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#environment-variables-supported-by-docker-compose that an allow you to automatically add requirements when you restart the container - dynamically. Absolutely not recommended for production but good for quicker iterations.

* also if you do not like docker and docker-compose behaviour of containers that are started from images that you build upfront, you might not use that and run your Airflow in a virtual environment. https://airflow.apache.org/docs/apache-airflow/stable/start.html - there you can stop and restart processes as you see fit.

None of that has anything to do with airflow's CLI allowing to stop/start webserver.

**Comment by theskycow** [comment]
As acknowledged in the initial post, rebuilding is a valid approach, but it is slow and cumbersome.  You are correct in that it's supposed to be immutable when deployed.  Testing is another story.  Restarting a container deletes error messages that are necessary for troubleshooting and to determine which additional libraries/plugins need to be added.

Due to restrictions on software that can be installed on a corporate device, Airflow cannot be installed directly (but Docker can).  This is not uncommon.

Regardless of agreement on the validity of the intent, there are valid reasons to restart the webserver, which the cli does not currently support.  A low priority would be more appropriate than closing.

**Comment by potiuk** [comment]
> As acknowledged in the initial post, rebuilding is a valid approach, but it is slow and cumbersome. 

I think this is the point that should be raised to Docker and Docker-compose. This is how the development workflow looks there and there is not much we can do about it.

> Regardless of agreement on the validity of the intent, there are valid reasons to restart the webserver, which the cli does not currently support. 

You completely miss the point. It's not about CLI. Docker compose works in the way that it runs a process. Having CLI will not change anything because once the process starts and when it ends, the container stops.

What you are REALLY asking for is a completely different approach - possibly not doing Docker Compose where you can run everything in Docker as multiple processes and restart processes inside docker without restarting the composer. Which - if you really want, you can do of course, but this is not something that:

1) requires CLI change
2) should require anything in Docker Compose of ours

You are completely free to do something like that if you want. See for example at "start-airflow" breeze command of ours that we use to develop airflow. Airflow Breeze is the development environment we use for airflow development itself (not to develop dags and things you want to use it for).

In there we are using tmux (temrinal multiplexer) and split the `docker run <airflow-image> bash` terminal (bash) into several terminals and run airflow components in those terminals. As long as you contrinue running the container, you can easily install any dependencies there and Ctrl-C webserver and restart it (for example) - or scheduler, or even celery workers if you run it with Celery Executor and Celery integration.

And you can do the same if you only can run docker. You can start your docker container and THEN inside your docker container install your airflow within venv and do what you want to do there in the way that will be best for you. You could do it with tmux, or you could do it witth `docker exec` (This is also supported in our "airflow breeze" development environment). You can take it for inspiration. It's far more complex and contains complete CI integration for running Airflow tests and developing airflow so it's not directly replicable but you can take a look (especially at `start-airflow` command and you can easily replicate something like that on your own, very tailored to your needs and use case.

You are absolutely free to do something like that if you want - but this has very little to do with our docker-compose and it has nothing to do with the CLI allowing to restart webserver. That's why I closed the ticket, not because we do not see the need, but because using a generic "docker-compose" and "modifying CLI" is not the way to do it.

You are completely not blocked to do something similar. It will be far easier for you to do it in your specific way, than for the community to develop more generic tooling for that, that's why we do not have it now. It may change in the future to make it easier, but whatever we do - it won't be the docker-compose you mentioned, nor the CLI modification you requested.  

That's why it's closed.

**Comment by theskycow** [comment]
Thank you for the details, this was helpful in understanding what's going on underneath the surface.  I will investigate the other approaches you recommend.
