### ISSUE TITLE
Error out with hilarious message if attempting to use python2.6

### ISSUE THREAD

**Issue by mistercrunch** [apache/airflow#336]

**Comment by trixpan** [comment]
Maxime, 

Shouldn't we simply deprecate Python 2.6 ?

The documentation as it stands states:

> Note that Airflow is only tested under Python 2.7.\* as many of our dependencies don’t support python3 (as of 2015-06).

A perhaps more direct comment would be the software requires Python 2.7.\* and has experimental support for Python 3. Python 2.6 present in systems like RHEL6 and derivatives is not supported.

Otherwise we will be expecting users to quickly find: https://groups.google.com/d/msg/airbnb_airflow/eOW-JV9HKXs/EE4KRbq2CgAJ

**Comment by mistercrunch** [comment]
Python 3 is supported as far as I can tell, some operators that have 2.7 dependencies won't work though. 

We run the CI on both 2.7 and 3.4.

I'll edit the docs.
