### ISSUE TITLE
Unable to fetch CloudWatch Logs of previous run attempts

### ISSUE THREAD

**Issue by ghost** [apache/airflow#33634]
### Apache Airflow version

2.7.0

### What happened

After upgrading to `apache-airflow-providers-amazon==8.5.1`, I am no longer able to view logs from previous run attempts. 

Airflow is able to find the log stream successfully, but there's no content viewable (even though there are logs in the actual streams):
```
REDACTED.us-west-2.compute.internal
*** Reading remote log from Cloudwatch log_group: REDACTED log_stream: dag_id=REDACTED/run_id=REDACTED/task_id=REDACTED/attempt=1.log.
```

I believe this issue occurred from #33231 -  Looking at the [CloudWatch Logs code](https://github.com/apache/airflow/blob/providers-amazon/8.5.1/airflow/providers/amazon/aws/log/cloudwatch_task_handler.py#L109-L133), I think `task_instance.start_date` and `task_instance.end_date` somehow refer to its __latest__ run, and so the log contents are getting filtered out on previous attempts.

### How to reproduce

1. Configure environment with remote CloudWatch logging
2. Run task
3. Clear task and re-run
4. The logs for the first attempt now no longer show

### Operating System

Debian 11

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.5.1

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Yep, seem like. Just because `task_instance.start_date` and `task_instance.end_date` only stored for latest TaskInstance run and after restart it refers to new one

cc: @vincbeck

**Comment by vincbeck** [comment]
Damn ... And If I dont set any boundary, then logs are not working either ... I need to think about it and see if there is any solution

**Comment by vincbeck** [comment]
Any idea which date and time I should take then? Do we have this information somewhere actually?

**Comment by Taragolis** [comment]
Unfortunetly, I don't have a right answer, because there some kind different side effects might exists. For example even for last task run it might return incomplete or empty data, for example user do not sync time as result wrong data stored into the Airflow Database.

I'm also not familiar with performance of Cloudwatch, only familiar with huge bills in case when I was ignored what I send to Cloudwatch 😄 

IMHO, I though there is some fundamental issue with remote logging - result not cached, so each time it retrieved from remote storage again. 😢

**Comment by vincbeck** [comment]
I just thought of a potential solution. Here the issue is `start_time` right? When tasks are rerun, `task_instance.start_date` is the lastest run and as such, previous logs are ignored. What if we do not set `start_time`? I know that the optimization is actually done on the `end_time`, when `end_time` is not provided, very old tasks can take a lot of time to load logs because CLoudWatch scans since now. But if we provide only `end_time`, then the optimization is still in place and the bug would be fixed because no `start_time` is provided. I'll create a PR, discussion can happen there or here

**Comment by vincbeck** [comment]
See PR #33673

**Comment by mshober** [comment]
I'm a little confused on what the purpose was for that original change. Given that a log stream should only contain logs from a single run attempt, why would we need to provide date filter?

**Comment by vincbeck** [comment]
As explained in #33231:

> Fetching logs from AWS CloudWatch can take a lot of times or even fail when the log stream is old and no time boundary is specified when querying CloudWatch.
> 
> Example: if you try to look at the logs of an old task on the Airflow UI, it can be very slow or even fail doing so.
> 
> By setting start_time and end_time (end_time is the most important), it improves drastically the latency. CloudWatch team recommended adding end time for performance to restrict the search space. I tested it with a 10 days old task and I could experience an improvement from 5 seconds to 1 second when fetching task logs from the UI.

**Comment by vincbeck** [comment]
In case of an old log stream, fetching logs from this log stream can take a lot of time or even time out. Setting some boundary helps Cloudwatch a lot and make it way faster
