### ISSUE TITLE
General Error deleting DAG Run

### ISSUE THREAD

**Issue by david-royo-db** [apache/airflow#33658]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I'm trying to remove a DAG Run but I get a "General Error <class 'AssertionError'>" red message in the DAG Runs screen in the UI

I have a User permission so that should be OK

The version I'm using in GCP Cloud Composer is the last available one: composer-2.4.1-**airflow-2.5.3**

I've found a similar fixed issue from some time ago: #12448 

![image](https://github.com/apache/airflow/assets/117661491/caf16506-ea2c-4d61-94f0-1b8b72dc6c32)

![image](https://github.com/apache/airflow/assets/117661491/3f083392-594d-4bdd-bd29-94355a8561f3)

![image](https://github.com/apache/airflow/assets/117661491/3cb46da7-c0c5-4d94-9ee0-cef8e17b5b3a)

### How to reproduce

Go to list of DAG Runs and try to remove a DAG Run

### Operating System

Whatever Google uses in Composer 2.4.1 :-)

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
I'm not able to reproduce this.
Please add reproduce steps with latest version of vanila Airflow.
If the issue happens only in Google Cloud Composer then please report the issue to their support team

**Comment by jackemuk** [comment]
I'm getting the same exact issue using airflow 2.5.3. 
The dag consists of a @task() decorated task and then a @task.external_python() task.

<img width="353" alt="Screen Shot 2023-08-24 at 9 01 52 AM" src="https://github.com/apache/airflow/assets/17601652/c2b70905-091e-4519-bb78-4953a0c78bcd">

**Comment by potiuk** [comment]
Following what elad wrote @jackemuk : Please add reproduce steps with latest version of vanila Airflow. ?

Can yo share your dag showing the behaviour? Word-description is prone to interpretation and guessing -but you seem to have simple DAG that reproduces it? Can you share it here?

**Comment by potiuk** [comment]
> Maybe @jackemuk can share his DAG. Unfortunately mine contains some confidential details. I can say it is composed of multiple @task decorators, as well as Dataproc operators (Create/Delete cluster + Run a spark job).
> 
> In our case the DAG is triggered through the Airflow API with a custom dag_run_id and a multi-line note, in case that's relevant, since the logs mention a dag_run_note (Not sure if related TBH)

You can try to narrow it down and remove stuff. You can even use bisect  - remove part, see that it still fails etc. What is important is that there is a small, reproducible case here. Otherwise we can only wildly guess how to reproduce it. Getting small reproducible case might simply increase a probability that someone will take a close look.

**Comment by jackemuk** [comment]
The dag code is pretty simple. There are two tasks, the first is to just pull the dag config and then pass it to the next external_python task because the dag config {params} is not passed in the context when using task.external_python decorator. I've renamed the dag tasks for security purposes. 

We are able to delete new dag runs. The first 4 dag runs are unable to be deleted. Would deleting the dag and then reloading it resolve the issue? 

I'm also noticing when we redeploy the dag, without changes, the first task is loosing its run history. (see attached pic below) 

```
from airflow.decorators import dag, task
from airflow.operators.python import get_current_context
import pendulum
import datetime as dt

from utils.email import generic_task_failure_alert

python_venv = "/path/to/virtualenv/bin/python"
worker_queue = "default"

@dag(
    schedule=None,
    start_date=pendulum.datetime(2022, 3, 24, tz="US/Eastern"),
    catchup=False,
    default_args={
        "owner": "jackemuk",
        "on_failure_callback": generic_task_failure_alert,
        "queue": worker_queue,
        "expect_airflow": False,
    },
)
def sync_test_data():
    @task()
    def get_dag_config():
        context = get_current_context()
        return context.get("params")

    @task.external_python(doc=None, python=python_venv, retry_delay=dt.timedelta(minutes=5))
    def test_data(params):
        from logic.sync_data import SyncData

        sync = SyncData()
        sync.sync_test_data(params=params)

    test_data(get_dag_config())

sync_test_data_dag = sync_test_data()
```
![Screen Shot 2023-08-25 at 7 57 42 AM](https://github.com/apache/airflow/assets/17601652/c3ced04c-b5f1-4359-bcfa-75c9805b54c3)

**Comment by potiuk** [comment]
Interesting. Can you try to change "params" name in your task to a different name (say `parameters`) and see if it helps ? 

I believe the root cause might be tha that when you name your task parameter "params", weird things might happen, becaue `params` is already an existing constructor field in the operator and it gets `params` set from the dag definition, not from XCom, so this might cause weird side-effects (that's only a hypothesis now).

**Comment by jackemuk** [comment]
I can try that... but how does that relate to the 4 dag runs that can't be deleted when all new runs are running fine and can be deleted? A bunch of our code uses that same structure and parameter name "params" without any issues.

**Comment by potiuk** [comment]
no idea.

**Comment by potiuk** [comment]
Just to add: I do not have all the answers in the world. I can help with hypotheses what could go wrong. You can try them if they can help you or not, up to you.

**Comment by jackemuk** [comment]
I ended up deleting the dag from the interface, which deleted the associated data from the database. When the dag reloaded, any new runs are back to normal and I can delete them again.
