### ISSUE TITLE
Default run_id prefix for DAGs triggered via API should be "api__" instead of "manual__"

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#33945]
### Description

Currently, using the REST API to trigger a dag run without specifying the run id results in the dag run's run id to be in the form `manual__YYYY-mm-dd...`:

```
curl -X POST -H 'Content-Type: application/json' -d {} localhost:8080/api/v1/dags/example_dag_advanced/dagRuns --user "admin:admin"
{
  "conf": {},
  "dag_id": "example_dag_advanced", 
  "dag_run_id": "manual__2023-08-31T05:12:23.526154+00:00", <--------see here--------------
  "data_interval_end": "2023-08-31T00:00:00+00:00",
  "data_interval_start": "2023-08-30T00:00:00+00:00",
  "end_date": null,
  "execution_date": "2023-08-31T05:12:23.526154+00:00",
  "external_trigger": true,
  "last_scheduling_decision": null,
  "logical_date": "2023-08-31T05:12:23.526154+00:00",
  "note": null,
  "run_type": "manual",
  "start_date": null,
  "state": "queued"
}
```

 It would be better for it to be something like `api__YYYY-mm-dd...` or even `airflow_rest_api__YYYY-mm-dd...`

### Use case/motivation

Triggering a dag run via automation (i.e. REST API) and having the run id be prefixed with `manual__` is confusing to new users.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Why do you consider a difference between invoking DAG via API or from the UI?
If `manual__` is misleading maybe we should just classify `adhoc__` for both

**Comment by potiuk** [comment]
Let's not forget it would be a breaking change whatever we choose here. Many of our users already probably have tooling that checks run_ids and do some stuff based on that.

My vote would be to add an API parameter "run_id_prefix" and use it - but leave "manual" as default.

**Comment by RNHTTR** [comment]
> Why do you consider a difference between invoking DAG via API or from the UI? If `manual__` is misleading maybe we should just classify `adhoc__` for both

Applications can be built around the Airflow API that would make triggering DAG runs from the API an automatic and not adhoc/manual process

**Comment by Bisk1** [comment]
How about adding it to configuration rather than API parameters? I feel like this kind of customisation is purely aesthetical 
and very few users would care about it. Adding things like this to request params could lead to a bloated API cluttered with rarely used features.

**Comment by RNHTTR** [comment]
What about something similar to what was done to ["trigger dag with config"](https://airflow.apache.org/docs/apache-airflow/2.7.0/release_notes.html#the-trigger-ui-form-is-skipped-in-web-ui-if-no-parameters-are-defined-in-a-dag-33351)? A breaking change was introduced but was announced with a newsfragment and an option to "roll back".

**Comment by potiuk** [comment]
> What about something similar to what was done to ["trigger dag with config"](https://airflow.apache.org/docs/apache-airflow/2.7.0/release_notes.html#the-trigger-ui-form-is-skipped-in-web-ui-if-no-parameters-are-defined-in-a-dag-33351)? A breaking change was introduced but was announced with a newsfragment and an option to "roll back".

> Adding things like this to request params could lead to a bloated API cluttered with rarely used features.

I personally think it's not worthy. Any solution like that will create user migration problems. Yes. Easy to solve, but I think if we do use those kind of flags. And we are really trading the "cleaner API" with "more options to configure" and "more complex code to handle those options".

And I think we should only introduce such option when we REALLY want to drive users into changing their beheaviours for the future (this is what happened with "dag run conf" - we REALLLY, REALLY want to change how users are writing their DAGS and to give the new users impression that Parameters is the only way to go (they will need to dicover the "old ways with dict config only") 

I personally think having a new option for that is a bit too much  and the case of just having a little more descriptive name in "dag run id" is too disruptive and really "cosmetic" - so risking a number of users, opening issues "After upgrading my stuff stopped working" is not worth it. We could take the risk (and handle the issues) with dag_run conf. But this is really small improvement in consistency of naming comparing to harm it can make and number of issues we - maintainers - will have to handle.

**Comment by potiuk** [comment]
> Also the motivation behind this issue is to avoid confusing new users, but new users typically run Airflow with default settings, so keeping existing value as the default might kind of miss the point

Fully agree. My proposal was not achieving the goal. But I have another constructive proposal. If our goal is not to confuse the user, then we should do it completely differently. The current way when type of the run is part of t run_id is fundamentally broken - since the moment we allowed the users to add their own run_ids. 

IMHO the right, backwards compatible and forward looking solution to it is to add the "run_type" fields with enum field that explained the type of the run and possibly even few more fields (people often ask to be able to see who triggered the run - so having a field where we could keep that information in run_id - currently users are looking at teh audit logs to find it out, but this is also fundamentally flawed.

So if our goal is to avoid confusion, and help our users- I would say we should forget about run_jd and add other - more structured and defined ways that the users will be able to use to determine type of run and other releated information.

And in this case - we could leave the `manual_` prefix as is and even explain it "don't use it to determine the run type, this is purely historical - use the run_type field to do it".

Yes. It's more complex (also involves changing the UI for example to surface that information) but IMHO - trying to keep the flawed mechanisms of determining the run type and fixing it "a little" is not a god idea if we can do it better, backwards compatible and future looking as well.

**Comment by potiuk** [comment]
UPDATE:  of course - we already have run_type :). :facepalm: . I must have been tired writing it.

So i am not sure if there is much to do in "backend" here as everything is in-place already :). Possibly a way of displaying what type of run it is in the drop-down box in UI when you choose it would be much better than trying to change the default run_id implementation. And maybe just explanation about the run_id (historically like that) would be enough. 

And  (somewhat) related discussion - is that we could allow the user to plug-in their own logic on how to generate the run_id https://github.com/apache/airflow/discussions/34064. You could have an extension point "create_run_id" - with a few parameter (dag_id, execution_date, run_type I guess shoudl be enough) and we could let the  deployment manager to not only plug-in their implementation of it but also make it as complex or as simple as they want - for example they could choose different run_id schemes for different dags.

That would go hand-in-hand with "airflow-as-a-platform" approach.

It's just related, but it shows that rather than relying on specific run_id conventions, having logical run_type to distinguish the is a much better than relying on run_id and we should implement a way to make our users relying on run_type rather than run_id. And while implementing it - we could provide an implementation that is "more consistent" with run_type for the deployment manager to choose from.

Another option (if we really want to change it in backwards compatible way) we could likely introduce two types of defaults:

1) default for new installation
2) default for upgrade

This is a bit tricky to pull-off thoug
