### ISSUE TITLE
Incorrect try_number when searching task instances

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#34309]
### Apache Airflow version

2.7.1

### What happened

In `Browse` -> `Task Instances` search, the `Try Number` filter is actually the "next_try_number" instead of "try_number".

![2023-09-12_09-49](https://github.com/apache/airflow/assets/14293802/1ba9ad90-3fec-404b-ac1b-00e47cd96575)

Task Instance Details:

![2023-09-12_09-48](https://github.com/apache/airflow/assets/14293802/67ec0aab-f79e-4e62-b531-861c937d848b)

![2023-09-12_09-48_1](https://github.com/apache/airflow/assets/14293802/17b3dbbb-e79a-4968-a5da-2664c08956a4)

I just saw this in 2.6.3 and also 2.7.1, but I don't remember the behavior in older versions

### What you think should happen instead

The `Try Number` filter should filter on the "try_number" instead of the "next_try_number"

### How to reproduce

1. Go to the main UI -> `Browse` -> `Task Instances` search
2. Use the `Try Number` filter to initial a search
3. Go to the "Task Instance Details", find "try_number" and "next_try_number"
4. compare them with the search results

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment]
I think that this is because of how `try_number` is defined in task_instance, it will be increased by 1 if the task is completed.
https://github.com/apache/airflow/blob/eed2901e877b32a211e0e74bc9d69fc11e552f2a/airflow/models/taskinstance.py#L607-L618

So we should probably use `prev_attempted_tries` (which is the _actual_ try number) when surfacing this in the UI. Feel free to assign to me and I can figure something out.

**Comment by potiuk** [comment]
Yeah. It's beaten us more than once that try_num definition changes depends on state and in-memory/db state.
