### ISSUE TITLE
BaseBranchOperator should allow passing of a Taskgroup group_id.

### ISSUE THREAD

**Issue by bfeif** [apache/airflow#34526]
### Description

At present, `BaseBranchOperator` only accepts `task_id`'s as possible branches. This can be awkward in the case that a `Taskgroup` is one of the branches: for example if the `Taskgroup` starts with two parallel tasks, then an additional task must be created at the start of the `Taskgroup` (e.g. `start_taskgroup`) for the `BaseBranchOperator` to point to. Forcing this can impede readability.

### Use case/motivation

Simple--`BaseBranchOperator` should accept a `Taskgroup` `group_id` as a possible branch, as opposed to only accepting task `task_id`'s as possibile branches.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Just add some additional information why it doesn't work right now and why it won't work without serious refactoring.
 
There is no information about task group after it created, it just a nice namespace with additional abilities during DAG creation, all other information not available during DagRun because it transform into a prefix(es) for task_id:
- No any API
- No DB Record for task group, except information in `serialized_dag`

**Comment by Taragolis** [comment]
Better you could do right now it is provide `{task_group_variable}.roots` into the branch operator

**Comment by tsafacjo** [comment]
can I take this issue ?

**Comment by potiuk** [comment]
Assigned
