### ISSUE TITLE
Configuration setting to make CronTriggerTimetable default

### ISSUE THREAD

**Issue by collinmcnulty** [apache/airflow#34695]
### Description

Add a configuration setting under the scheduler section that changes the timetable used when passing a bare cron string to `schedule` from CronDataIntervalTimetable to CronTriggerTimetable.

### Use case/motivation

Airflow's CronDataIntervalTimetable behavior is unintuitive to many users of Airflow who do not really need a concept of data_interval and who expect behavior more like cron itself. Airflow provides the CronTriggerTimetable now, which would be a suitable choice for these users. However, most Airflow users are not accustomed to using alternative timetables, and I think many organizations would want to make this change across the board if they knew it existed. I posit that odd cron behavior contributes to a feeling that Airflow is unintuitive, and this simple change could help that.

On backwards compatibility, we'd need to make the current behavior the default setting. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dstandish** [comment]
I like it and agree that this is unintuitive and not great behavior, particularly for learners.
Thinking it through, one concern is that until airflow 3, it will make documentation more difficult because we'll have to keep the old docs with the confusing behavior and explanations, but then also explain this other option that you can only get to after changing the config. This would limit its ability to reduce the "airflow is unintuitive" perception, because it essentially adds more complexity to explain.
I'm not sure how to mitigate that.

**Comment by collinmcnulty** [comment]
We do already have a doc section discussing the difference between these two [here](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/timetable.html#differences-between-the-two-cron-timetables). We could link to it in the description of this new setting.

**Comment by astronautyates** [comment]
Love this idea! If backwards compatibility is implemented as described can see no downside

**Comment by kentdanas** [comment]
I agree this could reduce confusion for new users. Even though having docs explaining both and having to change a config for now to get the simpler behavior is a bit complicated, I still think it's worth it to have the option. We can frame the docs to present this option "first" so that at least there's a "if you need this, change this config and stop reading" option for newer users.
