### ISSUE TITLE
CLI: Variables set should allow to set description

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#34756]
### Body

The CLI:

`airflow variables set [-h] [-j] [-v] key VALUE`

https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#set_repeat1

Doesn't support adding description though column exists and we support it from Rest API:
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_variables

**The Task:**

Allow to set description from cli command

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Zhenye-Na** [comment]
Hi @eladkal ,

I am willing to take this issue and make a PR for this.

Before I made any changes, I think this issue is related to this code snippet https://github.com/apache/airflow/blob/99eeb84c820c8a380721e5d40f5917a01616b943/airflow/cli/commands/variable_command.py#L61-L66

In order to achieve this, I will need to update the following line

```python
Variable.set(args.key, args.value, serialize_json=args.json)
```

to something like this:

```python
Variable.set(args.key, args.value, args.description, serialize_json=args.json)
```

---

I am wondering if this approach looks good to you and please feel free to assign me to this issue.

Thanks!

**Comment by eladkal** [comment]
seems right.
you should be able to test it with breeze https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#id11

**Comment by starkhushi** [comment]
i wanted to solve this isuue .please assign me to solve

**Comment by Zhenye-Na** [comment]
> seems right. you should be able to test it with breeze https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#id11

Cool, let me do it real quick

**Comment by Zhenye-Na** [comment]
https://github.com/apache/airflow/pull/34791 is ready for review

**Comment by Zhenye-Na** [comment]
https://github.com/apache/airflow/pull/34791 is waiting for another approval, thanks!
