### ISSUE TITLE
Scheduler is spending most of its time in clear_not_launched_queued_tasks function

### ISSUE THREAD

**Issue by dirrao** [apache/airflow#34877]
### Apache Airflow version

2.7.1

### What happened

Airflow running the clear_not_launched_queued_tasks function on a certain frequency (default 30 seconds). When we run the airflow on a large Kube cluster (pods more than > 5K).  Internally the clear_not_launched_queued_tasks function loops through each queued task and checks the corresponding worker pod existence in the Kube cluster. Right this existence check using list pods Kube API. The API is taking more than 1s. if there are 120 queued tasks, then it will take ~ 120 seconds (1s * 120). So, this leads the scheduler to spend most of its time in this function rather than scheduling the tasks. It leads to none of the jobs being scheduled or degraded scheduler performance.

### What you think should happen instead

It would be nice to get all the airflow worker pods in a one/few batch calls rather than for each task. These batch calls helps to speed the processing of clear_not_launched_queued_tasks function call. 

### How to reproduce

Run the airflow on large Kube clusters (> 5K pods). Simulate the airflow to run the 100 parallel DAG runs for every minute. 

### Operating System

Cent OS 7

### Versions of Apache Airflow Providers

2.3.3, 2.7.1

### Deployment

Other Docker-based deployment

### Deployment details

Terraform based airflow deployment

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ROVAN1220** [comment]
It seems like you've identified a performance bottleneck in your Airflow setup when running on a large Kubernetes cluster with a high number of queued tasks. Your proposed solution of making batch calls to get all the Airflow worker pods instead of making individual calls for each task is a reasonable approach to address the issue. Here are some steps you can take to optimize the situation:

Batch API Calls: Modify the clear_not_launched_queued_tasks function to make batch calls to the Kubernetes API to fetch information about all the Airflow worker pods. This will significantly reduce the overhead of making individual API requests for each queued task.

Optimize Query Filters: When querying for pods, ensure you use efficient filters to fetch only the necessary information. For example, you may want to filter by labels or other criteria to narrow down the list of relevant pods.

Caching: Consider implementing a caching mechanism to store information about worker pods, so you don't need to query the Kubernetes API every time the function runs. You can set up a cache expiration strategy to periodically refresh the pod information.

Throttling: If the Kubernetes API calls are still causing performance issues, you can implement a throttling mechanism to limit the frequency and number of API calls. This can help balance the load on the API server.

Scaling Resources: In case the Kubernetes cluster is continually growing or experiencing resource constraints, consider scaling your cluster to ensure that it can handle the increased workload efficiently.

Tune Airflow Scheduler Settings: Review the Airflow scheduler settings and parameters to optimize its performance. For example, you can adjust the scheduling_interval, max_threads, or other configuration options to better align with your cluster's capacity.

Asynchronous Processing: If possible, you may explore asynchronous processing for certain tasks that don't need immediate scheduling, which can help reduce the load on the scheduler.

**Comment by dirrao** [comment]
@ROVAN1220 
Thanks for the inputs.

I am working on the MR to address the performance issue.

**Comment by mattp-** [comment]
@dirrao I think that may be a chatgpt AI comment lol

**Comment by eladkal** [comment]
> So, this leads the scheduler to spend most of its time in this function rather than scheduling the tasks

This is interesting.
I believe this is the K8s equivalent for https://github.com/apache/airflow/issues/8854 ?
cc @jedcunningham @ephraimbuddy

**Comment by dirrao** [comment]
@eladkal They are related. Its more close to #7542
