### ISSUE TITLE
Feature Request : Support namespacing in Variables

### ISSUE THREAD

**Issue by r39132** [apache/airflow#349]
We are starting to use Variables in multiple DAGs and would like to use the DAG Name as the default namespace for the variables, so that they don't collide. Of course, if someone changes their DAG name, then there will be an issue. 

We are managing a flat namespace ourselves through convention, but I can imagine this view quickly becoming overwhelming as more people in the company start using it. There will be hundreds of variables. 

<img width="637" alt="screenshot 2015-09-01 18 21 42" src="https://cloud.githubusercontent.com/assets/581734/9621025/66f9b388-50d6-11e5-8679-eb5f1d11824d.png">

The Variables API in Python could then automatically prepend the namespace to the names of variables.

**Comment by mistercrunch** [comment]
Variables may be used across DAG. What's great with a key value store is the simplicity and that you define your own conventions. A clean convention may be to have a single json object for each dag_id that has all the variables for that DAG. Or maybe allowing for a category or tags field in the variable model so that you can filter on that, but that's not super high value.... I think if you have hundreds or thousands of Airflow variables you probably need to rethink the way you want to organize this metadata.
