### ISSUE TITLE
Add HttpToS3Operator

### ISSUE THREAD

**Issue by simonprydden** [apache/airflow#35137]
### Description

This operator allows users to effortlessly transfer data from HTTP sources to Amazon S3, with minimal coding effort. Whether you need to ingest web-based content, receive data from external APIs, or simply move data from a web resource to an S3 bucket, the HttpToS3Operator simplifies the process, enabling efficient data flow and integration in a wide range of use cases.

### Use case/motivation

The motivation for introducing the HttpToS3Operator stems from the need to streamline data transfer and integration between HTTP sources and Amazon S3. While the SimpleHttpOperator has proven to be a valuable tool for executing HTTP requests, it has certain limitations, particularly in scenarios where users require data to be efficiently stored in an Amazon S3 bucket.

### Related issues

Only issue that mentions this operator is [here](https://github.com/apache/airflow/pull/22758#discussion_r849820953)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment]
The text reads as if this is a PR already. If you have a direct code contribution no explicit issue ticket is needed, just open a PR (I also needed to learn this :-D). A ticket is beneficial if you want to have community opinion first.

This sounds like a good and generic feature and might be in relation to AIP-58 which has a PR in parallel. Before raising a PR, can you check whether a HTTP adapter might make sense to the new Storage API concept? Because this would benefit of having on one side a generic backend not only for S3 but for various supported storage systems --> https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=263430565

Relates to #34729
