### ISSUE TITLE
Issue with slim image: ModuleNotFoundError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by RonaldGalea** [apache/airflow#35255]
### Apache Airflow version

2.7.2

### What happened

  I tried to use the slim docker image version for running dockerized airflow, as explained in the [docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#fetching-docker-compose-yaml). It works fine with the default tag (`apache/airflow:2.7.2`), but upon switching to `apache/airflow:slim-2.7.2`, I get the following errors:

```
airflow-dags-airflow-init-1       | Traceback (most recent call last):
airflow-dags-airflow-init-1       |   File "/home/airflow/.local/bin/airflow", line 5, in <module>
airflow-dags-airflow-init-1       |     from airflow.__main__ import main
airflow-dags-airflow-init-1       |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-dags-airflow-init-1       |     settings.initialize()
airflow-dags-airflow-init-1       |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py", line 524, in initialize
airflow-dags-airflow-init-1       |     configure_orm()
airflow-dags-airflow-init-1       |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py", line 220, in configure_orm
airflow-dags-airflow-init-1       |     engine = create_engine(SQL_ALCHEMY_CONN, connect_args=connect_args, **engine_args, future=True)
airflow-dags-airflow-init-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-dags-airflow-init-1       |   File "<string>", line 2, in create_engine
airflow-dags-airflow-init-1       |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
airflow-dags-airflow-init-1       |     return fn(*args, **kwargs)
airflow-dags-airflow-init-1       |            ^^^^^^^^^^^^^^^^^^^
airflow-dags-airflow-init-1       |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
airflow-dags-airflow-init-1       |     dbapi = dialect_cls.dbapi(**dbapi_args)
airflow-dags-airflow-init-1       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-dags-airflow-init-1       |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 811, in dbapi
airflow-dags-airflow-init-1       |     import psycopg2
airflow-dags-airflow-init-1       | ModuleNotFoundError: No module named 'psycopg2'
airflow-dags-airflow-init-1       | 
airflow-dags-airflow-init-1       | ERROR!!!: Too old Airflow version !
airflow-dags-airflow-init-1       | The minimum Airflow version supported: 2.2.0. Only use this or higher!
airflow-dags-airflow-init-1       | 
airflow-dags-airflow-init-1 exited with code 1
```

### What you think should happen instead

Using the slim image should work. It seems there's a missing dependency, however.

### How to reproduce

Take the unmodified docker compose file from the docs and change the [tag](https://airflow.apache.org/docs/apache-airflow/2.7.2/docker-compose.yaml) to use the slim image.

### Operating System

22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
That is expected that is why it is a slim image. 
You need provide additional dependencies (Debian or/and Python packages) by your own

**Comment by RonaldGalea** [comment]
> That is expected that is why it is a slim image.
> You need provide additional dependencies (Debian or/and Python packages) by your own

I thought it should have enough dependencies to start, though. If the user writes DAGs that need certain providers it would make sense to be installed at that point. Anyhow, thanks for clarifying

**Comment by Taragolis** [comment]
It have enough dependency to start with SQLite and Sequential executor, this is not suitable for production, but for support all DB backends it would be required also drivers for MySQL, Postgres and MS SQL Server (discontinue soon in Airflow 2.8)

**Comment by potiuk** [comment]
> > That is expected that is why it is a slim image.
> > You need provide additional dependencies (Debian or/and Python packages) by your own
> 
> I thought it should have enough dependencies to start, though. If the user writes DAGs that need certain providers it would make sense to be installed at that point. Anyhow, thanks for clarifying

I am very curious, because I always assume our users are making resonable assumptions based on documentation available to them. Where did you draw this assumption from @RonaldGalea ?

 Or maybe you missed that statement in the documentation? I really would like to get it clearer for our users to understand what they are doing and I assume the users are making reasonable assumptions based on the docs we write. Could you explain how do you understand this chapter in the docs and why you thought slim image is good to start even if it is expained you should add what you need and even points you to the documentation?

> You can also use “slim” images that contain only core airflow and are about half the size of the “regular” images but you need to add all the [Reference for package extras](https://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html) and providers that you need separately via [Building the image](https://airflow.apache.org/docs/docker-stack/build.html#build-build-image).

My goal is to make clearer, so I would like to understand where the assumption is for. But be aware that I will ask you to click "Suggest a change on this page" and propose a change on this page when you say it's not clear - so maybe just start a PR right away if you think you can improve it to be clearer and help other to better undertand it.

**Comment by RonaldGalea** [comment]
I thought there could be something wrong with the image given that it was also complaining about Airflow being too old (`ERROR!!!: Too old Airflow version !`).

Regarding the package extras page, I probably too quickly skimmed over it - Postgres is listed under the "Provider extras" section, but I didn't need the provider, just the dependencies. Now that I look at it more carefully it is mentioned that in that case provider and dependencies are kept together... So the docs are clear, I just didn't read it carefully enough - my bad

**Comment by christophelec** [comment]
@potiuk, I made the same mistake as @RonaldGalea, and the exact sentence that gave me the wrong assumption is this one :

`Slim Airflow image, which is a minimal image, contains all supported backends database clients installed for AMD64 platform and Postgres for ARM64 platform, but contains no extras or providers, except the 4 default providers.`

From https://airflow.apache.org/docs/docker-stack/build.html#base-images

This made me assume all required dependencies to communicate with a psql database were installed on a slim image

**Comment by potiuk** [comment]
> This made me assume all required dependencies to communicate with a psql database were installed on a slim image

That's wrong assumption. The clients mentioned are on the system level (debian dependencies) not on Python driver level. You do not need Python packages for postgres if you use MySQL and slim image was the slimest image we can come up with that would not require you to install extra debian packages - while you are supposed to add those packages (or airflow extras) that you need.

If you can think of a good  way of formulating it in the documentation - such as people like you would not be confused - I strongly encourage you to click a "Suggest a change on this page" button bottom-right of the doc page - it will open a PR that you will be able to submit and make it clearer. You are probably one of the best people to know how to formulate it for people like you since you- yourself was confused.

Airflow is created by ~ 2700 contributors who often found things confusing and decided to contribute it back in a form of documentation update, code fixes etc. - as a great way to contribute back for the free software they used. So I encourage you to join this pretty big group of peopler @christophelec . That's one of the best first-time contributions you can make.

**Comment by potiuk** [comment]
Will  you accept the challeng @christophelec ?

**Comment by christophelec** [comment]
That's a fair comment, I'm looking into it now.

However I don't find a way to update the documentation properly because I'm still a bit confused about the slim image : I understand the reasoning for keeping the slim image without extras, but what is the reason for the database clients to be installed at all ?

Sorry if the answer is obvious, I'm learning to use Airflow just now so I might still be missing core concepts

**Comment by potiuk** [comment]
Well, it's not obvious - that's why we are having that discussion in the first place. Since you are asking, I will provide you very detailed answer, from which you understand WHY it is difficult to explain it succintly in the user documentation.


The reason why we are installing database clients "system level" software in slim image that it is not a one-liner and we do not want to make our users to repeat it in all their docker files. 

The idea with slim image is that you can install any Python package or provider by easily extending the image. 

For example this will install latest postgres provider (see examples in https://airflow.apache.org/docs/docker-stack/build.html#building-the-image)

```
FROM apache/airflow:slim-2.7.3
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" "apache-airflow-providers-postgres"
```

or this will install any packages you specify in requirements.txt

```
FROM apache/airflow:slim-2.7.3
COPY requirements.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt
```

(note `apache-airflow==` must be there in order to prevent `pip` from accidentally upgrading/downgrading airlflow in case you add conflicting dependencies - you can also see my talk from the Summit explaining why https://www.youtube.com/watch?v=zPjIQjjjyHI and some more details)

This is easy to explain and (except the `==` for airflow that is a protection against accidental upgrades) is pretty "standard" and "expected".

If we would remove the clients ALSO ask user to install the postgres binary clients, it would be way more complex

This is the script that installs all necessary system dependencies in order to be able to connect to Postgres: 

https://github.com/apache/airflow/blob/main/scripts/docker/install_postgres.sh

```bash
install_postgres_client() {
    echo
    echo "${COLOR_BLUE}Installing postgres client${COLOR_RESET}"
    echo

    if [[ "${1}" == "dev" ]]; then
        packages=("libpq-dev" "postgresql-client")
    elif [[ "${1}" == "prod" ]]; then
        packages=("postgresql-client")
    else
        echo
        echo "Specify either prod or dev"
        echo
        exit 1
    fi

    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    echo "deb https://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    apt-get update
    apt-get install --no-install-recommends -y "${packages[@]}"
    apt-get autoremove -yqq --purge
    apt-get clean && rm -rf /var/lib/apt/lists/*
}

# Install Postgres client from Postgres repositories
# But only if it is not disabled
if [[ ${INSTALL_POSTGRES_CLIENT:="true"} == "true" ]]; then
    install_postgres_client "${@}"
fi
```

And we certainly would not want the users of the slim image to have to understand and copy all the lines of that installation to their Dockerfiles. 

Of course it could be slighlty simplified - for example you could only install runtime dependencies, and you could rely on the postgres client that is available in Debian repositories, but our image is really "production ready" so our installation of clients uses latest, most secure and most up-to-date version of Debian compatible system level libraries that the producer of the software (Postgres) offers - that's why we are installing it directly from the source. 

Now. Having all the explanation: I would really appreciate if you find a way to describe it clearly and succintly enough in the user documentation :)
