### ISSUE TITLE
Your CUSTOM_SECURITY_MANAGER must extend FabAirflowSecurityManagerOverride, not FAB's own security manager.

### ISSUE THREAD

**Issue by maiconkkl** [apache/airflow#36432]
### Apache Airflow version

2.8.0

### If "Other Airflow 2 version" selected, which one?

current

### What happened?

When trying to implement custom authentication I am receiving this warning, I believe that line 342 should not have that "not"

### What you think should happen instead?

By extending the class, the authentication system should work

### How to reproduce

just create a class that extends FabAirflowSecurityManageOverride as shown in https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html#web-authentication

### Operating System

ubuntu

### Versions of Apache Airflow Providers

2.8.0 celery

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

No deploy.

### Anything else?

no....

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vincbeck** [comment]
Fixed in #36538

**Comment by Darlan4I** [comment]
I also received this error in Airflow 2.8.1, when I went to configure authentication through some provider.
The [documentation](https://airflow.apache.org/docs/apache-airflow/stable/security/webserver.html#example-using-team-based-authorization-with-github-oauth) says to extend the FabAirflowSecurityManagerOverride class.

But when I do this, it generates this exception because the custom class does not extend AirflowSecurityManager
![image](https://github.com/apache/airflow/assets/89137830/88416940-a52b-4846-b522-45992e9509df)
Directory of the print above: "./python3.10/site-packages/airflow/auth/managers/fab/fab_auth_manager.py"

A provisional solution (I believe) was to extend both.
