### ISSUE TITLE
[MySqlOperator] execute a multi-statement file

### ISSUE THREAD

**Issue by alybel** [apache/airflow#366]
Hi, 

I am trying to use a collection of SQL statements (that need to be carried out in the right order) stored in a *.sql file. Airflow detects the file and starts processing it but then the throws this error: 

2015-09-07 11:37:53,838 - root - ERROR - (2014, "Commands out of sync; you can't run this command now")

The database I use is MySQL. I believe this is not Airflow causing the issue but presumably some of the used libraries or I am missing to set some argument properly.

If I copy&paste my SQL Script into SQL Workbench it runs smoothly, so I would exclude an error in the SQL statements itself. 

Thanks for any help

**Comment by griffinqiu** [comment]
You cannot do that? only one sql command can be accept in mysql_hook.

I have reported it at
https://github.com/airbnb/airflow/issues/329

**Comment by alybel** [comment]
alright, that clarifies it. In this case I misunderstood the instructions for the mysql operator: 

'''sql (Can receive a str representing a sql statement, a list of str (sql statements), or reference to a template file. Template reference are recognized by str ending in ‘.sql’) – the sql code to be executed'''

thanks for clarification

**Comment by mistercrunch** [comment]
You can pass it as a list of statements, but not a reference to a multi-statement sql script. DbApi doesn't seem to expose a standard way to run a script (multi-statements - separated by semicolons). That's usually a CLI feature.

Related:
http://stackoverflow.com/questions/4408714/execute-sql-file-with-python-mysqldb

So solutions are:
- Users break their scripts down into lists, either by parsing the file themselves (`f = open('foo.sql')`) in their pipeline script, or writing `sql = [...]` in their script
- The operator(s) logic could apply a regex that looks for semi-colons and breaks down the statements, trying to avoid the pitfalls (semi-colons in a sql string, ...)
- Writing alternate hooks that wraps the CLI (I think that's overkill, less desirable). That's what we did for Hive since we needed perfect compatibility there and had a lot of `hql` files to run.

For now option 1 works and doesn't require a new version out or anything...

**Comment by mistercrunch** [comment]
It it's important enough to someone I'll be happy to review the PR
