### ISSUE TITLE
doc version seems to high (4.8) 

### ISSUE THREAD

**Issue by bumhwan** [apache/airflow#36612]
### What do you see as an issue?

I checked the version while browsing the document, and it came out as shown in the image below.
I know that the current version is 2.8, but it seems that version 4.8 is being released due to some bug in the documentation.
![image](https://github.com/apache/airflow/assets/95680257/448b77b8-a94b-47e3-879c-e9041c134dca)

### Solving the problem

The problem seems to occur only in other operator httpoperator documents. I think the document needs to be edited.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aritra24** [comment]
Operators follow a [different release cycle](https://github.com/apache/airflow/blob/main/PROVIDERS.rst?plain=1#L34) compared to Airflow core, thus while airflow core is on version 2.8.0 the http operator is on 4.8.0 thus the difference in version. You would notice all the operators would have different versions. Closing this since it's not an issue.
