### ISSUE TITLE
Pendulum not importing correctly with certain lib

### ISSUE THREAD

**Issue by teraearlywine** [apache/airflow#36741]
### Apache Airflow version

2.8.0

### What happened?

When importing airflow, breaking change with pendulum 3.0. Fixed the issue by from pendulum import tz etc.. 
pendulum 3.0 was released last month

`The tz argument is keyword-only, unlike in version 1.x`
https://pendulum.eustace.io/docs/

### What you think should happen instead?

from pendulum import tz 
### How to reproduce

install airflow locally and try running script with date used
```
from airflow import DAG 
schedule = "@once"

...
dag = DAG(
    dag_id=dag_id,
    default_args=default_args,
    schedule_interval=schedule,
    catchup=False,
)
```

### Operating System

macOS

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You should use constraints to install airflow https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html - it is specifically designed to prevent people instaliing Airflow from experiencing such problems.

That's why Airflow 2.8.0 has Pendulum <3 and I am quite surprised that you were able to install Airlfow 2.8.0 and Pendulum 3 together. This is what you find in Airflow 2.8.0 package metadata:

```
Requires-Dist: pendulum (<3.0,>=2.0)
```

You must have done something completely forbidden even if you used constraints.

And yes we know very well tha tPendulum 3 is not ocmpatible with Airflow - but it has more breaking changes that you found.

And if you'd search for Pendulum you'd find out that this PR https://github.com/apache/airflow/pull/36281 adds support for Pendulum 3.

For the future I suggest you use search functionality first - that will save you time for reporting issues and maintainers for having to close them.

**Comment by potiuk** [comment]
BTW. We plan to cherry-pick it for 2.8.1 so likely 2.8.1 will be Pendulum-3 compatible
