### ISSUE TITLE
CVE-2023-46136 Werkzeug==2.2.3

### ISSUE THREAD

**Issue by bmoon4** [apache/airflow#36915]
### Description

Hi team, 

Airflow latest (2.8.0+) is using `Werkzeug==2.2.3` and it has a CVE (Score 7.5 High).

It would be nice if we can have it  2.3.8 above (3.0.1) to avoid security issues. 

https://nvd.nist.gov/vuln/detail/CVE-2023-46136

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
See :

https://github.com/apache/airflow/blob/056118342b3c28488d20558a1fd3ff15b4934460/pyproject.toml#L151-L153

Thus it depends on completing https://github.com/apache/airflow/pull/36052 first

**Comment by potiuk** [comment]
Closing as duplicate. We know about it. Airflow is likely not vulnerable. We invite any commercial users who is interested in their scanner results to be better to help with implementing and reviewing #36052 or - if they think Airflow is vulnerable because of that CVE to report reproducible vulnerability scenario to `security@airflow.apache.org`
