### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by brunolnetto** [apache/airflow#37344]
### What do you see as an issue?

I run Airflow installation on [page](https://airflow.apache.org/docs/apache-airflow/stable/start.html) . There is a simple issue of `python` instead of `python3` on Quickstart section 

### Solving the problem

On [Quickstart description](https://airflow.apache.org/docs/apache-airflow/stable/start.html#quick-start), change `python` to `python3` due slow transtion from python 2 to 3.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
Just wondering which OS use `python` as alias to `python2` in 2024, after 4 years of EOL of Python 2.7?

**Comment by brunolnetto** [comment]
Linux, sorry.

**Comment by Taragolis** [comment]
> Linux, sorry.

This is answer contain pretty wide options :smile:  https://upload.wikimedia.org/wikipedia/commons/a/ad/2023_Linux_Distributions_Timeline.svg

**Comment by Taragolis** [comment]
Anyway instead of replace `python` to `python3` better write note that user should replace by appropriate command or even full path: `/usr/bin/python3.10` or `/home/awesomeuser/.pyenv/versions/3.10.6/bin/python`

`python3` not always a correct option if end user try to use provided python version by selected linux distribution and install it into the user space (not recommended) or even as a root (highly not recommend), e.g. some abstract Linux distribution might have pretty old version of default python interpreter, and `python3` may stands for Python 3.7, which is also would not work, and instead of that user should run `python3.9` or `python3.8`, etc.

In the other cases when user install airflow into the activated [Virtual Environment ](https://docs.python.org/3/tutorial/venv.html) , into the [Official Python Docker Image](https://docs.python.org/3/tutorial/venv.html), or into the [Official Airflow Docker Image](https://hub.docker.com/r/apache/airflow) then `python` and `python3` are links to the same python interpreter
