### ISSUE TITLE
test_settings.py not being evaluated

### ISSUE THREAD

**Issue by Dev-iL** [apache/airflow#37587]
### Apache Airflow version

main (development)

### What happened?

A PR was merged with incorrectly defined tests. These should've failed but didn't. It's possible that they weren't even evaluated.

### What you think should happen instead?

The build should've failed, alerting everyone involved to the issue.

### How to reproduce

```bash
airflow$ pytest tests/test_settings.py
```

### Operating System

Ubuntu 22.04

### Versions of Apache Airflow Providers

Irrelevant

### Deployment

Virtualenv installation

### Deployment details

Irrelevant

### Anything else?

This fixes the test definitions:
```python
@patch("airflow.settings.conf")
@patch("airflow.settings.is_sqlalchemy_v1")
def test_encoding_present_in_v1(is_v1, mock_conf):
    is_v1.return_value = True
    mock_conf.getjson.return_value = {}

    engine_args = settings.prepare_engine_args()

    assert "encoding" in engine_args


@patch("airflow.settings.conf")
@patch("airflow.settings.is_sqlalchemy_v1")
def test_encoding_absent_in_v2(is_v1, mock_conf):
    is_v1.return_value = False
    mock_conf.getjson.return_value = {}

    engine_args = settings.prepare_engine_args()

    assert "encoding" not in engine_args
```
However, I don't know how to get these tests to be picked up.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
You don't have to create an issue if you could fix it and send the the PR. Airflow is PR friendly - create a PR rather than a task. You also might ask ad-hoc questions into the `#contributors` or `#new-contributors` Slack Channels. Join link https://s.apache.org/airflow-slack

We have to custom test collector and also selective checks which might exclude tests outside of specific directories.
So the solution would be fix the and move it into the [`tests/core/test_setting`](https://github.com/apache/airflow/blob/main/tests/core/test_settings.py)
