### ISSUE TITLE
Custom build get rate limited because of Dockerfile first line

### ISSUE THREAD

**Issue by V0lantis** [apache/airflow#37716]
### Apache Airflow version

2.8.1

### What happened?

When using custom build, we use the base Airflow Dockerfile. The issue is that the first line is `# syntax=docker/dockerfile:1.4`

leading to the following rate limiting in our CI

```
Dockerfile:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1.4
   2 |     # Licensed to the Apache Software Foundation (ASF) under one or more
   3 |     # contributor license agreements.  See the NOTICE file distributed with
--------------------
ERROR: failed to solve: unexpected status from HEAD request to https://registry-1.docker.io/v2/docker/dockerfile/manifests/1.4: 429 Too Many Requests
Error: Process completed with exit code 1.
```

Is thee anyway this could be mitigated? I tried to use `sed` to replace this first line, but this is quite a dirty solution.

### How to reproduce

Hard to reproduce, but I guess, doing thousand of build at the same time with the same IP would do the job

### Operating System

Github Actions on Github Entreprise

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is absolutely needed and standard way to explain what syntax is used. You should authenticate your CI jobs in docker to solve your problem. The issue is that docker - similarly to any other service will rate limit any client that is not logged in using IP address (and if you are behind NAT with 1000s of users, they are added to rate limit).

You should issue a `docker login` with valid credentials before your build. It will solve your problem.
