### ISSUE TITLE
Provide context to SimpleHttpOperator#response_check

### ISSUE THREAD

**Issue by alvarogimenez** [apache/airflow#380]
Hi,

I have a sequential DAG defined as follows:
1. An HTTP Operation performs a POST against some endpoint which returns an UUID 
   
   > **POST /process**
   > _34ac3fe0-5798-11e5-885d-feff819cdc9f_
2. An _HttpSensor_ checks some other endpoint using the previous obtained UUID until it reaches a certain state (Defined in the response body)
   
   > **GET /process/34ac3fe0-5798-11e5-885d-feff819cdc9f**
   > _OK_

To provide the UUID to the second step I'm using the XCom utility over Jinja. The _HttpSensor_ is configured as follows:

``` python
getStatus = HttpSensor(
    ...
    endpoint="process/{{ ti.xcom_pull(key='uuid', task_ids='getUuid') }}",
    ...
)
```

The tricky part comes when I try to provide XCom with the UUID value resulting from the first POST operation. The only place (as far as I know) which has access to the _response_ object outside the _SimpleHttpOperator_ is the _response_check_ function (Configured by parameter when creating the Operator as a lambda or a defined function). Since the _response_check_ function only receives the _response_ object when its called during _execute_ I have no reference to the _Task Instance_ to call _TaskInstance#xcom_push_. I have modified the _SimpleHttpOperator_ into _ExtendedHttpOperator_ to provide _context_ as follows:

``` python
def execute(self, context):
    ...
    if self.response_check:
        if not self.response_check(response, context):
            raise AirflowException("Response check returned False.")
```

With this modification I can define a check function as follows:

``` python
def check(response, context):    
    processId = response.content
    context['ti'].xcom_push(key='uuid', value=processId)
    return True

...

startProcess = ExtendedHttpOperator(
    task_id='getUuid',
    method='POST',
    endpoint='process',
    response_check=check,
    ...
)
```

The DAG works as expected, sharing the POST UUID information with the following _HttpSensor_ node in the graph. I would like to know if this is the right way to go when sharing information between DAG nodes and, if so, it would be nice to improve the _SimpleHttpOperator_ to provide _context_ to the _response_check_ function just as _PythonOperator_ does (Based in a _provide_context_ parameter). 

Please note that these are my very first steps with Airflow so maybe I'm doing something really wrong. Thanks in advance!

**Comment by mistercrunch** [comment]
This is still fairly unmapped territories, so operators or function arguments you might need or best practices have not been defined yet. 

One easy way to leverage more out of the xcom framework would be for `SimpleHttpOperator` to return the response's data, which will create an xcom entry (any operator's execute return value gets "xcommed"). This would become available wherever `SimpleHttpOperator` is used.

It also seems like posting + sensing is a common use case and it's nicer when it's executed atomically as one task instead of 2. So there could be a `HttpPostThenSense` of some kind, or you can do this in a very simple PythonOperator as well.

Now I'm guessing you are interfacing with a specific system that exposes a web API. So say if that system was something called "AmazonBackups", you could write a specific AmazonBackupOperator with the perfect interface for it.

**Comment by kapil-malik** [comment]
^ +1 to HttpPostThenSense. When dealing with REST APIs, the POST is often an async trigger, and I need to confirm whether the job completed successfully or failed / killed, by continuously sensing with a GET.
We've defined it as a Plugin operator, for our particular pattern of POST/GETs, but I believe a generic solution will be very helpful too. xcom is excellent for doing ad-hoc communication, but in this case it's more convenient to define and treat Post+Sense as a single operator.

**Comment by mistercrunch** [comment]
HttpPostThenSense might be harder to use than writing your own operator actually is. I'm happy reviewing a PR that does this though.
