### ISSUE TITLE
AWS Batch job stuck in runnable state with no retry

### ISSUE THREAD

**Issue by aiqc** [apache/airflow#38298]
### Description

I am running AWS Batch jobs using the BatchOperator.

When I use Spot Instances, sometimes the job gets stuck in a "Runnable" status in the AWS Batch Queue. Probably because there are no spot capacity instances available. Eventually, the job will show `statusReason`:`UNDETERMINED - Batch job is blocked, root cause is undetermined.`

Meanwhile, Airflow shows these stuck jobs in the green "running" state and keeps polling them. My DAG has both `retries` and `retry_delay` defined, but I think the running state is preventing them from getting triggered.

I'd like for the task to fail and retry in this scenario

---

### Use case/motivation

Cost savings -- I'd like a bit more retry functionality baked into the BatchOperator so that I can run spot instance jobs affordably

---

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
I guess it something related to the [Jobs stuck in a `RUNNABLE` status ](https://docs.aws.amazon.com/batch/latest/userguide/troubleshooting.html#job_stuck_in_runnable)?

**Comment by aiqc** [comment]
@Taragolis Indeed, it's surprising that the `statusReason` does not mention "capacity"

I should mention that as soon as I rerun the DAG with **reserved** (non-spot) instances, it works as expected.

**Comment by Taragolis** [comment]
Oh that is old issue with Batch but a least it nowadays provide a bit more information rather than couple years ago.

Right now BatchOperator use waiters in some places so it would be nice to get example of the output https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch/client/describe_jobs.html at the moment when job are stuck (do not forget to replace any sensible information by placeholders) and after that someone could try to check is it possible to detect this case by waiters and fail the job.

**Comment by aiqc** [comment]
Circling back here. The root problem was service quota limits on AWS Fargate.

**Comment by o-nikolas** [comment]
> Circling back here. The root problem was service quota limits on AWS Fargate.

Sounds good, closing the issue then :)
