### ISSUE TITLE
[Backfill] Support Partial DAG Backfills while still honoring dependencies

### ISSUE THREAD

**Issue by whitleykeith** [apache/airflow#38407]
### Description

One current major limitation on backfills with Airflow is how `--ignore-dependencies` works when using `task_regex`, as it also ignores dependencies of the resulting partial dag. However, not using `--ignore-dependencies` means that you end up rerunning tasks you may not need/want to rerun in a given backfill.

For example, say you have a dag like this: 

```python
sensors = [ExternalTaskSensor(external_dag_id=dag_id, external_task_id=task_id) for dag_id, task_id in sensor_list]

foo = DummyOperator(task_id="not_sensor_foo")
bar = DummyOperator(task_id="not_sensor_bar")
baz = DummyOperator(task_id="not_sensor_baz")

sensors >> foo >> bar >> baz

```

A common use case is to backfill just the non-sensor tasks, because those ultimately may not need to be rerun. However `--reset-dagruns` would reset these tasks if they already completed, and sometimes that flag is desired to clear existing runs of tasks.

This leads to a situation where you cannot skip the desired sensor tasks without also effectively ignoring dependencies you actually don't want to ignore. Therefore you must either:

* Run the backfill with all unwanted tasks
* Or run individual backfills for each "layer" of the DAG dependency tree

Both options are not ideal and require either waiting longer than necessary for backfills to finish or manual hand-holding 

### Use case/motivation

Ideally, when running the above DAG with task regex of `not_sensor_.*`, either the existing `ignore_dependencies` flag or another flag allows for partial dag dependencies to be honored, while still ignoring dependencies of tasks filtered out

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

> [!NOTE]
> Looking at the code this may be non-trivial, so I'd like some feedback on feasbility of this before I take a stab at it.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by AryaMoghaddam** [comment]
I can take this up as a first issue

**Comment by potiuk** [comment]
Assigned you

**Comment by AryaMoghaddam** [comment]
I've read through the issue, since there hasn't been a clear wanted solution I thought I would ask here, or open a discussion post to narrow it.

I could think of three possible approaches:

Custom Backfill Logic
Implementing a custom backfill script or function that programmatically determines which tasks to run based on your specific logic. This script could use Airflow's APIs or database to check task states and decide which tasks to rerun, considering dependencies as needed.

Enhancing Airflow Features
Proposing changes or enhancements to Airflow's core to support more granular dependency management in backfilling scenarios. This could involve:

Introducing a new flag that allows for partial ignoring of dependencies based on more sophisticated rules or patterns.
Extending the task_regex functionality to include or exclude specific dependencies.
Use of Dynamic Task Generation
Utilizing Airflow's dynamic task generation capabilities to create tasks that can decide at runtime whether to execute based on external conditions, previous task states, or custom logic. This approach requires careful design to ensure it doesn't add unnecessary complexity to DAG definitions.

**Comment by potiuk** [comment]
That sounds like something that needs a devlist discussion - not GitHuyb issue I am afraid - it's not that straightforward and I have a feeling this one will not play well with versioning (https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-63%3A+DAG+Versioning) - so possibly it's not a "good first issue". But if you will to explore some of those options and propose them then likely devlist discussion should happen for that one.

**Comment by AryaMoghaddam** [comment]
@potiuk Sounds good, I will look for other issues to work on.
