### ISSUE TITLE
Support time zones when running tasks

### ISSUE THREAD

**Issue by kimtore** [apache/airflow#385]
It seems that Airflow is using naive time zones. What does this mean? Is the system's local time zone used, or is the time stamp in UTC?

I kindly suggest that all dates and times are made time zone aware, so that there is no ambiguity.

**Comment by mistercrunch** [comment]
Right, currently it's consistently server time zone throughout the framework, for us it happens to be UTC.

I get your point though, but I'm not sure on the implications or how easy / complex this would be, and how much change management would be required.

**Comment by sergioherg** [comment]
Hi, there is a way to cheat timezones. We are in Madrid (Spain) and our servers are UTC. We need to program with spanish hours, so we transform a spanish datetime to utc and then remove timezone info. This is tricky and is not the better way, but it works well. We use pytz.

```
dt = datetime(2015, 10, 1, 12, 20) 
madrid_tz = pytz.timezone('Europe/Madrid')
schedule_date = pytz.utc.normalize(madrid_tz.localize(dt)).replace(tzinfo=None)
```
First we create a datetime without timezone info. Then we localize that dt with spanish timezone (adding tzinfo when creating datetime not works well) and transform to utc datetime. With utc dt we last need to remove timezone info to works well with airflow.

In a future, there are libraries like tzlocal that get timezones from local system. It could be great use them to works with datetimes with timezones.

Thank you for reading

**Comment by sergiohgz** [comment]
At this time, you can use pytz to make conversions between timezones and make your dags work at correct time. In example, we make a datetime without timezone, then localize at our timezone, later we normalize to UTC and finally remove timezone info (because airflow don't work with tzs). It's a bit tricky but it works as well as it pass the change of daylight saving without problems.
Note: we have our system in UTC and want to make it work with special tz. Logs are showing them output in UTC, but knowing how many hours differs with UTC, we know that it works.
Thank you so much
