### ISSUE TITLE
Allowing for multiple scheduler processes to run in parallel

### ISSUE THREAD

**Issue by r39132** [apache/airflow#392]
We are using EC2 auto-scaling. It turns out that our airflow machines are on the autoscaled EC2 instances, resulting in multiple machines launching schedulers with LocalExecutors. Is this a design pattern that is dangerous?

We originally worked around this using EC2 "user-data" scripts that fire after an EC2 auto-scaled instances is launched -- the "user-data" script kills the scheduler processes. However, we suspect that some of these schedulers pick up duplicate work and execute them before they are killed. 

Hence, I am wondering how the scheduler with local executor works in a topology with schedulers running on multiple machines.

**Comment by mistercrunch** [comment]
I think allowing the scheduler to scale out to multiple processes or machines would be very simple. There are already some of the mechanics in place (`DagModel.scheduler_lock`, DagModel.last_scheduler_run).

Now it would be only a matter of taking and releasing the locks in `SchedulerJob`, and have some mechanism to expire the locks.

Without locking in place 2 schedulers could step on each other's toes, though in theory no task instance should ever double trigger since the worker checks and alters the task instance's status as part of a database transaction. So 2 schedulers might send the same message to the queue, but in theory the workers should sort it out (only the first worker to get the message should actually end up running the task).

**Comment by bolkedebruin** [comment]
Locks can be handled by the database "with_for_update". SQLAlchemy supports this.

@r39132 this should become a Jira issue. Please close after creation
