### ISSUE TITLE
DAG disappearing from Airflow in case of standalone DAG processor

### ISSUE THREAD

**Issue by kosteev** [apache/airflow#39332]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.3

### What happened?

If DAG processor is running in a standalone mode with defined --num-runs flag
```
airflow dag-processor --num-runs 100
```

Some DAGs disappear from Airflow until DAG processor will run again.

### What you think should happen instead?

DAGs shouldn't disappear never.

### How to reproduce

- run Airflow 2.7.3 with standalone DAG processor (separate from scheduler) with --num-runs flag
Example:
```
airflow dag-processor --num-runs 100
```
- deploy some DAGs
- after some time, ~20 mins (once DAG processor will parse all DAG files ~50), deploy another DAG (new DAG file)
- after some time observe that DAGs will start to disappear 

The issue is, basically, that:
- DAG processor runs until it parses each file exactly num_runs times
https://github.com/apache/airflow/blob/2872d370178ffed402ac15d2983dbeda8ed7902b/airflow/dag_processing/manager.py#L1245
- if a new DAG file will be added to the DAG bag during DAG processor running, this new file will have different number of parsing runs than others already existing there
- at some point other DAGs (those which were already in the DAG bag) will stopped to be parsed due to hitting run limit (they will be excluded from parsing loop), see "Last Run" column in the screenshot below
https://github.com/apache/airflow/blob/2872d370178ffed402ac15d2983dbeda8ed7902b/airflow/dag_processing/manager.py#L1164
- DAG processor will continue to parse DAGs until each file will be parsed exactly num_runs times
- Due to the fact that DAGs are not parsed for some time, they will be removed from Airflow DAG bag

![image](https://github.com/apache/airflow/assets/1017130/1ee0d636-7d65-4c77-b195-9173d7d1bfe8)

### Operating System

Ubuntu

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> If "Other Airflow 2 version" selected, which one?
> 2.7.3

Is it reproduced in Airflow 2.9.0?

**Comment by potiuk** [comment]
>  Is it reproduced in latest Airflow (2.9.0 at that moment)? 

I do not think there was a change in this area since. But it looks plausible and likely not very difficult to fix - so I will mark it as good-first-issue to investigate and fix.

**Comment by kosteev** [comment]
I didn't test it in Airflow 2.9, but the implementation of the DAG processor at this place of code should be the same, so the issue has to be there as well.

**Comment by potiuk** [comment]
@kosteev -> maybe a chance to contribute a fix yourself ?

**Comment by andyjianzhou** [comment]
Hey, is it okay if I get assigned to this issue? Thanks!

**Comment by bmoon4** [comment]
I found same issue in 2.9.1 .. Had to revert back to traditional schedulers :(

**Comment by andyjianzhou** [comment]
Hey all! So I have been trying to reproduce the error and haven't been successful. 

I've ran the DagProcessor Job standalone, and created 40+ test dag files, some of them having a timeout functionality within them.

From my understanding, this is my workflow:
I run the command -> I can view all my dags on the airflow UI. -> I add a new Dag file -> wait 5 minutes -> Refresh my page and all dag files exists. If there's a timeout error, there will be an explanation in terminal and/or on UI about an invalid DAG file or a runtime error. 

Wondering if you can share me what your dags/environment setup looks like? If you can be more specific on how to reproduce the issue? 

Some questions to consider:
1. How do you know when the Dag Processor Job has "finished" parsing all DAG files before you added a new DAG file.
2. What your DAG files look like approximately
3. More specific reproducibility steps. 

Thank you!

**Comment by vghar-bh** [comment]
Hi facing the same issue in airflow 2.7.3 and 2.9.1 both.
these logs are from 2.7.3
we are getting this in dag-processer pod logs :
**DAG airflow_dag1 is missing and will be deactivated.[2024-06-28T09:03:57.806+0000] {manager.py:543} INFO - DAG airflow_dag2 is missing and will be deactivated.[2024-06-28T09:03:57.809+0000] {manager.py:553} INFO - Deactivated 2 DAGs which are no longer present in file.[2024-06-28T09:03:57.816+0000] {manager.py:557} INFO - Deleted DAG airflow_dag1 in serialized_dag table[2024-06-28T09:03:57.823+0000] {manager.py:557} INFO - Deleted DAG airflow_dag2 in serialized_dag**

some times we are getting this in scheduler  logs:
**[2024-07-02T08:02:45.975+0000] {scheduler_job_runner.py:1786} INFO - Found (3) stales dags not parsed after 2024-07-02 07:52:45.971946+00:00.**
the dags are disappearing from airflow ui and serialized_dag table and after some time they are appearing again 

could any once help me with this issue

**Comment by potiuk** [comment]
as explained in slack - likely your DAG code is producing different outputs (different DAGs) at different times it is parsed. look for bug in your DAG code.

**Comment by raphaelauv** [comment]
I have the problem with 2.10.1 and only deterministic dags ( not using any dynamic config for the dag authoring ) 

and 

`airflow_dag_processing_total_parse_time` is between 0.1 and 1.2s

`airflow_dag_processing_file_path_queue_size` is between 0 and 5

I had zero problem without the dagprocessor and 2 scheduler

**Comment by AlaxHAM** [comment]
I ran into the same problem, and a later look at scheduler found a log：

``Found (18) stales dags not parsed after 2024-10-08 08:13:19.911344+00:00``

Later, when you look at the source code in ``_cleanup_stale_dags`` method, after the dag-processor finishes, the DAG that is not updated for the timeout is marked as inactive and removed from the SerializedDagtable

**Comment by rtrindvg** [comment]
I created a discussion here (https://github.com/apache/airflow/discussions/44495) but it seems related to this issue.

**Comment by potiuk** [comment]
Just one comment here. I think it's worth looking at the description of the issue first and understand that - not all issues are the same even if log messages are similar. 

This isssue has nothing to do with regular ways how airflow dag file processor runs in production. The "--num-runs" flag is really a "test" flag that should not be used in production, really. It's a remnant of Airlfow 1 where we had to recycle scheduler - and you are not supposed to use it in production. It's not the intention of this flag (and yes it's behaviour should like be fixed - or more likely we should remove this flag completely because yes @kosteev is right that this has those kinds of effects he mentioned here). 

I added a detailed explanation in https://github.com/apache/airflow/discussions/44495#discussioncomment-11421723 to explain what and how you can take  look at to see the root cause of the problem. I would love if everyone who has similar issue follows it and post their finding on what kind of problem they found with their system and how they fixed it. 

I don't believe there is a consistent issue in Airflow, it's more set of not following the best practices, hiding problems with the way how DAGs are written, or synced or some similar issues.


But having a result of the investigation and possible issues that users could have, following my outline and "investigation scenario" that I put there might help us to see if we can add better guidelines or maybe even better warnings/messages for similar reasons:

So if I might ask you:

* @vghar-bh 
* @raphaelauv 
* @AlexHam
* @rtrindvg 

Please follow the  https://github.com/apache/airflow/discussions/44495#discussioncomment-11421723 and post THERE (this is a different issue altogether as I explained above) results of your investigation following my guidelines.

Thanks in advance.

**Comment by potiuk** [comment]
I reopened it. The `--num-runs` behaviour is worth to be fixed or removed regardless.

**Comment by rtrindvg** [comment]
Thanks, @potiuk, and you are right. I am not using the flag, sorry if I derailed the discussion from the main objective of the issue here, it was not my intention. I got more focused on the topic description than on the specific way the OP used to trigger the condition.

Will continue answering on the discussion, as requested.
