### ISSUE TITLE
Password autocompletion set to off on login page

### ISSUE THREAD

**Issue by datta90** [apache/airflow#40125]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.1

### What happened?

my company vulnerability scanning tool has reported that the login page of airflow should have autocomplete field set to off 

### What you think should happen instead?

the autocomplete parameter should be set to off in the password field 

### How to reproduce

simply doing a curl request on the airflow url with /login appended will reveal a html page where we see that the password field does not have autocomplete set 

for eg curl -X GET http://airflow:8080/login 

### Operating System

rhel 8.9

### Deployment

Virtualenv installation

### Deployment details

using virtualenv to install airflow 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to work on that if you want @datta90 - otherwise I marked it as a good first issue - hopefully someone will pick it up and implement it if you will not want, but if you want to get it fixed faster, contributing PR is a most effective way.

Also note - generally speaking if you are reporting security issue, you should NEVER use public issues. This one - luckily - is not "really" security issue, certainly not a CVE worthy one, so it's quite ok to put in public, but generally speaking approaching security issues in a "responsible" way - you should follow our [security policy](https://github.com/apache/airflow/security/policy) to report such issues. And this is the same for all projects out there, so you might consider in the future finding out and following security policy when you are reporting security-related issues.

**Comment by datta90** [comment]
hi team,

@jmelot patch fixed this issue for me. thank you so much . i am marking this as closed now

**Comment by rajeshjagmohan** [comment]
@datta90 How did you patch fix this issue ? Did you create build using @jmelot change ? it seems this change is still not merged . 
FYI : @potiuk

**Comment by datta90** [comment]
i directly changed in the source code of flask_appbuilder as shown by @jmelot

**Comment by rajeshjagmohan** [comment]
Thanks Datta
