### ISSUE TITLE
Codecov is not in sync and shows inaccurate coverage

### ISSUE THREAD

**Issue by shahar1** [apache/airflow#40174]
### Apache Airflow version

main (development)

### What happened?

After merging my PR that added unit and integration tests to Kafka's hook (#40142), I noticed that its source code and associated coverage did not update on its corresponding [Codecov page](https://app.codecov.io/gh/apache/airflow/blob/main/airflow%2Fproviders%2Fapache%2Fkafka%2Fhooks%2Fbase.py).

I'm aware that there were issues with the Codecov token that should have been solved after merging #40138, but it seems it went out of sync as it got stuck on [this commit](https://app.codecov.io/gh/apache/airflow/commit/1a61eb3afdaf0496ce6c308b1a36357cfd5728b7), while no errors were omitted.

Finally, I find the calculation of the coverage metric, shown in the [commits](https://app.codecov.io/gh/apache/airflow/commits) page, to be very weird (it jumps between constant values that are quite far from one another):

![image](https://github.com/apache/airflow/assets/60007259/51430d2e-4f50-4497-aa0d-f81c706d251f)

### What you think should happen instead?

1. Ensure how the coverage metric is calculated.
2. Rerun Codecov manually for all existing source code.
3. Fix the `post-tests-success` action if needed, and figure out if it's possible to make it more verbose than it is today.

### How to reproduce

Take a look at the Codecov [recent commits](https://app.codecov.io/gh/apache/airflow/commits).

### Operating System

N/A

### Deployment

Official Apache Airflow Helm Chart

### Anything else?

cc: @potiuk

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
To be honest, the number of times it broke in the past (and often not our fault) was so big that I kinda stopped paying attention. @Taragolis had made the last attempt to fix it and since then the only change was to make it works with new codecov plugin (which required adding a key) - because of nodejs warning we got. 

And codecov has a history of having some quirks in the process that make the coverage works (or does not) somewhat mysteriously.

There is a good reason why calculation on PRs can never be good - because we are running selective checks  to save build and feedback time, vast majority of the PRs will simply run a subset of tests relevant to the change.

That's why the only relevant measure of coverage **should** be taken only from `main` (i.e. canary builds) and I believe it's been like that last time @Taragolis fixed it. But coverage from PR will **never** work well - that's why we disabled it.

Not sure what happened here - maybe some issue where switching to the new codecov plugin, but to be honest almost no-one consistently looks at those metrics for it to be high priority :). But if someone would like to take a look and figure out what's wrong, that would be great.

**Comment by shahar1** [comment]
Gotcha. I agree that PR calculations are not ideal for coverage calculation. In the issue's description, I referred only to commits in `main` when talking about the actual output on Codecov. 

I'd be happy to try tackling it later on - I dealt with installing both Codecov and SonarQube in my workplace, so there's a chance I'll figure it out. However, I'll need to check how to integrate it with my forked repo, and later have permissions to work on Airflow's account.

**Comment by potiuk** [comment]
This is one of the difficulties there, that it's notoriously difficult to test :D

**Comment by potiuk** [comment]
Should be fixed now (hopefully) it was bad token .
