### ISSUE TITLE
Include .Values.volumeMounts into chart/templates/cleanup/cleanup-cronjob.yaml

### ISSUE THREAD

**Issue by iiskandarov-clgx** [apache/airflow#40191]
### Description

Since all templates supported airflow_config_mount supports Values.volumeMounts (except cleanup-cronjob.yaml)
Is it possible to add Values.volumeMounts support to cleanup-cronjob.yaml as well?

Thank you

### Use case/motivation

use custom ConfigMap for airflow_local_settings.py instead of .Values.airflowLocalSettings

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Sure. Feel free to add it.

**Comment by sanskrutikhedkar9** [comment]
I am interested. Could you please assign this to me

**Comment by potiuk** [comment]
Done

**Comment by amoghrajesh** [comment]
@sanskrutikhedkar9 are you working on this actively?

**Comment by dada-engineer** [comment]
I would like to jump in here and fix this issue alongside with a problem that you are not able to deactivate the job history because the check {{ if .Values.cleanup.successfulJobsHistoryLimit }} if false if I use --set cleanup.successfulJobsHistoryLimit=0 and then the default of k8s (3) is used.

Are you fine with this or do you prefer a separate issue here?
