### ISSUE TITLE
After deleting a dag from the dags directory, it is still displayed in the UI

### ISSUE THREAD

**Issue by tatyana12345** [apache/airflow#40363]
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

2.8.3

### What happened?

Dag has been removed from the airflow dags directory /opt/airflow/dags. Dag is not displayed when running the airflow dags list command. But it is still available in the Airflow UI, and it is also available in the Airflow postgres database.
I can remove the dag from the database or by some other additional means. But it seems that deleting the same dag from two different places is not very convenient and this point is not reflected in the documentation.

### What you think should happen instead?

It is expected that dag will be automatically removed from the web interface after deleting dag from the dags directory.
Or it would be nice to add information to the documentation that in new versions it is necessary to remove the same dag from several places.

### How to reproduce

Remove dag from the /opt/airflow/dags directory and it will still be available in the web interface even after a few days

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shahar1** [comment]
@tirkarthi answered your question in the [discussion](https://github.com/apache/airflow/discussions/40331) - there was no need to recreate it as an issue again.
If you're convinced it's a bug, you'd have to supply more details about how to reproduce it (e.g., Airflow versions and configurations for both cases, screenshots, etc.); otherwise, no one else would be able to solve it.
As long as you can't provide the above, I'd like to ask that you continue the troubleshooting in the already open discussion rather than recreating the issue.
