### ISSUE TITLE
switch HttpHook from using requests library to httpx?

### ISSUE THREAD

**Issue by kiaradlf** [apache/airflow#40580]
### Description

the [`HttpHook`](https://github.com/apache/airflow/blob/main/airflow/providers/http/hooks/http.py) currently uses the [`requests`](https://requests.readthedocs.io/) library for HTTP calls.
[`httpx`](https://www.python-httpx.org/) appears a more modern alternative, boasting support for e.g. http2, async support, and type annotations.
it would be nice if the http hook could perhaps take advantage of these as well.

### Use case/motivation

my own immediate use-case was password-protected client certificates, which seem not supported in `requests`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I am not sure we recently switched back from httpx to requests in file task handler, because it did not work with some specific NO_PROXY settings https://github.com/apache/airflow/pull/39799. And since HTTPHook is just simple wrapper and has simple fuynctionality - we do not need all the "fancy" features `httpx` has. But if someone (like you) take on the task to make sure to handle the issues like the one in #39799  - then why not  - with documentation etc. 

We need someone to take a lead, analyse all pros and cons and things supported/not supported by both and come up with good documentation.

Would you like to take a lead on that one ?
