### ISSUE TITLE
AWS SNS Sensor

### ISSUE THREAD

**Issue by InonS** [apache/airflow#40796]
### Description

The Airflow AWS provider provides an SNS Operator which allows publishing to a topic (through the SNS hook), but does not provide an SNS Sensor that would allow triggering a DAG based on subscription to a topic (as is currently supported for SQS, for example).

### Use case/motivation

As a developer, I want to be able to multicast to an SNS topic and trigger multiple DAGs (e.g. in different environments) by subscribing each of the DAGs to the SNS topic.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
I don't think it's possible.
I think what you are after is SQS rather than SNS.

If you want Airflow to support this behavior please share the API endpoint of SNS that we ahould integrate with. From the list of APIs
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html
I don't see such option. If the SNS API doesn't suport it then it's feature request for SNS not for Airflow.
We can support only APIs offered by SNS

**Comment by eladkal** [comment]
Closing for now.
Should SNS add API for this we can revisit
