### ISSUE TITLE
ElasticsearchSQLHook fails with AttributeError: __enter__

### ISSUE THREAD

**Issue by Pooort** [apache/airflow#41486]
### Apache Airflow Provider(s)

elasticsearch

### Versions of Apache Airflow Providers

apache-airflow-providers-common-io==1.3.2
apache-airflow-providers-common-sql==1.14.0
apache-airflow-providers-elasticsearch==5.4.1
apache-airflow-providers-fab==1.1.1
apache-airflow-providers-ftp==3.9.1
apache-airflow-providers-http==4.11.1
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-sqlite==3.8.1

### Apache Airflow version

v2.9.2

### Operating System

v2.9.2

### Deployment

Virtualenv installation

### What happened

[Documentation's usage example](https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/5.4.1/hooks/elasticsearch_sql_hook.html) for ElasticsearchSQLHook:
```
from airflow.providers.elasticsearch.hooks.elasticsearch import ElasticsearchSQLHook

es = ElasticsearchSQLHook(elasticsearch_conn_id='elasticsearch')

# Handle ES conn with context manager
with es.get_conn() as es_conn:
    tables = es_conn.execute("SHOW TABLES")
    for table, *_ in tables:
        print(f"table: {table}")
```
fails with:
```
Traceback (most recent call last):
  File "/home/port/projects/Encortex/airflow/new_test.py", line 6, in <module>
    with es.get_conn() as es_conn:
AttributeError: __enter__
```

### How to reproduce

Implement [Documentation's usage example](https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/5.4.1/hooks/elasticsearch_sql_hook.html).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Which version of elastic are you running?

**Comment by Pooort** [comment]
8.13.1

**Comment by eladkal** [comment]
cc @Owen-CH-Leung maybe you can take a look?

**Comment by Owen-CH-Leung** [comment]
Sure. Will take a look soon

**Comment by Owen-CH-Leung** [comment]
Indeed, I can reproduce the same error as @Pooort pointed out: 

![image](https://github.com/user-attachments/assets/3d7717a0-ceaf-4eb4-91b0-b0f1c13354cd)

The root cause is that the current implementation of `ElasticsearchSQLHook` is dependent on an unofficial ES library `elasticsearch-dbapi` which we have already deprecated it since it doesn't support ES8.

Luckily the official es python client has a SQL client available so we can easily refactor our implementation : 

https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/_sync/client/sql.py#L26

I'll file a PR to refactor it soon
