### ISSUE TITLE
airflow.exceptions.AirflowException: No module named 'airflow.api.auth.backend.ldap_auth'

### ISSUE THREAD

**Issue by manel00** [apache/airflow#42127]
### Apache Airflow version

2.10.0

### What happened?

LDAP does not work

### How to reproduce

Deploy airflow on Docker

### Operating System

Ubuntu 22

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kunaljubce** [comment]
@manel00 Can you please provide some details on this? 

* What is the exact error message? Simply mentioning "LDAP does not work" is not sufficient. 
* Can you provide the error trace or logs? 
* How can anyone reproduce it? You have mentioned "Deploy Airflow on Docker", which isn't sufficient. Any specific configs you are passing to setup LDAP?
* What do you think should happen instead of the failure you're facing?
