### ISSUE TITLE
Please update google cloud provider cloud functions api to support v2

### ISSUE THREAD

**Issue by cbio-erik** [apache/airflow#42146]
### Description

We should parameterize this api_version argument to allow users to trigger v1 or v2 functions. Right now v2 functions just not reachable because this hard coded value.  (https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/operators/functions.py#L453) 

### Use case/motivation

Able to trigger cloud functions v2 with larger machine types

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@cbio-erik I don't believe this is a hardcoded value but the default value.  Your should be able to override this when using the operator.

```
test = CloudFunctionInvokeFunctionOperator(
        task_id='my-task',
        project_id='my-project',
        function_id='my-function',
        input_data={'key': 'value'},
        api_version='v2',
    )
```

**Comment by cbio-erik** [comment]
@nathadfield Seems like the google cloud functions v2 has to different base uri. I will close this ticket since CloudRunExecuteJobOperator is an alternative operator to run cloud function v2 jobs.

**Comment by houtanb** [comment]
@nathadfield NB that just providing `api_version='v2',` does not solve work.

@cbio-erik it's not clear to me how `CloudRunExecuteJobOperator` works for both v1 and v2 functions. And do we need to create jobs for each individual v2 function we want to call if we want to use `CloudRunExecuteJobOperator`? I have a lot of v1 and v2 functions that I would like to call, so I didn't see `CloudRunExecuteJobOperator` as an option, but perhaps I'm missing something in my setup...

It's unfortunate that `CloudFunctionInvokeFunctionOperator` hasn't been updated for v2 functions since they've been generally available since [August 10, 2022](https://cloud.google.com/blog/products/serverless/cloud-functions-2nd-generation-now-generally-available).

But we don't have to rely on the Google library! We can just authenticate and call the v1 or v2 function directly...
```python
@task
def cloud_function_task(endpoint):
    """Call cloud function represented by endpoint."""
    auth_req = google.auth.transport.requests.Request()
    id_token = google.oauth2.id_token.fetch_id_token(auth_req, endpoint)
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {id_token}",
    }

    response = requests.post(
        url=endpoint,
        headers=headers,
        data=None,
    )

    if response.status_code != 200:
        raise Exception(f"\nError invoking {endpoint}: {response.text}\n")

    return response.text
```

Your service account will need permissions to invoke the given cloud functions.

If running locally, you'll need to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the credentials file.
