### ISSUE TITLE
Airflow local settings no longer importable from dags folder

### ISSUE THREAD

**Issue by pdebelak** [apache/airflow#42156]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.1

### What happened?

As of 2.10.1 Airflow no longer imports local settings from the dags folder because of changes in #41672.

### What you think should happen instead?

Either Airflow should continue to import local settings from the dags folder or this breaking change should be documented. For example [the docs for local settings](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html#configuring-local-settings) don't make it clear that `$AIRFLOW_HOME/dags` is _not_ in `sys.path` when this is loaded even though it is later.

### How to reproduce

Put your airflow_local_settings.py file in dags/ and see that it is loaded in 2.10.0 and not in 2.10.1.

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free to add documentation to explain it @pdebelak  in the place that you feel is best (click 'suggest a change on this page') and PR will be opened for you.

This was a security fix and the fact that you could add locL_settings.py to DAG folder was an accidental behaviour (it should never be possible because of our security model).

I think since you are the user who used this accidental  behaviour you might be the best to describe it for people like you so that they can understand it

**Comment by potiuk** [comment]
See the CVE advisory published on users@ mailing list  for details

**Comment by jishangarg** [comment]
I am trying to get this done.

**Comment by jishangarg** [comment]
@potiuk can you please review it.
