### ISSUE TITLE
remove librabbitmq from dependencies

### ISSUE THREAD

**Issue by LilithWittmann** [apache/airflow#423]
librabbitmq is not python3 compatible and it looks like that it's nowhere used…

**Comment by mistercrunch** [comment]
http://celery.readthedocs.org/en/latest/userguide/optimizing.html#librabbitmq

**Comment by jlowin** [comment]
It shouldn't be an issue with `pip install airflow` because it's marked as optional. 

However, I echo that it shouldn't be a requirement for airflow. It's not even a hard requirement for celery (we use a redis backend for celery on python 3 -- `pip install celery[redis]`. Works great with airflow.)

**Comment by LilithWittmann** [comment]
Yes I also use airflow with redis and celery and was only a bit confused why librabbitmq is in the dependencies…
