### ISSUE TITLE
Add attributes "name" and "group" to Asset class

### ISSUE THREAD

**Issue by Lee-W** [apache/airflow#42310]
### Description

[The Asset Class](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=311627073#AIP74IntroducingDataAssets-TheAssetClass)

### Use case/motivation

[Rationale](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=311627073#AIP74IntroducingDataAssets-Rationale)

### Related issues

https://github.com/apache/airflow/issues/42307

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
First PR published on the database end. https://github.com/apache/airflow/pull/42407

**Comment by phanikumv** [comment]
@uranusjr is going to pick this next

**Comment by uranusjr** [comment]
Database changes are done. Next I’m going to add the two arguments to the public-facing Asset class so the user can pass them to be stored in the database.

There’s one thing we need to address in the database after we do the above. Since we want to keep history in the asset table, we need to have the unique constraint on `(name, uri)` so a name can be reused by different assets as long as the URIs are different, vice versa. But we still want only one _active_ asset to use that name. So I’ll add a separate table to only keep track of active (non-orphaned) assets so we can add all those unique constraints appropriately.

**Comment by uranusjr** [comment]
PR to add database-level uniqu constraint (see previous message)
https://github.com/apache/airflow/pull/42612

(Draft) Main change to add `name` and `group` to Asset (tests tbd)
https://github.com/apache/airflow/pull/42812

(Draft) Tweak AssetAlias to match Asset (not strictly a part of AIP-73 but should be a good thing)
https://github.com/apache/airflow/pull/42814

**Comment by uranusjr** [comment]
Both `name` and `group` have been added to `Asset`, and they are stored on `AssetModel`.

#42814 is a related PR to also add `group` to `AssetAlias`, and change `name` constraints to match `Asset`, but not a strict blocker.

**Comment by uranusjr** [comment]
I think we’re done here!
