### ISSUE TITLE
AIP-84 Migrate Config related public endpoint to FastAPI 

### ISSUE THREAD

**Issue by rawwar** [apache/airflow#42745]
### Description

Migrate the following endpoint:

- [x] Get Current configuration
- [x] Get a option from configuration

### Use case/motivation

[AIP-84](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-84+UI+REST+API)

### Related issues

Relates to: https://github.com/apache/airflow/issues/42370

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
I think we should support all the `content-type` that the legacy endpoint was supporting, so yes I would say multiple of them (JSON, text etc.) we need to actually check what should be supported.

We can add 406 that's not a problem. Though I would tend to return a general 422 ValidationError, like the client response is wrong because the mimetype suggested is not supported. I'm not really for having a multitute of response code from the API, the 406 one is really singular I would say.

**Comment by jason810496** [comment]
Hi @rawwar, I can take this on. Could you please assign the issue to me? Thanks!
