### ISSUE TITLE
`skip_if` decorator evaluated after pool slot allocation

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#42824]
### Apache Airflow version

2.10.2

### What happened?

The `skip_if` decorator is currently evaluated after a task has already been allocated a pool slot. This leads to inefficient use of pool resources, as tasks that end up being skipped still occupy pool slots unnecessarily.

### What you think should happen instead?

Ideally, the `skip_if` decorator should be evaluated before the task attempts to acquire a pool slot.

### How to reproduce

1. Create a Pool with the name `limited_pool` and 0 slots.
2. Create the following example DAG:

```python
from airflow.decorators import dag, task
from datetime import datetime

@dag(
    dag_id='skip_if_pool_issue',
    schedule_interval=None,
    start_date=datetime(2023, 1, 1),
    catchup=False,
    is_paused_upon_creation=False,
)
def skip_if_pool_issue():

    @task.skip_if(lambda context: True)
    @task(pool='limited_pool')
    def task_with_pool():
        print("This task is in a pool and should always be skipped")

    task_with_pool()

skip_if_pool_issue()
```

3. Trigger a DAG Run for this DAG.

### Operating System

Ubuntu 22.04.4 LTS

### Deployment

Docker-Compose

### Deployment details

Used `LocalExecutor`.

### Anything else?

Hopefully this is possible.
If this is considered a feature request not a bug, please change the tags.
Related PR: 
- https://github.com/apache/airflow/pull/41116

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pedro-cf** [comment]
Hey @phi-friday , maybe you could share some thoughts abouts this, thank you in advance for the great work!

**Comment by phi-friday** [comment]
> Hey @phi-friday , maybe you could share some thoughts abouts this, thank you in advance for the great work!

This feature is entirely dependent on `pre_execute`, so if `pre_execute` can be executed before the `slot` allocation, then the scenario you mentioned should be possible. 

However, I believe (though I don't know exactly) that having a `Task` assigned to an `executor` and getting a `slot` are isomorphic, so wouldn't this scenario be impossible.

**Comment by eladkal** [comment]
I don't think this is a bug(?) The way I see it this feature is a shorter way to write conditions. Normally you would use a branch operator or ShortCircuitOperator and both occupy a pool slot.

**Comment by potiuk** [comment]
Currently custom code provided by DAG author cannot be executed in scheduler for securiy reasons - so what you want is not possible because it violates airflow security model  - specifically capabilities of DAG authors https://airflow.apache.org/docs/apache-airflow/stable/security/security_model.html#dag-authors 

In Airflow 3.+ we will likely have a possibility to run different types of workflows, so we could potentially execute such condition somewhere else than in pre-execute of a task - and not occupy a pool slot for such a check.

If you would like to work on it @pedro-cf - that would likely require discussion on the devlist and getting consensus on a scope of it - because this is quite a big change in architecture. And if you would like to come back to it after we know how task sdk and executing of non-task workflows will look like, because this is not likely anyone would even look at it before Airflow 3 is out.
