### ISSUE TITLE
SlackAPIFileOperator is not propagating filetype API call

### ISSUE THREAD

**Issue by hzlmn** [apache/airflow#42889]
### Apache Airflow Provider(s)

slack

### Versions of Apache Airflow Providers

2.9.2

### Apache Airflow version

2.9.2

### Operating System

MacOS 14.3.1

### Deployment

Amazon (AWS) MWAA

### What happened

`SlackAPIFileOperator` not propagating correctly filetype ending up sending csv file and json as plain text uploads.

As you can see here `filetype` is passed to initial params but not used than in execution.
https://github.com/apache/airflow/blob/main/providers/src/airflow/providers/slack/operators/slack.py#L263-L271

### What you think should happen instead

Should correctly pass down `filetype` value.

Can be fixed as following
```python
class SlackAPIFileOperator(SlackAPIOperator):
    ...
    def execute(self, context: Context):
        self._method_resolver(
            channels=self.channels,
            # For historical reason SlackAPIFileOperator use filename as reference to file
            file=self.filename,
            filetype=self.filetype,   # here missing filetype
            content=self.content,
            initial_comment=self.initial_comment,
            title=self.title,
        )

```

### How to reproduce
```python
slack = SlackAPIFileOperator(
    task_id="slack_file_upload",
    dag=dag,
    slack_conn_id="slack",
    channel="#general",
    initial_comment="Hello World!",
    filename="hello_world.csv",
    filetype="csv",
    content="hello,world,csv,file",
)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bowrna** [comment]
@hzlmn On debugging further with the data you shared above, could you tell me what method_version you are using to upload files using SlackOperator? The default one is "v2", while you can still pass the old version "v1". 

https://github.com/apache/airflow/blob/e20146d44b340f719f7fb432f93741e011690558/providers/src/airflow/providers/slack/operators/slack.py#L232-L234

Here the execute method to invoke the Slack API chooses the upload based on the method version.

https://github.com/apache/airflow/blob/e20146d44b340f719f7fb432f93741e011690558/providers/src/airflow/providers/slack/operators/slack.py#L257-L271

The send_file method call of v1 function invokes API call where we send the filetype. The above issue fix that you have recommended applies here.

Then there is another version v2 which is the updated version, where we upload file with different SDK method call. We pass a dict of file_uploads. ( in this dict we can pass file(or content) (here file represents the filepath, content represents the actual filecontent), filename, title, snippet_type, alt_txt)

https://github.com/apache/airflow/blob/e20146d44b340f719f7fb432f93741e011690558/providers/src/airflow/providers/slack/hooks/slack.py#L289-L322

In the above method we are passing the filetype into snippet_type. But snippet_type is an optional argument for syntax highlighting in case code content is uploaded. ( It can support types like python, HTML etc. Passing the filetype into snippet_type seems to be incorrect). In V2 version, there is no explicit way to pass the filetype, as I think with file upload directly as multipart binary, the metadata or MIME of the file content can be used to find the file type.

@potiuk Can you tell me if I can raise a fix where we can get another param for snippet_type, rather than passing the filetype into it?
