### ISSUE TITLE
Adding Elestio as deployment option Elestio

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [apache/airflow#42998]
### Description

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Airflow application as shown [here](https://elest.io/open-source/airflow). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

### Use case/motivation

Example of one-click deploy button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/airflow)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Andd just to comment  - any kind of revenue sharing/etc. opportunities are not possible. This is a vendor-neutral PMC of the Apache Software Foundation and since ASF is a registerd 501 c3 charity in Delaware (https://apache.org/foundation/) that has the motto of "Releasing Software for Public Good", the Airflow PMC cannot endorse or promote any vendors on the software the ASF releases. This is why Ecosystem page has a clear disclaimer that those are unverified, public links that are neither endorsed nor affiliated with Airflow PMC.

And one - even more important thing - as a PMC member of the Apache Airlfow, my responsibility is to notice and follow up on branding issues when Airlfow registered trademark is used by 3rd parties.

Your website is violating branding rules and you MUST fix it, otherwise we will involve Apache Software Foundation trademarks team to follow up with you - you should fix it promptly.

Airflow (R) is a registered trademark of the Apache Software Foundation and if you want to refer or use the trademark you need to follow the ASF Branding policy. The policy is here https://apache.org/foundation/marks/ and you and your lawyers should read it in detail and you should follow all the detailed guidelines if you want to use "Airflow" trademark.

Example things that are wrong here https://elest.io/open-source/airflow 

* The wording suggest that Airlfow is "by Elastio" this is huge misuse, Airlfow is an Apache project and suggesting that other entity owns it "which this statement does" is strictly forbidden and ASF trademark team is very strict about following and enforcing it (And the fact that Airflow is a registered trademark in US makes it very, very enforceable). You should refer to "Apache Airflow" in the first prominent place as "Apache Airlfow (R)" and name of your offering should be a "nominative use" - for example Manager Workflows for Apache Airlfow" (MWAA) is a good name from Amazon because "for Apache Airflow" is a nominative use. "Airlfow by Elastio" is definitely not.

* There are a number of other branding rules (again link here https://apache.org/foundation/marks/) - and you (and your lawyers) have to read it in detail and you have to apply all the rules explained there to your website.

Also you have other ASF projects in your managed application list (I did not check all but for example I saw Superset) - and you have exactly the same issues - so you should implement the changes for all ASF projects you manage. 

Please do it promptly and let us know when done, to avoid unnecessary escalation and lawyer involvement. I will let the trademark team in the ASF know that we noticed the issue and get you some time to react but I want you to know that the ASF treats such violation of their trademarks very, very seriously, so my advice is to quickly comply with those requirements.

**Comment by potiuk** [comment]
@kaiwalyakoparkar - I renamed the issue to "Elastio violating trademarks of ASF" and assigned you to it.

**Comment by kaiwalyakoparkar** [comment]
Hey @potiuk, I appreciate your comment. I have forwarded your suggestions to the appropriate teams internally and we will resolve it at the soonest and get back to you here. Thanks :)

**Comment by potiuk** [comment]
Let us know please, this is pretty important topic that the ASF treats with all seriousness.

**Comment by jbenguira** [comment]
> * s statement does) is strictly forbidden and ASF trademark team is very strict about following and enforcing it. The fact that Airflow is a registered trademark in US makes it very, very enforceable. You should refer to "Apache Airflow" in the first prominent place as "Apache Airlfow (R)" and name of your offering should be a "nominative use" - for example "Managed Workflows for Apache Airlfow" (MWAA) is a good name from Amazon because "for Apache Airflow" is a nominative use. "Airlfow by Elestio" is definitely not.

Hey @potiuk, I've double checked and I'm not seeing ANY places where Elestio claims it's "The wording suggest that Airlfow is "by Elestio". 

**It's interesting how you built your argument by truncating "fully managed by elestio" to just "by elestio"
Your whole argument now seems to be done iun BAD FAITH!**

**ON THE CONTRARY** it's very clearly indicated everywhere: "Airflow, fully managed by Elestio" which seems ok based on the allowed example you provided "Managed Workflows for Apache Airlfow" and we are linking directly to the official repo on the same page.

Please forward this case to your legal team so we can ensure our implementation is OK and not infringing anything.

**Comment by potiuk** [comment]
First of all @jbenguira thanks for already responding to our request - even if you failed to mention it in your response.

I see that you already corrected some of the things I mentioned. Namely you started to use Apache Airflow, instead of Airflow. I did copy the previous screenshots with only "Airflow" - now it shows "Apache Airflow". Thanks for being so receptive:

![image](https://github.com/user-attachments/assets/1d331567-f955-4656-aa48-ebb89d3b7494)

But I am afraid it's not nearly enough.

First of all there are other Apache Software Foundation projects that you have not corrected - for example https://elest.io/open-source/superset and https://elest.io/open-source/kafka (probably there is more - you should fix it in the same way for all the places).

But secondly - there are many more rules that I pointed out before that you still have to fix.

I suggest you take a look at the ASF branding rules which I linked to above. The problem is @jbenguira that Airflow is not used in Nominative use https://en.wikipedia.org/wiki/Nominative_use - if you need your legal team to look at the "nominative use" definition, this is the right time. This is US legal doctrine, and since Airflow and other trademarks are registered trademarks in the US, you should follow it.

In short - you can use "Powered by Apache Airflow" or "Managed Elastio **for** Apache Airflow" - this is the "nominative use" case. Using "Airflow managed by Elastio" is not. I suggest to consult your legal team about the "nominative use" there. Also in the documents I linked you can clearly see the description of it:

> What is nominative use?

> Anyone can use ASF trademarks if that use of the trademark is nominative. The "nominative use" (or "nominative fair use") defense to trademark infringement is a legal doctrine that authorizes everyone (even commercial companies) to use another person's trademark as long as the use meets three requirements:

> The product or service in question must be one not readily identifiable without use of the trademark (for example, it is not easy to identify Apache HadoopCertain ASF trademarks are reserved exclusive for official Apache Software Foundation activities. For example, "ApacheCon" is our exclusive trademark for our regular ASF conferences, and the ASF feather is intended for ASF use at events in which we participate.

® software without using the trademark "Hadoop").

> Only so much of the mark or marks may be used as is reasonably necessary to identify the product or service.

> The organization using the mark must do nothing that would, in conjunction with the mark, suggest sponsorship or endorsement by the trademark holder.

> The trademark nominative fair use defense is intended to encourage people to refer to trademarked goods and services by using the trademark itself. This trademark defense has nothing to do with copyright fair use and should not be confused with those rules.

> What is the "confusing similarity" or "likelihood of confusion" test?

> Some uses of another person's trademark are nominative fair use, but some uses are simply infringing. Indeed, if someone uses a trademark in a way that the relevant consuming public will likely be confused or mistaken about the source of a product or service sold or provided, likelihood of confusion exists and the mark has been infringed.

> Note that, even if there is no likelihood of confusion, you may still be liable for using another company's trademark if you are blurring or tarnishing their mark under the state and/or federal dilution laws.

> To avoid infringing ASF's marks, you should verify that your use of our marks is nominative and that you are not likely to confuse software consumers that your software is the same as ASF's software or is endorsed by ASF. This policy is already summarized in section 6 of the [Apache License](https://apache.org/licenses/) , and so it is a condition for your use of ASF software:

Also this is rather clear:

> Using ASF Trademarks in software product branding

> In general you may [not use ASF trademarks in any software product branding](https://apache.org/foundation/marks/faq/#products). However in very specific situations you may use the [Powered By naming form](https://apache.org/foundation/marks/faq/#poweredby) for software products.

And the link here explains more https://apache.org/foundation/marks/faq/#poweredby - including the fact that you should not really use Airflow Logo without the "powered by" mark unless you get specific permission. You can request your permission by sending the request to trademarks@apache.org and again - I highly recommend you start discussing your case and permissions there, before we pass the case for them to handle. It would show that you want to play nicely with the community and that your intention is not take an unfair advantage of the trademarks owned by the Foundation.

Also this is very clear:

> You needn't ask us for permission to use the ASF's graphics logos (the versions published on individual project's websites) on your own website solely as a hyperlink to the specific ASF project website or to [www.apache.org](https://apache.org/). The VP, Brand Management, a member of the Brand Management Committee, or the relevant Apache project's VP must [approve in writing](https://apache.org/foundation/marks/contact) all other uses of Apache Foo (and similar) graphic logos.

The graphic logo of yours does not link to Apache Airflow website and you need written permission if you want to use the logo for different purpose.

Also Apache Branding rules that I linked to explicitly expect you to use "Apache Airflow (R)" and link from the name directly to https://apache.airflow.org in the first prominent place you refer to it. Also you do not provide the required attributions in the footers or elsewhere: 

In case you missed that in the branding rules, here are the right chapters quoted (https://apache.org/foundation/marks/faq/#attribution) 


> To properly attribute Apache marks, and to ensure that the volunteer communities that build Apache software get the credit they deserve, place prominent trademark attributions wherever you use Apache marks. On websites, add hyperlinks to the relevant project homepage and to the ASF. For example, to provide an attribution for Apache Hadoop and its yellow elephant logo (using basic HTML with hyperlinks):

> Apache®, [Apache Hadoop, Hadoop®](http://hadoop.apache.org/), and the yellow elephant logo are either registered trademarks or trademarks of the [Apache Software Foundation](https://apache.org/) in the United States and/or other countries.

> In text, use Apache Lucene® in the first and most prominent uses because it is a registered trademark; some other Apache project names like Apache Zookeeper™ are unregistered but are still considered trademarks of the ASF.


The branding rules are pretty clear and  pretty clearly your use is violating them - so I suggest that you read them closely and follow - those are just excerpts where your usage is clearly not following the rules, but maybe there are more

**Comment by potiuk** [comment]
> It's interesting how you built your argument by truncating "fully managed by elestio" to just "by elestio"
Your whole argument now seems to be done in BAD FAITH! And I also noticed you (Jarek Potiuk) trying to make some damage to our brand by renaming this incident to "Elestio is violating" without even discussing first with us or even consulting your legal team.

It was in response to public issue you created which clearly violated the rules, so I just responded to it, and made it clear that this issue is really driver to fix the issues you have.

> Please forward this case to your legal team so we can ensure our implementation is OK and not infringing anything. Our goal is to comply.

Then please comply.

>  In the meantime please stay professional instead of going to conclusions, you are not a lawyer nor a judge. So don't say we are not compliant when you are not in a position to decide that.

Oh. I am very much in the position to point it out. As a PMC member, it's not only my right, but also a responsibility to point out such clear violations, that are explicitly against what's written in the branding rules. 

If you look here - reporting such issues is clearly within the expectations the ASF has for PMC members. https://www.apache.org/dev/pmc.html#brand-policy

> PMCs SHALL ensure that they manage their projects' brand and treat all Apache® marks properly as defined in the overview of
[PMC Branding Responsibilities](https://www.apache.org/foundation/marks/responsibility) and the [Apache Project Branding Requirements](https://www.apache.org/foundation/marks/pmcs) for project websites.

> Responsibly report misuses of Apache brands
PMCs SHALL review use of their Apache project brand by third parties and follow the [Apache trademark use reporting guidelines](https://www.apache.org/foundation/marks/reporting.html) when appropriate.

**Comment by potiuk** [comment]
Also @jbenguira  I would really appreciate if you stop threatening me. Your original 'issue' was not an airflow iasuE at all it was  mostly a marketing campaign. Normally we report such issues as spam to GitHub and authors of such messages are usually quickly disabled and need to ask GitHub to reinstate their accounts - so renaming the issue to clarify the actual issue that came out of us seeing the message ( I.e. elestio violating branding rules) is actually better course of action that allows you to correct the issue in a more gentle way

**Comment by jbenguira** [comment]
> Also @jbenguira I would really appreciate if you stop threatening me. Your original 'issue' was not an airflow iasuE at all it was mostly a marketing campaign. Normally we report such issues as spam to GitHub and authors of such messages are usually quickly disabled and need to ask GitHub to reinstate their accounts - so renaming the issue to clarify the actual issue that came out of us seeing the message ( I.e. elestio violating branding rules) is actually better course of action that allows you to correct the issue in a more gentle way

@potiuk I didn't threaten you, I simply pointed how you turned this original post that was a partnership request with sharing of part of our profits to apache into a a very aggressive attack on our company and trying to hurt our band reputation by your actions to weaponize the title of this github issue.  

Maybe you should read again the apache guidelines you cited before? It seems you are not following them! (https://www.apache.org/foundation/marks/reporting.html#pmcs)
More specifically:
- Discuss questions in private: We recommend discussing these issues in private because it is easier to clear up many unintentional misuses of marks in this way. 
- The intent is to send a polite, non-confrontational email to the infringing party, reminding them of the proper treatment of our trademarks. Do not imply any legal action or suggest that lawyers need to be involved

About the other points you cited, as I said in my first answer we intend to be compliant and are working on it.

**Comment by potiuk** [comment]
> @potiuk I didn't threaten you, I simply pointed how you turned this original post that was a partnership request with sharing part of our profits to apache into a a very aggressive attack on our company and trying to hurt our brand reputation by your actions to weaponize the title of this github issue.

Maybe you have not read the instruction that were printed to you when you opened the marketing issue here. Issues are for reporitng any issues with Apache Airflow, not about promoting your company and product, and not about partnership with Apache - which as I explained clearly is not how things work here - you apparently have not understood what Apache Software Foundation is. So rather than reporting it, I gently pointed out - very objectively and without a slight hint of being aggreesive all the issues you should fix - in all the messages of mine there is no aggression, just objective facts.

And well, it's you who started to publicly post lins to the website that clearly violates the rules in an attempt to drag traffic to your site, so I think pointing it out in the same issue, made a lot of sense. I would definitely do it in private if I noticed that accidentally - but here I had few choices:

* report your messasge as spam
* delete it altogether (which I think would be quite aggressive way of protecting people here for getting into the trademark-violating site
* or point it out objectively

Which I think I did.

> About the other points you cited, as I said in my first answer we intend to be compliant and are working on it.

I sincerely hope it will happen. But your message was different - you wrote "we do not think we are doing wrong" and "you are not qualified to talk to me about it", so I am a little confused what intent of your message was.

**Comment by jbenguira** [comment]
> And well, it's you who started to publicly post lins to the website that clearly violates the rules in an attempt to drag traffic to your site, so I think pointing it out in the same issue, made a lot of sense. I would definitely do it in private if I noticed that accidentally - but here I had few choices:
> 
> * report your messasge as spam
> * delete it altogether (which I think would be quite aggressive way of protecting people here for getting into the trademark-violating site
> * or point it out objectively
> 

You are making the assumption it was a marketing campaign, it was clearly not, goal was to do a partnership and share revenues with the authors / foundations of open source software, since we don't have any contact yet we opened a github issue to try contact the authors.

It would be clearly preferable to delete this issue when it's resolved (as I said we are working on others points related to airflow and the other apache software we support), If you are not trying to weaponize this ticket as you claim and you are acting in good faith you will agree to delete this issue once the points are resolved? 

> 
> > About the other points you cited, as I said in my first answer we intend to be compliant and are working on it.
> 
> I sincerely hope it will happen. But your message was different - you wrote "we do not think we are doing wrong" and "you are not qualified to talk to me about it", so I am a little confused what intent of your message was.

Maybe read my messages again? **I said clearly twice already that we want to be compliant and are working on it.** 

Please read AGAIN apache guidelines and apply their recommendations.
- "The intent is to send a polite, non-confrontational" **this is NOT at all what you are doing here.**  
- We recommend discussing these issues in private because it is easier to clear up many unintentional misuses of marks in this way. **This is obviously preferable to an approach that causes unnecessary damage to our brand and reputation. As you have already identified, when our unintentional oversights were brought to our attention we immediately commenced addressing and rectifying them**

**Comment by potiuk** [comment]
> It would be clearly preferable to delete this issue when it's resolved (as I said we are working on others points related to airflow and the other apache software we support), If you are not trying to weaponize this ticket as you claim and you are acting in good faith you will agree to delete this issue once the points are resolved?

I am happy to do it when the issue is solved

**Comment by jbenguira** [comment]
> I am happy to do it when the issue is solved

Great, I'll let you know when the changes are completed.

**Comment by jbenguira** [comment]
Hey @potiuk 
We have reviewed and fixed our page for Apache Airflow and also for other Apache software
Please have a look when you can

**Comment by potiuk** [comment]
This is fantastic. Thank you - I have no more issues withe the page you addressed all my concerns, I will delete/hide that issue then.

If you want to be absolutely sure you - now or in the future - that you are doing the right thing, reach out to treademarks@apache.org please and ask them for opinion

**Comment by potiuk** [comment]
And thank you for being so receptive and following all the guidelines and rules. Much appreciated.

**Comment by potiuk** [comment]
I cannot delete the issue myself I closed it and restored the original title. If you want the issue to be deleted I will need to as the ASF infrastructure - who own the repo. But I think closed like that might be good - it will show you are receptive to the ASF requirements, so this one is "good" eventually.
