### ISSUE TITLE
Python 3.8 with breeze causes import error

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#43092]
When we are using Python 3.8 or less for breeze, it failes on functools.cache and the error is not telling too much.

![Image](https://github.com/user-attachments/assets/bf1af725-3e46-4d72-bc9f-a9045c3ddf14)

We should catch the import error and print meaningful message

**Comment by jscheffl** [comment]
If a PR/fix is available we also need to add this to PR for version 2.10 in PR https://github.com/apache/airflow/pull/42788 (or on the same branch)

**Comment by dirrao** [comment]
Python 3.8 support was recently removed. Do we still need to address this issue, or is it now obsolete?

**Comment by jscheffl** [comment]
It is helping users who try to contribute but (by accident an old interpreter in the $PATH or just have not read the docs) that the root cause can be better identified. Same we had in the past when people tried to contribute tried (and failed) to start breeze in Windows.
So it might not only be specifically for Python 3.8 but for all versions <= 3.8
