### ISSUE TITLE
Airflow webserver and worker constantly restart everyday at the same time

### ISSUE THREAD

**Issue by robinisme2** [apache/airflow#43295]
### Official Helm Chart version

1.13.1

### Apache Airflow version

2.8.3

### Kubernetes Version

1.30.4

### Docker Image customizations

No

### What happened

I created an airflow application by helm chart on my k8s cluster, and I found that the worker and webserver will restart everyday at the same time for no reason, there's nothing special in the log, and also not liveness issue. Besides, the helm chart is deployed by argocd, and I found that the argocd sync time is exactly the same as the pod restart time. 

### How to reproduce

It happens everyday at the same time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment]
@robinisme2 I don't think there's much we can do to help you here currently because this is more than likely a configuration/implementation issue on your side rather than an Airflow bug AFAIK.  If you are able to identify a bug, validate that it still exists in the latest version and then provide a way for anyone to reproduce it then you might get the assistance you are looking for.
