### ISSUE TITLE
CloudDataFusionStartPipelineOperator.partial().expand_kwargs() not working in airflow 2.9.1

### ISSUE THREAD

**Issue by VinodMalleshappa** [apache/airflow#43513]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.1

### What happened?

Our dag working fine in airflow 2.5.3 , but when we created new composer 2.9.5 and airflow 2.9.1 in this same dag and code is not working , only one task is not working as we call the data dynamically from previous tasks , issue with one task i.e. CloudDataFusionStartPipelineOperator.partial(task_id='start_cdfpipeline_name',
Location='us-cenrtal-1',
Timeout=900,
).expand_kwargs(previous _task.output)
Failing as "airflow.exception.AirflowException: Starting a pipeline failed with code 400"

### How to reproduce

Plz provide your help to fix the issue

### Operating System

Na

### Versions of Apache Airflow Providers

2.9.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
What version of `airflow.providers.google.cloud.operators.datafusion` is installed in each environment?

**Comment by VinodMalleshappa** [comment]
Not sure how to check, but we have used the from airflow.providers.google.cloud.operators.datafusion import CloudDataFusionStartPipelineOperator

**Comment by potiuk** [comment]
You can see provider's version in the UI of Airflow. Also there is a https://airflow.apache.org/docs/apache-airflow-providers-google/stable/changelog.html changelog of Google provider which is the one that interfaces with cloud fusion.

Google team is testing and running the providers (including system testing them), they also manage CloudDataFusion sand they are managing composer, so Composer should be your support  - especially that you have paid support with them.

So I suggest you open a support ticket with them, this does look like a problem that squarely falls into the support of the service you pay for rather than volunteer-run free open-source software that they manage.

Converting it into discussion if more discussion needed.
