### ISSUE TITLE
AIP-84 Standardize PATCH Behavior Across Endpoints in FastAPI

### ISSUE THREAD

**Issue by bugraoz93** [apache/airflow#43650]
#### None Values
Currently, the handling of `None` values in `PATCH` requests is inconsistent across different parts of the codebase. In some instances, when no mask is provided, None values are filtered out, while in others, such as the `Pool` model, all values (including None) are validated and persisted if the payload is valid. The objective of this work item is to standardize `PATCH` request behaviour regarding None values:
1. When a mask is provided, use the values as specified by the mask.
2. When no mask is provided, ensure the payload is validated independently as a fully-formed database entity, allowing for explicit setting of fields to None.

#### Database Calls
Avoid making database calls solely to check for existence; instead, delegate this responsibility to the database itself during the primary operation.

### Use case/motivation

A standardized approach for PATCH endpoints is needed.

### Related issues

Relates to: #42370
Follow Up of: #43102

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
Thanks a lot, great description.

**Comment by pierrejeambrun** [comment]
Up for grab, #good first issue!

**Comment by ajitg25** [comment]
Hello @pierrejeambrun,

I went through the related links provided in the description, and here’s my understanding:

To standardize the implementation, I need to add a `mask` parameter to the function. If the parameter is passed, I will use the specified values; otherwise, I will validate the entire payload.

I have updated the `create_or_update_pool` function accordingly:
`@staticmethod
@provide_session
def create_or_update_pool(
    name: str,
    slots: int | None,
    description: str | None,
    include_deferred: bool | None,
    session: Session = NEW_SESSION,
    mask: list[str] | None = None,
) -> Pool:
    """Create a pool with given parameters or update it if it already exists."""
    if not name:
        raise ValueError("Pool name must not be empty")
    pool = session.scalar(select(Pool).filter_by(pool=name))
    if pool is None:
        pool = Pool(pool=name, slots=slots, description=description, include_deferred=include_deferred)
        session.add(pool)
    else:
        if mask:
            if 'slots' in mask:
                pool.slots = slots
            if 'description' in mask:
                pool.description = description
            if 'include_deferred' in mask:
                pool.include_deferred = include_deferred
        else:
            pool.slots = slots
            pool.description = description
            pool.include_deferred = include_deferred
    session.commit()
    return pool
`
Does this align with the requirements?

Additionally, regarding the description mentioning changes in different parts of the codebase, I found several functions with create_or_update. Are there any others that I should look into? Let me know your thoughts on the scope of changes and the specific files that need to be updated.

**Comment by pierrejeambrun** [comment]
Hello [ajitg25](https://github.com/ajitg25),

I have assigned you. The function you are mentioning is located in the `models`. We do not want to update that part.

This issue is referring to HTTP endpoints that are located in the FastAPI Rest API. Files of interests are in `api_fastapi`. More precisely in `api_fastapi/core_api/routes/public` for the public endpoint definition. In here you will find a multitude of endpoints, and several are for `updating` a resource. (Pool, Connection, Variable, etc...). We want the behavior of those `Update` endpoints to be harmonized, especially regarding the `mask` query parameter and also for `None` value handling.

The idea is:
- If a mask is provided, only update values specified in the mask
- If no mask is provided, instanciate a DB entity and ensure that the payload is valid in that regard. update payload is a fully formed resource

In both cases I think we should only use `set` values. Things that the user explicitely filed in the payload. (independently if those are None or not None). You can take a look at `patch_task_instance` that leverages `model_fields_set` to only retrive explicitely set values.

**Comment by ajitg25** [comment]
@pierrejeambrun I have raised a PR for review. PTAL!!
Thank you
