### ISSUE TITLE
Deprecate accessing outlet and inlet events through string in Airflow 3.0

### ISSUE THREAD

**Issue by Lee-W** [apache/airflow#43956]
### Description

as title

### Use case/motivation

Since the introduction of DatasetAlias/AssetAlias and the name attribute to Asset, accessing outlet_events and inlet_evnets has become confusing.

e.g., What should something like the following mean?

```python
   def produce_asset_events_through_asset_alias_with_no_taskflow(*, outlet_events=None):
        bucket_name = "bucket"
        object_path = "my-task"
        outlet_events["example-alias-no-taskflow"]
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Lee-W** [comment]
* PR for adding deprecation warning to v2-10-test https://github.com/apache/airflow/pull/43922
* PR for removing it from Airflow 3 (WIP)

**Comment by uranusjr** [comment]
I’ve decided to hold this for a now. This needs to be done in the 2.x branch, and according to discussions in https://github.com/apache/airflow/pull/44283#discussion_r1854909127, we should hold merging this kind of PRs until 2.10 is finalised. There’s not much point for us to do this right now since the PR won’t be able to be merged immediately. Let’s keep this in the back log and come back when we can actually merge the PR.

**Comment by Lee-W** [comment]
Got it. I'll push my uncommitted local work and then stop working on this one
