### ISSUE TITLE
Add support to filter by dag_id in recent_dag_runs endpoint

### ISSUE THREAD

**Issue by tirkarthi** [apache/airflow#44606]
Also this just makes me realize that `http://localhost:29091/ui/dags/recent_dag_runs?dag_id_pattern=xxxxx` endpoint should most certainly also support a `dag_id` query params or `dag_ids`.

I am affraid that using a `pattern` like this could end up matching multiple dags while we are really trying to get the dag_runs from a specific dag like here.

_Originally posted by @pierrejeambrun in https://github.com/apache/airflow/issues/44074#issuecomment-2482613859_

**Comment by jason810496** [comment]
Hi @tirkarthi , I think this issue is resolve after https://github.com/apache/airflow/pull/44345 is merged:

https://github.com/apache/airflow/blob/main/airflow/api_fastapi/core_api/routes/public/dag_stats.py#L56-L61

After the refactor, we can leverage `FilterParam` and `filter_param_factory` for query parameters with simple logic. By passing `list[str]` to `_type`, we can standardize the format of request query parameters using FastAPI's native features.

**Comment by pierrejeambrun** [comment]
Indeed, now with the refactoring we have tools to achieve that. We still need to add this capability though, so we can close it. 

It's quite straightforward with the new parameter system.
