### ISSUE TITLE
Versions conflicts / pinned versions

### ISSUE THREAD

**Issue by bolkedebruin** [apache/airflow#487]
Some of the versions specified in setup.py are quite old (flask-admin, flask-login come to mind) although it seems that removing that restriction does not end up in issues. This was just determined after a quick glance however. Is there a reason for this?

**Comment by mistercrunch** [comment]
I'm pinning the versions because these libs might eventually break their APIs, sometimes on purpose. Actually what prompted the pinning was flask-login breaking their API on purpose (for pretty much everyone using their lib) and when I posted on their Github they told me that they thought it was absolutely insane to not systematically pin everything. 

My current logic is to trust the package maintainers to not break the API within big version numbers after 1.0.0 and second digit before 1.0.0, so I enable a range from what I use to run unit tests to the next version number where the API might change.
