### ISSUE TITLE
windows support?

### ISSUE THREAD

**Issue by timeisapear** [apache/airflow#489]
Unfortunately many of our production environments are Windows. Has anyone had success installing/running airflow in Windows 7/Server 2008 and up?

**Comment by mistercrunch** [comment]
I'm not sure if the libs we use do support Windows, but if they do it seems like it may not be too hard to support windows. Well I mean for Airflow to be retrofitted to work on windows. It's probably mostly a matter of making sure all file references use `os.path.join` instead of  `FOLDER + "/foo"`.

Though there may be more to it, I haven't touched a Windows server since NT4. I tried to SSH in one for Tableau one time and was told that you couldn't do that.

Airbnb won't be driving Windows support but if someone from the community wants to send PRs in that direction we'll be happy to review / merge them.
