### ISSUE TITLE
What is the easiest way to run custom schema migrations? 

### ISSUE THREAD

**Issue by lumengxi** [apache/airflow#495]
I would like to modify some metadata tables for internal usage. I understand that airflow uses `alembic` for schema migrations, is there a way to have `airflow upgradedb` points to a custom location with migration scripts?

**Comment by mistercrunch** [comment]
Airflow has its own "migrations" folder for its own sake, I wouldn't mix up anything in there. 

Is this for an Airflow plugin? tables used in a pipeline?

**Comment by lumengxi** [comment]
@mistercrunch Yea, I was planning to add a few more columns to the `BaseUser` model, like `roles` etc.

**Comment by mistercrunch** [comment]
I think that'd be very useful for everyone. We probably need the following models:
Role (many to many with User)
Permission (many to many with Role)

The list of permissions could be each UI view, and potentially CRUD related for each model (view / modify).

OR a bolder move would be to migrate the application to use a more complete web framework. I've been using "Flask App Builder" for another project and I love it. It ships with CRUD, authentication, security, localization, bootstrap, charts, icons, ... It's a better fit for Airflow than Flask-Admin (the current CRUD framework Airflow uses).
http://flask-appbuilder.readthedocs.org/en/latest/

I don't think it would be extremely hard to migrate since they're built on the same stack (Flask / Jinja / Bootstrap, ....)

**Comment by lumengxi** [comment]
Nice! `Flask App Builder` looks pretty good. I'd love to take a stab at it to have 1) a richer BaseUser model 2) some layer of web auth (currently I modified `default_login` to work with Google oauth2 for security).

**Comment by mistercrunch** [comment]
Porting to FAB might be easy, I'll try to find time to take a stab at it.

**Comment by gwax** [comment]
I did a little bit of hacking at things on my end and looking at the alembic documentation: http://alembic.readthedocs.org/en/latest/branches.html

If we modify the alembic.ini file in airflow such that it looks for migrations in the airflow root and AIRFLOW_HOME. I'm not sure if this is the right syntax for an alembic.ini file (in my testing, I hard coded AIRFLOW_HOME) but it should be something roughly like:

``` ini
version_locations = %(here)s/migrations %(AIRFLOW_HOME)s/migrations
```

and modify utils.upgradedb so the last line is:

``` python
command.upgrade(config, 'heads') # note the s in heads
```

This should let people set up a migrations/versions folder in their airflow home and branch the metadata db.
