### ISSUE TITLE
SQL Alchemy Connection String - How to store password?

### ISSUE THREAD

**Issue by praveev** [apache/airflow#523]
I would like to use mysql for the SqlAlchemy backend. I understand that I can set the metadata db connection string in airflow.cfg like this:

[core]
sql_alchemy_conn = my_conn_string

or as an env variable like this

AIRFLOW__CORE__SQL_ALCHEMY_CONN=my_conn_string

But in any case, my_conn_string will contain the password in plain text. I am looking for thoughts on how to not store the password in plain text.

I use kerberos, so was thinking it would be nice for airflow to read from a keytab file and get the password at run time.

@mistercrunch

**Comment by mistercrunch** [comment]
We use chef, so that kind of information is stored in an encrypted chef databag and deployed by chef.

**Comment by jlowin** [comment]
Something important to keep in mind: SqlAlchemy URI strings are always passed to the engine as plain text (whether they come from Airflow or any other library). In addition, the password can be viewed (in plain text) in SqlAlchemy at any time, if you know where to look. So while you may use different strategies to securely transmit the password to the machine on which SqlAlchemy is running, once there it becomes potentially visible to anyone with permission to run code in the same environment.

**Comment by bolkedebruin** [comment]
I think this warrants a FAQ entry: not really solvable as long as all airflow's processes have access to airflow's database.

@r39132 can you add this to the FAQ and close this

**Comment by atsalolikhin-spokeo** [comment]
I don't see this in the [FAQ](https://airflow.apache.org/docs/stable/faq.html)  

I am trying to figure out how to store a password in Airflow variable table.  I see from https://github.com/apache/airflow/blob/v1-10-stable/docs/ui.rst#variable-view that Airflow UI won't show the password if the key name has e.g. `api_key` in it, but I also see that the password is stored unencrypted in the Airflow `variable` table.  

I'm also a bit confused because Admin -> Variables list has a column `is_encrypted`, but when I go to add a variable, I am prompted for name and value -- there is nothing about encryption. 

So how do encrypted variables work?
