### ISSUE TITLE
Handling code redeployment when a DAG is running

### ISSUE THREAD

**Issue by praveev** [apache/airflow#555]
I would like to understand how airflow scheduler works when there is a new code push. I have a DAG with 3 tasks: T1 -> T2 -> T3 where T2 is currently being executed.

Will T3 execute after re-deployment?

When there is a new code push I restart webserver, scheduler, worker and flower.  Do I need to restart these services? ( I restart b/c there could be a code change that could affect these services like a change in airflow.cfg or start_date, schedule_interval etc )

I have encountered cases where T3 doesn’t execute but unable to reproduce this consistently.

cc: @mistercrunch @jlowin

**Comment by mistercrunch** [comment]
You shouldn't have to restart anything. Though we had corner cases on the scheduler side that we solved with a shortcut at Airbnb. We fully restart the scheduler every 5 runs to make sure it 100% represents what's in the file system. Corner cases included dag_ids that had moved from a file to another, files getting deleted and the dag_id lingering, ... 

We will address these issues so that no one has to restart the scheduler, but in the meantime you may want to wrap an `airflow scheduler -n 5` (run 5 schedule cycles and exits) command into a bash script or something like runit that restarts it as soon as it's done.

No need to restart flower.

As far as the web server goes, you may need to hit the refresh button on the main page, it's the rightmost  icon on the DAGs table view. This "expires" the DAG, meaning that the webserver(s) will see that they loaded the DAG before that expiration date and reload it, assuming that it's still in the same file where it found it originally.

**Comment by praveev** [comment]
Thanks. I'll change it to not restart anything. But to confirm, so scheduler restart could cause T3 to not execute?

**Comment by mistercrunch** [comment]
Restarting the scheduler should never be a problem.
