### ISSUE TITLE
Tree view can't display

### ISSUE THREAD

**Issue by alvin1** [apache/airflow#593]
Hi,

I'm using Airflow v1.5.1. This week I got a small problem with the WebUI.
There're 6 dags listed in Dags page. And some dags had success running more than 14,000 tasks I called dag A here. 
There's a dag only success running more than 100 tasks and I called dag B here.
I can't open dag A's tree view but dag B's tree view can open quickly. And the other view of dag A working fine.
I had to clear all the task status of dag A, and then the tree view can be open.

How to resolve this issue with out clear task status?

**Comment by mistercrunch** [comment]
How many tasks has the DAG? Also note that the tree view has trouble when the shape of the DAG converges and expands, exploding the number of paths while computing the tree view. 

A workaround is to filter on the graph view and pivot into the tree view.

Long term fix would be to change the d3/javascript to receive a graph data structure instead of a tree data structure and be more dynamic. I don't think that will be on top of the priority list very soon...

**Comment by alvin1** [comment]
Sorry for the incorrect information. The actually situation is DAG A can open tree view but Dag B can't. Dag A have 46 tasks and Dag  B only have 7 tasks

**Comment by mistercrunch** [comment]
Still a problem? What browser are you using?

**Comment by alvin1** [comment]
Sorry for the delay. I use chrome

**Comment by bolkedebruin** [comment]
@alvin1 if this is still an issue with recent airflows please create a Jira issue for it.
