### ISSUE TITLE
How to use xcom to pull values from previous run

### ISSUE THREAD

**Issue by cwong99** [apache/airflow#596]
I will have to refer value that the job stored for the previous run.  I saw that there is 'include_prior_dates' option on xcom_pull.  I set that to True, but am still getting only one value from the current execution.
Can you explain how I can use it to pull values from the previous executions?

**Comment by mistercrunch** [comment]
cc @jlowin

**Comment by jlowin** [comment]
@cwong99 can you post your code? `xcom_pull()` gets the most recent matching XCom, so if you are getting one from the current execution it sounds like you are calling `xcom_push` _before_ `xcom_pull` (because that would push the current value as the most recent one). Try pulling the previous XCom at the beginning of your function and pushing the current one at the end.

For example:

``` python
def fn(ti, **_):
    # first get previous value
    ti.xcom_pull(..., include_prior_dates=True)
    # do stuff
    ...
    # then push latest value
    ti.xcom_push(...)
```

**Comment by portah** [comment]
If you are derived from BaseOperator, you can use something like this:

```
        upstream_task_ids = [t.task_id for t in self.upstream_list]
        upstream_data = self.xcom_pull(context=context, task_ids=upstream_task_ids)
```

**Comment by cwong99** [comment]
Thanks for the info
