### ISSUE TITLE
'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by tostasqb** [apache/airflow#61]
Running through the [Quickstart](http://pythonhosted.org/airflow/start.html) page right about the line that says:

```
pip install airflow
```

I get the following error:

```
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_hugo/pandas
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
```

It happens both on ubuntu 14.04 and Centos 7 at least...

**Comment by artwr** [comment]
Hi @tostasqb, 
It looks to be more an issue with pip and the numpy install (which is a required package for airflow).
Maybe following [this](http://stackoverflow.com/questions/26473681/pip-install-numpy-throws-an-error-ascii-codec-cant-decode-byte-0xe2) might solve it?
 What happens if you upgrade pip in a virtualenv and retry the install?

**Comment by artwr** [comment]
Apparently installing the system python-dev package for python 2.7 may be of help.
I hope this helps. Let us know if you encounter more problems.

**Comment by tostasqb** [comment]
Installing python-numpy, as the first link suggests takes care of this issue although the default version of numpy still has incompatibilities. I'll be closing this for now. I Appreciate the help.
