### ISSUE TITLE
Building EC2 Container Service Operator

### ISSUE THREAD

**Issue by pedrorjbr** [apache/airflow#649]
I am developing a EC2 Container Service Operator and I really don't know if it is the right place to ask some development questions about airflow. I would like to contribute.

For building this operator:
1. Extends BaseOperator
2. Implements a Hook for AWS. I see that exists a S3 Hook already, but i was thinking in create a AWS hook, for all aws services.

Comments, opinions, recommendations?

**Comment by artwr** [comment]
@pedrorjbr, I have been thinking of overhauling our s3_hook by using [boto3](https://github.com/boto/boto3). I think this is the library we should use. Because of the very diverse nature of AWS services, I highly recommend we create a hook per underlying service to avoid confusion about where data might be sent or were work might be done. I could create a BaseBoto3Hook that imports the boto3 package and sets up some of the authentication and you could build the container service hook on top. How does that sound?

**Comment by pedrorjbr** [comment]
@artwr  It sounds great!Plz push BaseBoto3Hook.  I already make a pull request, and i going to update it. I am having difficult how can i make a test case for ECS. I need a task definiton on AWS enviroment. Any ideas?

**Comment by pedrorjbr** [comment]
@artwr  Do u have any idea how can I test ECS task? I saw in the source code that S3 Hook operator is not been test, just the s3 url.

**Comment by pedrorjbr** [comment]
@artwr  Hello! Do u have already developed the s3_hook?

**Comment by bolkedebruin** [comment]
implemented afaik. please open jira if issue persists.
