### ISSUE TITLE
BUG: Why does clearing a DAG make it start running from EARLIER than the start_date?

### ISSUE THREAD

**Issue by jasminetsai** [apache/airflow#732]
We've been testing a dag whose config has a `start_date` from Nov 27, 2015.
We changed the DAG structure by adding two additional tasks, so as part of testing we just cleared all the DAG runs and task metadata (cleared task upstream and downstream)
But when the DAG started running again, it started running from Nov 24, 2015, instead of the specified date. Why would this happen?

Another question is sometimes when we clear failed tasks and try to re-run, the tasks which have `depends_on_past`=True just simply doesn't run. It seems like it's because the FIRST of those tasks doesn't get triggered automatically, so all subsequent ones don't either. If we ran a manual backfill of that DAG on that date, things will start running again.

Here are some screenshots:

<img width="762" alt="screen shot 2015-12-04 at 6 47 03 pm" src="https://cloud.githubusercontent.com/assets/1663847/11605548/9740d262-9ab7-11e5-9d69-77ade54af4bb.png">

<img width="581" alt="screen shot 2015-12-04 at 6 47 19 pm" src="https://cloud.githubusercontent.com/assets/1663847/11605545/877843ec-9ab7-11e5-854f-e16847e49102.png">

**Comment by mistercrunch** [comment]
If no DagRun and task instances exist for a DAG, the first DagRun gets seeded on the min(start_date). 

If there are task instances, the first DagRun is created a few runs before the most recent task instance (5 I believe). This was an arbitrary attempt at keeping the flow when people migrated from `1.4` to `1.5`. It's not perfect, but it worked for most of our 100+ DAGs with little work.

I'm guessing that when you cleared everything, you might have left some orphan task instances behind. Task instances linked to task_ids that are no longer. Anyhow, we shouldn't account for those when getting the set of tasks but we do. You can see those on the "Task Instances" view in the UI, they'll show up there even if the tasks have been removed from your DAG.

Here's a link to the related code:
https://github.com/airbnb/airflow/blob/master/airflow/jobs.py#L378

A line that would say `.filter(TI.task_id.in_(DAG.task_ids))` would help disregarding the orphan task_ids...

The `depends_on_past` logic is somewhat easy to understand though sometimes tricky to deal with. Those tasks depend on the success of their immediate previous instance, except for the start_date since it needs to start somewhere AND for the start_date of a backfill command since otherwise your backfill may never start.

**Comment by jasminetsai** [comment]
Seems like its only for tasks where depends_on_past is not true.
<img width="323" alt="screen shot 2015-12-04 at 8 20 39 pm" src="https://cloud.githubusercontent.com/assets/1663847/11606007/b9955e10-9ac5-11e5-9d5e-753571d16ad4.png">

**Comment by jasminetsai** [comment]
Ok, that makes sense -- is there any reason to keep that code around right now?
Also, it seems like it only schedules extra tasks for where depends_on_past is not True?

**Comment by mistercrunch** [comment]
Yes, we still need the code as people may still be migrating. 
I'm not sure what you mean in your second statement, but depends_on_past does force a sequential execution
