### ISSUE TITLE
Run DAG in the past?

### ISSUE THREAD

**Issue by ksonj** [apache/airflow#758]
airflow certainly looks like a very interesting project and I'm definitely gonna have a closer look at it. Playing around a little bit I've had some issues though. For instance, why does the scheduler run the `tutorial` DAG like a hundred times? Or put differently: why would I want to run DAGs as if that run happened in the past? From what I've read around the webs, that seems to be what people expect, although to me it looks like a bug.

**Comment by mistercrunch** [comment]
ETL or batch processing in the data world is often differential loads. Each run loads a specific time period. So you may want to backfill, in which case there's a backfill command in the CLI.

You can also set the start_date at the DAG level or for each task. 

For the example we set the start_date a week in the past so that we can demonstrate how the scheduler works and how it can catch up.

**Comment by mistercrunch** [comment]
There's also externally triggered DAG if your workload isn't not on a schedule.
