### ISSUE TITLE
Scheduler functionality to run tasks at start of coverage period

### ISSUE THREAD

**Issue by toryhaavik** [apache/airflow#777]
From the documentation:

```
Note that if you run a DAG on a schedule_interval of one day, the run stamped 2016-01-01 will be trigger soon after 2016-01-01T23:59. In other words, the job instance is started once the period it covers has ended.
```

We would be interested in a feature that tells the scheduler to run at the beginning of the job's covered period, rather than the end.  As soon as the clock ticks over to midnight, the scheduler kicks off the task, based on a DAG parameter.

I _believe_ a workaround for this would be to use `{{ tomorrow_ds }}` rather than `{{ ds }}` so that the task that gets started by the scheduler `soon after 2016-01-01T23:59` processes `2016-01-02` data.  However, I think this would cause problems with tasks that are started by anything other than the scheduler.  For example, I believe running `airflow run dag_id task_id 2016-01-02` would then actually act upon data for `2016-01-03`, but I am not certain.

It would be nicer to be able to just specify what part of the schedule interval "boundary" you want to be the trigger for the task.

**Comment by jihygk** [comment]
+1 this

**Comment by mistercrunch** [comment]
I think that supporting both is confusing. Especially if an environment can be heterogenous in that regard on a per-dag or per-task (crazy!) basis. Also swapping from one way to another would offset (and mess up) the recorded state. 

I think it's easier to just align on this way of doing things. Left bound makes most sense to me.

Just think about that one statement in the docs being rewritten to take the optional approach: `Note that if you run a DAG on a schedule_interval of one day, ... BUT if you're not happy with that you can mess with the "date_achor_bound" (left|right) parameter in your airflow.cfg and get it to behave in a different way where the run for the 2015-01-01 rerpresents the run that should have started on that date where exectuion_date actually references 2014-12-31`. 

You'd read that and be like "damn. how is my environment set up? what's the default? should I change it? should I start an internal debate about this?"

**Comment by toryhaavik** [comment]
Thanks for the feedback.  I admit I don't fully understand the internals of the scheduler.  But it doesn't necessarily need to a be a binary like `left|right`, though.  Couldn't the dag have a setting called `scheduler_wait` or something that is a `timedelta` that defaults to be equal to the `schedule_interval` but could be set to anything?  The scheduler would just do an extra time calculation to see whether it should trigger a `DagRun` for that dag.

**Comment by jihygk** [comment]
@toryhaavik I think you can use the TimeDeltaSensor operator for this, although it doesn't currently seem to work with DAGs with no `schedule_interval` parameter. Also TimeSensor but I read somewhere that it will be deprecated in the future. See https://groups.google.com/forum/#!searchin/airbnb_airflow/timedeltasensor.

@mistercrunch Thanks for your feedback. I guess the difference in convention about 'gaps' in intervals causes the confusion for me. I interpret the execution dates of runs/tasks as 'points' in time where as you see it as 'intervals'.

**Comment by DevJac** [comment]
@jihygk You said "I think you can use the TimeDeltaSensor operator for this", what are you referring to? (The word "this" can refer to a few different things in the conversation.)

The original post was asking for a way to run tasks inside their scheduled "period", rather than after the period has ended (as is the current behavior). Are you saying that a negative TimeDeltaSensor would allow this?

About the original post: I agree strongly. As a newcomer to Airflow the fact that tasks run after their period has ended has been my biggest source of confusion. As an Airflow user I am focused on creating tasks and DAGs, and it's confusing that the `start_date` is not the date that my DAGs will start running, but the day before. Is this the default behavior for legacy reasons, or do the Airflow authors believe this is the optimal behavior? Will the original suggestion in this thread ever be implemented? Would a PR to change this behavior be accepted?

**Comment by bolkedebruin** [comment]
I think this is more suitable for the mailinglist to be discussed. Closing for now.
