### ISSUE TITLE
End-to-end DAG testing

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7907]
**Description**

This is the placeholder issue for the End-to-end DAG testing framework that we are proposing to make airflow more robust.

**Use case / motivation**

**Related Issues**

Copied from https://issues.apache.org/jira/browse/AIRFLOW-79

**Comment by nikste** [comment]
any news on this?

**Comment by mik-laj** [comment]
@nikste I know a lot of organizations are working on solutions internally, but there is no community progress.

**Comment by nikste** [comment]
@mik-laj thanks for the update, i think it would make a lot of sense to have some easy end-to-end testing (I would definitely find it useful :) )

**Comment by mik-laj** [comment]
@nikste  What specific E2E tests would be of interest to you?  In my case, E2E tests mean the configuration of a separate test environment, services that are used to monitor the cluster, and then running several DAG Runs. As a result, we get information about the DAG status, but also performance metrics.

**Comment by nikste** [comment]
Sorry, this somehow drowned in other messages.
So, I have a DAG and some specified input, and i expect a certain output. I want to run all operators end to end.

Currently I'm trying to write some unit test in python that will mock over the some configuration,
and then I also want to overwrite some input paramters in `dag_run.conf`. 
This seems to be super cumbersome, since i did not find a way yet to both mock `Variables.get, `BaseHook.get_connection` and trigger a dag in the python unit test, where i can specify the `dag_run.conf`.
Is there some further documentation on how Airflow works internally (I'm suspecting it starts different processes that overwrite the mocks?) 
Or maybe I'm just not doing this the way it was intended to be done?
