### ISSUE TITLE
Passing network and config/secret to DockerSwarmOperator 

### ISSUE THREAD

**Issue by PriOliveira** [apache/airflow#7955]
I've been searching how to pass a network to a DockerSwarmOperator but in the docs there's only mention of `network_mode`.
Configs/secrets aren't even mentioned. 
Am I missing something? 

I'd like that a DockerSwarmOperator task was part of a network different than the default one in Docker Swarm. 
And also pass some defined Docker config or Docker secret to it.

**Comment by RosterIn** [comment]
maybe @akki knows

**Comment by akki** [comment]
I don't think passing network is currently supported by `DockerSwarmOperator`.

Can you find this feature in [Python Docker API](https://docker-py.readthedocs.io/en/stable/api.html) ?
If yes, it should be plausible to support this feature via `DockerSwarmOperator` as well.

In general, anything supported by the Python Docker API can theoretically be integrated into `DockerSwarmOperator`. For example, support for `tty` was added in https://github.com/apache/airflow/commit/7ab9e957d3ade7af607b597592b624c9e4951b73.


BTW the `network_mode` mentioned in the issue seems to be from the [`DockerOperator`](https://github.com/apache/airflow/blob/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/docker/operators/docker.py#L80) not the [`DockerSwarmOperator`](https://github.com/apache/airflow/blob/3c4ca62af11e84fc7c09428642d09055b704c576/airflow/providers/docker/operators/docker_swarm.py).
