### ISSUE TITLE
Does airflow handle memory management ?

### ISSUE THREAD

**Issue by afarbos** [apache/airflow#8]
I didn't any ui pictures about that.

**Comment by mistercrunch** [comment]
Nope. Celery does not support sandboxing or any sort of containment. We are considering writing a YarnExecutor and using docker containers in the future. BaseExecutor is easily extensible, so someone could write a MesosExecutor for instance. 

For now it's a matter of making sure that operators shouldn't spin up too many threads, use too much memory or use too much disk. Since Airflow is mostly orchestrating workload that takes place in external systems, Airflow workers have been very healthy. We've had one incident were a bad operator fill up the disk on some workers which created a small outage.
