### ISSUE TITLE
Scheduler keeps throwing exceptions for removed dags

### ISSUE THREAD

**Issue by Tjorriemorrie** [apache/airflow#800]
I keep getting various and loads of the following type of exceptions:

```
2015-12-21 14:03:16,697 - root - ERROR - Task import_dataflow_new_customer not found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 552, in _execute
    self.manage_slas(dag)
  File "/usr/local/lib/python2.7/dist-packages/airflow/utils.py", line 354, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 292, in manage_slas
    ti.task = dag.get_task(ti.task_id)
  File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 2199, in get_task
    raise AirflowException("Task {task_id} not found".format(**locals()))
AirflowException: Task import_dataflow_new_customer not found
```

As we are developing our workflow we are renaming various dags, but these old and removed dags are now being thrown as exceptions by the scheduler. It's extremely irritating and there doesn't seem to be a way to clear it out. Shouldn't the scheduler automatically ignore tasks when the dag is removed?

**Comment by r39132** [comment]
Hi @Tjorriemorrie
Without knowing the exact details of your problem, I'll try to answer what I think your issue is.
I've found the following works.

Let's say that you have a DAG file `my_first_dag.py` that is imported by both the scheduler and webserver. At Agari, we use local executors and run a single scheduler with local executors as well as the webserver on the same (single) EC2 instance. 

Let's also say that your dag_id is `my_first_dag_v1`. You can always wipe out your old DAG and its history while simultaneously importing a new DAG by 1) changing `my_first_dag_v1` to `my_first_dag_v2` in your `my_first_dag.py` file and 2) restarting both webserver and scheduler. The result will be a new DAG with no history and the name of the DAG (i.e. the dag_id) will now be `my_first_dag_v2`.

If you ever want to change the name of a DAG file, then you should change both the dag_id and the DAG file name. If you just change the DAG file name, but keep the dag_id the same, there will be a problem. 

So, in the example above, your new file and dag_id could be `blah_blah_dag.py` and `blah_blah_dag_v1`, respectively.

**Comment by Tjorriemorrie** [comment]
That's interesting: why would it matter if the DAG filename is changed? Shouldn't airflow only care about the ID?

**Comment by r39132** [comment]
Not sure, but did it resolve your issue?

```
                      Table "public.dag"
       Column       |            Type             | Modifiers 
--------------------+-----------------------------+-----------
 dag_id             | character varying(250)      | not null
 is_paused          | boolean                     | 
 is_subdag          | boolean                     | 
 is_active          | boolean                     | 
 last_scheduler_run | timestamp without time zone | 
 last_pickled       | timestamp without time zone | 
 last_expired       | timestamp without time zone | 
 scheduler_lock     | boolean                     | 
 pickle_id          | integer                     | 
 fileloc            | character varying(2000)     | 
 owners             | character varying(2000)     | 
Indexes:
    "dag_pkey" PRIMARY KEY, btree (dag_id)

```

I do see the fileloc set in the dag table. You can try changing the file name, restart the webserver and scheduler, and query the airflow db's `dag` table to see if fileloc column is updated.

**Comment by Tjorriemorrie** [comment]
Not really:

> StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back

but thanks for your help, appreciate it.

**Comment by bolkedebruin** [comment]
@Tjorriemorrie is thi still an issue? Can you please create a Jira for it, if so? Will close here for now
