### ISSUE TITLE
[AIP-31] Enable arbitrary XCom class

### ISSUE THREAD

**Issue by casassg** [apache/airflow#8059]
**Description**

- Enable custom XCom backend functionality for custom serialization/deserialization.
- XCom backend can be set from airflow.cfg and defaults to existing `airflow.models.XCom`. 

**Use case / motivation**
This comes from a discussion with @turbaszek . We were talking that it would be nice to have a flexible XCom backend that allowed us to serialize/deserialize XCom values using custom logic. A possible extension here would be to enable large objects to be serialized into a custom file system while XCom would only include a pointer (and metadata) of the object in the file system. 

An example use case would be data processing:

```

@task
def process_data(input: pd.DataFrame) -> pd.DataFrame
   # make some magic
```

Where DataFrame are saved between tasks as `csv`.

This is probably a stretch and maybe out of scope for this AIP (or require a new AIP). But wanted to put this out there.

**Comment by turbaszek** [comment]
Thanks @casassg for putting this into an issue! 
 
The idea comes from DAGs where we have two operators:
- OP1 that does: upload from API and put file on GCS
- OP2 that does: download from GCS and do something

Abstracting this layer of writing to and reading from persistent storage will make writing functional operators much easier. Because then my function will be called `process_data` not `download_and_process_data`.  That's why I think it's related to UX of functionals operators

**Comment by kaxil** [comment]
+1 to Making Xcom backend pluggable with the default of `airflow.models.xcom.XCom`
