### ISSUE TITLE
 In BREEZE.rst the command to create a user is outdated.

### ISSUE THREAD

**Issue by ghost** [apache/airflow#8086]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

**What you expected to happen**:
BREEZE.rst contains outdated command to create a user

**How to reproduce it**:

**Anything else we need to know**:

**Comment by mik-laj** [comment]
Could you write some more?  I would be happy as if you immediately updated it in the documentation You can do this from Github Web UI.
![Screenshot 2020-04-03 at 07 10 25](https://user-images.githubusercontent.com/12058428/78326324-65a51900-757a-11ea-85cc-6d00637da506.png)
https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by ashb** [comment]
The command is currently

```
airflow users create --role Admin --username admin --password admin --email admin@example.com --firstname foo --lastname bar
```

Which is the correct command for the master branch. I'm going to close this as I believe this command is correct. If you think it is wrong please comment and say what it should be. Note on the master branch the commands have been reorganized since the 1.10 release branch.
