### ISSUE TITLE
dag will never start if we set a cron string with a clear day of week to  the schedule_interval  arg 

### ISSUE THREAD

**Issue by forbxy** [apache/airflow#8237]
dag like this
```
dag = DAG(
    dag_id='sch_test',
    default_args=args,
    schedule_interval='12 14 * * 5',
    dagrun_timeout=timedelta(minutes=60),
    tags=['bxy']
)
```

**Comment by khyurri** [comment]
Could you provide more information on how you run this DAG and what do you expect?

You write that you have a "clear day of week", but in the CRONTAB, the day of the week is the last value. In your case, it is `5`, that means `Friday`.

**Comment by forbxy** [comment]
yes，dag never run at Friday or any day ，if i set a range of weekdays , like 1-5，it works. I think u can easily  to recurrent it ，just set  schedule_interval='12 14 * * 5'

**Comment by khyurri** [comment]
Bug confirmed at 1.10.10 with celery executor. 
If i've got time tomorrow, I'll try to explore it tomorrow.

**Comment by khyurri** [comment]
**How to reproduce**

I set the value of `schedule_interval = '52 11 * * * '`, then I expect DAG will execute every day at 11:52 after the date of `start_date`.

```python
start_date=datetime(year = 2020, day = 11, month = 4, hour = 0, minute = 0) #yesterday
timezone.utcnow() #2020-04-12 12:47:37.304143+00:00
```

I expect the DAG will execute twice (2020-04-11 11:52:00 and 2020-04-12 11:52:00). But only one execution was obtained. 

**Where is the problem?**

The problem is in the `SchedulerJob.create_dag_run` method, in the condition `if next_run_date and period_end and period_end <= timezone.utcnow()`.
The variable `period_end` gets value `next_run_date + interval`. In the last run It is always greater, than `timezone.utcnow()`.

To fix this task, I will need to understand in detail how `period_end` and the condition` period_end <= timezone.utcnow () `should work.
If no one else takes this issue, I can do it at the end of the next week.

**Comment by ashb** [comment]
> I expect the DAG will execute twice (2020-04-11 11:52:00 and 2020-04-12 11:52:00).

This is not currently how the scheduler operates -- the task is not scheduled until _after_ period is over, so period for 2020-04-12 11:52:00 will be scheduled at-or-just-after 2020-04-13 11:52:00.

_Currently_.

[AIP-39](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-39+Richer+scheduler_interval) has just been accepted and we will start working on this, and that will give the ability to have this kind of behaviour.
