### ISSUE TITLE
airflow clear leaves dag_runs

### ISSUE THREAD

**Issue by abridgett** [apache/airflow#829]
Doing some testing and wondering why max_active_runs=1 wasn't behaving, it looks like it's because "airflow clear -c -d -s 2016-01-03 dagid" is only cleaning task_ids not dag_runs.

DAG:clear does have a "reset_dag_runs" parameter (which isn't set by the CLI) but it defaults to true.  However that calls set_dag_runs_state.  That function doesn't look quite right - it doesn't seem to limit dates and it looks like it sets them all to RUNNING which seems odd.

**Comment by mistercrunch** [comment]
`set_dag_runs_state` does limit dates to the range specified. It sets dag runs as running since clearing is typically used in order to re-run jobs. You can almost think of clear as a way to get the scheduler to re-run what you clear.

You either clear a failed state after you fix the issue and want it to re-run, or you clear a success state because it was a false positive or something has changed that requires re-running the task.

I'm not sure where to clarify that in the UI / CLI / docs. Let me know if you have input.

**Comment by abridgett** [comment]
I see, it doesn't look like there's an easy way to get that to play nicely with max_active_runs (ATM I'm stopping the scheduler, then "airflow clear", psql to delete dagrun, then start scheduler). Is there a reason why we those dag_runs to RUNNING rather than deleting them (won't the scheduler repopulate them anyway?)  They do disappear from the UI (tree view).

Each day reuses the same resources (directories etc), pooling and depends_on_past don't help - only max_active_runs does (tasks are roughly "delete directory", "product output into directory", "upload directory").  Maybe I need to use the external task sensor as per 768.

**Comment by bolkedebruin** [comment]
@abridgett Can you create a Jira for this issue please?

**Comment by abridgett** [comment]
Sure thing - https://issues.apache.org/jira/browse/AIRFLOW-78 created
