### ISSUE TITLE
Support Duration in AwsHook when using assume role

### ISSUE THREAD

**Issue by snazzyfox** [apache/airflow#8301]
**Description**

Boto3 `assume_role` [supports a `DurationSeconds` option](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html#STS.Client.assume_role) to generate assumed role credentials valid for a specified duration, instead of the default of 1 hour. 

Airflow should also support specifying this option for `AwsHook`.

**Use case / motivation**

When an `AwsHook` is created with a connection that specifies a role, the hook internally calls STS and generates temporary credentials to use. These credentials are always valid for one hour since the hook does not pass the `DurationSeconds` parameter. 

Many airflow AWS operators perform long-polling, such as `ECSOperator` (to wait for task completion), `AwsAthenaOperator`, `DynamoDBToS3Operator` (to stream data in chunks), and many more. These operations can run for more than one hour on larger jobs. 

Since the credentials generated at hook creation time is only valid for one hour, these jobs will fail one hour after start because credentials in the hook are no longer valid. 

**Proposal**

Add a `duration_seconds` attribute to connection extras for AWS Connections. In AwsHook, if using assumed role credentials and this extra exists, pass it through to the boto3 `assume_role` call.

**Related Issues**
None found

**Comment by mik-laj** [comment]
Would you like to work on this issue?  Apache Airflow is an open-source project without paid technical support. Each problem is solved by community members - other Airflow users. If this issue is important to you, it is best to take action yourself.
If you are interested, I invite you to read:
Contributor Guide: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst
Development Environment Guide: https://github.com/apache/airflow/blob/master/BREEZE.rst
Testing Guide: https://github.com/apache/airflow/blob/master/TESTING.rst

I hope this information will be helpful for you and I look forward to your PR.

**Comment by snazzyfox** [comment]
After digging a little into the code, it appears that #7619 introduced the ability to set arbitrary kwargs for the assume role function call. That solves this issue, but the change is only on master. Any chance we can backport it to 1.10?

**Comment by mik-laj** [comment]
We don't cheery pick new changes related to operators to Airflow 1.10, but we want to release operators from Ariflow 2.0 as a pip package.
More information: https://github.com/apache/airflow/blob/master/README.md#using-hooks-and-operators-from-master-in-airflow-110

**Comment by Falydoor** [comment]
@snazzyfox: were you able to change the role session duration to more than 1h in Airflow 1.10.X?  I might have to update to 2.X unless there is a way for 1.10.X

**Comment by mik-laj** [comment]
We support the refreshable credentials on Airflow 2.1. https://github.com/apache/airflow/pull/16771
