### ISSUE TITLE
BingAds to Google storage

### ISSUE THREAD

**Issue by KevinKobi** [apache/airflow#8303]
**Description**

I'm interested in getting BingAds data into GCS using Airflow
SDK for python is available: https://github.com/BingAds/BingAds-Python-SDK
https://pypi.org/project/bingads/

**Use case / motivation**

Getting data from Bing

**Related Issues**

None

**Comment by mik-laj** [comment]
Would you like to work on this issue? Apache Airflow is an open-source project without paid technical support. Each code is contributed by community members - other Airflow users. If this issue is important to you, it is best to take action yourself.
If you are interested, I invite you to read the following guides:
Contributor Guide: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst
Development Environment Guide: https://github.com/apache/airflow/blob/master/BREEZE.rst
Testing Guide: https://github.com/apache/airflow/blob/master/TESTING.rst

I hope this information will be helpful for you and I look forward to your PR.

**Comment by KevinKobi** [comment]
Sadly I don't have the time. We are even paying to a company to bring the data for us due to lack of time to work on the ETLs from scratch.

**Comment by mik-laj** [comment]
If you are looking for Airflow experts who can write integration and help with Airflow, I can recommend my company. 
@turbaszek, @potiuk and me are most active Airflow contributors last time
https://github.com/apache/airflow/graphs/contributors

If you have questions, feel free to contact kamil.bregula@polidea.com.

**Comment by eladkal** [comment]
this is actually a request to add a new provider bing.ads
If anyone wants to implement it I suggest first to read the mixed-governance model:
https://github.com/apache/airflow#release-process-for-providers

Closing for now till someone will commit to it and explain the value of such provider
