### ISSUE TITLE
AAD Authentication 

### ISSUE THREAD

**Issue by anayyar82** [apache/airflow#8378]
How to add or  introduce AAD auth to an Azure workspace.

**Comment by mik-laj** [comment]
Github Issue is not used to ask questions, so it's for a new feature request. Apache Airflow is an open-source project without paid technical support. Each problem is solved by community members - other Airflow users. If this issue is important to you, it is best to take action yourself.
If you are interested, I invite you to read the following guides:
Contributor Guide: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst
Development Environment Guide: https://github.com/apache/airflow/blob/master/BREEZE.rst
Testing Guide: https://github.com/apache/airflow/blob/master/TESTING.rst

I hope this information will be helpful for you and I look forward to your PR.
