### ISSUE TITLE
PostgresToGCSOperator doesn't convert DATE correctly

### ISSUE THREAD

**Issue by KevinKobi** [apache/airflow#8387]
**What happened**:

Time datatypes are treated as datetime in the operator this create problems when dumping to csv (so can be loaded to BigQuery) because the data will be date type yet bigquery will expect datetime format.

**How to reproduce it**:
dump DATE column to csv using the operator and create a table from it in bigquery. The column will not be of DATE format.

**Anything else we need to know**:

probably need fix at https://github.com/apache/airflow/blob/master/airflow/providers/google/cloud/operators/postgres_to_gcs.py#L46 changing it from `TIMESTAMP`  to `DATE` as:
```
  Date                  -> 1082
  Time                  -> 1083
  Timestamp             -> 1114
  TimestampWithTimeZone -> 1184
```
https://github.com/psycopg/psycopg2/blob/master/psycopg/pgtypes.h#L41

and make some adjustments in `convert_type` function.

**Comment by mik-laj** [comment]
The proposed change looks good. I think it's worth testing this problem with system tests.

A system test is a type of test that uses an example DAG and communicates with a real service. Example DAGs for operators for GCP are available:
https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags
The system tests are available:
https://github.com/apache/airflow/tree/master/tests/providers/google/cloud/operators
Files with system test have prefix "_system.py"
Here is a good example of system tests for transfer operator: 
https://github.com/apache/airflow/blob/master/tests/providers/google/cloud/operators/test_presto_to_gcs_system.py

Would you like to work on PR? Apache Airflow is an open-source project without paid technical support. Each problem is solved by community members - other Airflow users. If this issue is important to you, it is best to take action yourself.
If you are interested, I invite you to read the following guides:
Contributor Guide: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst
Development Environment Guide: https://github.com/apache/airflow/blob/master/BREEZE.rst
Testing Guide: https://github.com/apache/airflow/blob/master/TESTING.rst

I hope this information will be helpful for you and I look forward to your PR.

**Comment by RobGoretsky** [comment]
I will take a look!

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hello,
Is this still available?

**Comment by eladkal** [comment]
@vijaya-lakshmi-venkatraman yes - assigned to you

**Comment by RobGoretsky** [comment]
@vijaya-lakshmi-venkatraman - Thanks for taking this one over!  I had started looking at it, but was unclear on proceeding given that it seems the same code in `sql_to_gcs.py` is used to export CSV, JSON, and Parquet formats.  I wasn't sure if changing the way dates are exported for CSV would break export for those other formats.

**Comment by eladkal** [comment]
Recently https://github.com/apache/airflow/pull/20807 was merged. 
It added a generic `SqlToS3Operator` and deprecated `MySqlToS3Operator`.

I would say that probably the best thing to do is to implement similar generic operator for Gcs
cc @mariotaddeucci

**Comment by eladkal** [comment]
https://github.com/apache/airflow/pull/22536 might have solved this.
@pierrejeambrun can you confirm?

**Comment by pierrejeambrun** [comment]
Normally it does indeed solve this issue. In my test I could export and then load in bigquery each of these different fields.
