### ISSUE TITLE
Use exec instead of subprocess for webserver command

### ISSUE THREAD

**Issue by ybendana** [apache/airflow#852]
Stopping the webserver using systemd only kills the parent process but leaves the gunicorn master and workers around, similar to what was reported with [gunicorn+supervisor](https://github.com/benoitc/gunicorn/issues/520). It appears the problem is related to running gunicorn with subprocess.Popen in cli.py instead of os.exec which would replace the process under control by systemd.

**Comment by mistercrunch** [comment]
Oh interesting we have the same problem while using runit with chef. This is clearly beyond my field of competency. The solution on our side was to `pkill gunicorn` when the process gets stopped which is not clean but got us this far...

I'm open to trying `os.exec` or anything that will clean subprocesses!

**Comment by bolkedebruin** [comment]
Interesting indeed we also saw that behavior. I can prepare a PR

**Comment by mistercrunch** [comment]
I noticed a year or so ago that CTRL-C had a different effect then our process manager was using. CTRL-C was killing the sub processes but `sudo sv stop airflow_service` didn't. I looked a bit into the different signals (SIGTERM, SIGINT, ..) and the Python signal module but didn't figure it out in a half day or so and got frustrated, resorted to an os level approach featuring `pkill`. 

I'd love for someone to figure this out.

**Comment by bolkedebruin** [comment]
Ok the issue is that gunicorn forks. This way signals (ie. SIGKILL) are not being passed to the children. Thus you need a way to track the PID of the process group of the children. `os.exec` is not the right way to do this as it is deprecated. However, normally you can solve this by passing `os.preexec_fn=os.setsid` to `subprocess.Popen` but this only works when executing as root as it breaks some assumed requirements. There are two solutions to this:
1. Let airflow run gunicorn, store its PID in a file (ie. /var/run/airflow-webserver.pid) and exit immediately. This how most daemons are run and init.d scripts and systemd know how to handle this. However it might break some assumptions around airflow how it is currently run.
2. Create a signal handler in airflow that manages the gunicorn process and passes the signals. This is more complex but keeps the way airflow currently works.

I'm in favor of option 1 as it is more standard, I'll see if I can keep current behavior by including a flag (-f for foreground or something like that). Please let me know if option 2 seems more logical.

**Comment by bolkedebruin** [comment]
@ybendana can you please test the PR?

**Comment by bolkedebruin** [comment]
@mistercrunch I am slightly worried that some other subprocess might also need some work (celery workers?). I didn't check though.

**Comment by ybendana** [comment]
The PR resolves the issue, thanks!  Just a couple of things: 1) the tmpfiles.d-airflow.conf should probably be renamed to airflow.conf to be consistent with the other files in /usr/lib/tmpfiles.d. 2) Add note in doc to create /run/airflow if it doesn't exist and set owner to airflow:airflow.

**Comment by bolkedebruin** [comment]
@ybendana thanks @mistercrunch PR-#855 is done

**Comment by t1m0thy** [comment]
I have the same problem with zombies in supervisor.  The only issue with PR-#855 is that the fix to this issue would only work for systemd users I believe.  It might be more of a universal solution to use an os.exec\* variant instead of Popen as suggested above, or to utilize a signal handler to relay signals to the gunicorn child.  Then the PR-#855, which daemonizes airflow webserver by default, could be handled as a separate issue.

**Comment by amerkel2** [comment]
I can confirm that PR-[#855](https://github.com/airbnb/airflow/pull/855) does not really solve the issue with supervisor, as supervisor is explicitly designed to handle processes in the foreground. And I agree with @t1m0thy that the PR introducing daemon behavior is orthogonal to how running the webserver in the foreground is done. The argument against using `os.exec*` was that it is deprecated, but is that really the case? `os.popen` and `os.spawn*` surely are deprecated, but as far as I know, the `os.exec*` family is still the standard way of replacing the process image with that of another process?

**Comment by bolkedebruin** [comment]
I think you are right on the os.exec part, my apologies it should not have been added to the discussion. However. subprocess.Popen uses os.execvp underneath, so I am not sure what problem I'll be solving. It also replaces the current process so there should not be a need to do separate signaling. 

Can you provide some output on what is happening (I dont run supervisord) (process lists, debug output) and I'll gladly look at the issue @amerkel2

**Comment by amerkel2** [comment]
The problem is that `subprocess.Popen` does a `fork()` (in `_posixsubprocess.fork_exec()`) before the `os.execvp`. This creates a child process, which is then replaced by `gunicorn`, so the original `airflow scheduler` process still lives on:

```
init(1)
     ├─supervisord(10778)───airflow(20833)───gunicorn: maste(20838)─┬─gunicorn: worke(20852)
     │                                                              ├─gunicorn: worke(20853)
     │                                                              ├─gunicorn: worke(20854)
     │                                                              └─gunicorn: worke(20859)
```

Supervisor, when terminating the webserver, kills the airflow process, leaving the gunicorn alive since airflow does no signal propagation. So the situation afterwards is an orphaned gunicorn directly attached to `init`:

```
init(1)
     ├─gunicorn: maste(20838)─┬─gunicorn: worke(20852)
     │                        ├─gunicorn: worke(20853)
     │                        ├─gunicorn: worke(20854)
     │                        └─gunicorn: worke(20859)
```

On the other hand, if `os.execvp` were done directly by Airflow instead of using `subprocess.popen`, the fork would not be done and the airflow process replaced by gunicorn:

```
init(1)
     ├─supervisord(10778)───gunicorn: maste(20838)─┬─gunicorn: worke(20852)
     │                                             ├─gunicorn: worke(20853)
     │                                             ├─gunicorn: worke(20854)
     │                                             └─gunicorn: worke(20859)
```

supervisor would then terminate the gunicorn master process (since this is the process that has replaced the airflow process that supervisor spawned), which does signal propagation to its children and everything would be properly terminated.

**Comment by bolkedebruin** [comment]
Ok. Got it. I will provide a pr shortly please test it if you can.

**Comment by turtlemonvh** [comment]
You may be able to get away with calling `os.killpg` on the process that starts gunicorn.

``` python
# Put this after opening up the guinicorn subprocesses
# https://github.com/airbnb/airflow/blob/airbnb_1.7.1rc2/airflow/bin/cli.py#L349
atexit.register(cleanup)

def cleanup():
    os.killpg(sp.pid, signal.SIGTERM)
```

I tested that locally, and calling `os.killpg` on the webserver process does bring down all the gunicorn processes with it.

**Comment by bolkedebruin** [comment]
@turtlemonvh Thanks for the suggestion. For now I will stick with os.execvp just to keep the cli slightly cleaner. If that does not solve the issue I will use your suggestion.

**Comment by bolkedebruin** [comment]
@amerkel2 btw (I will still refactor to os.execvp) I wonder if the pidproxy program, as mentioned in the supervisord documentation would work for the current circumstances.

**Comment by amerkel2** [comment]
@bolkedebruin , thanks for considering this issue again. I'll be happy to test the PR in our setup.
Concerning pidproxy: yes, this would work in the supervisord case, but would only solve half of our problems. We are also running Airflow on an Aurora/Mesos cluster and have the same issues there with stopping the webserver. Currently, we resort to not using the `airflow webserver` command at all and directly call `gunicorn` with the parameters that `airflow webserver` uses. So I think a solution that allows to properly terminate a non-daemonized webserver still has its use cases.

**Comment by bolkedebruin** [comment]
@amerkel2 please check and respond on the PR if you don't mind.

**Comment by amerkel2** [comment]
Done:) Thanks for fixing this so quickly!

**Comment by omnilinguist** [comment]
What version is this being pushed out as?

In any case, while waiting for this fix to be released into pypi, putting `stopasgroup=true` in your supervisor config (http://supervisord.org/configuration.html) should do the trick, no? It seemed to work for me for both the scheduler and the webserver...

**Comment by amerkel2** [comment]
I tried `stopasgroup`, but even then, I observed some hanging `gunicorn` processes.

**Comment by bolkedebruin** [comment]
1.7.1 which will be out one of these days will contain the fix. Thanks for your patience
