### ISSUE TITLE
Kubernetes Pods fail silently when container runs out of memory

### ISSUE THREAD

**Issue by Sinsin1367** [apache/airflow#8722]
**Description**

In Airflow when a container runs out of memory the pod fails and OOMKilled is not published as a pod event. So nothing would show up in the logs. The OOMKilled is displayed as container status. We need to log container statuses if the pod fails to show in the logs that the container ran out and needs more resources to succeed. 

**Use case / motivation**

**Related Issues**

None

**Comment by astolle** [comment]
Hi,

we have the same issue with Airflow v2.2.5, but when using the Kubernetes Executor.

When a POD get's killed by K8S because of OOM, Airflow logs "FAILED" in the scheduler log and nothing to the DAG logs. 

```
2022-06-17 06:22:38,609 kubernetes_executor.py INFO - Event: mypod.73f04e8e8d8142c084e0584a9ec7f9dc had an event of type MODIFIED
2022-06-17 06:22:38,611 kubernetes_executor.py ERROR - Event: mypod.73f04e8e8d8142c084e0584a9ec7f9dc Failed
```

Wished behaviour: DAG developers get the reason "why" the DAG (executor pod) failed. 

Best, Alex
