### ISSUE TITLE
Backfills Executing w/o generating DagRuns

### ISSUE THREAD

**Issue by mmacny** [apache/airflow#874]
Hi Team,

I have an unscheduled dag that gets daily data and I'd like to run it across a date range using `backfill`.  When this dag runs, I can see the appropriate task instances get scheduled, however the parent dag_run is never generated. I've confirmed in a few places that this dag_run doesn't exist. Image is included of the lifecycle of the backfill.

A couple of points that might be helpful:
- My environment right now = 1 Airflow Box (Running: Scheduler, Worker, CeleryExecutor, Flower)
- Initial Command I kicked off over cli = "airflow backfill richardaws -s 2015-11-28 -e 2015-12-05"... 
- The Dag Runs list (at http://<server>/admin/dagrun) doesn't have any record of this backfill
- In Image 5: You can see the last item [Dag] is never green.

![missing_dagruns](https://cloud.githubusercontent.com/assets/9614883/12341610/eb13204e-baf0-11e5-9ed0-455e55440b2f.jpg)

Any help would be appreciated!

**Comment by jihygk** [comment]
+1

I think this is by design (backfill can take `-t TASK_REGEX` so you can selectively run tasks which wouldn't necessarily be part of a DagRun), but then again you can't run `airflow trigger_dag` whilst also specifying a `start_date`.

So running a `trigger_dag` with an `execution_date` parameter would be what I am looking for, but solution may not be straightforward because tasks within a DAG can have different `start_dates` and `schedule_intervals` (not sure about the latter).

#337 seems also related.

**Comment by mistercrunch** [comment]
It's by design, if a "running" DagRun was created it would create a race condition between say a local backfill and the scheduler. DagRun are mostly designed to inform the scheduler as to where to evaluate and trigger tasks as part of normal operations (schedule and filling reprocessing small chunks using `clear`).

A DAG can't have multiple `schedule_intervals` as it is a DAG level parameter.

**Comment by mmacny** [comment]
Hey @mistercrunch  - We treat the existence of a dag_run (marked success) as a persistent record that data has been processed for that day, so it's good for the schedule and as an artifact for record-keeping.

If we can't get it into the CLI (as a flag saying "create a dag_run for this backfill), would you be open to either a collection of utilities that exists outside the CLI for this sort of thing?  I imagine utilities like these would be helpful for quickly re-trying dags with different architectures to help understand good design patterns for airflow. Also, we're going to make mistakes and need to create/re-instantiate dag_runs.

**Comment by bolkedebruin** [comment]
This will most likely be included fixed, without the race condition, as part of AIRFLOW-20 when it lands
