### ISSUE TITLE
Install airflow to kubernetes failed

### ISSUE THREAD

**Issue by kinderyj** [apache/airflow#8799]
In release 1.10.3 wen can install the airflow to the kubernetes by using the following commands:
./scripts/ci/kubernetes/Docker/build.sh
./scripts/ci/kubernetes/kube/deploy.sh
But in release 1.10.10, it does not work. For 1.10.10, is there any other way or document to install airflow to kubernetes? Thanks.

**Comment by potiuk** [comment]
Note that this was Dockerfile that was only used for testing. The location of scripts and way of installation changed since then - you can see it here: https://github.com/apache/airflow/blob/v1-10-test/TESTING.rst#running-tests-with-kubernetes . Also note that we have a new production image in 1.10.10 (Alpha quality) and we are working on official helm chart #8777 that you will be able to use to install production-ready Airflow on Kubernetes. We aim to have it all working in 1.10.11.

**Comment by kinderyj** [comment]
> Note that this was Dockerfile that was only used for testing. The location of scripts and way of installation changed since then - you can see it here: https://github.com/apache/airflow/blob/v1-10-test/TESTING.rst#running-tests-with-kubernetes . Also note that we have a new production image in 1.10.10 (Alpha quality) and we are working on official helm chart #8777 that you will be able to use to install production-ready Airflow on Kubernetes. We aim to have it all working in 1.10.11.

Thanks a lot.
