### ISSUE TITLE
Add AWS S3 create and delete bucket operator

### ISSUE THREAD

**Issue by randr97** [apache/airflow#8890]
**Description**
AWS missing operators include CREATE and DELETE  S3 operator. This issue caters to creating these operators. Also writing system tests for the same.
**Use case / motivation**
Many organisations would want to utilise such operators using xcoms for their projects. Especially when S3 is used with redshift and some ETL process has to be deployed to pull data from and dump data to a data lake.

**Comment by prateeksan** [comment]
@randr97 is this to create and delete buckets or objects in buckets? If it is to create/delete buckets, how would you interact with Terraform state backends?

**Comment by randr97** [comment]
> @randr97 is this to create and delete buckets or objects in buckets? If it is to create/delete buckets, how would you interact with Terraform state backends?
Hi @prateeksan, this is to create and delete S3 buckets.
I did not get as to why we would need to interact with Terraform state backends.
It would be help if you could explain the use case.

**Comment by prateeksan** [comment]
@randr97 a lot of organizations manage infrastructure like S3 buckets through infrastructure-as-code scripts, usually Terraform since that is what AWS supports natively. The way Terraform works is that it maintains the state of all infrastructure in a backend (usually remote). Let's say someone configured an s3 bucket and deployed it using Terraform, if your DAG then deletes that bucket, it will create a mismatch between the Terraform state and the reality of the deployment (TF state will presume the bucket exists when in fact it doesn't).

I still think this is a useful feature, but I am wondering if there is a way for the operator to accept a flag that somehow communicates to a TF backend in case a bucket is deleted.

Also keep in mind that your create bucket operator should have all the required configuration options for IAM roles, ACL permissions etc.

**Comment by randr97** [comment]
> @randr97 a lot of organizations manage infrastructure like S3 buckets through infrastructure-as-code scripts, usually Terraform since that is what AWS supports natively. The way Terraform works is that it maintains the state of all infrastructure in a backend (usually remote). Let's say someone configured an s3 bucket and deployed it using Terraform, if your DAG then deletes that bucket, it will create a mismatch between the Terraform state and the reality of the deployment (TF state will presume the bucket exists when in fact it doesn't).
> 
> I still think this is a useful feature, but I am wondering if there is a way for the operator to accept a flag that somehow communicates to a TF backend in case a bucket is deleted.
> 
> Also keep in mind that your create bucket operator should have all the required configuration options for IAM roles, ACL permissions etc.

Oh now I get the issue. So there should be a mechanism where airflow could talk to TF backend so that for eg if some keys have to be created via terraform and dag deletes the bucket it should technically fail!

**Comment by prateeksan** [comment]
Something like that, I'll message you on Slack.
