### ISSUE TITLE
Some task log lines are "decorated" twice

### ISSUE THREAD

**Issue by ghost** [apache/airflow#8972]
**Apache Airflow version**:
1.10.10

**What happened**:

Use airflow out of the box, create any DAG, run the DAG.

Log will contain nested log messages like this (one line):

[2020-05-22 17:07:20,614] {logging_mixin.py:112} INFO - [2020-05-22 17:07:20,613] {local_task_job.py:103} INFO - Task exited with return code 0

Not all log messages will be like this but SOME. 
- using self.log.info('foobar') in a own operator will result in correct log messages
- using for example   b = BaseHook.get_connection('existing_connection') will result in broken double log messages

**What you expected to happen**:

Log messages should be correct

**How to reproduce it**:

 see above

**Comment by halilduygulu** [comment]
As far as I understood this happens because all `logger.info/debug()` etc goes to this loggingmixin and printed as info as I saw here today. 
https://stackoverflow.com/questions/53677056/does-anyone-know-how-to-suppress-all-airflow-info-level-logs-but-not-suppress/54131307#54131307

I am also looking a way to stop this and adhere log levels and also stop logging debug when i give `logging_level = INFO` in conf file.

**Comment by ashb** [comment]
Long standing issue, migrating here from AIRFLOW-4990

**Comment by ashb** [comment]
Might this also fix the issue where some logs are disappearing?
