### ISSUE TITLE
Fetching logs of tasks which are not currently executed with DAGS

### ISSUE THREAD

**Issue by bhavaniravi** [apache/airflow#9367]
**Description**

Need a way to access logs of tasks that are executed at a particular instance of time but are not currently a part of the DAG.

**Use case / motivation**

I have a use case where tasks are generated based on the number of entries created on a DB after a timestamp

The dag would look something like this

```
for study in read_db():
    PythonOperator(
            task_id="python_task_" + study["pk"]
             execute_callable=process_data
             op_kwargs={study: study}
    )
```

Each task has a unique id based on the primary key of the entry in the DB. Once the item is processed, it is marked success and won't be processed again, thereby removing it from tasks.

On trying to access logs of these tasks I get the following error

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/10116000/84975691-ad801900-b143-11ea-85a8-6f715b0216df.png">

Despite tasks not being a part of the DAGs at the given instance of time, they are displayed in the `task instance` page. But the error pops up on trying to access the logs

**Comment by eladkal** [comment]
This is really a bad idea to create tasks in such manner. Airflow expects a static or slowly changing DAG structure. You are also making expensive calls to the database as a top level code - this can easily overwhelm your database.

Since this use case is not something we encourage I'm closing the issue.
As for the technical issue of how to access logs please ask the question in Stackoverflow or Slack.
