### ISSUE TITLE
2 notifications send `on_failure`

### ISSUE THREAD

**Issue by gfelot** [apache/airflow#9392]
**Apache Airflow version**:
1.10.9

- **Cloud provider or hardware configuration**: GCP
- **OS** (e.g. from /etc/os-release): Debian (VM)

**What happened**:

Try to send custom email and notification to Teams with the `on_failure_callback`.
Strangely I got 2 emails and 2 notifications.

Something trigger twice the callback and I cannot find out what.

**How to reproduce it**:

Here my test DAG:

```
from datetime import datetime

from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
from airflow.utils.email import send_email_smtp
from operators.ms_teams_webhook_operator import MSTeamsWebhookOperator

default_args = {
    "owner": "me",
    "depends_on_past": False,
    "start_date": datetime(2020, 6, 15),
    'email_on_failure': False
}


def on_failure(context):
    dag_id = context['dag_run'].dag_id

    task_id = context['task_instance'].task_id

    logs_url = f"https://myairflow/admin/airflow/log?dag_id={dag_id}&task_id={task_id}&execution_date={context['ts']}"

    teams_notification = MSTeamsWebhookOperator(
        task_id="msteams_notify_failure",
        trigger_rule="all_done",
        message=f"{dag_id} has failed on task: {task_id}",
        button_text="View log",
        button_url=logs_url,
        theme_color="FF0000",
        http_conn_id='msteams-python-webhook')
    teams_notification.execute(context)

    title = f"Titre {dag_id} - {task_id}"
    body = title

    send_email_smtp("gil.felot@lisea.fr", title, body)


def print_fail():
    print("Hello !")
    exit(1)


with DAG(
        "test_email2",  # ICI
        default_args=default_args,
        schedule_interval=None
) as dag:
    preprocessing_started = DummyOperator(
        task_id="go_email_go"
    )

    python_fail = PythonOperator(
        task_id="pyhton_def",
        python_callable=print_fail,
        on_failure_callback=on_failure,
        email_on_failure=False
    )

preprocessing_started >> python_fail

```

Here is one try I have on Teams, I got also 2 emails in the row.

![image](https://user-images.githubusercontent.com/7879555/85064380-c7eddd00-b1ab-11ea-8720-6c34d841f83a.png)

How is that possible ? I think there is a bug somewhere in the process to trigger the callback

**Comment by potiuk** [comment]
Following the rule for issues - the issues in Github are not supposed to be used for such investigations. Rather than that try to get some help and input on our Slack http://airflow.apache.org/community/ (follow the "Ask a question") path. There is a #troubleshooting channel there and you might find some help there.

**Comment by potiuk** [comment]
> I also have this issue, and wonder why it did not qualify as an issue in Airflow?
> 
> In my case, it happens with the on_failure_callback of a DAG. The DAG has multiple tasks (without individual callbacks) and a DAG-level timeout of a few minutes. When the timeout is triggered, the running tasks are terminated (marked skipped) and the main DAG fails. It triggers the on_failure_callback not once, but twice with the same context. Is there any reason why that would happen twice? It's consistent and happens every time this DAG times out. The second invocation is a few seconds after the first, I also checked the context and stack traces and they are exactly the same.

If you provide a detailed stack trace @Oduig  in a new issue (especially after migration to latest version of airflow) - please open a new issue.  This issue is about airflow 1.10.9 which reached EOL way more than 2 years ago. If you are also using 1.10 then the answer can be only answer: Upgrade to latest airflow.

If you are upgraded to latest airflow and the issue is reproducible, opening a new issue with reproducible steps (including the logs and stack traces) is a good idea.
