### ISSUE TITLE
Decouple DAG tagging from RBAC

### ISSUE THREAD

**Issue by roskoN** [apache/airflow#9709]
**Description**

Currently, in order to use DAG tags, one needs to enable RBAC. Thus, one needs to set it up in order to be able to use the feature.

**Use case / motivation**

While, this feature is super helpful for multi-user, multi-role environments, it has additional value beyond this specific use case. In general, tags are helpful to organize/categorize the DAGs and it shouldm't be limited to role-based access control. 

The DAG tagging in the UI should be available regardles of RBAC.

**Related Issues**

N/A

**Comment by mik-laj** [comment]
@roskoN Airflow 2.0 will not have a non-RBAC interface. For this reason, we try to encourage users to use RBAC. One way to do this is to create additional reasons for migrating to the RBAC interface - exclusive feature. There is another reason. We develop all the new features in the master branch (Airflow 2.0), and then each change is manually cherry-picked into the 1.10 release by the release maintainer. If we want a feature to be available for non-RBAC, then the release maintainer has to spend a lot of time preparing a change for the non-RBAC interface that we plan to drop in the next version.  Preparing changes in the interface is time-consuming because the Javascript code is not covered by automatic tests. Each change in Javascript is tested manually.

**Comment by roskoN** [comment]
@mik-laj Thank you for the detailed but concise explanation. It perfectly makes sense. 

And, of course, for those who do not like this, there is an easy workaround.
