### ISSUE TITLE
S3 Backend for metadatabase or DAGS post endpoint.

### ISSUE THREAD

**Issue by kyprifog** [apache/airflow#9937]
Would be nice if you could post DAGS to airflow by updating DAG files on s3.  Has anyone worked on this?    Alternatively a rest API endpoint to update DAGS would work.   Right now rest api only seems to support CRUD for dag_runs.

**Comment by potiuk** [comment]
There is a whole AIP (AIP-5) dedicated to that: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher and discussion you could find there. The last conclusion was that we do not want Airflow to build own mechanisms for synchronization of the DAG folder - that it should be done externally (for example using sidecars or well,, cron job :) rather than integrated into Airflow itself. However, if you think there are good reasons why it would make sense, the devlist is the right place to raise it and (re)open discussion.

**Comment by kyprifog** [comment]
@potiuk Thanks for the quick reply, I have an integration with airflow that would potentially benefiet from being able to submit updates to DAGS either through a rest api or an S3 backend but it sounds like the consensus is that sync should happen externally so it feels a bit akward for the integration to ask for S3 credentials if it then requires someone setting up a sync.    Alot of the conversation there seems to revolve around mounting volumes, but I simply would like a more standard (out of the box) way of setting up something like an s3 backend or registry so it doesn't require users of the integration to go through more hoops.

**Comment by potiuk** [comment]
I think we are going a bit different direction. Rather than making Airflow more complex, we are integrating more and more external services using existing tools. For example we have the helm chart in `charts` folder which allows you to set-up Airflow on Kubernetes cluster easily. And one of the  Helm Chart configuration options is to integrate `git sync` sidecar where syncing git via regular process running in separate container but sharing DAG volume is performed. This is more "sustainable" way of doing such integrations. That's the philosophy of "a tool that only does one job well" rather than integrate all the possible options in the airflow itself. What you are describing here is more like a "s3-sync sidecar" that you might want to build instead of extending Airflow. Which (not too surprising) someone (or many someones) already did https://github.com/namshi/s3-sidecar , https://gitlab.koehn.com/docker/s3-sync, https://medium.com/nuvo-group-tech/copy-files-and-directories-between-kubernetes-and-s3-d290ded9a5e0 and many more. 

So rather than adding such functionality to airflow  maybe you would like to test/review and contribute back such a sidecar solution to the helm chart of ours ? Also we are going to have officially supported docker-compose #8548 in the future and using such side-car could be an option there, so that you would not have to use Kubernetes.

I thin this is much more reasonable approach.

**Comment by kyprifog** [comment]
@potiuk I guess my point of reference here is the existing POST /dag_runs/ endpoint.    That seems to set a prescedent for being able to create dag runs using the api.  So why wouldn't you also have an endpoint for posting Dags as well?   Also if not a rest api endpoint, this work seems like its 80% of the way to developing a concept of an external airflow registry and directionally consistent with that idea:  https://airflow.apache.org/docs/stable/dag-serialization.html

**Comment by mik-laj** [comment]
There are many methods of API synchronization, and under the simple concept of creating a DAG, there would have to be complex logic. We decided that we did not want to go in this direction. 

If you need to extend the API with an additional endpoint, you can use the plugins mechanism: 
https://airflow.readthedocs.io/en/latest/plugins.html
